{
  "hash": "c252c24fedaefb591398482ff6cc62a9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Aula 6 - Imputação e Normalização de Dados'\ndate: last-modified\ntoc: true\nformat:\n  html: default\n  ipynb: default\njupyter:\n  kernel: python3\nexecute:\n  enabled: true\n---\n\n\n\n\n\n\n## Motivação\n\nNa Aula 5, usamos assimetria, curtose e valores atípicos para **descrever** distribuições. O valor dos pedidos, por exemplo, apresentava uma cauda longa à direita, e um grupo pequeno de clientes atacadistas elevava a média. Essa análise caracterizava os dados observados, mas ainda não envolvia qualquer modificação da base.\n\nNesta aula, o diagnóstico passa a orientar **decisões de tratamento**. Antes de ajustar um modelo, construir um indicador ou comparar grupos, uma base real geralmente exige algum preparo. Esse conjunto de operações recebe o nome de pré-processamento. As escolhas feitas nessa etapa alteram os dados que chegam às análises posteriores e, portanto, afetam as estimativas e conclusões produzidas a partir deles.\n\nPara ilustrar, usaremos a base de anúncios de aluguel em São Paulo da atividade prática. Ela reúne três problemas que aparecem com frequência em dados reais:\n\n- **lacunas** em algumas colunas, que podem representar perda de informação ou ausência estrutural,\n- variáveis medidas em **unidades diferentes**, como área em m², aluguel em reais e número de quartos,\n- Distribuições com **cauda longa**, em que poucos imóveis muito caros esticam a escala.\n\nCada problema pede uma decisão diferente. A **imputação** estima valores que não foram observados. O **escalonamento** coloca variáveis em escalas numéricas comparáveis. As **transformações não lineares** modificam a geometria da distribuição e podem reduzir sua assimetria. O termo *normalização* aparece na literatura com significados diferentes, por isso o roteiro distingue explicitamente escalonamento de transformação. Nenhum desses tratamentos é neutro. Imputar introduz valores estimados, escalonar muda a unidade de representação e transformar altera as distâncias entre as observações. Avaliaremos cada técnica tanto pelo problema que resolve quanto pelas mudanças que produz.\n\n> **O que cada tratamento muda nos dados?**\n\n## Objetivos de aprendizagem\n\nAo final deste roteiro, você será capaz de:\n\n1. Distinguir ausência estrutural de ausência por falha de registro.\n2. Imputar valores pela média, mediana, moda e mediana por grupo, além de medir o erro de cada estratégia.\n3. Escalonar variáveis com `StandardScaler`, `RobustScaler` e `MinMaxScaler`, reconhecendo a sensibilidade de cada um a extremos.\n4. Reduzir a assimetria com `log`, `log1p`, Box-Cox e Yeo-Johnson.\n5. Explicar a diferença entre mudar a **régua** (escalonar) e mudar a **forma** (transformar) de uma distribuição.\n\n::: {.callout-tip}\n## Como usar este roteiro\n\nO roteiro usa a base `imoveis_sao_paulo.csv`, a mesma da atividade prática, salva em `imoveis-sao-paulo/data/`.\n\nAlém das bibliotecas da Aula 5, usamos o módulo `sklearn.preprocessing` do **scikit-learn**.\n\nAo final, três perguntas ajudam a consolidar as escolhas de tratamento.\n:::\n\n# 1. Preparando a base\n\nComeçamos importando as bibliotecas usadas no carregamento, na transformação e na visualização dos dados.\n\n::: {#9eab738f .cell execution_count=1}\n``` {.python .cell-code}\n# Importa as bibliotecas e define o tema dos gráficos\nfrom pathlib import Path\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\n\nfrom sklearn.preprocessing import (\n    MinMaxScaler,\n    PowerTransformer,\n    RobustScaler,\n    StandardScaler,\n)\n\nsns.set_theme(style=\"whitegrid\", palette=\"colorblind\")\n```\n:::\n\n\nEm seguida, carregamos a base e fazemos três ajustes iniciais:\n\n- padronizamos os nomes das colunas,\n- removemos linhas duplicadas,\n- criamos `property_type`: imóveis sem andar são casas.\n\n::: {#64014dfd .cell execution_count=2}\n``` {.python .cell-code}\n# Novos nomes para as colunas com espaços e símbolos\ncolumn_names = {\n    \"parking spaces\": \"parking_spaces\",\n    \"hoa (R$)\": \"hoa\",\n    \"rent amount (R$)\": \"rent_amount\",\n    \"property tax (R$)\": \"property_tax\",\n    \"total (R$)\": \"total\",\n}\n```\n:::\n\n\n::: {#a66b9413 .cell execution_count=3}\n``` {.python .cell-code}\n# Carrega a base, remove duplicatas e identifica o tipo de imóvel\nimoveis = (\n    pd.read_csv(\"imoveis-sao-paulo/data/imoveis_sao_paulo.csv\")\n    .rename(columns=column_names)\n    .drop_duplicates()\n    .reset_index(drop=True)\n    .assign(\n        property_type=lambda df: np.where(  # <1>\n            df[\"floor\"].isna(),\n            \"casa\",\n            \"apartamento\",\n        )\n    )\n)\n```\n:::\n\n\n1. `np.where` escolhe o rótulo linha a linha: imóveis sem andar são casas, e os demais, apartamentos.\n\n## 1.1 Os três problemas da aula\n\nAntes de tratar qualquer coluna, precisamos saber o que há de errado com ela. Esta seção faz um diagnóstico rápido da base, no espírito da Aula 5, e o resume em uma única figura com três painéis. Cada painel responde a uma pergunta e antecipa um dos problemas que a aula vai tratar.\n\n| Painel | Pergunta | O que observar |\n|---|---|---|\n| 1. Valores ausentes | Quais colunas têm lacunas, e em que proporção? | Se as proporções são parecidas ou se alguma coluna destoa das demais |\n| 2. Escalas incompatíveis | As variáveis numéricas estão na mesma ordem de grandeza? | A distância entre as medianas de quartos, área e aluguel |\n| 3. Cauda longa | Como os aluguéis se distribuem? | Onde se concentra a maioria dos imóveis e até onde a cauda se estende |\n\nPara montar a figura, calculamos antes três objetos:\n\n- `missing`: a porcentagem de valores ausentes em `hoa`, `parking_spaces` e `floor`;\n- `scales`: a mediana de `rooms`, `area` e `rent_amount`, cada uma em sua unidade original;\n- `limit`: o percentil 99 do aluguel, usado apenas para recortar o eixo do histograma. Sem ele, os poucos aluguéis mais altos esticariam o eixo e esconderiam a forma da distribuição.\n\n::: {#8143436e .cell execution_count=4}\n``` {.python .cell-code}\n# Valores exibidos em cada painel da figura\nmissing = (\n    imoveis[[\"hoa\", \"parking_spaces\", \"floor\"]]\n    .isna()\n    .mean()  # <1>\n    .mul(100)\n)\n\nscales = (\n    imoveis[[\"rooms\", \"area\", \"rent_amount\"]]\n    .median()\n)\n\nlimit = imoveis[\"rent_amount\"].quantile(.99)  # <2>\n```\n:::\n\n\n1. A média de uma coluna booleana é a proporção de valores `True`, aqui a proporção de ausentes.\n2. O percentil 99 recorta o 1% mais extremo apenas na visualização. Nenhum dado é removido.\n\n::: {#4a5ac52b .cell execution_count=5}\n``` {.python .cell-code}\n# Figura-resumo com os três problemas da aula\nfig, axes = plt.subplots(1, 3, figsize=(15, 4))\n\nsns.barplot(\n    x=missing.index,\n    y=missing.values,\n    ax=axes[0],\n    color=\"#4C72B0\",\n)\naxes[0].set(\n    title=\"1. Valores ausentes\",\n    ylabel=\"Ausentes (%)\",\n    xlabel=\"\",\n)\naxes[0].tick_params(axis=\"x\", rotation=20)\n\nsns.barplot(\n    x=scales.index,\n    y=scales.values,\n    ax=axes[1],\n    color=\"#55A868\",\n)\naxes[1].set(\n    title=\"2. Escalas incompatíveis\",\n    ylabel=\"Mediana original\",\n    xlabel=\"\",\n)\n\nsns.histplot(\n    imoveis[\"rent_amount\"],\n    bins=50,\n    binrange=(0, limit),\n    ax=axes[2],\n    color=\"#C44E52\",\n)\naxes[2].set(\n    title=\"3. Cauda longa\",\n    xlabel=\"Aluguel (R$)\",\n    ylabel=\"Imóveis\",\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-6-output-1.png){}\n:::\n:::\n\n\nA leitura da figura revela os três problemas:\n\n1. **Valores ausentes.** `hoa` e `parking_spaces` têm poucas lacunas (cerca de 2% e 1%), enquanto `floor` chega a 15%. Uma diferença tão grande sugere que a ausência em `floor` tem uma causa própria, investigada na seção 2.\n2. **Escalas incompatíveis.** O imóvel típico tem 2 quartos, cerca de 76 m² e aluguel de R$ 2.900. As três medianas estão separadas por ordens de grandeza, e o aluguel domina o painel apenas por causa da unidade.\n3. **Cauda longa.** Três quartos dos aluguéis ficam abaixo de cerca de R$ 5.100, mas a cauda se estende muito à direita. O maior aluguel chega a quase R$ 38 mil, bem além do recorte do gráfico. A média (cerca de R$ 4.000) fica acima da mediana, o mesmo padrão de assimetria positiva visto na Aula 5.\n\nA ordem das seções acompanha uma sequência comum de pré-processamento. Primeiro, investigamos as lacunas e decidimos quais delas representam informação perdida. Muitos estimadores não aceitam valores ausentes em sua entrada, mas esse não é o único motivo para tratá-los. Também precisamos evitar que procedimentos diferentes descartem subconjuntos distintos da base. Depois, examinamos separadamente a escala numérica e a forma das distribuições.\n\n# 2. Ausência estrutural\n\nAo encontrar uma coluna com lacunas, é tentador preenchê-las imediatamente. Antes de escolher uma técnica, precisamos investigar **por que** o valor está ausente. Nem toda célula vazia representa erro de coleta ou perda de informação.\n\nNa base de imóveis, `floor` e `total_floors` estão ausentes nas casas. Não houve falha de cadastro. Esses atributos descrevem a posição de uma unidade em um edifício e, portanto, não se aplicam a casas. Esse tipo de lacuna é chamado de **ausência estrutural**, pois decorre da definição da variável para determinado tipo de observação. Imputar um número produziria um valor sem referente real.\n\n::: {#f3834725 .cell execution_count=6}\n``` {.python .cell-code}\n# Número de imóveis e proporção sem andar, por tipo\n(\n    imoveis\n    .groupby(\"property_type\")\n    .agg(\n        imoveis=(\"property_type\", \"size\"),\n        proporcao_sem_andar=(\n            \"floor\",\n            lambda x: (\n                x\n                .isna()\n                .mean()\n            ),\n        ),\n    )\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=168}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>imoveis</th>\n      <th>proporcao_sem_andar</th>\n    </tr>\n    <tr>\n      <th>property_type</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>apartamento</th>\n      <td>25024</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>casa</th>\n      <td>4415</td>\n      <td>1.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-important}\nQuando a ausência decorre de uma característica conhecida da observação, registre essa característica e **não impute** um valor numérico. Aqui, `property_type` torna explícita a informação que antes estava codificada apenas pela lacuna.\n:::\n\nDepois de separar o caso estrutural, restam lacunas que podem representar informação perdida, como um aluguel não informado ou um número de vagas não registrado. Para esses casos, a imputação é uma alternativa possível. A escolha ainda depende do mecanismo que produziu a ausência e da quantidade de dados faltantes.\n\n# 3. Imputação: o impacto das alternativas\n\nImputar consiste em substituir um valor ausente por uma estimativa calculada a partir das informações disponíveis. Há estratégias simples, como usar uma medida de posição da própria coluna, e métodos multivariados, que estimam cada lacuna a partir de outras variáveis. Nesta aula, trabalharemos com estatísticas descritivas da Aula 5. Mesmo simples, essas estratégias permitem observar efeitos importantes, como concentração artificial de valores e redução da variabilidade.\n\nHá uma dificuldade prática. Em uma lacuna real, o valor verdadeiro não foi observado. Sem uma referência, não podemos calcular diretamente o erro cometido pela imputação.\n\nA saída é simular o problema:\n\n1. partir de registros completos,\n2. apagar alguns valores conhecidos,\n3. imputar e comparar com o valor original.\n\nPrimeiro, a função que apaga uma fração dos valores e a base completa, que servirá de gabarito.\n\n::: {#4c51fe5b .cell execution_count=7}\n``` {.python .cell-code}\n# Função de apagamento e base-gabarito\nrng = np.random.default_rng(42)  # <1>\n\ndef erase_at_random(values, share):\n    return values.mask(rng.random(len(values)) < share)  # <2>\n\nimoveis_true = (  # <3>\n    imoveis\n    .dropna(subset=[\"hoa\", \"parking_spaces\"])\n    .reset_index(drop=True)\n)\n```\n:::\n\n\n1. A semente fixa garante o mesmo apagamento a cada execução.\n2. `rng.random` sorteia um número em [0, 1) para cada linha. `.mask` troca por `NaN` os valores cujo sorteio fica abaixo de `share`.\n3. O gabarito mantém apenas registros com `hoa` e `parking_spaces` conhecidos.\n\nEm seguida, criamos lacunas em três variáveis de tipos diferentes: discreta, contínua e categórica.\n\n::: {#55dae71d .cell execution_count=8}\n``` {.python .cell-code}\n# Apaga valores em três colunas de tipos diferentes\nimoveis_missing = (\n    imoveis_true\n    .assign(  # <1>\n        rooms=lambda df: erase_at_random(df[\"rooms\"], .10),\n        rent_amount=lambda df: erase_at_random(df[\"rent_amount\"], .15),\n        furniture=lambda df: erase_at_random(df[\"furniture\"], .08),\n    )\n)\n```\n:::\n\n\n1. As proporções apagadas são 10% dos quartos, 15% dos aluguéis e 8% da mobília.\n\nConferimos quantos valores foram apagados:\n\n::: {#17183cf3 .cell execution_count=9}\n``` {.python .cell-code}\n# Quantidade e proporção de valores apagados por coluna\n(\n    imoveis_missing[[\"rooms\", \"rent_amount\", \"furniture\"]]\n    .isna()\n    .sum()\n    .to_frame(\"ausentes\")\n    .assign(\n        proporcao=lambda x: (\n            x.ausentes / len(imoveis_missing)\n        ).round(3)\n    )\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=171}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ausentes</th>\n      <th>proporcao</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>rooms</th>\n      <td>2783</td>\n      <td>0.097</td>\n    </tr>\n    <tr>\n      <th>rent_amount</th>\n      <td>4308</td>\n      <td>0.150</td>\n    </tr>\n    <tr>\n      <th>furniture</th>\n      <td>2254</td>\n      <td>0.079</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Por que o mecanismo de ausência importa?\n\nO apagamento simulado é completamente aleatório, mecanismo conhecido como MCAR (*missing completely at random*). Isso significa que a probabilidade de apagar uma célula não depende de nenhuma variável observada nem do próprio valor apagado.\n\nEm dados reais, essa condição é forte e nem sempre plausível. A ausência pode estar associada ao próprio valor. Se imóveis caros anunciam \"valor sob consulta\" com maior frequência, por exemplo, a distribuição dos aluguéis observados deixa de representar a distribuição completa. Uma imputação baseada apenas nesses valores tende a subestimar os aluguéis omitidos.\n:::\n\n## 3.1 Média, mediana e mediana agrupada\n\nAs estratégias mais simples substituem todas as lacunas por uma única constante calculada com os valores observados da coluna. A média utiliza toda a magnitude dos dados e, por isso, responde fortemente a valores extremos. A mediana depende apenas da ordenação e é mais resistente a caudas longas.\n\n::: {#4897e35a .cell execution_count=10}\n``` {.python .cell-code}\n# Constantes para a imputação simples\nrent_mean = (\n    imoveis_missing.rent_amount\n    .mean()\n)\n\nrent_median = (\n    imoveis_missing.rent_amount\n    .median()\n)\n```\n:::\n\n\nA mediana por `tier` condiciona a estimativa ao padrão do imóvel. Cada lacuna recebe a mediana calculada entre os anúncios do mesmo grupo. Se um `tier` não tiver aluguéis observados, não será possível calcular sua mediana. Nesse caso, a mediana global funciona como estratégia de contingência.\n\n::: {#87ad0802 .cell execution_count=11}\n``` {.python .cell-code}\n# Imputação pela mediana de cada tier\nrent_group = (\n    imoveis_missing\n    .groupby(\"tier\")\n    .rent_amount\n    .transform(lambda x: x.fillna(x.median()))  # <1>\n    .fillna(rent_median)  # <2>\n)\n```\n:::\n\n\n1. `.transform` devolve uma série do mesmo tamanho da original, alinhada ao seu índice.\n2. Grupos sem observações recebem a mediana global.\n\nReunimos as versões do aluguel para compará-las lado a lado:\n\n::: {#4ce4b491 .cell execution_count=12}\n``` {.python .cell-code}\n# Versões do aluguel a comparar\nrent_versions = {\n    \"Original\": imoveis_true.rent_amount,\n    \"Com lacunas\": imoveis_missing.rent_amount,\n    \"Média\": imoveis_missing.rent_amount.fillna(rent_mean),\n    \"Mediana\": imoveis_missing.rent_amount.fillna(rent_median),\n    \"Mediana por tier\": rent_group,\n}\n```\n:::\n\n\n::: {#543be421 .cell execution_count=13}\n``` {.python .cell-code}\n# Histograma de cada versão do aluguel\nfig, axes = plt.subplots(1, 5, figsize=(20, 4), sharey=True)\n\nlimit = imoveis_true.rent_amount.quantile(.99)\n\nfor ax, (label, values) in zip(axes, rent_versions.items()):\n    sns.histplot(\n        values.dropna(),\n        bins=50,\n        binrange=(0, limit),\n        ax=ax,\n        color=\"#4C72B0\",\n    )\n    ax.set(\n        title=label,\n        xlabel=\"Aluguel (R$)\",\n        ylabel=\"Imóveis\",\n    )\n    if label == \"Média\":  # <1>\n        ax.axvline(\n            rent_mean,\n            color=\"#C44E52\",\n            linestyle=\"--\",\n        )\n    if label == \"Mediana\":\n        ax.axvline(\n            rent_median,\n            color=\"#C44E52\",\n            linestyle=\"--\",\n        )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-14-output-1.png){}\n:::\n:::\n\n\n1. Nos painéis da média e da mediana, a linha tracejada marca a constante usada para preencher as lacunas.\n\nDois efeitos aparecem nos histogramas:\n\n- **média e mediana** concentram todas as lacunas em um único valor, criando um pico artificial e reduzindo a dispersão,\n- **mediana por tier** distribui as lacunas entre vários valores, um por grupo.\n\n### 3.1.1 Erro absoluto médio (MAE)\n\nOs histogramas mostram como cada estratégia altera a **forma** da distribuição, mas não dizem quão perto cada valor imputado ficou do valor verdadeiro. Uma estratégia pode preservar bem o formato do histograma e, ainda assim, errar muito imóvel a imóvel. Para avaliar a **precisão** das estimativas, precisamos de uma métrica de erro. É aqui que o gabarito se torna útil: como os valores foram apagados de propósito, sabemos exatamente quanto cada lacuna deveria valer.\n\nO erro de uma imputação é a diferença entre o valor verdadeiro $y_i$ e o valor imputado $\\hat{y}_i$. Essa diferença pode ser positiva ou negativa, e uma média simples dos erros deixaria que subestimativas e superestimativas se cancelassem, como a soma dos desvios em torno da média na Aula 5. O **erro absoluto médio** (MAE, do inglês *mean absolute error*) evita esse cancelamento ao tomar o valor absoluto de cada erro antes de calcular a média:\n\n$$\n\\text{MAE} = \\frac{1}{n}\\sum_{i=1}^{n} \\left| y_i - \\hat{y}_i \\right|\n$$\n\nAqui, $n$ é o número de lacunas imputadas. O MAE é expresso na mesma unidade da variável, o que facilita a interpretação: um MAE de R$ 500 significa que, em média, a imputação errou o aluguel em R$ 500, para mais ou para menos.\n\nUm exemplo pequeno ajuda a fixar o cálculo. Suponha três imóveis cujo aluguel foi apagado e imputado com a mesma constante, R$ 3.000:\n\n| Imóvel | Verdadeiro ($y_i$) | Imputado ($\\hat{y}_i$) | Erro absoluto |\n|---|---|---|---|\n| A | R$ 2.000 | R$ 3.000 | R$ 1.000 |\n| B | R$ 3.000 | R$ 3.000 | R$ 0 |\n| C | R$ 10.000 | R$ 3.000 | R$ 7.000 |\n\nO MAE é $(1.000 + 0 + 7.000)/3 \\approx$ R$ 2.666,67. Observe que um único imóvel caro responde pela maior parte do erro.\n\nDois cuidados orientam o cálculo nesta seção:\n\n- **Apenas as posições imputadas entram na conta.** Nas posições observadas, o valor não foi alterado e o erro é zero por construção. Incluí-las reduziria artificialmente o MAE.\n- **A escolha da métrica favorece certas estratégias.** A mediana é o valor constante que minimiza a soma dos erros absolutos, enquanto a média minimiza a soma dos erros quadráticos. Por isso, entre as duas constantes, espera-se que a mediana apresente MAE menor, sobretudo em distribuições assimétricas como a do aluguel.\n\nPrimeiro, recuperamos no gabarito os valores verdadeiros das posições apagadas:\n\n::: {#d5948cd2 .cell execution_count=14}\n``` {.python .cell-code}\n# Posições apagadas e seus valores verdadeiros\nrent_missing = imoveis_missing.rent_amount.isna()\n\ntruth = imoveis_true.loc[rent_missing, \"rent_amount\"]\n```\n:::\n\n\n::: {#ee86884e .cell execution_count=15}\n``` {.python .cell-code}\n# MAE de cada estratégia, apenas nas posições imputadas\n(\n    pd.Series(\n        {\n            \"Média\": (\n                (truth - rent_mean)\n                .abs()\n                .mean()\n            ),\n            \"Mediana\": (\n                (truth - rent_median)\n                .abs()\n                .mean()\n            ),\n            \"Mediana por tier\": (\n                (truth - rent_group[rent_missing])\n                .abs()\n                .mean()\n            ),\n        },\n        name=\"MAE (R$)\",\n    )\n    .round(2)\n    .to_frame()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=177}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>MAE (R$)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Média</th>\n      <td>2505.30</td>\n    </tr>\n    <tr>\n      <th>Mediana</th>\n      <td>2313.52</td>\n    </tr>\n    <tr>\n      <th>Mediana por tier</th>\n      <td>1820.84</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nQuanto menor o MAE, menor foi o erro médio das imputações neste experimento. Como esperado, a mediana erra menos que a média. A mediana por `tier` reduz ainda mais o erro, porque usa uma informação adicional, o padrão do imóvel, para aproximar a estimativa do valor verdadeiro.\n\nEssa comparação avalia a precisão pontual sob o mecanismo MCAR simulado. Ela não garante que a mesma estratégia seja adequada quando o padrão de ausência dos dados reais for diferente.\n\n## 3.2 Moda e variáveis discretas\n\nPara variáveis categóricas nominais, operações aritméticas como média e mediana não têm interpretação válida. Uma alternativa simples é a moda, isto é, a categoria observada com maior frequência.\n\nCalculamos a categoria mais frequente de `furniture`:\n\n::: {#86c03d43 .cell execution_count=16}\n``` {.python .cell-code}\n# Categoria mais frequente de furniture\nfurniture_mode = (\n    imoveis_missing.furniture\n    .mode()  # <1>\n    .iloc[0]\n)\n\nfurniture_mode\n```\n\n::: {.cell-output .cell-output-display execution_count=178}\n```\n'not furnished'\n```\n:::\n:::\n\n\n1. `.mode()` devolve uma série, pois pode haver empate. `.iloc[0]` seleciona o primeiro valor.\n\nDepois da imputação, todas as lacunas passam a contar como ocorrências dessa categoria. A frequência da moda aumenta artificialmente, um efeito que precisa ser considerado ao interpretar a distribuição resultante.\n\n::: {#ed810eff .cell execution_count=17}\n``` {.python .cell-code}\n# Contagem das categorias antes e depois da imputação\n(\n    pd.concat(\n        {\n            \"Antes\": imoveis_missing.furniture.value_counts(dropna=False),  # <1>\n            \"Depois da moda\": (\n                imoveis_missing.furniture\n                .fillna(furniture_mode)\n                .value_counts()\n            ),\n        },\n        axis=1,\n    )\n    .fillna(0)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=179}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Antes</th>\n      <th>Depois da moda</th>\n    </tr>\n    <tr>\n      <th>furniture</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>not furnished</th>\n      <td>17265</td>\n      <td>19519.0</td>\n    </tr>\n    <tr>\n      <th>furnished</th>\n      <td>9122</td>\n      <td>9122.0</td>\n    </tr>\n    <tr>\n      <th>NaN</th>\n      <td>2254</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `dropna=False` inclui os valores `NaN` na contagem.\n\nEm uma variável quantitativa discreta, como o número de quartos, a média é matematicamente definida, mas pode produzir um valor incompatível com o domínio da variável, como uma quantidade fracionária de quartos:\n\n::: {#c5fb19d1 .cell execution_count=18}\n``` {.python .cell-code}\n# Média, mediana e moda do número de quartos\n(\n    pd.Series(\n        {\n            \"média\": imoveis_missing.rooms.mean(),\n            \"mediana\": imoveis_missing.rooms.median(),\n            \"moda\": (\n                imoveis_missing.rooms\n                .mode()\n                .iloc[0]\n            ),\n        },\n        name=\"quartos\",\n    )\n    .to_frame()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=180}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>quartos</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>média</th>\n      <td>2.262085</td>\n    </tr>\n    <tr>\n      <th>mediana</th>\n      <td>2.000000</td>\n    </tr>\n    <tr>\n      <th>moda</th>\n      <td>2.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 3.3 Resumo da imputação\n\n| Situação | Escolha inicial |\n|---|---|\n| Contínua e simétrica | Média |\n| Assimétrica ou com extremos | Mediana |\n| Categórica ou discreta | Moda ou mediana |\n| Varia entre grupos conhecidos | Estatística por grupo |\n\n::: {.callout-important}\nAntes de imputar, crie uma **coluna indicadora** para distinguir valores observados de estimados.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## E se um grupo não tiver observações?\n\nSua mediana será `NaN`. Use a mediana global como segunda opção. Mesmo quando existe algum valor observado, grupos muito pequenos produzem estimativas com alta variabilidade amostral.\n:::\n\nEncerrada a comparação entre estratégias de imputação, passamos a outro problema. As colunas são expressas em unidades e ordens de grandeza diferentes. As duas próximas seções distinguem o escalonamento, que modifica a representação numérica, das transformações não lineares, que também alteram a forma da distribuição.\n\n# 4. Escalonamento: a régua muda, a forma não\n\nO termo **normalização** não tem uso inteiramente uniforme na literatura e nas bibliotecas. Nesta seção, tratamos de **escalonamento**, isto é, transformações afins do tipo $x' = (x - c)/s$. O parâmetro $c$ representa um centro, como média, mediana ou mínimo, e $s$ representa uma medida de escala, como desvio-padrão, IQR ou amplitude. Essa operação preserva a ordenação das observações. Também multiplica todas as distâncias por uma mesma constante positiva, de modo que o formato do histograma, a assimetria e a curtose não se alteram. Muda a unidade em que a variável é representada.\n\nO objetivo do escalonamento é colocar variáveis numéricas em escalas comparáveis. Algoritmos que calculam distâncias, como k-vizinhos mais próximos e k-médias, são diretamente sensíveis às magnitudes dos atributos. Métodos ajustados por gradiente e modelos com regularização também podem ser afetados. Sem escalonamento, uma variável de maior ordem de grandeza pode dominar o cálculo apenas por causa de sua unidade. A padronização por z-score e o escalonamento Min-Max são duas alternativas conhecidas. O scikit-learn ainda reserva o nome `Normalizer` para a normalização de cada amostra por sua norma vetorial, uma operação diferente das três estudadas aqui. Por isso, convém verificar a definição exata da técnica em vez de confiar apenas no termo empregado.\n\nNa base de imóveis, área em m², aluguel em reais e número de quartos têm ordens de grandeza muito diferentes. Uma diferença de um quarto pode distinguir substancialmente dois imóveis. Uma diferença de R$ 1 no aluguel costuma ser desprezível. O escalonamento permite que essas diferenças sejam comparadas em unidades relativas à distribuição de cada atributo.\n\n## 4.1 Três escaladores\n\nOs três escaladores diferem na escolha do centro e da escala, e essa escolha determina a sensibilidade a valores extremos.\n\n| Técnica | Centro e escala | Sensibilidade a extremos | Indicação |\n|---|---|---|---|\n| `StandardScaler` | Média e desvio-padrão | Alta | Sem extremos importantes |\n| `RobustScaler` | Mediana e IQR | Baixa | Com valores extremos |\n| `MinMaxScaler` | Mínimo e máximo | Muito alta | Limites estáveis |\n\nAplicamos os três escaladores ao aluguel.\n\nOs escaladores do scikit-learn recebem um `DataFrame` e devolvem uma matriz. `.ravel()` converte essa matriz em vetor.\n\n::: {#d91fe0b1 .cell execution_count=19}\n``` {.python .cell-code}\n# Aplica os três escaladores ao aluguel\nrent_frame = imoveis_true[[\"rent_amount\"]]  # <1>\n\nscaled = {\n    \"Original\": rent_frame.rent_amount.to_numpy(),\n    \"StandardScaler\": (\n        StandardScaler()\n        .fit_transform(rent_frame)  # <2>\n        .ravel()\n    ),\n    \"RobustScaler\": (\n        RobustScaler()\n        .fit_transform(rent_frame)\n        .ravel()\n    ),\n    \"MinMaxScaler\": (\n        MinMaxScaler()\n        .fit_transform(rent_frame)\n        .ravel()\n    ),\n}\n```\n:::\n\n\n1. Os colchetes duplos mantêm uma tabela (2D), formato que o scikit-learn espera.\n2. `.fit_transform` estima os parâmetros do escalador (média, IQR ou mínimo e máximo) e já os aplica aos dados.\n\nObserve o eixo horizontal e a assimetria de cada painel:\n\n::: {#09183f09 .cell execution_count=20}\n``` {.python .cell-code}\n# Histograma do aluguel em cada escala\nfig, axes = plt.subplots(1, 4, figsize=(16, 4), sharey=True)\n\nfor ax, (label, values) in zip(axes, scaled.items()):\n    sns.histplot(values, bins=50, ax=ax, color=\"#55A868\")\n    ax.set(\n        title=f\"{label}\\nassimetria = {stats.skew(values):.2f}\",\n        xlabel=\"Escala\",\n        ylabel=\"Imóveis\",\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-21-output-1.png){}\n:::\n:::\n\n\nOs quatro histogramas têm a mesma forma e a mesma assimetria. Apenas os valores do eixo horizontal mudam, porque cada método define uma nova origem e uma nova unidade de medida.\n\n## 4.2 Sensibilidade a extremos\n\nO Min-Max usa o mínimo e o máximo observados como referências. Um único aluguel extremo aumenta a amplitude usada no denominador e comprime os demais valores em uma faixa estreita próxima de zero.\n\nPara ver o efeito, acrescentamos um aluguel fictício de R$ 500 mil e o descartamos depois do ajuste:\n\n::: {#94410a3b .cell execution_count=21}\n``` {.python .cell-code}\n# Min-Max ajustado com um aluguel fictício de R$ 500 mil\nwith_extreme = pd.concat(\n    [rent_frame, pd.DataFrame({\"rent_amount\": [500_000.]})],\n    ignore_index=True,\n)\n\nminmax_extreme = (\n    MinMaxScaler()\n    .fit_transform(with_extreme)\n    .ravel()[:-1]  # <1>\n)\n```\n:::\n\n\n1. `[:-1]` descarta o último valor do vetor, o aluguel fictício.\n\n::: {#256eadc4 .cell execution_count=22}\n``` {.python .cell-code}\n# Min-Max sem e com o valor extremo\nfig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)\n\nfor ax, values, title in zip(\n    axes,\n    [scaled[\"MinMaxScaler\"], minmax_extreme],\n    [\"Sem extremo\", \"Com aluguel de R$ 500 mil\"],\n):\n    sns.histplot(\n        values,\n        bins=50,\n        binrange=(0, 1),\n        ax=ax,\n        color=\"#8172B2\",\n    )\n    ax.set(\n        title=title,\n        xlabel=\"Escala Min-Max\",\n        ylabel=\"Imóveis\",\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-23-output-1.png){}\n:::\n:::\n\n\nCom o extremo, quase todos os imóveis ficam concentrados no início da escala. O `RobustScaler`, baseado na mediana e no IQR, é muito menos sensível a esse efeito. O ponto extremo ainda permanece distante depois da transformação, mas não determina o centro nem a escala usados para representar a maioria das observações.\n\n::: {.callout-important}\n**Escalonar muda a régua, não a forma.**\n:::\n\nO escalonamento tornou as unidades comparáveis, mas o aluguel continua com a mesma cauda longa observada na figura inicial. Poucos imóveis muito caros ainda ocupam grande parte do eixo, enquanto a maioria dos anúncios permanece concentrada à esquerda. Reduzir essa assimetria exige uma transformação não linear.\n\n# 5. Transformações: a forma muda\n\nEsta seção trata do segundo sentido em que o termo **normalização** aparece na literatura. Na seção 4, normalizar significava escalonar, isto é, mudar a origem e a unidade de uma variável sem alterar sua forma. Aqui, normalizar significa transformar a própria distribuição, em geral para aproximá-la de uma forma mais simétrica e, em muitos casos, mais próxima da distribuição normal, origem do nome. As duas operações recebem o mesmo rótulo em textos e bibliotecas, mas produzem efeitos diferentes sobre os dados. Por isso, ao encontrar o termo, convém verificar qual dos dois sentidos está em jogo.\n\nNesta seção, usamos **transformação da distribuição** para designar a aplicação de uma função não linear, como $\\log(x)$ ou uma transformação de potência. O objetivo pode ser reduzir a assimetria, estabilizar a variância ou tornar uma relação multiplicativa mais próxima de uma relação linear. Aproximar a variável de uma distribuição normal é uma finalidade possível, mas não constitui uma exigência geral do pré-processamento.\n\nAo contrário do escalonamento afim, uma função não linear comprime regiões diferentes do eixo em intensidades diferentes. O logaritmo reduz mais as distâncias entre valores altos do que entre valores baixos. Na escala logarítmica, a distância entre R$ 1.000 e R$ 2.000 é igual à distância entre R$ 10.000 e R$ 20.000, pois os dois pares representam a mesma razão. A ordenação é preservada, mas as diferenças absolutas e as razões entre distâncias mudam. Com isso, também podem mudar a assimetria, a curtose e a influência de observações extremas.\n\nEsse tipo de transformação é útil quando a escala original produz forte heterogeneidade de variância, quando relações multiplicativas descrevem melhor o fenômeno ou quando uma cauda longa exerce influência excessiva sobre o ajuste. O custo aparece na interpretação. Um coeficiente ou uma média calculados na escala transformada já não estão expressos diretamente em reais. Transformações como Box-Cox e Yeo-Johnson ampliam as possibilidades do logaritmo ao estimar, a partir dos dados, um parâmetro de potência associado à aproximação da normalidade.\n\nQuando o problema é a cauda longa, mudar a régua não basta. É preciso mudar a **forma** da distribuição. A escolha da transformação depende dos valores que a variável aceita: algumas exigem valores estritamente positivos, outras aceitam zero ou até negativos.\n\n## 5.1 Aluguel positivo: log e Box-Cox\n\nNesta base, todos os aluguéis são estritamente positivos, condição necessária para aplicar `log` e Box-Cox. Começamos pelo logaritmo, frequentemente adequado a valores monetários com variação multiplicativa, e o comparamos com Box-Cox, que estima um parâmetro de potência a partir dos dados.\n\n`stats.boxcox` devolve os valores transformados e o λ estimado.\n\n::: {#e121bbf2 .cell execution_count=23}\n``` {.python .cell-code}\n# Aluguel original, em log e em Box-Cox\nrent = imoveis_true.rent_amount\n\nboxcox_rent, boxcox_lambda = stats.boxcox(rent)  # <1>\n\nrent_transformed = {\n    \"Original\": rent,\n    \"log\": np.log(rent),\n    f\"Box-Cox (λ={boxcox_lambda:.2f})\": boxcox_rent,\n}\n```\n:::\n\n\n1. `stats.boxcox` devolve uma tupla com os valores transformados e o λ estimado.\n\n::: {#2cdf6344 .cell execution_count=24}\n``` {.python .cell-code}\n# Histogramas das transformações do aluguel\nfig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)\n\nfor ax, (label, values) in zip(axes, rent_transformed.items()):\n    sns.histplot(values, bins=50, ax=ax, color=\"#C44E52\")\n    ax.set(\n        title=f\"{label}\\nassimetria = {stats.skew(values):.2f}\",\n        xlabel=\"Escala\",\n        ylabel=\"Imóveis\",\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-25-output-1.png){}\n:::\n:::\n\n\nBox-Cox estima o parâmetro λ por máxima verossimilhança sob a hipótese de que os valores transformados se aproximam de uma distribuição normal. Quando λ = 0, sua definição corresponde ao logaritmo natural.\n\nO valor de λ próximo de zero mostra que, dentro da família Box-Cox, a transformação estimada é muito semelhante ao logaritmo. Isso sustenta o uso de `log` para o aluguel desta base.\n\nNem toda variável, porém, é estritamente positiva. Quando há zeros, o logaritmo deixa de ser definido, e é preciso recorrer a variantes.\n\n## 5.2 Distância com zeros: `log1p` e Yeo-Johnson\n\nA distância ao transporte pode ser igual a zero para imóveis localizados junto a uma estação. Como `log` e Box-Cox exigem valores estritamente positivos, não podem ser aplicados diretamente. Duas alternativas são `log1p`, que calcula $\\log(1+x)$, e Yeo-Johnson, uma transformação de potência definida também para zero e valores negativos.\n\nCom `standardize=False`, o `PowerTransformer` apenas transforma, sem escalonar.\n\n::: {#f2d17f5b .cell execution_count=25}\n``` {.python .cell-code}\n# Distância original, em log1p e em Yeo-Johnson\ntransit = imoveis_true.transit_distance_min\n\npt = PowerTransformer(method=\"yeo-johnson\", standardize=False)\n\ntransit_yj = (\n    pt\n    .fit_transform(imoveis_true[[\"transit_distance_min\"]])\n    .ravel()\n)\n\ntransformed = {\n    \"Original\": transit,\n    \"log1p\": np.log1p(transit),  # <1>\n    f\"Yeo-Johnson (λ={pt.lambdas_[0]:.2f})\": transit_yj,  # <2>\n}\n```\n:::\n\n\n1. `np.log1p` calcula $\\log(1 + x)$, que é definido em zero.\n2. `pt.lambdas_` guarda um λ para cada coluna ajustada. Aqui há apenas uma.\n\n::: {#08fc2141 .cell execution_count=26}\n``` {.python .cell-code}\n# Histogramas das transformações da distância\nfig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)\n\nfor ax, (label, values) in zip(axes, transformed.items()):\n    sns.histplot(values, bins=50, ax=ax, color=\"#DD8452\")\n    ax.set(\n        title=f\"{label}\\nassimetria = {stats.skew(values):.2f}\",\n        xlabel=\"Escala\",\n        ylabel=\"Imóveis\",\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-27-output-1.png){}\n:::\n:::\n\n\nCompare as assimetrias:\n\n- `log1p` aceita zeros, mas aqui comprime a cauda direita além do necessário,\n- Yeo-Johnson aceita qualquer sinal e estima uma transformação mais branda.\n\n## 5.3 Resumo das transformações\n\n| Técnica | Valores aceitos | Interpretação |\n|---|---|---|\n| `log` | Positivos | Boa: diferenças representam razões |\n| `log1p` | Zero e positivos | Boa, com inversa `expm1` |\n| Box-Cox | Positivos | Menos direta |\n| Yeo-Johnson | Qualquer sinal | Menos direta |\n\n::: {.callout-note collapse=\"true\"}\n## Fórmula e interpretação\n\nA transformação de Box-Cox é dada por:\n\n$$\nx^{(\\lambda)} =\n\\begin{cases}\n\\dfrac{x^\\lambda - 1}{\\lambda}, & \\lambda \\ne 0 \\\\[6pt]\n\\log(x), & \\lambda = 0\n\\end{cases}\n$$\n\nPara voltar à unidade original:\n\n- após `log`, use `np.exp`,\n- após `log1p`, use `np.expm1`.\n:::\n\n::: {.callout-important}\n**Transformar muda a forma.** A redução da assimetria deve ser avaliada junto com a perda de interpretação direta na unidade original.\n:::\n\nAté aqui, cada técnica foi estudada isoladamente, em uma ou duas variáveis e sobre a base de gabarito. Na prática, porém, as decisões são aplicadas em conjunto e na ordem certa, sobre a base original, com suas lacunas reais.\n\n# 6. Aplicação e comparação final\n\nEsta seção reúne as decisões anteriores em um único fluxo aplicado à base completa. A ordem das operações importa. As colunas indicadoras precisam ser criadas antes da imputação, enquanto as posições originalmente ausentes ainda são identificáveis. A imputação precede as transformações para que as medianas sejam calculadas e interpretadas na unidade original.\n\nAplicamos as decisões em três etapas.\n\n## 6.1 Registrar as lacunas\n\nAs colunas indicadoras são criadas **antes** da imputação. Depois dela, o rastro se perderia.\n\n::: {#b33596d0 .cell execution_count=27}\n``` {.python .cell-code}\n# Colunas indicadoras das lacunas originais\nimoveis_processed = (\n    imoveis\n    .assign(\n        hoa_missing=lambda x: x.hoa.isna(),\n        parking_spaces_missing=lambda x: x.parking_spaces.isna(),\n    )\n)\n```\n:::\n\n\n## 6.2 Imputar pela mediana do grupo\n\nOs grupos combinam tipo de imóvel e `tier`. Grupos sem observações recebem a mediana global.\n\n::: {#216b24ef .cell execution_count=28}\n``` {.python .cell-code}\n# Imputa hoa e vagas pela mediana de cada grupo\ngroups = [\"property_type\", \"tier\"]\n\nimoveis_processed = (\n    imoveis_processed\n    .assign(\n        hoa=lambda x: (\n            x\n            .groupby(groups)\n            .hoa\n            .transform(lambda s: s.fillna(s.median()))\n            .fillna(imoveis.hoa.median())  # <1>\n        ),\n        parking_spaces=lambda x: (\n            x\n            .groupby(groups)\n            .parking_spaces\n            .transform(lambda s: s.fillna(s.median()))\n            .fillna(imoveis.parking_spaces.median())  # <1>\n        ),\n    )\n)\n```\n:::\n\n\n1. Grupos sem observações recebem a mediana global como segunda opção.\n\nConferimos que não restaram lacunas e quantos valores foram estimados:\n\n::: {#09b9971b .cell execution_count=29}\n``` {.python .cell-code}\n# Lacunas restantes e valores estimados\n(\n    imoveis_processed\n    .agg(\n        {\n            \"hoa\": lambda s: s.isna().sum(),  # <1>\n            \"parking_spaces\": lambda s: s.isna().sum(),  # <1>\n            \"hoa_missing\": \"sum\",  # <2>\n            \"parking_spaces_missing\": \"sum\",  # <2>\n        }\n    )\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=191}\n```\nhoa                         0\nparking_spaces              0\nhoa_missing               505\nparking_spaces_missing    297\ndtype: int64\n```\n:::\n:::\n\n\n1. Lacunas que restaram em cada coluna. O esperado é zero.\n2. Valores estimados, contados pelas colunas indicadoras.\n\n## 6.3 Reduzir as caudas\n\nSeguimos o resumo da seção 5.3:\n\n- área e valores monetários são positivos e recebem `log`,\n- a distância, que pode ser zero, recebe Yeo-Johnson.\n\n::: {#d8f663f1 .cell execution_count=30}\n``` {.python .cell-code}\n# Log nas variáveis positivas e Yeo-Johnson na distância\nimoveis_processed = (\n    imoveis_processed\n    .assign(\n        area=lambda x: np.log(x.area),\n        rent_amount=lambda x: np.log(x.rent_amount),\n        property_tax=lambda x: np.log(x.property_tax),\n        total=lambda x: np.log(x.total),\n        transit_distance_min=lambda x: stats.yeojohnson(\n            x.transit_distance_min\n        )[0],  # <1>\n    )\n)\n```\n:::\n\n\n1. `stats.yeojohnson` devolve os valores transformados e o λ estimado. `[0]` seleciona os valores.\n\n## 6.4 Antes e depois\n\nComparamos as distribuições das cinco variáveis transformadas:\n\n::: {#cc17066c .cell execution_count=31}\n``` {.python .cell-code}\n# Variáveis comparadas e seus rótulos nos gráficos\ncolumns = [\n    \"area\",\n    \"rent_amount\",\n    \"property_tax\",\n    \"total\",\n    \"transit_distance_min\",\n]\n\nlabels = [\"Área\", \"Aluguel\", \"IPTU\", \"Total\", \"Distância\"]\n```\n:::\n\n\n::: {#8ae1a6c2 .cell execution_count=32}\n``` {.python .cell-code}\n# Distribuições antes (linha de cima) e depois (linha de baixo)\nfig, axes = plt.subplots(2, 5, figsize=(18, 7))\n\nfor col, label, ax1, ax2 in zip(columns, labels, axes[0], axes[1]):\n    before, after = imoveis[col], imoveis_processed[col]\n    sns.histplot(before, bins=50, ax=ax1, color=\"#4C72B0\")\n    ax1.set(\n        title=f\"{label}: antes\\nassimetria = {stats.skew(before):.2f}\",\n        xlabel=\"\",\n        ylabel=\"Imóveis\",\n    )\n    sns.histplot(after, bins=50, ax=ax2, color=\"#55A868\")\n    ax2.set(\n        title=f\"{label}: depois\\nassimetria = {stats.skew(after):.2f}\",\n        xlabel=\"\",\n        ylabel=\"Imóveis\",\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](06-imputacao-normalizacao-dados_files/figure-ipynb/cell-33-output-1.png){}\n:::\n:::\n\n\nNa linha inferior, as distribuições apresentam menor assimetria, e os valores extremos ocupam uma parcela menor do eixo. Isso não significa que os extremos foram removidos. Suas distâncias em relação ao centro foram comprimidas pela transformação.\n\n::: {.callout-warning collapse=\"true\"}\n## Evite vazamento\n\nEm um projeto de modelagem, os dados são divididos em treino e teste.\n\nMedianas, parâmetros λ e parâmetros dos escaladores devem ser estimados **apenas no conjunto de treino**. Em seguida, os mesmos valores estimados são aplicados ao conjunto de teste. Ajustá-los antes da separação permite que informações do teste influenciem o pré-processamento e produz vazamento de dados.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Extensão opcional: ydata-profiling\n\nO relatório automático é útil para auditoria, mas não é necessário para o argumento visual da aula.\n\n::: {#fb761de1 .cell execution_count=33}\n``` {.python .cell-code}\n# Relatório comparativo antes e depois do pré-processamento\nfrom ydata_profiling import ProfileReport, compare\n\nbefore = ProfileReport(\n    imoveis,\n    minimal=True,\n)\n\nafter = ProfileReport(\n    imoveis_processed,\n    minimal=True,\n)\n\n(\n    compare([before, after])\n    .to_file(\n        \"imoveis-sao-paulo/reports/comparacao_pre_processamento.html\"\n    )\n)\n```\n:::\n\n\n:::\n\n# 7. Guia rápido\n\nA tabela reúne as decisões discutidas no roteiro. Ela oferece critérios iniciais, não regras automáticas. A escolha final depende do mecanismo de ausência, da distribuição observada, do modelo empregado e do objetivo da análise.\n\n| Problema | Técnica |\n|---|---|\n| Ausência estrutural | Não imputar, registrar |\n| Contínua simétrica | Média |\n| Assimétrica ou com extremos | Mediana |\n| Categórica ou discreta | Moda ou mediana |\n| Varia entre grupos | Mediana por grupo |\n| Escalas diferentes, sem extremos | Z-score |\n| Escalas diferentes, com extremos | RobustScaler |\n| Limites estáveis | Min-Max |\n| Cauda positiva | Log ou Box-Cox |\n| Cauda com zeros | log1p ou Yeo-Johnson |\n\n## Síntese\n\nTrês classes de tratamento foram aplicadas à base de imóveis:\n\n1. **Imputação.** Nem toda ausência corresponde a um valor que deveria existir. Quando a imputação for apropriada, a estratégia deve considerar o tipo da variável, sua distribuição e as informações disponíveis em outros atributos. Uma coluna indicadora preserva o registro das posições estimadas.\n2. **Escalonamento.** Uma transformação afim altera a origem e a unidade da variável sem modificar a forma de sua distribuição. A presença de valores extremos influencia a escolha entre parâmetros convencionais, como média e desvio-padrão, e parâmetros robustos, como mediana e IQR.\n3. **Transformação.** Uma função não linear modifica as distâncias entre observações e pode reduzir a assimetria. Essa mudança pode favorecer a modelagem, mas exige cuidado ao interpretar e comunicar resultados na escala original.\n\n# Perguntas para consolidar\n\n## Pergunta 1: imputar sempre melhora a análise?\n\nA seção 2 mostrou lacunas que não deveriam ser preenchidas. Em que situação uma estratégia com MAE baixo no experimento controlado ainda pode piorar a análise quando aplicada à base real?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nO MAE mede a distância entre valores imputados e valores verdadeiros nas posições apagadas artificialmente. Ele avalia o desempenho sob o mecanismo de ausência usado na simulação. Não demonstra que a variável seja aplicável a todas as observações nem que o mesmo padrão de ausência exista na base real.\n\nNo caso do andar de uma casa, não existe valor verdadeiro a estimar, pois o atributo não se aplica à observação. O MAE nem sequer é uma métrica conceitualmente válida para esse caso. Em lacunas não estruturais, uma estratégia também pode apresentar baixo MAE sob MCAR e introduzir viés quando a ausência real depende do valor omitido. Imputações por constantes ainda reduzem a variabilidade observada e criam concentrações artificiais. Sem uma coluna indicadora, deixa de ser possível separar o que foi observado do que foi estimado.\n:::\n\n## Pergunta 2: por que o `StandardScaler` não resolveu a assimetria?\n\nNa seção 4.1, os três escaladores produziram a mesma assimetria do aluguel original. Por que isso acontece?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nOs escaladores estudados aplicam uma transformação afim. Eles subtraem um centro e dividem por uma constante positiva. A operação desloca o eixo e multiplica todas as distâncias pela mesma constante.\n\nComo todas as distâncias são multiplicadas pelo mesmo fator, os momentos padronizados que definem assimetria e curtose permanecem iguais. Para mudar a forma, precisamos de uma transformação não linear, como `log` ou Box-Cox.\n:::\n\n## Pergunta 3: qual escala você apresentaria ao gestor?\n\nO `log` reduziu fortemente a assimetria do aluguel. Você apresentaria ao gestor um gráfico do aluguel em escala log?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nDepende do objetivo e do público. Para determinados modelos estatísticos, a escala transformada pode produzir relações mais lineares, variância mais estável ou menor influência da cauda.\n\nPara comunicação, a unidade original em reais costuma ser mais direta. Uma possibilidade é ajustar o modelo na escala logarítmica e converter previsões com `np.exp` antes de apresentá-las. Essa conversão exige atenção. A exponencial de uma previsão média na escala log não coincide, em geral, com a média condicional na escala original sem uma correção de retransformação.\n:::\n\n# Para casa\n\n1. Compare o MAE da média e da mediana para `rooms` e relacione o resultado à assimetria e ao caráter discreto da variável.\n2. Impute o aluguel por `tier` e `zona`. Depois, use o bairro como grupo e discuta o efeito de grupos pequenos.\n3. Entre apartamentos, compare `log1p`, Box-Cox e Yeo-Johnson para `hoa`. Qual produz menor assimetria? Qual você apresentaria a um gestor?\n4. Antes de considerar o notebook pronto, use Restart Kernel and Run All.\n\n> Escalonar muda a régua. Transformar muda a forma. Imputar muda os dados e deve deixar rastro.\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3\n    language: python\n    name: python3\n    path: /home/oandrefonseca/.local/share/jupyter/kernels/python3\n---\n",
    "supporting": [
      "06-imputacao-normalizacao-dados_files/figure-ipynb"
    ],
    "filters": []
  }
}