{
  "hash": "9d04c75c19faebf0474f5259a699d7ed",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Aula 8 - Testes Paramétricos'\ndate: last-modified\ntoc: true\nformat:\n  html: default\n  ipynb: default\njupyter:\n  kernel: python3\nexecute:\n  enabled: true\n---\n\n\n## Motivação\n\nNa Aula 7, construímos a distribuição nula de duas formas: embaralhando rótulos, no teste de permutação, e por fórmula, no teste *t* de Welch. Vimos também como ler o *p*-valor, como decidir com $\\alpha$ e quais erros essa decisão pode cometer. Nesta aula, partimos desse ponto e respondemos a duas perguntas novas. **Quando** a distribuição nula pode vir de uma fórmula? E, diante de dados de natureza diferente, **qual** fórmula usar?\n\nUm teste paramétrico troca a simulação por uma curva teórica: *t*, *F*, *Z* ou $\\chi^2$. Essa troca só é segura quando os dados cumprem certas premissas. A escolha da curva, por sua vez, depende do que medimos e de como as observações foram coletadas. A primeira parte do roteiro trata dessas condições. A segunda aplica sete testes a sete problemas reais, cada um com seu próprio conjunto de dados.\n\n> **Qual teste responde à minha pergunta, e posso confiar nele?**\n\n## Objetivos de aprendizagem\n\nAo final deste roteiro, você será capaz de:\n\n1. Explicar o que torna um teste *paramétrico* e o que se ganha e se arrisca com ele.\n2. Verificar normalidade, homocedasticidade e independência com Q-Q plot, Shapiro-Wilk e o desenho do estudo.\n3. Escolher o teste pelo objetivo, pela escala da variável e pelo delineamento.\n4. Aplicar em Python os testes *t* de uma amostra, de Welch e pareado, a ANOVA, a correlação de Pearson, o teste *Z* de duas proporções e o $\\chi^2$ de independência.\n5. Interpretar os resultados e reconhecer quando migrar para um teste não paramétrico.\n\n::: {.callout-tip}\n## Como usar este roteiro\n\nO roteiro usa cinco conjuntos de dados, cada um salvo em `<nome>/data/`:\n\n| Base | Origem | Casos |\n|---|---|---|\n| `mtcars` | Revista *Motor Trend*, 1974 (já usada na Aula 7) | 1 e 5 |\n| `penguins` | Pinguins do arquipélago Palmer, Antártida | 2 |\n| `sleep` | Ensaio clínico com dois soníferos (Student, 1908) | 3 |\n| `iris` | Flores de três espécies de íris (Fisher, 1936) | 4 |\n| `titanic` | Passageiros do naufrágio do Titanic, 1912 | 2.3, 6 e 7 |\n\nAlém das bibliotecas da Aula 7, usamos o `statsmodels` no caso 6.\n:::\n\n# 1. Preparando os dados\n\nComeçamos com as bibliotecas e as cinco bases. A seção 1.1 apresenta as bases que aparecem pela primeira vez no curso.\n\n::: {#a15e974f .cell execution_count=1}\n``` {.python .cell-code}\n# Importa as bibliotecas e define o tema dos gráficos\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nfrom statsmodels.stats.proportion import proportions_ztest, proportion_confint\n\nsns.set_theme(style=\"whitegrid\", palette=\"colorblind\")\n```\n:::\n\n\n::: {#b00f03a5 .cell execution_count=2}\n``` {.python .cell-code}\n# Carrega as cinco bases\nmtcars = pd.read_csv(\"mtcars/data/mtcars.csv\")\npenguins = pd.read_csv(\"penguins/data/penguins.csv\")\nsleep = pd.read_csv(\"sleep/data/sleep.csv\")\niris = pd.read_csv(\"iris/data/iris.csv\")\ntitanic = pd.read_csv(\"titanic/data/titanic.csv\")\n```\n:::\n\n\n## 1.1 Conhecendo as bases\n\nO `mtcars` já foi apresentado na Aula 7: são 32 linhas, uma por modelo de carro, e 12 colunas. As outras quatro bases aparecem pela primeira vez. Para cada uma, olhamos as cinco primeiras linhas e descrevemos suas variáveis.\n\nAs bases têm tamanhos bem diferentes, do ensaio clínico com 20 registros ao Titanic com quase 900 passageiros. Isso influencia diretamente as decisões desta aula. Com 20 registros, a normalidade precisa ser **verificada com cuidado**. Com centenas, o teorema central do limite torna o teste *t* robusto, mas o Shapiro-Wilk passa a rejeitar desvios pequenos.\n\n### `penguins`\n\nMedidas de pinguins adultos coletadas entre 2007 e 2009 em três ilhas do arquipélago Palmer, na Antártida. São 344 linhas, uma por pinguim, e 8 colunas.\n\n::: {#e9e2656b .cell execution_count=3}\n``` {.python .cell-code}\n# Cinco primeiras linhas da base de pinguins\npenguins.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=579}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>species</th>\n      <th>island</th>\n      <th>bill_len</th>\n      <th>bill_dep</th>\n      <th>flipper_len</th>\n      <th>body_mass</th>\n      <th>sex</th>\n      <th>year</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Adelie</td>\n      <td>Torgersen</td>\n      <td>39.1</td>\n      <td>18.7</td>\n      <td>181.0</td>\n      <td>3750.0</td>\n      <td>male</td>\n      <td>2007</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Adelie</td>\n      <td>Torgersen</td>\n      <td>39.5</td>\n      <td>17.4</td>\n      <td>186.0</td>\n      <td>3800.0</td>\n      <td>female</td>\n      <td>2007</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Adelie</td>\n      <td>Torgersen</td>\n      <td>40.3</td>\n      <td>18.0</td>\n      <td>195.0</td>\n      <td>3250.0</td>\n      <td>female</td>\n      <td>2007</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Adelie</td>\n      <td>Torgersen</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2007</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Adelie</td>\n      <td>Torgersen</td>\n      <td>36.7</td>\n      <td>19.3</td>\n      <td>193.0</td>\n      <td>3450.0</td>\n      <td>female</td>\n      <td>2007</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n- `species`: espécie do pinguim (Adelie, Chinstrap ou Gentoo).\n- `island`: ilha onde o animal foi observado (Biscoe, Dream ou Torgersen).\n- `bill_len`: comprimento do bico, em milímetros.\n- `bill_dep`: profundidade (altura) do bico, em milímetros.\n- `flipper_len`: comprimento da nadadeira, em milímetros.\n- `body_mass`: massa corporal, em gramas.\n- `sex`: sexo do animal (`female` ou `male`). Está ausente em 11 pinguins.\n- `year`: ano da observação (2007, 2008 ou 2009).\n\n### `sleep`\n\nDados do ensaio clínico usado por Student em 1908 para apresentar o teste *t*. Dez pacientes receberam dois soníferos, em períodos diferentes. São 20 linhas, uma por paciente e droga, e 3 colunas.\n\n::: {#eb776220 .cell execution_count=4}\n``` {.python .cell-code}\n# Cinco primeiras linhas da base do ensaio de sono\nsleep.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=580}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>extra</th>\n      <th>group</th>\n      <th>ID</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.7</td>\n      <td>1</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>-1.6</td>\n      <td>1</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>-0.2</td>\n      <td>1</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>-1.2</td>\n      <td>1</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>-0.1</td>\n      <td>1</td>\n      <td>5</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n- `extra`: aumento nas horas de sono em relação ao período sem medicamento. Valores negativos indicam que o paciente dormiu menos.\n- `group`: droga administrada (1 ou 2).\n- `ID`: identificação do paciente (1 a 10). Cada paciente aparece duas vezes, uma com cada droga.\n\n### `iris`\n\nMedidas de flores de três espécies do gênero *Iris*, publicadas por R. A. Fisher em 1936. São 150 linhas, uma por flor (50 de cada espécie), e 5 colunas.\n\n::: {#4cac53ba .cell execution_count=5}\n``` {.python .cell-code}\n# Cinco primeiras linhas da base de íris\niris.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=581}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>sepal_length</th>\n      <th>sepal_width</th>\n      <th>petal_length</th>\n      <th>petal_width</th>\n      <th>species</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>5.1</td>\n      <td>3.5</td>\n      <td>1.4</td>\n      <td>0.2</td>\n      <td>setosa</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>4.9</td>\n      <td>3.0</td>\n      <td>1.4</td>\n      <td>0.2</td>\n      <td>setosa</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>4.7</td>\n      <td>3.2</td>\n      <td>1.3</td>\n      <td>0.2</td>\n      <td>setosa</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4.6</td>\n      <td>3.1</td>\n      <td>1.5</td>\n      <td>0.2</td>\n      <td>setosa</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5.0</td>\n      <td>3.6</td>\n      <td>1.4</td>\n      <td>0.2</td>\n      <td>setosa</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n- `sepal_length` e `sepal_width`: comprimento e largura da sépala, a parte externa e geralmente verde que protege a flor, em centímetros.\n- `petal_length` e `petal_width`: comprimento e largura da pétala, em centímetros.\n- `species`: espécie da flor (setosa, versicolor ou virginica).\n\n### `titanic`\n\nRegistros de passageiros do naufrágio do Titanic, em abril de 1912. São 891 linhas, uma por passageiro, e 15 colunas.\n\n::: {#4dea1e8b .cell execution_count=6}\n``` {.python .cell-code}\n# Cinco primeiras linhas da base do Titanic\ntitanic.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=582}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>survived</th>\n      <th>pclass</th>\n      <th>sex</th>\n      <th>age</th>\n      <th>sibsp</th>\n      <th>parch</th>\n      <th>fare</th>\n      <th>embarked</th>\n      <th>class</th>\n      <th>who</th>\n      <th>adult_male</th>\n      <th>deck</th>\n      <th>embark_town</th>\n      <th>alive</th>\n      <th>alone</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>3</td>\n      <td>male</td>\n      <td>22.0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>7.2500</td>\n      <td>S</td>\n      <td>Third</td>\n      <td>man</td>\n      <td>True</td>\n      <td>NaN</td>\n      <td>Southampton</td>\n      <td>no</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>1</td>\n      <td>female</td>\n      <td>38.0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>71.2833</td>\n      <td>C</td>\n      <td>First</td>\n      <td>woman</td>\n      <td>False</td>\n      <td>C</td>\n      <td>Cherbourg</td>\n      <td>yes</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1</td>\n      <td>3</td>\n      <td>female</td>\n      <td>26.0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>7.9250</td>\n      <td>S</td>\n      <td>Third</td>\n      <td>woman</td>\n      <td>False</td>\n      <td>NaN</td>\n      <td>Southampton</td>\n      <td>yes</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>1</td>\n      <td>female</td>\n      <td>35.0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>53.1000</td>\n      <td>S</td>\n      <td>First</td>\n      <td>woman</td>\n      <td>False</td>\n      <td>C</td>\n      <td>Southampton</td>\n      <td>yes</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>0</td>\n      <td>3</td>\n      <td>male</td>\n      <td>35.0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>8.0500</td>\n      <td>S</td>\n      <td>Third</td>\n      <td>man</td>\n      <td>True</td>\n      <td>NaN</td>\n      <td>Southampton</td>\n      <td>no</td>\n      <td>True</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n- `survived`: se o passageiro sobreviveu (1) ou não (0).\n- `pclass`: classe da passagem (1, 2 ou 3).\n- `sex`: sexo do passageiro (`female` ou `male`).\n- `age`: idade, em anos. Está ausente em 177 passageiros.\n- `sibsp`: número de irmãos e cônjuges a bordo.\n- `parch`: número de pais e filhos a bordo.\n- `fare`: valor pago pela passagem, em libras esterlinas.\n- `embarked`: porto de embarque, abreviado (C, Q ou S).\n- `class`: classe da passagem, por extenso (First, Second ou Third).\n- `who`: categoria do passageiro (`man`, `woman` ou `child`).\n- `adult_male`: se o passageiro é um homem adulto (`True` ou `False`).\n- `deck`: convés da cabine. Está ausente em 688 passageiros.\n- `embark_town`: porto de embarque, por extenso (Cherbourg, Queenstown ou Southampton).\n- `alive`: sobrevivência em texto (`yes` ou `no`), equivalente a `survived`.\n- `alone`: se o passageiro viajava sem familiares (`True` ou `False`).\n\nAlgumas colunas do Titanic repetem a mesma informação em formatos diferentes: `class` e `pclass`, `alive` e `survived`, `embark_town` e `embarked`. Nos casos 6 e 7, usamos as versões numéricas ou abreviadas.\n\n# 2. O que um teste paramétrico exige\n\n## 2.1 A curva teórica e sua largura\n\nUm teste paramétrico não simula a distribuição nula: ele supõe que os dados seguem uma família conhecida, como a normal, e lê o *p*-valor como uma área sob uma curva teórica. No caso de uma média, a estatística e a largura da curva são:\n\n$$\nt = \\frac{\\bar{x} - \\mu_0}{SE}\n\\qquad\\qquad\nSE = \\frac{s}{\\sqrt{n}}\n$$\n\nAqui, $\\mu_0$ é o valor de referência sob $H_0$. Sob $H_0$, *t* segue a distribuição *t* de Student com $n - 1$ graus de liberdade.\n\nO erro-padrão decide se uma diferença é grande ou pequena. Considere a mesma diferença de 1,5 unidade em duas amostras de 20 observações, uma com dados pouco dispersos ($SE = 0{,}52$) e outra com dados muito dispersos ($SE = 1{,}29$). Na @fig-same-diff, a diferença está na mesma posição nos dois painéis. O que muda é a largura da curva ao redor dela.\n\n::: {#cell-fig-same-diff .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![A mesma diferença observada (1,5 unidade, linha laranja) diante de duas distribuições nulas com larguras diferentes. As áreas sombreadas são as diferenças tão ou mais extremas que a observada, nos dois sentidos. Com erro-padrão pequeno (esquerda), elas somam cerca de 1%. Com erro-padrão grande (direita), cerca de 26%.](08-testes-parametricos_files/figure-html/fig-same-diff-output-1.png){#fig-same-diff width=1041 height=350}\n:::\n:::\n\n\nDividindo a diferença pelo erro-padrão, os dois cenários vão para a mesma régua (@fig-t-scale). O primeiro dá $t = 2{,}88$ e cai na região de rejeição ($p \\approx 0{,}01$). O segundo dá $t = 1{,}16$ e cai no miolo da curva ($p \\approx 0{,}26$).\n\n::: {#cell-fig-t-scale .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Os dois cenários na escala da estatística *t*, sobre a distribuição *t* com 19 graus de liberdade. As áreas sombreadas formam a região de rejeição para α = 0,05. O valor t = 2,88 (erro-padrão pequeno) cai na cauda e leva à rejeição de H₀. O valor t = 1,16 (erro-padrão grande) cai no miolo.](08-testes-parametricos_files/figure-html/fig-t-scale-output-1.png){#fig-t-scale width=753 height=349}\n:::\n:::\n\n\nA diferença é a mesma, mas as conclusões são opostas. E nenhuma das duas merece confiança se as premissas do teste não valerem.\n\n## 2.2 As três premissas clássicas\n\nPremissas violadas distorcem o erro-padrão e a forma da distribuição nula. Na prática, o $\\alpha$ de 5% deixa de ser 5%.\n\n| Premissa | O que afirma | Se falhar |\n|---|---|---|\n| **Normalidade** | A resposta, ou os resíduos do modelo, segue uma distribuição normal na população | A distribuição da estatística muda, e o *p*-valor se descalibra em amostras pequenas |\n| **Homocedasticidade** | A variância é a mesma em todos os grupos: $\\sigma_1^2 = \\sigma_2^2 = \\dots$ | O erro-padrão combinado fica errado. A solução é a versão de Welch |\n| **Independência** | A medida de uma unidade não influencia as demais | Nenhum ajuste de fórmula resolve. É preciso mudar o desenho do teste, por exemplo para o pareado |\n\nA independência é a premissa mais crítica e também a única que não se verifica olhando os dados: ela depende de **como** foram coletados. A homocedasticidade se verifica comparando os desvios-padrão dos grupos ou com o teste de Levene, que aparecerá nos casos 2 e 4. A normalidade tem ferramentas próprias, apresentadas a seguir.\n\n## 2.3 Verificando a normalidade\n\nHá dois instrumentos complementares:\n\n- **Diagnóstico gráfico.** O histograma com a curva normal revela assimetria, bimodalidade e valores atípicos. O **Q-Q plot** compara os quantis da amostra com os quantis esperados de uma normal. Se os dados forem normais, os pontos seguem uma reta.\n- **Teste formal.** O **Shapiro-Wilk** testa $H_0$: os dados vêm de uma normal. A estatística $W$ varia de 0 a 1, e valores próximos de 1 indicam forma próxima da normal. Se $p < \\alpha$, rejeitamos a normalidade.\n\nO gráfico mostra **como** os dados fogem da normal. O teste diz **se** o desvio é maior que o esperado pelo acaso. Cada forma de distribuição deixa uma assinatura típica no Q-Q plot:\n\n| Forma da distribuição | Assinatura no Q-Q plot |\n|---|---|\n| Normal | Pontos sobre a reta |\n| Assimetria à direita | Curva em U: as duas pontas acima da reta |\n| Assimetria à esquerda | Arco (∩): as duas pontas abaixo da reta |\n| Caudas pesadas | Forma de S: as pontas fogem da reta em sentidos opostos |\n| Caudas leves | S invertido: as pontas achatadas |\n| Bimodal | Degrau no meio: faltam observações no centro |\n\nVejamos dois casos reais: o consumo dos carros do `mtcars` e o preço das passagens do Titanic.\n\n::: {#c0050644 .cell execution_count=9}\n``` {.python .cell-code}\n# Q-Q plot e Shapiro-Wilk em duas variáveis reais\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\n\nfor ax, values, title in zip(\n    axes,\n    [mtcars[\"mpg\"], titanic[\"fare\"]],\n    [\"mtcars · mpg (n = 32)\", \"titanic · fare (n = 891)\"],\n):\n    stats.probplot(values, dist=\"norm\", plot=ax)  # <1>\n    ax.set(title=title, xlabel=\"Quantil teórico da normal\",\n           ylabel=\"Quantil da amostra\")\n\nplt.tight_layout()\nplt.show()\n\npd.DataFrame(\n    {\n        \"mpg\": stats.shapiro(mtcars[\"mpg\"]),\n        \"fare\": stats.shapiro(titanic[\"fare\"]),\n    },\n    index=[\"W\", \"p\"],\n).T  # <2>\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-10-output-1.png){width=945 height=368}\n:::\n\n::: {.cell-output .cell-output-display execution_count=585}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>W</th>\n      <th>p</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>mpg</th>\n      <td>0.947565</td>\n      <td>1.228814e-01</td>\n    </tr>\n    <tr>\n      <th>fare</th>\n      <td>0.521891</td>\n      <td>1.084044e-43</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `stats.probplot` ordena os valores e os compara com os quantis de uma normal. Com `plot=ax`, desenha os pontos e a reta de referência.\n2. `stats.shapiro` devolve a estatística $W$ e o *p*-valor.\n\nOs dois diagnósticos concordam. No `mtcars`, os pontos seguem a reta, com um leve afastamento só na cauda direita. O Shapiro-Wilk dá $W \\approx 0{,}95$ e $p \\approx 0{,}12$: não rejeitamos a normalidade. No Titanic, o Q-Q plot forma uma curva acentuada, a assinatura de forte assimetria à direita. Algumas tarifas ficam quase 10 desvios-padrão acima da média. O teste dá $W \\approx 0{,}52$ e um *p*-valor praticamente zero.\n\n::: {.callout-warning}\n## Cuidado com o tamanho da amostra\n\nCom *n* pequeno, o Shapiro-Wilk tem pouco poder e deixa passar desvios importantes. Com *n* grande, rejeita desvios irrelevantes. Por isso, a decisão nunca deve se apoiar só no *p*-valor do teste: olhe sempre o Q-Q plot. Lembre também que, pelo teorema central do limite, com amostras moderadas ou grandes o que precisa ser aproximadamente normal é a **média**, não cada observação.\n:::\n\n## 2.4 O tipo de variável\n\nSaber a forma da distribuição não basta. O teste também depende de **o que** medimos. A escala da variável resposta define quais operações fazem sentido e, portanto, quais testes podem ser aplicados:\n\n| Tipo | Exemplo | Operações permitidas |\n|---|---|---|\n| Numérica contínua | Consumo em mpg (`mtcars`) | Média, desvio-padrão, todas as operações |\n| Numérica discreta | Número de carburadores (`mtcars`): 1, 2, 3, 4, 6 ou 8 | Contagem, ordem, mediana, moda. Média com cautela |\n| Categórica binária | Sobreviveu ou não (`titanic`) | Frequência e proporção |\n| Categórica ordinal | Escala Likert de 1 a 5, escolaridade | Ordenação, mediana, percentis |\n| Categórica nominal | Espécie (`iris`, `penguins`), classe da cabine (`titanic`) | Contagem, moda, tabela de contingência |\n\nEm uma variável ordinal, há ordem entre os níveis, mas a distância entre eles não é medida diretamente. Tratar uma escala Likert como contínua, sem justificativa, invalida o cálculo do erro-padrão.\n\n## 2.5 Amostras independentes ou pareadas\n\nO teste depende ainda de **como** as observações foram coletadas:\n\n| | Independentes | Pareadas (dependentes) |\n|---|---|---|\n| Exemplo | Massa de pinguins machos e fêmeas (`penguins`) | Sono dos mesmos pacientes com duas drogas (`sleep`) |\n| Foco | Diferença entre médias: $\\bar{x}_1 - \\bar{x}_2$ | Média das diferenças individuais: $D = X_2 - X_1$ |\n| Erro-padrão | Carrega a variação entre indivíduos | O pareamento cancela a variação de base de cada indivíduo |\n| Poder | Menor, para o mesmo *n* | Maior: isola o efeito do tratamento |\n\nA pergunta-chave é: **saber o valor de uma observação diz algo sobre uma observação do outro grupo?** Se sim, as amostras são pareadas. O caso 3 mostra o que acontece quando essa estrutura é ignorada.\n\n## 2.6 Três perguntas escolhem o teste\n\nA escolha do teste resulta de três perguntas, feitas nesta ordem:\n\n1. **Qual o objetivo?** Comparar médias, comparar proporções ou medir associação.\n2. **Qual a escala?** Da resposta e da variável explicativa: contínua, binária ou nominal.\n3. **Qual o desenho?** Uma amostra, dois grupos ou três ou mais; independentes ou pareados.\n\nRespondidas as três, o teste fica determinado, e resta verificar suas premissas. A matriz abaixo resume os sete casos desta aula:\n\n| Objetivo | Resposta | Explicativa e desenho | Teste | Caso |\n|---|---|---|---|---|\n| Média contra uma meta | Contínua | Nenhuma (valor $\\mu_0$) | *t* de uma amostra | 1 · `mtcars` |\n| Médias de 2 grupos | Contínua | Binária, independentes | *t* de Welch | 2 · `penguins` |\n| Antes e depois | Contínua | 2 momentos, pareados | *t* pareado | 3 · `sleep` |\n| Médias de 3 ou mais grupos | Contínua | Nominal, independentes | ANOVA + Tukey | 4 · `iris` |\n| Associação linear | Contínua | Contínua | Pearson | 5 · `mtcars` |\n| Proporções de 2 grupos | Binária | Binária, independentes | *Z* de duas proporções | 6 · `titanic` |\n| Associação entre categorias | Nominal | Nominal, independentes | Qui-quadrado | 7 · `titanic` |\n\nErrar a escolha, por exemplo usando um teste para amostras independentes em dados pareados, ou vários testes *t* no lugar da ANOVA, altera as taxas de erro dos tipos I e II.\n\n# 3. Conceitos importantes\n\nEsta seção reúne os conceitos que atravessam os sete casos. Os três primeiros já foram vistos na Aula 7 e aparecem aqui apenas como lembrete. Os demais são novos e ajudam a ler as saídas dos testes.\n\n## 3.1 Hipóteses e *p*-valor\n\nTodo teste confronta a hipótese nula $H_0$, de que não há efeito, com a hipótese alternativa $H_1$, de que há. O *p*-valor é a probabilidade, **supondo $H_0$ verdadeira**, de obter um resultado tão ou mais extremo que o observado. Ele não é a probabilidade de $H_0$ ser verdadeira. Neste roteiro, todos os testes são **bilaterais**: admitem diferenças nos dois sentidos.\n\n## 3.2 Nível de significância e erros de decisão\n\nO nível de significância $\\alpha$, em geral 0,05, é fixado antes da análise: se $p \\leq \\alpha$, rejeitamos $H_0$. Rejeitar uma $H_0$ verdadeira é um erro do tipo I, cuja taxa é o próprio $\\alpha$. Não rejeitar uma $H_0$ falsa é um erro do tipo II. A probabilidade de detectar um efeito que existe é o **poder** do teste, que cresce com o tamanho da amostra.\n\n## 3.3 Tamanho do efeito\n\nUm *p*-valor pequeno indica que a diferença dificilmente é acaso, mas não diz se ela é grande. Por isso, além do *p*-valor, reportamos o **tamanho do efeito**. Nesta aula, ele aparece de várias formas: a diferença de médias em gramas ou mpg, o coeficiente $r$ de Pearson, a fração da variação explicada pela espécie na ANOVA ($\\eta^2$) e o V de Cramér no qui-quadrado.\n\n## 3.4 Estatística de teste\n\nCada teste resume os dados em um único número, a **estatística de teste**. Em quase todos os casos, ela tem a forma de uma razão entre **sinal** e **ruído**: o efeito observado dividido pela variação que o acaso produziria. Quanto maior a razão, mais o efeito se destaca do acaso. Cada estatística tem a sua distribuição de referência sob $H_0$:\n\n| Teste | Estatística | Sinal ÷ ruído | Distribuição sob $H_0$ |\n|---|---|---|---|\n| Testes *t* | $t$ | Diferença de médias ÷ erro-padrão | *t* de Student |\n| ANOVA | $F$ | Variação entre grupos ÷ variação dentro dos grupos | *F* |\n| Pearson | $r$ | Covariação ÷ variação de cada variável | *t* de Student, após conversão |\n| *Z* de proporções | $Z$ | Diferença de proporções ÷ erro-padrão | Normal padrão |\n| Qui-quadrado | $\\chi^2$ | Soma das discrepâncias $(O - E)^2 / E$ | Qui-quadrado |\n\n## 3.5 Graus de liberdade\n\nAs distribuições *t*, *F* e $\\chi^2$ não são curvas únicas: cada uma é uma família, e o membro certo é escolhido pelos **graus de liberdade** (gl). Intuitivamente, eles contam quantas informações independentes restam para estimar a variabilidade.\n\nPense em três números cuja média precisa ser 10. Você pode escolher os dois primeiros à vontade, por exemplo 8 e 15, mas o terceiro já está decidido: tem de ser 7. São três números, e só dois são livres. Da mesma forma, cada parâmetro estimado a partir dos dados, como uma média, \"consome\" um grau de liberdade.\n\nQuanto menos graus de liberdade, menos confiável é a estimativa da variabilidade, e mais cautelosa é a curva de referência: com poucos gl, a curva *t* tem caudas mais pesadas e exige uma estatística maior para rejeitar $H_0$. A tabela mostra como os graus de liberdade são contados nos casos desta aula:\n\n| Caso | Teste | Graus de liberdade | Valor no caso |\n|---|---|---|---|\n| 1 | *t* de uma amostra | $n - 1$ | 31 |\n| 2 | *t* de Welch | Aproximação de Welch-Satterthwaite | ≈ 324 |\n| 3 | *t* pareado | $n_{\\text{pares}} - 1$ | 9 |\n| 4 | ANOVA | $k - 1$ entre grupos e $N - k$ dentro | 2 e 147 |\n| 5 | Pearson | $n - 2$ | 30 |\n| 6 | *Z* de proporções | Não usa: a referência é a normal padrão | · |\n| 7 | Qui-quadrado | $(\\text{linhas} - 1)(\\text{colunas} - 1)$ | 2 |\n\nNo teste pareado, a unidade de análise é o par, e não cada medida. Por isso o `sleep`, com 20 medidas, tem apenas 9 graus de liberdade. No qui-quadrado, os graus de liberdade dependem do tamanho da tabela, e não do número de passageiros.\n\n## 3.6 Intervalo de confiança\n\n\nO *p*-valor responde se um valor específico, o de $H_0$, é compatível com os dados. O **intervalo de confiança** amplia a pergunta e delimita quais valores do parâmetro são compatíveis com os dados. Em uma média, ele é construído a partir da estimativa e do erro-padrão:\n\n$$\n\\bar{x} \\pm t_{crit} \\cdot SE\n$$\n\nAqui, $t_{crit}$ é o valor crítico da distribuição *t* com $n - 1$ graus de liberdade, cerca de 2 para amostras moderadas. No caso 1, por exemplo, a média de 20,09 mpg, com erro-padrão de 1,07 mpg e $t_{crit} = 2{,}04$, gera o intervalo de 95% de 17,9 a 22,3 mpg.\n\nTrês pontos orientam a leitura:\n\n- **Interpretação.** O \"95%\" descreve o método, não um intervalo específico. Se repetíssemos a coleta muitas vezes, 95% dos intervalos construídos dessa forma conteriam o valor verdadeiro do parâmetro. Não é correto dizer que há 95% de probabilidade de a média estar dentro de um intervalo já calculado.\n- **Largura.** O intervalo é mais estreito quando o erro-padrão é menor: com mais dados ou dados menos dispersos, a estimativa fica mais precisa.\n- **Ligação com o teste.** Um intervalo de 95% que **não contém** o valor de $H_0$ equivale a rejeitar $H_0$ com $\\alpha = 0{,}05$ em um teste bilateral. Se o contém, não rejeitamos. A vantagem do intervalo é mostrar também o tamanho do efeito e a incerteza sobre ele.\n\nNos casos a seguir, o intervalo é obtido com o método `.confidence_interval()`, disponível nos resultados dos testes *t* e da correlação de Pearson.\n\n# 4. Sete casos, sete testes\n\nCada caso segue o mesmo roteiro: o cenário com as hipóteses, em destaque, as premissas do teste, o cálculo passo a passo, a verificação das premissas nos dados, o gráfico e a interpretação.\n\nAntes de mais nada, as funções de teste do SciPy e do `statsmodels` devolvem objetos com vários campos, como `TtestResult(statistic=..., pvalue=..., df=...)`. Para ler os resultados com mais facilidade, usamos ao longo da aula uma função que resume cada teste em uma única linha:\n\n::: {#2b8a23e4 .cell execution_count=10}\n``` {.python .cell-code}\n# Resume o resultado de um teste em uma linha legível\ndef report(name, result, stat=\"estatística\", df=None):\n    if isinstance(result, tuple):  # <1>\n        value, p = result\n    else:\n        value, p = result.statistic, result.pvalue\n    df = df if df is not None else getattr(result, \"df\", None)  # <2>\n\n    parts = [f\"{stat} = {value:.3f}\"]\n    if df is not None:\n        parts.append(f\"gl = {df:.4g}\" if np.isscalar(df) else f\"gl = {df}\")\n    parts.append(\"p < 0.001\" if p < 0.001 else f\"p = {p:.3f}\")\n    if hasattr(result, \"confidence_interval\"):  # <3>\n        ci = result.confidence_interval()\n        parts.append(f\"IC 95% [{ci.low:.2f} ; {ci.high:.2f}]\")\n\n    print(f\"{name}: \" + \" · \".join(parts))\n```\n:::\n\n\n1. Algumas funções, como `proportions_ztest`, devolvem apenas uma tupla com a estatística e o *p*-valor.\n2. `getattr` busca os graus de liberdade no resultado e devolve `None` quando o teste não os informa.\n3. Os testes *t* e a correlação de Pearson oferecem o método `.confidence_interval()`, que devolve o intervalo de confiança de 95%.\n\n## Caso 1. Teste *t* de uma amostra\n\n::: {.callout-note icon=false}\n## Cenário\n\nA gestão de uma frota pergunta se o consumo médio (`mpg`) dos veículos atende à meta de projeto de 20 mpg. Você tem os dados de 32 carros: a média deles basta para responder?\n\n- $H_0$: o consumo médio é igual à meta ($\\mu = 20$).\n- $H_1$: o consumo médio é diferente da meta ($\\mu \\neq 20$).\n:::\n\n**Premissas do teste**\n\n- Observações independentes entre si.\n- Variável resposta numérica contínua.\n- Distribuição normal na população ou amostra grande o bastante para que a média seja aproximadamente normal, pelo teorema central do limite.\n\nCalculamos a estatística passo a passo, seguindo as fórmulas da seção 2.1:\n\n::: {#3664ae7c .cell execution_count=11}\n``` {.python .cell-code}\n# Teste t de uma amostra, passo a passo\nmpg = mtcars[\"mpg\"]\ntarget = 20\n\nn = len(mpg)\nse = mpg.std() / np.sqrt(n)  # <1>\nt = (mpg.mean() - target) / se\np = 2 * stats.t.sf(abs(t), df=n - 1)  # <2>\n```\n:::\n\n\n1. `.std()` do pandas usa $n - 1$ no denominador, como a fórmula do desvio-padrão amostral.\n2. `stats.t.sf` é a área da cauda direita da curva *t*. Multiplicamos por 2 porque o teste é bilateral.\n\n::: {#5bf78f73 .cell execution_count=12}\n``` {.python .cell-code}\nprint(f\"média       = {mpg.mean():.3f}\")\nprint(f\"dp          = {mpg.std():.3f}\")\nprint(f\"erro-padrão = {se:.3f}\")\nprint(f\"t           = {t:.3f}\")\nprint(f\"gl          = {n - 1}\")\nprint(f\"p           = {p:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmédia       = 20.091\ndp          = 6.027\nerro-padrão = 1.065\nt           = 0.085\ngl          = 31\np           = 0.933\n```\n:::\n:::\n\n\nA média da frota, 20,09 mpg, fica só 0,09 mpg acima da meta. Como o erro-padrão é de 1,07 mpg, a diferença equivale a menos de um décimo de erro-padrão. A função do SciPy confirma o resultado e fornece o intervalo de confiança de 95% para a média:\n\n::: {#a3d206d9 .cell execution_count=13}\n``` {.python .cell-code}\n# Teste t de uma amostra com o SciPy\ncase1 = stats.ttest_1samp(mpg, popmean=target)\n\nreport(\"t de uma amostra\", case1, stat=\"t\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt de uma amostra: t = 0.085 · gl = 31 · p = 0.933 · IC 95% [17.92 ; 22.26]\n```\n:::\n:::\n\n\nO intervalo de confiança contém os valores de média compatíveis com os dados.\n\nQuanto às premissas, os carros são modelos distintos, e a seção 2.3 já mostrou que o consumo passa no Shapiro-Wilk ($p \\approx 0{,}12$).\n\nO gráfico mostra os carros, a média e o intervalo em relação à meta. A mesma visualização será usada no caso 3, por isso fica em uma função:\n\n::: {#663e9dc2 .cell execution_count=14}\n``` {.python .cell-code}\n# Pontos, média e intervalo de confiança em relação a um valor de referência\ndef plot_mean_ci(values, ci, ref, xlabel, ax):\n    jitter = np.random.default_rng(1).uniform(0.6, 1.4, len(values))  # <1>\n    ax.scatter(values, jitter, color=\"#1F4E79\", alpha=.7)\n    error = [[values.mean() - ci.low], [ci.high - values.mean()]]\n    ax.errorbar(values.mean(), 0.2, xerr=error, fmt=\"o\", color=\"#DD8452\",\n                ecolor=\"#1F4E79\", capsize=6, markersize=10)\n    ax.axvline(ref, color=\"#333333\", linestyle=\"--\")\n    ax.set(xlabel=xlabel, yticks=[], ylim=(-0.2, 1.6),\n           title=f\"média {values.mean():.2f} · IC 95% [{ci.low:.2f} ; {ci.high:.2f}]\")\n\nfig, ax = plt.subplots(figsize=(8, 3.5))\nplot_mean_ci(mpg, case1.confidence_interval(), target, \"Consumo (mpg)\", ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-15-output-1.png){width=752 height=320}\n:::\n:::\n\n\n1. Os pontos recebem uma altura aleatória apenas para não se sobreporem. O eixo vertical não tem significado.\n\n**Interpretação.** Os carros se espalham dos dois lados da meta, de 10 a 34 mpg. A média (ponto laranja) cai praticamente sobre a linha tracejada, e o intervalo de confiança, de 17,9 a 22,3 mpg, contém a meta com folga. Se a média real da frota fosse 20 mpg, diferenças iguais ou maiores que a observada surgiriam em 93% das amostras ($p \\approx 0{,}93$). Não rejeitamos $H_0$: não há evidência de que a frota esteja fora da meta. Isso, porém, não prova que $\\mu = 20$. Os dados são apenas compatíveis com a meta, como também seriam com qualquer valor dentro do intervalo.\n\n## Caso 2. Teste *t* de Welch\n\n::: {.callout-note icon=false}\n## Cenário\n\nUma equipe de biólogos de campo quer saber se machos e fêmeas de pinguins têm massas corporais (`body_mass`, em gramas) médias diferentes, um sinal de dimorfismo sexual. Cada grupo é formado por animais distintos.\n\n- $H_0$: machos e fêmeas têm, em média, a mesma massa ($\\mu_1 = \\mu_2$).\n- $H_1$: as massas médias são diferentes ($\\mu_1 \\neq \\mu_2$).\n:::\n\n**Premissas do teste**\n\n- Observações independentes, dentro de cada grupo e entre os grupos.\n- Variável resposta numérica contínua.\n- Distribuição normal em cada grupo ou amostras grandes o bastante para o teorema central do limite.\n- As variâncias dos grupos **não** precisam ser iguais. É isso que distingue a versão de Welch do teste *t* clássico.\n\nA base tem 344 pinguins, mas 11 não têm o sexo registrado. Ficamos com os 333 restantes:\n\n::: {#fb4d9131 .cell execution_count=15}\n``` {.python .cell-code}\n# Pinguins com sexo e massa registrados\npenguins_sex = penguins.dropna(subset=[\"sex\", \"body_mass\"])\n\nmales = penguins_sex.loc[penguins_sex[\"sex\"] == \"male\", \"body_mass\"]\nfemales = penguins_sex.loc[penguins_sex[\"sex\"] == \"female\", \"body_mass\"]\n```\n:::\n\n\nO teste de Welch usa a variância de cada grupo separadamente. A tabela traz a parcela $s^2/n$ de cada um, que mede a incerteza da média do grupo:\n\n::: {#f7669649 .cell execution_count=16}\n``` {.python .cell-code}\n# Resumo por grupo e parcelas do erro-padrão de Welch\nwelch_table = (\n    penguins_sex\n    .groupby(\"sex\")\n    .body_mass\n    .agg(n=\"size\", média=\"mean\", dp=\"std\")\n    .assign(s2_n=lambda df: df[\"dp\"] ** 2 / df[\"n\"])\n)\n\nwelch_table.round(1)\n```\n\n::: {.cell-output .cell-output-display execution_count=592}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n</th>\n      <th>média</th>\n      <th>dp</th>\n      <th>s2_n</th>\n    </tr>\n    <tr>\n      <th>sex</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>female</th>\n      <td>165</td>\n      <td>3862.3</td>\n      <td>666.2</td>\n      <td>2689.6</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>168</td>\n      <td>4545.7</td>\n      <td>787.6</td>\n      <td>3692.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#91a2b6b2 .cell execution_count=17}\n``` {.python .cell-code}\n# Erro-padrão da diferença, estatística t e teste de Welch\nse_diff = np.sqrt(welch_table[\"s2_n\"].sum())  # <1>\nt_manual = (males.mean() - females.mean()) / se_diff\n\ncase2 = stats.ttest_ind(males, females, equal_var=False)\n\nprint(f\"erro-padrão da diferença = {se_diff:.1f} g\")\nprint(f\"t calculado à mão = {t_manual:.2f}\")\nreport(\"t de Welch\", case2, stat=\"t\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nerro-padrão da diferença = 79.9 g\nt calculado à mão = 8.55\nt de Welch: t = 8.555 · gl = 323.9 · p < 0.001 · IC 95% [526.25 ; 840.58]\n```\n:::\n:::\n\n\n1. O erro-padrão da diferença é a raiz da soma das duas parcelas $s^2/n$. Cada grupo entra com a sua própria variância.\n\nOs machos pesam, em média, 4.546 g, e as fêmeas, 3.862 g: uma diferença de 683 g. O erro-padrão da diferença é de cerca de 80 g, e a diferença cabe 8,55 vezes nele. Os graus de liberdade, cerca de 324, vêm da correção de Welch-Satterthwaite, que ajusta a curva *t* quando as variâncias diferem.\n\nCom mais de 160 animais por grupo, o teorema central do limite garante a normalidade das médias. E as variâncias, diferem? O teste de **Levene** verifica a homocedasticidade:\n\n::: {#04021238 .cell execution_count=18}\n``` {.python .cell-code}\n# Homocedasticidade, intervalo da diferença e sobreposição dos grupos\nci = case2.confidence_interval()\n\nprint(f\"Levene: p = {stats.levene(males, females).pvalue:.3f}\")  # <1>\nprint(f\"IC 95% da diferença: [{ci.low:.0f} ; {ci.high:.0f}] g\")\nprint(f\"fêmeas acima do macho médio: {(females > males.mean()).mean():.0%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene: p = 0.014\nIC 95% da diferença: [526 ; 841] g\nfêmeas acima do macho médio: 25%\n```\n:::\n:::\n\n\n1. O teste de Levene tem $H_0$: as variâncias dos grupos são iguais.\n\nO desvio-padrão dos machos (788 g) é maior que o das fêmeas (666 g), e o Levene rejeita a igualdade de variâncias ($p \\approx 0{,}014$). Esse é o motivo para usar a versão de Welch. O intervalo de confiança de 95% da diferença vai de 526 a 841 g, longe de zero.\n\nO gráfico mostra cada pinguim e a média de cada grupo. Ele será reutilizado no caso 4, por isso fica em uma função:\n\n::: {#818d17ac .cell execution_count=19}\n``` {.python .cell-code}\n# Observações e média de cada grupo\ndef plot_group_means(data, x, y, order, ylabel, ax):\n    sns.stripplot(data=data, x=x, y=y, order=order, ax=ax,\n                  color=\"#1F4E79\", alpha=.5, jitter=.25)\n    means = data.groupby(x)[y].mean().reindex(order)\n    ax.hlines(means, np.arange(len(order)) - .35, np.arange(len(order)) + .35,\n              color=\"#DD8452\", linewidth=3)\n    ax.set(xlabel=\"\", ylabel=ylabel)\n```\n:::\n\n\n::: {#77087b57 .cell execution_count=20}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 4.5))\nplot_group_means(penguins_sex, \"sex\", \"body_mass\", [\"female\", \"male\"],\n                 \"Massa corporal (g)\", ax)\nax.set_xticks([0, 1], [\"Fêmeas\", \"Machos\"])\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-21-output-1.png){width=561 height=416}\n:::\n:::\n\n\n**Interpretação.** Os dois grupos se sobrepõem bastante: cerca de 25% das fêmeas pesam mais que o macho médio. Ainda assim, a média dos machos fica bem acima da média das fêmeas. Se machos e fêmeas tivessem a mesma massa média, uma diferença de 683 g seria praticamente impossível por acaso ($p < 0{,}001$). Rejeitamos $H_0$: há evidência de dimorfismo sexual, com machos mais pesados. Note que o teste fala de **médias**. Ele não afirma que todo macho é mais pesado que toda fêmea.\n\n### Existe dimorfismo dentro de cada espécie?\n\nA base reúne três espécies de pinguim, com tamanhos bem diferentes. Ao comparar todos os machos com todas as fêmeas, misturamos essa variação entre espécies com a variação entre os sexos. Vejamos o desvio-padrão da massa em cada combinação de espécie e sexo:\n\n::: {#7d0dbd65 .cell execution_count=21}\n``` {.python .cell-code}\n# Média e desvio-padrão da massa por espécie e sexo\n(\n    penguins_sex\n    .groupby([\"species\", \"sex\"])\n    .body_mass\n    .agg([\"size\", \"mean\", \"std\"])\n    .round(0)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=597}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>size</th>\n      <th>mean</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>species</th>\n      <th>sex</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Adelie</th>\n      <th>female</th>\n      <td>73</td>\n      <td>3369.0</td>\n      <td>269.0</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>73</td>\n      <td>4043.0</td>\n      <td>347.0</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Chinstrap</th>\n      <th>female</th>\n      <td>34</td>\n      <td>3527.0</td>\n      <td>285.0</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>34</td>\n      <td>3939.0</td>\n      <td>362.0</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Gentoo</th>\n      <th>female</th>\n      <td>58</td>\n      <td>4680.0</td>\n      <td>282.0</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>61</td>\n      <td>5485.0</td>\n      <td>313.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nO boxplot mostra a mesma informação por espécie, com os sexos lado a lado:\n\n::: {#df023f34 .cell execution_count=22}\n``` {.python .cell-code}\n# Massa corporal por espécie e sexo\nfig, ax = plt.subplots(figsize=(8, 4.5))\n\nsns.boxplot(\n    data=penguins_sex,\n    x=\"species\",\n    y=\"body_mass\",\n    order=[\"Adelie\", \"Chinstrap\", \"Gentoo\"],\n    hue=\"sex\",  # <1>\n    hue_order=[\"female\", \"male\"],\n    palette={\"female\": \"#A1C9F4\", \"male\": \"#1F4E79\"},\n    ax=ax,\n)\nax.set(xlabel=\"Espécie\", ylabel=\"Massa corporal (g)\")\n\nhandles, _ = ax.get_legend_handles_labels()  # <2>\nax.legend(handles, [\"Fêmeas\", \"Machos\"], title=\"Sexo\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-23-output-1.png){width=753 height=416}\n:::\n:::\n\n\n1. `hue` divide cada espécie em uma caixa por sexo, com cores diferentes.\n2. Reaproveitamos os marcadores coloridos da legenda e trocamos apenas os rótulos, de `female`/`male` para português.\n\nEm todas as espécies, a caixa dos machos fica acima da caixa das fêmeas. As caixas, porém, são bem mais curtas do que a variação total da massa, porque a espécie pesa mais que o sexo: o macho Adelie típico, com cerca de 4.000 g, é mais leve que a fêmea Gentoo típica, com cerca de 4.700 g. Dentro de cada espécie, o desvio-padrão fica entre cerca de 270 e 360 g. No teste geral, ele passava de 660 g, porque cada grupo misturava pinguins pequenos e grandes. Repetimos então o teste de Welch separadamente em cada espécie:\n\n::: {#d1c4b58e .cell execution_count=23}\n``` {.python .cell-code}\n# Teste de Welch dentro de cada espécie\nfor species, group in penguins_sex.groupby(\"species\"):\n    male = group.loc[group[\"sex\"] == \"male\", \"body_mass\"]\n    female = group.loc[group[\"sex\"] == \"female\", \"body_mass\"]\n    report(species, stats.ttest_ind(male, female, equal_var=False), stat=\"t\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAdelie: t = 13.126 · gl = 135.7 · p < 0.001 · IC 95% [573.01 ; 776.30]\nChinstrap: t = 5.208 · gl = 62.58 · p < 0.001 · IC 95% [253.74 ; 569.79]\nGentoo: t = 14.761 · gl = 116.6 · p < 0.001 · IC 95% [697.08 ; 913.11]\n```\n:::\n:::\n\n\nO dimorfismo aparece nas três espécies, com $p < 0{,}001$ em todas. Em Adelie e Gentoo, a estatística *t* fica bem maior que a do teste geral (8,6), mesmo com menos animais, porque o erro-padrão cai de cerca de 80 g para cerca de 50 g. A diferença também varia entre as espécies: os machos Gentoo pesam cerca de 800 g a mais que as fêmeas, e os machos Chinstrap, cerca de 410 g. Separar os grupos torna a pergunta mais honesta e o teste mais preciso, uma ideia que retomaremos ao estudar modelos com mais de uma variável explicativa.\n\n## Caso 3. Teste *t* pareado\n\n::: {.callout-note icon=false}\n## Cenário\n\nEm um ensaio clínico, os mesmos 10 pacientes testaram dois soníferos, um em cada período, e foram medidas as horas extras de sono (`extra`). O médico quer saber se a droga 2 rende mais horas de sono que a droga 1.\n\n- $H_0$: em média, a droga 2 não muda as horas de sono em relação à droga 1 ($\\mu_D = 0$).\n- $H_1$: em média, as horas de sono mudam entre as drogas ($\\mu_D \\neq 0$).\n:::\n\n**Premissas do teste**\n\n- Cada par de medidas vem da mesma unidade, no caso o mesmo paciente.\n- Os pares são independentes entre si.\n- Variável resposta numérica contínua.\n- As diferenças dentro de cada par, $D_i = X_{2i} - X_{1i}$, seguem aproximadamente uma distribuição normal.\n\nA base `sleep` está no formato longo: uma linha por paciente e droga. Reorganizamos para uma linha por paciente e calculamos a diferença:\n\n::: {#8329e492 .cell execution_count=24}\n``` {.python .cell-code}\n# Uma linha por paciente, com a diferença entre as drogas\nsleep_wide = (\n    sleep\n    .pivot(index=\"ID\", columns=\"group\", values=\"extra\")  # <1>\n    .rename(columns={1: \"droga_1\", 2: \"droga_2\"})\n    .assign(D=lambda df: df[\"droga_2\"] - df[\"droga_1\"])\n)\n\nsleep_wide\n```\n\n::: {.cell-output .cell-output-display execution_count=600}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>group</th>\n      <th>droga_1</th>\n      <th>droga_2</th>\n      <th>D</th>\n    </tr>\n    <tr>\n      <th>ID</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>0.7</td>\n      <td>1.9</td>\n      <td>1.2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>-1.6</td>\n      <td>0.8</td>\n      <td>2.4</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>-0.2</td>\n      <td>1.1</td>\n      <td>1.3</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>-1.2</td>\n      <td>0.1</td>\n      <td>1.3</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>-0.1</td>\n      <td>-0.1</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>3.4</td>\n      <td>4.4</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>3.7</td>\n      <td>5.5</td>\n      <td>1.8</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>0.8</td>\n      <td>1.6</td>\n      <td>0.8</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>0.0</td>\n      <td>4.6</td>\n      <td>4.6</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>2.0</td>\n      <td>3.4</td>\n      <td>1.4</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `.pivot` transforma os valores da coluna `group` em colunas, uma para cada droga.\n\nA partir daqui, as colunas originais saem de cena. O teste pareado é um teste *t* de uma amostra sobre a coluna `D`, com $\\mu_0 = 0$:\n\n$$\nt = \\frac{\\bar{D} - 0}{s_D / \\sqrt{n}}\n$$\n\n::: {#1ad21b94 .cell execution_count=25}\n``` {.python .cell-code}\n# Teste t pareado e o mesmo teste ignorando o pareamento\ncase3 = stats.ttest_rel(sleep_wide[\"droga_2\"], sleep_wide[\"droga_1\"])\nunpaired = stats.ttest_ind(sleep_wide[\"droga_2\"], sleep_wide[\"droga_1\"])\n\npd.DataFrame(\n    {\"t\": [case3.statistic, unpaired.statistic], \"p\": [case3.pvalue, unpaired.pvalue]},\n    index=[\"pareado\", \"ignorando o pareamento\"],\n).round(4)\n```\n\n::: {.cell-output .cell-output-display execution_count=601}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>t</th>\n      <th>p</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>pareado</th>\n      <td>4.0621</td>\n      <td>0.0028</td>\n    </tr>\n    <tr>\n      <th>ignorando o pareamento</th>\n      <td>1.8608</td>\n      <td>0.0792</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nA média das diferenças é de 1,58 h, com desvio-padrão de 1,23 h. O teste pareado dá $t = 4{,}06$ com 9 graus de liberdade e $p \\approx 0{,}003$. Com os **mesmos dados**, tratados como dois grupos independentes, o *p*-valor sobe para 0,079, e a diferença deixa de ser significante.\n\nO motivo aparece no gráfico. À esquerda, cada linha liga as duas medidas de um paciente. À direita, cada ponto é a diferença de um paciente, com a média e o intervalo de confiança:\n\n::: {#575a081b .cell execution_count=26}\n``` {.python .cell-code}\n# Linhas por paciente e diferenças com intervalo de confiança\nfig, axes = plt.subplots(1, 2, figsize=(12, 4), width_ratios=[1, 1.6])\n\naxes[0].plot([0, 1], sleep_wide[[\"droga_1\", \"droga_2\"]].T, color=\"#1F4E79\", marker=\"o\")\naxes[0].set(xticks=[0, 1], xticklabels=[\"Droga 1\", \"Droga 2\"], xlim=(-.3, 1.3),\n            ylabel=\"Horas extras de sono\")\n\nplot_mean_ci(sleep_wide[\"D\"], case3.confidence_interval(), 0,\n             \"Diferença de sono: droga 2 − droga 1 (horas)\", axes[1])\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-27-output-1.png){width=1137 height=368}\n:::\n:::\n\n\nOs pacientes são muito diferentes entre si: alguns dormem bem com qualquer droga, outros dormem pouco. A correlação entre as duas medidas de cada paciente é de cerca de 0,80. Vistos como dois grupos soltos, os pontos se misturam, e a variação **entre pacientes** esconde o efeito. Olhando paciente a paciente, o padrão aparece: as linhas sobem em 9 dos 10 casos, e nenhum paciente piora. O pareamento cancela a variação de base de cada pessoa e isola o efeito da droga.\n\nHá, porém, uma ressalva. Com apenas 10 diferenças, a normalidade pesa mais:\n\n::: {#ba5e0e7b .cell execution_count=27}\n``` {.python .cell-code}\n# Normalidade das diferenças e alternativa não paramétrica\nreport(\"Shapiro-Wilk das diferenças\", stats.shapiro(sleep_wide[\"D\"]), stat=\"W\")\nreport(\"Wilcoxon\", stats.wilcoxon(sleep_wide[\"D\"]), stat=\"T\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nShapiro-Wilk das diferenças: W = 0.830 · p = 0.033\nWilcoxon: T = 0.000 · p = 0.004\n```\n:::\n:::\n\n\nO Shapiro-Wilk rejeita a normalidade das diferenças ($p \\approx 0{,}03$), em boa parte por causa do paciente com ganho de 4,6 h. O teste de Wilcoxon dos postos sinalizados, a alternativa não paramétrica ao *t* pareado, chega à mesma conclusão ($p \\approx 0{,}004$).\n\n**Interpretação.** Quase todos os pacientes estão à direita da linha de zero, e o intervalo da média, de 0,70 a 2,46 h, não toca nela. Se as duas drogas fossem equivalentes, um ganho médio de 1,58 h surgiria em apenas 0,3% dos ensaios. Rejeitamos $H_0$: nos mesmos pacientes, a droga 2 rende em média cerca de 1,6 h a mais de sono que a droga 1.\n\n## Caso 4. ANOVA one-way\n\n::: {.callout-note icon=false}\n## Cenário\n\nUm botânico mede flores de três espécies de íris e quer saber se o comprimento médio da sépala (`sepal_length`) é o mesmo nas três, antes de usá-lo para diferenciá-las.\n\n- $H_0$: as três espécies têm o mesmo comprimento médio ($\\mu_1 = \\mu_2 = \\mu_3$).\n- $H_1$: pelo menos uma espécie tem média diferente.\n:::\n\n**Premissas do teste**\n\n- Observações independentes, dentro de cada grupo e entre os grupos.\n- Variável resposta numérica contínua.\n- Resíduos aproximadamente normais em cada grupo.\n- Variâncias iguais entre os grupos (homocedasticidade).\n\nPor que não comparar as espécies duas a duas com três testes *t*? Porque cada teste acrescenta uma chance de falso positivo, como demonstraremos ao fim deste caso. A ANOVA responde à pergunta com **um único teste** e mantém o $\\alpha$ em 5%.\n\nA ideia da ANOVA é comparar duas fontes de variação. Se as médias das espécies se afastam muito da média geral, em relação à variação natural dentro de cada espécie, a estatística *F* fica grande:\n\n$$\nF = \\frac{MQG}{MQR} = \\frac{SQG / (k - 1)}{SQR / (N - k)}\n$$\n\nAqui, $SQG$ é a soma de quadrados **entre** grupos, $SQR$ a soma de quadrados **dentro** dos grupos (resíduos), $k$ o número de grupos e $N$ o total de observações. Calculamos a tabela da ANOVA passo a passo:\n\n::: {#d9e7fe64 .cell execution_count=28}\n``` {.python .cell-code}\n# Tabela da ANOVA calculada passo a passo\ngrand_mean = iris[\"sepal_length\"].mean()\n\nby_species = (\n    iris\n    .groupby(\"species\")\n    .sepal_length\n    .agg(n=\"size\", média=\"mean\", dp=\"std\")\n)\n\nss_between = (by_species[\"n\"] * (by_species[\"média\"] - grand_mean) ** 2).sum()  # <1>\n\nss_within = ((by_species[\"n\"] - 1) * by_species[\"dp\"] ** 2).sum()  # <2>\n\nk, N = len(by_species), len(iris)\n```\n:::\n\n\n1. Quanto cada média de espécie se afasta da média geral, ao quadrado, ponderado pelo tamanho do grupo.\n2. A soma dos desvios ao quadrado dentro de um grupo é $(n - 1)s^2$. Somamos os três grupos.\n\n::: {#61c51713 .cell execution_count=29}\n``` {.python .cell-code}\npd.DataFrame(\n    {\"SQ\": [ss_between, ss_within], \"gl\": [k - 1, N - k]},\n    index=[\"entre espécies\", \"dentro (resíduos)\"],\n).assign(MQ=lambda df: df[\"SQ\"] / df[\"gl\"]).round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=605}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>SQ</th>\n      <th>gl</th>\n      <th>MQ</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>entre espécies</th>\n      <td>63.212</td>\n      <td>2</td>\n      <td>31.606</td>\n    </tr>\n    <tr>\n      <th>dentro (resíduos)</th>\n      <td>38.956</td>\n      <td>147</td>\n      <td>0.265</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nO quadrado médio entre espécies (31,61) é cerca de 119 vezes o quadrado médio dentro das espécies (0,265). Conferimos com o SciPy e, como a ANOVA só diz que **alguma** média difere, usamos o teste de Tukey para descobrir **quais**:\n\n::: {#10df72d6 .cell execution_count=30}\n``` {.python .cell-code}\n# ANOVA, comparações de Tukey e homocedasticidade\nsetosa, versicolor, virginica = [\n    group[\"sepal_length\"] for _, group in iris.groupby(\"species\")\n]\n\nanova = stats.f_oneway(setosa, versicolor, virginica)\n\nreport(\"ANOVA\", anova, stat=\"F\", df=(k - 1, N - k))\nreport(\"Levene\", stats.levene(setosa, versicolor, virginica))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA: F = 119.265 · gl = (2, 147) · p < 0.001\nLevene: estatística = 6.353 · p = 0.002\n```\n:::\n:::\n\n\n::: {#0cecfbf5 .cell execution_count=31}\n``` {.python .cell-code}\n# Comparações de Tukey\nprint(stats.tukey_hsd(setosa, versicolor, virginica))  # <1>\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)\nComparison  Statistic  p-value  Lower CI  Upper CI\n (0 - 1)     -0.930     0.000    -1.174    -0.686\n (0 - 2)     -1.582     0.000    -1.826    -1.338\n (1 - 0)      0.930     0.000     0.686     1.174\n (1 - 2)     -0.652     0.000    -0.896    -0.408\n (2 - 0)      1.582     0.000     1.338     1.826\n (2 - 1)      0.652     0.000     0.408     0.896\n\n```\n:::\n:::\n\n\n1. Na saída do Tukey, os grupos são numerados na ordem dos argumentos: 0 = setosa, 1 = versicolor, 2 = virginica.\n\nA ANOVA dá $F \\approx 119{,}3$ com $(2, 147)$ graus de liberdade e $p < 0{,}001$. O Tukey indica que os três pares diferem, com diferenças de 0,65 a 1,58 cm e todos os *p*-valores abaixo de 0,001. A fração da variação total explicada pela espécie, $\\eta^2 = SQG / (SQG + SQR)$, é de cerca de 0,62.\n\n::: {#28220fb0 .cell execution_count=32}\n``` {.python .cell-code}\n# Comprimento da sépala por espécie\nfig, ax = plt.subplots(figsize=(7, 4.5))\nplot_group_means(iris, \"species\", \"sepal_length\", [\"setosa\", \"versicolor\", \"virginica\"],\n                 \"Comprimento da sépala (cm)\", ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-33-output-1.png){width=657 height=416}\n:::\n:::\n\n\n**Interpretação.** As médias sobem de setosa (5,01 cm) para versicolor (5,94 cm) e virginica (6,59 cm), e a distância entre elas é grande em relação à dispersão dentro de cada espécie. Se as espécies tivessem a mesma sépala média, diferenças desse tamanho seriam praticamente impossíveis por acaso. Rejeitamos $H_0$: o comprimento da sépala distingue as três espécies, e todos os pares diferem entre si.\n\nFica uma ressalva. O teste de Levene rejeita a igualdade de variâncias ($p \\approx 0{,}002$): a dispersão cresce de setosa para virginica. Nesse caso, uma alternativa mais segura é a ANOVA de Welch, seguida do teste de Games-Howell. Com diferenças tão grandes, a conclusão não muda.\n\n### Por que não rodar múltiplos testes *t* de Student?\n\nCom três espécies, seria tentador fazer três testes *t*: setosa × versicolor, setosa × virginica e versicolor × virginica. O problema é que cada teste tem 5% de chance de um falso positivo, e essas chances se acumulam. A probabilidade de errar **pelo menos uma vez** em $c$ comparações independentes é:\n\n$$\n\\alpha_{\\text{conjunto}} = 1 - (1 - \\alpha)^c\n$$\n\nCom $k$ grupos, há $c = k(k-1)/2$ pares. Com $\\alpha = 0{,}05$:\n\n| Grupos ($k$) | Comparações ($c$) | Chance de pelo menos um falso positivo |\n|---|---|---|\n| 2 | 1 | 5% |\n| 3 | 3 | 14% |\n| 4 | 6 | 26% |\n| 5 | 10 | 40% |\n\nPodemos verificar isso com a própria `iris`. Embaralhando os rótulos de espécie, como no teste de permutação da Aula 7, criamos um mundo em que **sabemos** que $H_0$ é verdadeira: as \"espécies\" passam a ser grupos sorteados ao acaso. Repetimos o sorteio 2.000 vezes e, em cada um, registramos se os três testes *t* encontraram alguma diferença e se a ANOVA encontrou:\n\n::: {#17b0c139 .cell execution_count=33}\n``` {.python .cell-code}\n# Falsos positivos com três testes t e com uma ANOVA, sob H0 verdadeira\nrng = np.random.default_rng(2026)\nvalues = iris[\"sepal_length\"].to_numpy()\nlabels = iris[\"species\"].to_numpy()\npairs = [(0, 1), (0, 2), (1, 2)]\n\nany_t, anova_rejects = [], []\nfor _ in range(2_000):\n    shuffled = rng.permutation(labels)  # <1>\n    groups = [values[shuffled == species] for species in np.unique(labels)]\n    p_values = [stats.ttest_ind(groups[a], groups[b]).pvalue for a, b in pairs]\n    any_t.append(min(p_values) <= .05)  # <2>\n    anova_rejects.append(stats.f_oneway(*groups).pvalue <= .05)\n\nprint(f\"três testes t: algum falso positivo em {np.mean(any_t):.1%} dos sorteios\")\nprint(f\"uma ANOVA: falso positivo em {np.mean(anova_rejects):.1%} dos sorteios\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrês testes t: algum falso positivo em 13.4% dos sorteios\numa ANOVA: falso positivo em 5.0% dos sorteios\n```\n:::\n:::\n\n\n1. Os valores ficam no lugar, e os rótulos de espécie são sorteados de novo. Qualquer diferença entre os grupos passa a ser puro acaso.\n2. Basta que o menor dos três *p*-valores fique abaixo de 0,05 para concluir, erradamente, que alguma espécie difere.\n\nCom três testes *t*, cerca de 13% dos sorteios produziram pelo menos uma \"diferença significante\", embora nenhuma exista. Com a ANOVA, a taxa fica em 5%, exatamente o $\\alpha$ escolhido. O valor simulado fica um pouco abaixo dos 14% da fórmula porque os três testes compartilham grupos e, por isso, não são independentes.\n\nPor isso a sequência correta é **ANOVA primeiro, post-hoc depois**. A ANOVA decide, com um único teste, se existe alguma diferença. Só então o teste de Tukey identifica quais pares diferem, ajustando os *p*-valores para que o conjunto de comparações mantenha o $\\alpha$ em 5%.\n\n## Caso 5. Correlação de Pearson\n\n::: {.callout-note icon=false}\n## Cenário\n\nUm engenheiro quer entender se carros mais pesados (`wt`, em milhares de libras) tendem a gastar mais combustível (`mpg`), e quão forte é essa relação, antes de propor um projeto mais leve.\n\n- $H_0$: não há relação linear entre peso e consumo ($\\rho = 0$).\n- $H_1$: existe relação linear entre peso e consumo ($\\rho \\neq 0$).\n:::\n\n**Premissas do teste**\n\n- Pares de observações independentes entre si.\n- As duas variáveis são numéricas contínuas.\n- A relação entre elas é linear.\n- Normalidade bivariada e ausência de valores atípicos influentes.\n\nO coeficiente de Pearson mede o quanto duas variáveis numéricas andam juntas **em linha reta**. O numerador soma os produtos dos desvios: é positivo quando valores altos de uma variável acompanham valores altos da outra. O denominador padroniza o resultado e o prende entre $-1$ e $+1$:\n\n$$\nr = \\frac{\\sum (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum (x_i - \\bar{x})^2 \\cdot \\sum (y_i - \\bar{y})^2}}\n$$\n\n::: {#c32ab3bd .cell execution_count=34}\n``` {.python .cell-code}\n# Coeficiente de Pearson pela fórmula e pelo SciPy\ndx = mtcars[\"wt\"] - mtcars[\"wt\"].mean()\ndy = mtcars[\"mpg\"] - mtcars[\"mpg\"].mean()\n\nr_manual = (dx * dy).sum() / np.sqrt((dx ** 2).sum() * (dy ** 2).sum())\ncase5 = stats.pearsonr(mtcars[\"wt\"], mtcars[\"mpg\"])\n\nprint(f\"r calculado à mão = {r_manual:.3f}\")\nreport(\"Pearson\", case5, stat=\"r\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr calculado à mão = -0.868\nPearson: r = -0.868 · p < 0.001 · IC 95% [-0.93 ; -0.74]\n```\n:::\n:::\n\n\nO coeficiente vale $r \\approx -0{,}87$, com $p < 0{,}001$. O sinal negativo indica a direção: mais peso, menos milhas por galão. O tamanho indica a força. Como referência, valores de $|r|$ abaixo de 0,3 costumam ser descritos como fracos, entre 0,3 e 0,5 como moderados e acima de 0,5 como fortes.\n\nO coeficiente tem duas propriedades úteis. Ele é **simétrico**: $r(\\text{peso}, \\text{consumo}) = r(\\text{consumo}, \\text{peso})$. E é **invariante** a mudanças de unidade. Convertendo o peso para quilogramas, o resultado não muda:\n\n::: {#a24355b6 .cell execution_count=35}\n``` {.python .cell-code}\n# O coeficiente não depende da unidade de medida\nr_kg = stats.pearsonr(mtcars[\"wt\"] * 453.6, mtcars[\"mpg\"]).statistic\n\nprint(f\"r com o peso em kg = {r_kg:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr com o peso em kg = -0.868\n```\n:::\n:::\n\n\n::: {#dde268a5 .cell execution_count=36}\n``` {.python .cell-code}\n# Consumo versus peso, com a reta de mínimos quadrados\nslope, intercept = np.polyfit(mtcars[\"wt\"], mtcars[\"mpg\"], deg=1)  # <1>\ngrid = np.linspace(mtcars[\"wt\"].min(), mtcars[\"wt\"].max(), 100)\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nax.scatter(mtcars[\"wt\"], mtcars[\"mpg\"], color=\"#1F4E79\", alpha=.8)\nax.plot(grid, intercept + slope * grid, color=\"#DD8452\", linewidth=2)\nax.set(title=f\"r = {case5.statistic:.2f}\", xlabel=\"Peso (wt, 1.000 lb)\",\n       ylabel=\"Consumo (mpg)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-37-output-1.png){width=657 height=416}\n:::\n:::\n\n\n1. `np.polyfit` com `deg=1` ajusta a reta que melhor descreve os pontos, apenas para guiar o olhar.\n\n**Interpretação.** Os pontos descem da esquerda para a direita e ficam próximos da reta. Se peso e consumo não tivessem relação linear, um *r* tão forte seria praticamente impossível por acaso. Rejeitamos $H_0$: carros mais pesados tendem a fazer menos milhas por galão.\n\nDois limites merecem atenção. Pearson só enxerga relações **lineares**: uma relação em forma de U pode ter $r \\approx 0$ e, para relações monotônicas mas curvas, o coeficiente de Spearman é mais adequado. E correlação **não é causalidade**: o coeficiente mede associação, e a causa exige um mecanismo ou um experimento.\n\n### A transformação log melhora a correlação?\n\nAinda no `mtcars`, carros mais potentes (`hp`) tendem a consumir mais combustível (menos `mpg`). Como o coeficiente de Pearson mede apenas a parte **linear** da relação, ele perde força quando os pontos formam uma curva. A transformação log, vista na Aula 6, pode corrigir isso. Calculamos o Pearson com a potência na escala original e em log:\n\n::: {#2ea9d752 .cell execution_count=37}\n``` {.python .cell-code}\n# Pearson com a potência na escala original e em log\nlog_hp = np.log(mtcars[\"hp\"])\n\nreport(\"Pearson com hp\", stats.pearsonr(mtcars[\"hp\"], mtcars[\"mpg\"]), stat=\"r\")\nreport(\"Pearson com log(hp)\", stats.pearsonr(log_hp, mtcars[\"mpg\"]), stat=\"r\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPearson com hp: r = -0.776 · p < 0.001 · IC 95% [-0.89 ; -0.59]\nPearson com log(hp): r = -0.849 · p < 0.001 · IC 95% [-0.92 ; -0.71]\n```\n:::\n:::\n\n\n::: {#b4a1632d .cell execution_count=38}\n``` {.python .cell-code}\n# Consumo versus potência, na escala original e com a potência em log\nfig, axes = plt.subplots(1, 2, figsize=(11, 4), sharey=True)\n\nfor ax, x, xlabel in zip(\n    axes,\n    [mtcars[\"hp\"], log_hp],\n    [\"Potência (hp)\", \"log da potência\"],\n):\n    slope, intercept = np.polyfit(x, mtcars[\"mpg\"], deg=1)\n    grid = np.linspace(x.min(), x.max(), 100)\n    ax.scatter(x, mtcars[\"mpg\"], color=\"#1F4E79\", alpha=.8)\n    ax.plot(grid, intercept + slope * grid, color=\"#DD8452\", linewidth=2)\n    ax.set(xlabel=xlabel, title=f\"r = {stats.pearsonr(x, mtcars['mpg']).statistic:.2f}\")\n\naxes[0].set_ylabel(\"Consumo (mpg)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-39-output-1.png){width=1041 height=368}\n:::\n:::\n\n\nNa escala original, à esquerda, o consumo cai rápido entre os carros de baixa potência e depois se estabiliza. Os pontos formam uma curva e ficam acima da reta nos dois extremos e abaixo dela no meio. O log comprime os valores altos de potência e estica os baixos, e os pontos passam a seguir melhor uma reta, à direita. Com isso, o coeficiente sobe de $r \\approx -0{,}78$ para $r \\approx -0{,}85$.\n\nA relação entre potência e consumo é a mesma nos dois gráficos. O que muda é a escala em que a medimos. Quando a relação é curva, transformar uma das variáveis pode torná-la mais linear e, assim, mais bem capturada pelo coeficiente de Pearson.\n\n## Caso 6. Teste *Z* de duas proporções\n\n::: {.callout-note icon=false}\n## Cenário\n\nUm historiador analisa o naufrágio do Titanic: a regra \"mulheres e crianças primeiro\" deixou marca nos números? A sobrevivência (`survived`) foi diferente entre mulheres e homens (`sex`)?\n\n- $H_0$: mulheres e homens tiveram a mesma taxa de sobrevivência ($p_1 = p_2$).\n- $H_1$: as taxas de sobrevivência foram diferentes ($p_1 \\neq p_2$).\n:::\n\n**Premissas do teste**\n\n- Variável resposta binária: sucesso ou fracasso.\n- Observações independentes, dentro de cada grupo e entre os grupos.\n- Amostras grandes o bastante para a aproximação normal: $n \\cdot \\hat{p} \\geq 5$ e $n \\cdot (1 - \\hat{p}) \\geq 5$ em cada grupo.\n\nA resposta agora é **binária**: sobreviveu (1) ou não (0). A média de uma variável 0/1 é a proporção de uns, e a comparação passa a ser entre proporções. Sob $H_0$, as duas taxas são iguais, e a melhor estimativa dessa taxa comum é a **proporção combinada** $\\hat{p}$, que junta os dois grupos:\n\n$$\nZ = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1 - \\hat{p})\\left(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\right)}}\n\\qquad\n\\hat{p} = \\frac{x_1 + x_2}{n_1 + n_2}\n$$\n\n::: {#cc4fd97c .cell execution_count=39}\n``` {.python .cell-code}\n# Sobreviventes, total e proporção por sexo\nby_sex = (\n    titanic\n    .groupby(\"sex\")\n    .survived\n    .agg(sobreviventes=\"sum\", n=\"size\")\n    .assign(\n        nao_sobreviventes=lambda df: df[\"n\"] - df[\"sobreviventes\"],  # <1>\n        proporcao=lambda df: df[\"sobreviventes\"] / df[\"n\"],\n    )\n)\n\nby_sex.round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=615}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>sobreviventes</th>\n      <th>n</th>\n      <th>nao_sobreviventes</th>\n      <th>proporcao</th>\n    </tr>\n    <tr>\n      <th>sex</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>female</th>\n      <td>233</td>\n      <td>314</td>\n      <td>81</td>\n      <td>0.742</td>\n    </tr>\n    <tr>\n      <th>male</th>\n      <td>109</td>\n      <td>577</td>\n      <td>468</td>\n      <td>0.189</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. Sobreviventes e não sobreviventes correspondem a $n \\cdot \\hat{p}$ e $n \\cdot (1 - \\hat{p})$. A condição de aplicação exige que os dois sejam pelo menos 5 em cada grupo.\n\nSobreviveram 74,2% das mulheres (233 de 314) e 18,9% dos homens (109 de 577). A menor contagem da condição é 81, muito acima de 5. Calculamos *Z* pela fórmula e com o `statsmodels`:\n\n::: {#a4a1d468 .cell execution_count=40}\n``` {.python .cell-code}\n# Estatística Z pela fórmula e pelo statsmodels\np_pooled = by_sex[\"sobreviventes\"].sum() / by_sex[\"n\"].sum()\nse_pooled = np.sqrt(p_pooled * (1 - p_pooled) * (1 / by_sex[\"n\"]).sum())\ndiff = by_sex.loc[\"female\", \"proporcao\"] - by_sex.loc[\"male\", \"proporcao\"]\nz_manual = diff / se_pooled\n\ncase6 = proportions_ztest(by_sex[\"sobreviventes\"], by_sex[\"n\"])  # <1>\n\nprint(f\"proporção combinada = {p_pooled:.3f}\")\nprint(f\"Z calculado à mão = {z_manual:.2f}\")\nreport(\"Z de duas proporções\", case6, stat=\"Z\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nproporção combinada = 0.384\nZ calculado à mão = 16.22\nZ de duas proporções: Z = 16.219 · p < 0.001\n```\n:::\n:::\n\n\n1. `proportions_ztest` recebe o número de sucessos e o total de cada grupo e devolve a estatística *Z* e o *p*-valor.\n\nA proporção combinada é de 38,4%, a taxa geral de sobrevivência. A estatística vale $Z \\approx 16{,}2$: a diferença entre as taxas equivale a mais de 16 erros-padrão. O gráfico mostra cada taxa com seu intervalo de confiança de 95%:\n\n::: {#963c0e5b .cell execution_count=41}\n``` {.python .cell-code}\n# Proporção de sobreviventes por sexo, com intervalo de confiança\nlow, high = proportion_confint(by_sex[\"sobreviventes\"], by_sex[\"n\"])  # <1>\n\nfig, ax = plt.subplots(figsize=(7, 3.5))\nax.barh([\"Homens\", \"Mulheres\"], by_sex.loc[[\"male\", \"female\"], \"proporcao\"],\n        xerr=[(by_sex[\"proporcao\"] - low)[[\"male\", \"female\"]],\n              (high - by_sex[\"proporcao\"])[[\"male\", \"female\"]]],\n        color=[\"#A1C9F4\", \"#1F4E79\"], capsize=6)\nax.axvline(p_pooled, color=\"#DD8452\", linestyle=\"--\")\nax.set(xlim=(0, 1), xlabel=\"Proporção de sobreviventes (com IC 95%)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-42-output-1.png){width=657 height=321}\n:::\n:::\n\n\n1. `proportion_confint` devolve os limites inferior e superior do intervalo de confiança de cada proporção.\n\n**Interpretação.** A barra das mulheres é quase quatro vezes a dos homens, e os intervalos ficam muito longe um do outro e da taxa geral de 38% (linha tracejada). Se mulheres e homens tivessem a mesma chance de sobreviver, 55 pontos percentuais de diferença seriam impossíveis por acaso ($p < 0{,}001$). Rejeitamos $H_0$: a regra \"mulheres e crianças primeiro\" aparece nos dados.\n\n## Caso 7. Qui-quadrado de independência\n\n::: {.callout-note icon=false}\n## Cenário\n\nO mesmo historiador pergunta se a classe da passagem (`pclass`: 1ª, 2ª ou 3ª) teve relação com quem sobreviveu (`survived`), ou se a sobrevivência foi independente da classe.\n\n- $H_0$: a sobrevivência não depende da classe. As variáveis são independentes.\n- $H_1$: a sobrevivência está associada à classe.\n:::\n\n**Premissas do teste**\n\n- As duas variáveis são categóricas.\n- Observações independentes, cada uma contada em uma única célula da tabela.\n- Frequência esperada de pelo menos 5 em pelo menos 80% das células e nenhuma abaixo de 1. Quando essa condição falha, usa-se o teste exato de Fisher.\n\nCom duas variáveis categóricas, os dados se resumem a uma **tabela de contingência**, que conta os passageiros em cada combinação de classe e desfecho:\n\n::: {#3061d6c9 .cell execution_count=42}\n``` {.python .cell-code}\n# Tabela de contingência: classe por desfecho\nobserved = pd.crosstab(titanic[\"pclass\"], titanic[\"survived\"])  # <1>\n\nobserved\n```\n\n::: {.cell-output .cell-output-display execution_count=618}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>survived</th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n    <tr>\n      <th>pclass</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>80</td>\n      <td>136</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>97</td>\n      <td>87</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>372</td>\n      <td>119</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `pd.crosstab` conta as ocorrências de cada combinação de valores das duas colunas.\n\nO teste compara essas contagens observadas ($O$) com as que **esperaríamos se a classe não tivesse nada a ver com a sobrevivência** ($E$). Sob independência, a contagem esperada de cada célula é o total da linha vezes o total da coluna, dividido pelo total geral. A estatística soma as discrepâncias padronizadas de todas as células:\n\n$$\n\\chi^2 = \\sum \\frac{(O - E)^2}{E}\n\\qquad\n\\text{gl} = (\\text{linhas} - 1)(\\text{colunas} - 1)\n$$\n\n::: {#3181ca42 .cell execution_count=43}\n``` {.python .cell-code}\n# Qui-quadrado, frequências esperadas e parcela de cada célula\ncase7 = stats.chi2_contingency(observed)  # <1>\n\nexpected = pd.DataFrame(\n    case7.expected_freq, index=observed.index, columns=observed.columns\n)\ncontributions = (observed - expected) ** 2 / expected\n\nprint(f\"χ² = {case7.statistic:.2f}, gl = {case7.dof}, p = {case7.pvalue:.1e}\")\npd.concat({\"esperado\": expected, \"(O−E)²/E\": contributions}, axis=1).round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nχ² = 102.89, gl = 2, p = 4.5e-23\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=619}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead tr th {\n        text-align: left;\n    }\n\n    .dataframe thead tr:last-of-type th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr>\n      <th></th>\n      <th colspan=\"2\" halign=\"left\">esperado</th>\n      <th colspan=\"2\" halign=\"left\">(O−E)²/E</th>\n    </tr>\n    <tr>\n      <th>survived</th>\n      <th>0</th>\n      <th>1</th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n    <tr>\n      <th>pclass</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>133.1</td>\n      <td>82.9</td>\n      <td>21.2</td>\n      <td>34.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>113.4</td>\n      <td>70.6</td>\n      <td>2.4</td>\n      <td>3.8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>302.5</td>\n      <td>188.5</td>\n      <td>15.9</td>\n      <td>25.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `stats.chi2_contingency` calcula as frequências esperadas, a estatística, os graus de liberdade e o *p*-valor a partir da tabela observada.\n\nA estatística vale $\\chi^2 \\approx 102{,}9$, com 2 graus de liberdade e $p < 0{,}001$. A menor frequência esperada é 70,6, e a condição de aplicação é atendida com folga. As parcelas mostram **onde** está o desvio: as maiores contribuições vêm da 1ª classe, que sobreviveu muito mais que o esperado, e da 3ª, que sobreviveu muito menos.\n\n::: {#c652113f .cell execution_count=44}\n``` {.python .cell-code}\n# Contagens observadas e esperadas sob independência\ncomparison = (\n    pd.concat(\n        {\"observado\": observed.stack(), \"esperado\": expected.stack()},  # <1>\n        axis=1,\n    )\n    .rename(index={0: \"morreu\", 1: \"sobreviveu\"}, level=\"survived\")\n)\n\nfig, ax = plt.subplots(figsize=(9, 4))\ncomparison.plot.bar(ax=ax, color=[\"#1F4E79\", \"#A1C9F4\"], rot=0)\nax.set_xticklabels([f\"{c}ª · {d}\" for c, d in comparison.index])\nax.set(xlabel=\"\", ylabel=\"Passageiros\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](08-testes-parametricos_files/figure-html/cell-45-output-1.png){width=849 height=368}\n:::\n:::\n\n\n1. `.stack()` transforma a tabela em uma série com uma linha por célula, indexada por classe e desfecho.\n\n**Interpretação.** Se classe e sobrevivência fossem independentes, as barras escuras e claras teriam a mesma altura em cada par. Em vez disso, a 1ª classe tem mais sobreviventes que o esperado (136 contra 83), e a 3ª classe tem muito menos (119 contra 188). A taxa de sobrevivência cai de 63% na 1ª classe para 47% na 2ª e 24% na 3ª. Um desequilíbrio desse tamanho seria praticamente impossível por acaso. Rejeitamos $H_0$: a chance de sobreviver dependeu da classe de embarque. O V de Cramér, uma medida da força da associação entre 0 e 1, vale cerca de 0,34, uma associação moderada.\n\n::: {.callout-note collapse=\"true\"}\n## Z e qui-quadrado: o mesmo teste em tabelas 2 × 2\n\nO teste *Z* do caso 6 também pode ser escrito como um qui-quadrado sobre a tabela sexo × sobrevivência, que tem 2 linhas e 2 colunas. Nesse caso particular, $Z^2 = \\chi^2$: $16{,}2^2 \\approx 263$. As duas abordagens dão o mesmo *p*-valor. O qui-quadrado tem a vantagem de se estender a tabelas maiores, como a da classe, com três linhas.\n:::\n\n# 5. Quando as premissas falham\n\nSe as premissas não se sustentam, troca-se o teste. As alternativas não paramétricas trabalham, em geral, com **postos**: a posição de cada valor na ordenação, em vez do valor em si. Isso as torna robustas a assimetria e a valores atípicos.\n\n| Paramétrico | Alternativa não paramétrica | Como funciona |\n|---|---|---|\n| *t* de duas amostras | Mann-Whitney | Compara a soma dos postos dos dois grupos |\n| *t* pareado | Wilcoxon dos postos sinalizados | Postos das diferenças, com sinal |\n| ANOVA one-way | Kruskal-Wallis | Postos em três ou mais grupos |\n| Pearson | Spearman | Correlação dos postos: capta relações monotônicas |\n| Qualquer um | Permutação | Distribuição nula por embaralhamento (Aula 7) |\n\nAmostras com menos de 10 observações, assimetria forte, valores atípicos extremos ou escala ordinal são sinais para trocar o teste. O preço é perder um pouco de poder nas situações em que as premissas valeriam.\n\n# 6. Guia rápido\n\n| Pergunta | Teste | Função |\n|---|---|---|\n| A média difere de uma meta? | *t* de uma amostra | `stats.ttest_1samp` |\n| Dois grupos independentes têm a mesma média? | *t* de Welch | `stats.ttest_ind(..., equal_var=False)` |\n| A mesma unidade muda entre dois momentos? | *t* pareado | `stats.ttest_rel` |\n| Três ou mais grupos têm a mesma média? | ANOVA + Tukey | `stats.f_oneway`, `stats.tukey_hsd` |\n| Duas variáveis contínuas têm relação linear? | Pearson | `stats.pearsonr` |\n| Dois grupos têm a mesma proporção? | *Z* de duas proporções | `proportions_ztest` |\n| Duas variáveis categóricas são independentes? | Qui-quadrado | `stats.chi2_contingency` |\n| Os dados são normais? | Q-Q plot + Shapiro-Wilk | `stats.probplot`, `stats.shapiro` |\n| As variâncias são iguais? | Levene | `stats.levene` |\n\n## Síntese\n\n1. **Paramétrico.** A distribuição nula vem da teoria (*t*, *F*, *Z* ou $\\chi^2$), em troca de premissas.\n2. **Premissas.** Antes do teste, verifique normalidade, homocedasticidade e independência. O Q-Q plot e o Shapiro-Wilk se complementam.\n3. **Escolha.** O objetivo, a escala da variável e o delineamento determinam o teste.\n4. **Pareamento.** Ignorar o pareamento infla o erro-padrão: no `sleep`, o *p*-valor foi de 0,003 para 0,079.\n5. **Muitos grupos.** Com três ou mais grupos, use a ANOVA seguida de um teste post-hoc, nunca uma série de testes *t*.\n\n# Perguntas para consolidar\n\n**Pergunta 1: por que o pareamento mudou o resultado do `sleep`?**\n\nOs mesmos 20 números deram $p \\approx 0{,}003$ no teste pareado e $p \\approx 0{,}079$ no teste para amostras independentes. Como isso é possível?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nA diferença média é a mesma nas duas análises: 1,58 h. O que muda é o erro-padrão. No teste independente, ele inclui a variação entre pacientes, que é grande: alguns dormem bem com qualquer droga, outros não. No teste pareado, cada paciente serve de controle para si mesmo. A diferença $D$ elimina o nível de base de cada pessoa, e sobra apenas a variação do efeito da droga, que é pequena. Com um erro-padrão menor, a mesma diferença se distingue do acaso. Ignorar o pareamento não é apenas menos eficiente: é usar um teste cuja premissa de independência foi violada.\n:::\n\n**Pergunta 2: não rejeitar $H_0$ no caso 1 prova que a frota cumpre a meta?**\n\nNo caso 1, $p \\approx 0{,}93$. O gestor pode afirmar que o consumo médio da frota é de 20 mpg?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nNão. O teste mostra apenas que os dados são compatíveis com a meta. O intervalo de confiança, de 17,9 a 22,3 mpg, mostra que eles também são compatíveis com uma frota 2 mpg abaixo ou acima da meta. Com 32 carros e um desvio-padrão de 6 mpg, a precisão da média é limitada. Para afirmar que a frota está **dentro** de uma faixa aceitável, seria necessário outro desenho de teste, chamado teste de equivalência, ou uma amostra maior.\n:::\n\n**Pergunta 3: o caso 6 precisava de um teste diferente do caso 7?**\n\nOs casos 6 e 7 usam a mesma base e a mesma resposta, a sobrevivência. Por que um usa *Z* e o outro $\\chi^2$?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nA diferença está na variável explicativa. No caso 6, ela é binária (sexo), e a pergunta é se duas proporções são iguais. No caso 7, ela tem três categorias (classe), e o teste *Z* de duas proporções não se aplica diretamente. Para tabelas 2 × 2, os dois testes são equivalentes: $Z^2 = \\chi^2$. O qui-quadrado generaliza a comparação de proporções para qualquer número de categorias.\n:::\n\n# Para casa\n\n1. Repita o caso 2 comparando a massa corporal das espécies Adelie e Gentoo. Verifique as premissas antes de escolher entre o *t* clássico e o de Welch.\n2. Aplique a ANOVA do caso 4 ao comprimento da **pétala** (`petal_length`). O que o teste de Levene indica? Compare o resultado com o teste de Kruskal-Wallis (`stats.kruskal`).\n3. No Titanic, teste se a taxa de sobrevivência difere entre os portos de embarque (`embarked`). Qual teste você escolheu, e por quê?\n4. Antes de considerar o notebook pronto, use Restart Kernel and Run All.\n\n## Referências\n\n1. Bruce, P.; Bruce, A.; Gedeck, P. *Practical Statistics for Data Scientists*. 2. ed. O'Reilly, 2020.\n2. Student. The probable error of a mean. *Biometrika*, 6(1), 1-25, 1908.\n3. Welch, B. L. The generalization of \"Student's\" problem when several different population variances are involved. *Biometrika*, 34(1-2), 28-35, 1947.\n4. Shapiro, S. S.; Wilk, M. B. An analysis of variance test for normality (complete samples). *Biometrika*, 52(3-4), 591-611, 1965.\n5. Fisher, R. A. The use of multiple measurements in taxonomic problems. *Annals of Eugenics*, 7(2), 179-188, 1936.\n6. Horst, A. M.; Hill, A. P.; Gorman, K. B. *palmerpenguins: Palmer Archipelago (Antarctica) penguin data*. R package, 2020.\n7. Henderson, H. V.; Velleman, P. F. Building multiple regression models interactively. *Biometrics*, 37(2), 391-411, 1981.\n\n",
    "supporting": [
      "08-testes-parametricos_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}