{
  "hash": "f4cd5d86181c83b040af30dd1dac534f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Aula 7 - Inferência Estatística'\ndate: last-modified\ntoc: true\nformat:\n  html: default\n  ipynb: default\njupyter:\n  kernel: python3\nexecute:\n  enabled: true\n---\n\n\n\n\n\n\n## Motivação\n\nNa Aula 5, a estatística descritiva resumiu os dados observados sem generalizá-los. Na Aula 6, o diagnóstico orientou o tratamento da base. Em ambas, as conclusões ficaram restritas à amostra disponível. Nesta aula, damos o passo seguinte. Ao comparar dois grupos, encontramos uma diferença. A pergunta passa a ser se essa diferença diz algo sobre o processo que gerou os dados ou se é apenas um resultado da variabilidade aleatória da amostra.\n\nConsidere um exemplo clássico. A revista *Motor Trend* mediu, em 1974, o consumo de 32 modelos de carro. Os carros com câmbio manual percorrem, em média, cerca de 7 milhas a mais por galão do que os automáticos. A diferença parece grande, mas a amostra é pequena. Se a revista tivesse escolhido outros 32 carros, a diferença seria outra. Talvez menor, talvez nula, talvez invertida.\n\nA estatística inferencial oferece um procedimento para responder a essa pergunta. Primeiro, supomos que **não existe** efeito algum. Em seguida, medimos quão raro seria observar uma diferença do tamanho da encontrada se essa suposição fosse verdadeira. Se a diferença for muito rara sob o acaso, temos evidência contra a suposição inicial. Estudaremos duas formas de construir essa referência: uma por simulação, o **teste de permutação**, e outra por fórmula, o **teste *t* de Student**.\n\n> **Diferença real ou acaso?**\n\n## Objetivos de aprendizagem\n\nAo final deste roteiro, você será capaz de:\n\n1. Medir o efeito observado ($\\Delta_{obs}$) entre dois grupos e comparar sua dispersão com boxplots.\n2. Formular a hipótese nula ($H_0$) e a hipótese alternativa ($H_1$) para uma comparação entre grupos.\n3. Aplicar o teste de permutação e construir a distribuição empírica do acaso.\n4. Aplicar o teste *t* de Student, reconhecendo suas premissas, seus limites e sua sensibilidade a valores atípicos.\n5. Interpretar o *p*-valor, o nível de significância ($\\alpha$) e os erros dos tipos I e II, distinguindo significância estatística de relevância prática.\n\n::: {.callout-tip}\n## Como usar este roteiro\n\nO roteiro usa a base `mtcars.csv`, salva em `mtcars/data/`, e um conjunto simulado de atendimentos em um pronto-socorro, gerado no próprio roteiro.\n\nAlém das bibliotecas das aulas anteriores, usamos o módulo `statsmodels` na seção 6.3.\n\nAo final, três perguntas ajudam a consolidar a interpretação dos testes.\n:::\n\n# 1. Preparando os dados\n\nComeçamos importando as bibliotecas usadas na simulação, nos testes e na visualização.\n\n::: {#4d4f09c1 .cell execution_count=1}\n``` {.python .cell-code}\n# Importa as bibliotecas e define o tema dos gráficos\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nimport statsmodels.formula.api as smf\n\nsns.set_theme(style=\"whitegrid\", palette=\"colorblind\")\n```\n:::\n\n\nA base `mtcars` reúne 32 modelos de carro vendidos nos Estados Unidos em 1973 e 1974. Usaremos quatro de suas onze colunas:\n\n| Coluna | Significado |\n|---|---|\n| `mpg` | Consumo, em milhas por galão. Quanto maior, mais econômico |\n| `am` | Câmbio: 0 = automático, 1 = manual |\n| `wt` | Peso, em milhares de libras |\n| `hp` | Potência, em cavalos |\n\nAo carregar a base, criamos duas colunas auxiliares: um rótulo legível para o câmbio e o peso convertido para quilogramas.\n\n::: {#3fdc7f87 .cell execution_count=2}\n``` {.python .cell-code}\n# Carrega a base e cria o rótulo do câmbio e o peso em kg\nmtcars = (\n    pd.read_csv(\"mtcars/data/mtcars.csv\")\n    .assign(\n        transmission=lambda df: np.where(  # <1>\n            df[\"am\"] == 1,\n            \"Manual\",\n            \"Automático\",\n        ),\n        weight_kg=lambda df: df[\"wt\"] * 453.6,  # <2>\n    )\n)\n\nmtcars.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=36}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>model</th>\n      <th>mpg</th>\n      <th>cyl</th>\n      <th>disp</th>\n      <th>hp</th>\n      <th>drat</th>\n      <th>wt</th>\n      <th>qsec</th>\n      <th>vs</th>\n      <th>am</th>\n      <th>gear</th>\n      <th>carb</th>\n      <th>transmission</th>\n      <th>weight_kg</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Mazda RX4</td>\n      <td>21.0</td>\n      <td>6</td>\n      <td>160.0</td>\n      <td>110</td>\n      <td>3.90</td>\n      <td>2.620</td>\n      <td>16.46</td>\n      <td>0</td>\n      <td>1</td>\n      <td>4</td>\n      <td>4</td>\n      <td>Manual</td>\n      <td>1188.432</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Mazda RX4 Wag</td>\n      <td>21.0</td>\n      <td>6</td>\n      <td>160.0</td>\n      <td>110</td>\n      <td>3.90</td>\n      <td>2.875</td>\n      <td>17.02</td>\n      <td>0</td>\n      <td>1</td>\n      <td>4</td>\n      <td>4</td>\n      <td>Manual</td>\n      <td>1304.100</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Datsun 710</td>\n      <td>22.8</td>\n      <td>4</td>\n      <td>108.0</td>\n      <td>93</td>\n      <td>3.85</td>\n      <td>2.320</td>\n      <td>18.61</td>\n      <td>1</td>\n      <td>1</td>\n      <td>4</td>\n      <td>1</td>\n      <td>Manual</td>\n      <td>1052.352</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Hornet 4 Drive</td>\n      <td>21.4</td>\n      <td>6</td>\n      <td>258.0</td>\n      <td>110</td>\n      <td>3.08</td>\n      <td>3.215</td>\n      <td>19.44</td>\n      <td>1</td>\n      <td>0</td>\n      <td>3</td>\n      <td>1</td>\n      <td>Automático</td>\n      <td>1458.324</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hornet Sportabout</td>\n      <td>18.7</td>\n      <td>8</td>\n      <td>360.0</td>\n      <td>175</td>\n      <td>3.15</td>\n      <td>3.440</td>\n      <td>17.02</td>\n      <td>0</td>\n      <td>0</td>\n      <td>3</td>\n      <td>2</td>\n      <td>Automático</td>\n      <td>1560.384</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `np.where` escolhe o rótulo linha a linha, como na Aula 6.\n2. Uma libra equivale a cerca de 0,4536 kg, e `wt` está em milhares de libras.\n\n# 2. A diferença observada\n\nO primeiro passo de qualquer comparação é descritivo. Calculamos uma estatística em cada grupo e medimos a distância entre elas. Chamamos essa distância de **efeito observado**:\n\n$$\n\\Delta_{obs} = \\bar{x}_A - \\bar{x}_B\n$$\n\nAqui, $\\bar{x}_A$ e $\\bar{x}_B$ são as médias amostrais dos grupos A e B. Quando há assimetria ou valores atípicos, a diferença de medianas é uma alternativa mais robusta, pelos mesmos motivos discutidos na Aula 5.\n\n::: {#970b3cf6 .cell execution_count=3}\n``` {.python .cell-code}\n# Tamanho, média, mediana e desvio-padrão do consumo por câmbio\n(\n    mtcars\n    .groupby(\"transmission\")\n    .mpg\n    .agg([\"size\", \"mean\", \"median\", \"std\"])\n    .round(2)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=37}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>size</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>transmission</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Automático</th>\n      <td>19</td>\n      <td>17.15</td>\n      <td>17.3</td>\n      <td>3.83</td>\n    </tr>\n    <tr>\n      <th>Manual</th>\n      <td>13</td>\n      <td>24.39</td>\n      <td>22.8</td>\n      <td>6.17</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#d052dead .cell execution_count=4}\n``` {.python .cell-code}\n# Efeito observado: diferença das médias de consumo\nmanual = mtcars.loc[mtcars.am == 1, \"mpg\"]\nautomatic = mtcars.loc[mtcars.am == 0, \"mpg\"]\n\ndelta_obs = manual.mean() - automatic.mean()\n\nround(delta_obs, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=38}\n```\nnp.float64(7.24)\n```\n:::\n:::\n\n\nOs carros manuais fazem, em média, 7,24 milhas por galão a mais. O boxplot mostra a diferença e a dispersão de cada grupo. Cada ponto é um carro, e as linhas tracejadas marcam as médias.\n\n::: {#fe0f3d7a .cell execution_count=5}\n``` {.python .cell-code}\n# Boxplot com os carros sobrepostos e as médias de cada grupo\nfig, ax = plt.subplots(figsize=(6, 4.5))\n\norder = [\"Automático\", \"Manual\"]\n\nsns.boxplot(\n    data=mtcars,\n    x=\"transmission\",\n    y=\"mpg\",\n    order=order,\n    color=\"#A1C9F4\",\n    showfliers=False,  # <1>\n    ax=ax,\n)\nsns.stripplot(\n    data=mtcars,\n    x=\"transmission\",\n    y=\"mpg\",\n    order=order,\n    color=\"#1F4E79\",\n    size=6,\n    jitter=.15,\n    ax=ax,\n)\nfor mean in [automatic.mean(), manual.mean()]:\n    ax.axhline(mean, color=\"#DD8452\", linestyle=\"--\")\n\nax.set(\n    title=f\"Δobs = {delta_obs:.2f} mpg\",\n    xlabel=\"\",\n    ylabel=\"Consumo (milhas por galão)\",\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-6-output-1.png){width=562 height=416}\n:::\n:::\n\n\n1. Os pontos já aparecem no `stripplot`. `showfliers=False` evita desenhá-los duas vezes.\n\nOs manuais parecem mais econômicos. Mas $\\Delta_{obs} \\neq 0$ é apenas uma descrição da amostra, não uma prova de diferença na população. Há três motivos para cautela:\n\n- **Natureza estocástica.** Cada amostra é uma entre muitas realizações possíveis. A média amostral flutua em torno do parâmetro verdadeiro e, por isso, dois grupos sem diferença real raramente apresentam médias idênticas.\n- **Sensibilidade a valores atípicos.** Um único valor extremo pode deslocar $\\bar{x}$ e fabricar um $\\Delta_{obs}$ expressivo que não representa a maior parte dos dados.\n- **Recorte limitado.** Os dados capturam uma janela no tempo e no espaço. Viés de amostragem e fatores ocultos limitam a extrapolação.\n\nO primeiro motivo é o tema central desta aula. Antes de formalizá-lo, vejamos como ele engana a intuição.\n\n# 3. O problema da aleatoriedade\n\nA **apofenia** é a tendência humana de perceber padrões e relações significativas em dados puramente aleatórios. Vemos rostos em nuvens e sequências em números sorteados. Uma variante conhecida é a *falácia do atirador do Texas*: atirar contra a parede de um celeiro e, só depois, desenhar o alvo em volta do grupo de tiros mais próximos.\n\nUm exemplo clássico entre profissionais de saúde é a crença de que \"plantão de lua cheia é sempre cheio\". Uma meta-análise com dezenas de estudos (Rotton & Kelly, 1985) não encontrou relação entre as fases da lua e o comportamento humano. A crença persiste por viés de confirmação: a noite agitada de lua cheia vira história, e a noite calma é esquecida.\n\n## 3.1 Um pronto-socorro simulado\n\nPara estudar a crença, simulamos um ano de atendimentos em um pronto-socorro fictício. A simulação tem uma vantagem didática importante: **sabemos** que a lua não tem efeito, porque os atendimentos de todos os dias são sorteados da mesma distribuição.\n\n::: {#27b01706 .cell execution_count=6}\n``` {.python .cell-code}\n# Um ano de atendimentos diários, sem nenhum efeito da lua\nrng = np.random.default_rng(2726)  # <1>\n\nfull_moon_days = np.round(np.arange(12) * 29.53 + 14)  # <2>\n\ner_visits = (\n    pd.DataFrame({\"day\": np.arange(365)})\n    .assign(\n        visits=rng.poisson(120, size=365),  # <3>\n        full_moon=lambda df: df[\"day\"].isin(full_moon_days),\n        moon=lambda df: np.where(df[\"full_moon\"], \"Lua cheia\", \"Demais dias\"),\n    )\n)\n```\n:::\n\n\n1. A semente fixa garante os mesmos atendimentos a cada execução.\n2. O ciclo lunar dura cerca de 29,53 dias, o que resulta em 12 dias de lua cheia no ano.\n3. A distribuição de Poisson é usada com frequência para contagens de eventos. Todos os dias têm a mesma média, 120 atendimentos.\n\n::: {#b8e070a4 .cell execution_count=7}\n``` {.python .cell-code}\n# Atendimentos por dia em cada grupo\n(\n    er_visits\n    .groupby(\"moon\")\n    .visits\n    .agg([\"size\", \"mean\", \"median\", \"std\"])\n    .round(2)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=41}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>size</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>moon</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Demais dias</th>\n      <td>353</td>\n      <td>119.78</td>\n      <td>119.0</td>\n      <td>10.94</td>\n    </tr>\n    <tr>\n      <th>Lua cheia</th>\n      <td>12</td>\n      <td>123.67</td>\n      <td>121.5</td>\n      <td>9.36</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#27d7a807 .cell execution_count=8}\n``` {.python .cell-code}\n# Efeito observado da lua cheia\nmoon_obs = (\n    er_visits.loc[er_visits.full_moon, \"visits\"].mean()\n    - er_visits.loc[~er_visits.full_moon, \"visits\"].mean()  # <1>\n)\n\nround(moon_obs, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=42}\n```\nnp.float64(3.88)\n```\n:::\n:::\n\n\n1. `~` inverte uma série booleana. Aqui, seleciona os dias que **não** são de lua cheia.\n\n::: {#887ca331 .cell execution_count=9}\n``` {.python .cell-code}\n# Boxplot dos atendimentos por grupo\nfig, ax = plt.subplots(figsize=(6, 4.5))\n\norder = [\"Demais dias\", \"Lua cheia\"]\n\nsns.boxplot(\n    data=er_visits,\n    x=\"moon\",\n    y=\"visits\",\n    order=order,\n    color=\"#A1C9F4\",\n    showfliers=False,\n    ax=ax,\n)\nsns.stripplot(\n    data=er_visits,\n    x=\"moon\",\n    y=\"visits\",\n    order=order,\n    color=\"#1F4E79\",\n    alpha=.4,\n    jitter=.2,\n    ax=ax,\n)\nax.set(\n    title=f\"Δobs = {moon_obs:+.2f} atendimentos/dia\",\n    xlabel=\"\",\n    ylabel=\"Atendimentos por dia\",\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-10-output-1.png){width=561 height=416}\n:::\n:::\n\n\nOs dias de lua cheia tiveram, em média, cerca de 3,9 atendimentos a mais. O resultado parece confirmar a crença, embora tenhamos construído os dados **sem** qualquer efeito da lua. A diferença surgiu apenas porque 12 dias sorteados raramente têm a mesma média que os outros 353.\n\nTemos agora duas diferenças: 7,24 mpg no `mtcars` e 3,9 atendimentos no pronto-socorro. Sabemos que a segunda é puro acaso. Precisamos de um procedimento que, sem conhecer a resposta de antemão, distinga um caso do outro.\n\n# 4. Formalizando o acaso\n\n## 4.1 Hipóteses nula e alternativa\n\nUm teste de hipóteses confronta duas proposições sobre a **população**, não sobre a amostra:\n\n| Hipótese | Notação | Leitura |\n|---|---|---|\n| Nula ($H_0$) | $\\mu_A = \\mu_B \\iff \\Delta = 0$ | Não há efeito. A diferença observada é fruto do acaso |\n| Alternativa ($H_1$) | $\\mu_A \\neq \\mu_B \\iff \\Delta \\neq 0$ | Existe um efeito real no processo gerador dos dados |\n\nAqui, $\\mu$ é a média populacional, $\\Delta$ é o efeito verdadeiro, que desconhecemos, e $\\Delta_{obs}$ é sua estimativa na amostra. A hipótese alternativa também aparece escrita como $H_a$.\n\nPara a lua cheia:\n\n- $H_0$: $\\mu_{\\text{lua cheia}} = \\mu_{\\text{demais dias}}$. A lua não afeta o movimento do pronto-socorro.\n- $H_1$: $\\mu_{\\text{lua cheia}} \\neq \\mu_{\\text{demais dias}}$. O movimento muda em noites de lua cheia.\n\nA lógica do teste lembra a de um tribunal:\n\n| Julgamento | Teste de hipóteses |\n|---|---|\n| Presunção de inocência | $H_0$: não há efeito |\n| Provas apresentadas | Dados observados ($\\Delta_{obs}$) |\n| Culpado \"além de dúvida razoável\" | *p*-valor $\\leq \\alpha$ |\n| Condenar um inocente | Erro do tipo I (falso positivo) |\n| Absolver um culpado | Erro do tipo II (falso negativo) |\n| \"Não culpado\" não significa inocente | Não rejeitar $H_0$ não prova $H_0$ |\n\nO réu é considerado inocente até que as provas tornem essa hipótese difícil de sustentar. Da mesma forma, partimos de $H_0$ e só a abandonamos se os dados forem improváveis sob ela.\n\n## 4.2 O teste de permutação\n\nSe $H_0$ for verdadeira, o rótulo \"lua cheia\" não carrega informação alguma sobre o número de atendimentos. Os 365 valores vêm de uma única distribuição, e o rótulo poderia estar em quaisquer 12 dias do ano. Dizemos que, sob $H_0$, os rótulos são **intercambiáveis**.\n\nEssa ideia leva a um procedimento em quatro passos:\n\n1. **Medir.** Calcular a estatística nos dados reais: $\\Delta_{obs}$.\n2. **Embaralhar.** Sob $H_0$, os rótulos não importam. Sortear novamente quais observações recebem cada rótulo.\n3. **Recalcular.** Calcular a mesma estatística nos dados embaralhados: $\\Delta_{perm}$.\n4. **Repetir.** Fazer isso muitas vezes, por exemplo 10.000, para obter a distribuição empírica de $\\Delta$ sob o acaso, chamada **distribuição nula**.\n\nEscrevemos duas funções. A primeira calcula a diferença de médias a partir de valores e rótulos. A segunda embaralha os rótulos e recalcula a diferença repetidas vezes.\n\n::: {#eb3e70d2 .cell execution_count=10}\n``` {.python .cell-code}\n# Diferença de médias e distribuição nula por permutação\ndef mean_diff(values, labels):\n    return values[labels].mean() - values[~labels].mean()\n\ndef permutation_null(values, labels, n_perm=10_000, seed=2026):\n    rng = np.random.default_rng(seed)\n    return np.array([\n        mean_diff(values, rng.permutation(labels))  # <1>\n        for _ in range(n_perm)  # <2>\n    ])\n```\n:::\n\n\n1. `rng.permutation` devolve uma cópia embaralhada dos rótulos. Os valores ficam no lugar, e os rótulos mudam de dono.\n2. `_` é o nome convencional para uma variável de laço que não será usada.\n\nAplicamos as funções aos dados do pronto-socorro:\n\n::: {#6bc1e4f1 .cell execution_count=11}\n``` {.python .cell-code}\n# Distribuição nula da lua cheia\nmoon_values = er_visits[\"visits\"].to_numpy()  # <1>\nmoon_labels = er_visits[\"full_moon\"].to_numpy()\n\nmoon_null = permutation_null(moon_values, moon_labels)\n\nmoon_null[:5].round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=45}\n```\narray([-5.33, -6.46, -2.23, -1.54,  4.49])\n```\n:::\n:::\n\n\n1. Arrays do NumPy aceitam indexação booleana sem alinhar índices, o que torna o laço mais rápido.\n\nCada valor de `moon_null` é a diferença que teríamos observado se 12 dias quaisquer tivessem recebido o rótulo de lua cheia. O histograma mostra onde $\\Delta_{obs}$ cai nessa distribuição. Como $H_1$ admite diferenças nos dois sentidos, marcamos $+\\Delta_{obs}$ e $-\\Delta_{obs}$.\n\n::: {#38ca3d6a .cell execution_count=12}\n``` {.python .cell-code}\n# Distribuição nula da lua cheia e posição do efeito observado\nfig, ax = plt.subplots(figsize=(9, 4))\n\nsns.histplot(moon_null, bins=50, color=\"#A1C9F4\", ax=ax)\nfor value in [-moon_obs, moon_obs]:\n    ax.axvline(value, color=\"#DD8452\", linewidth=2)\n\nax.set(\n    title=\"Lua cheia: onde cai o Δobs na distribuição do acaso?\",\n    xlabel=\"Δperm: diferença de médias após sortear 12 dias como lua cheia\",\n    ylabel=\"Permutações\",\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-13-output-1.png){width=850 height=369}\n:::\n:::\n\n\nO efeito observado cai em uma região bem povoada da distribuição. A proporção de permutações com resultado tão ou mais extremo que $\\Delta_{obs}$ responde à pergunta \"quão comum é esse resultado sob o acaso?\":\n\n::: {#74748824 .cell execution_count=13}\n``` {.python .cell-code}\n# Proporção de permutações tão ou mais extremas que o observado\nmoon_p = np.mean(np.abs(moon_null) >= abs(moon_obs))  # <1>\n\nmoon_p\n```\n\n::: {.cell-output .cell-output-display execution_count=47}\n```\nnp.float64(0.23)\n```\n:::\n:::\n\n\n1. A média de um vetor booleano é a proporção de `True`. O valor absoluto conta os dois sentidos: o teste é **bilateral**.\n\n## 4.3 O *p*-valor\n\nEssa proporção tem nome. O ***p*-valor** é a probabilidade, **supondo $H_0$ verdadeira**, de obter um efeito tão ou mais extremo que o observado:\n\n$$\np = P\\left(|\\Delta_{perm}| \\geq |\\Delta_{obs}| \\;\\middle|\\; H_0 \\text{ verdadeira}\\right)\n$$\n\nNo pronto-socorro, cerca de 23% das permutações produziram diferenças pelo menos tão grandes quanto a observada. Uma diferença de 3,9 atendimentos é, portanto, um resultado corriqueiro quando a lua não tem efeito algum.\n\nO *p*-valor é frequentemente mal interpretado. A American Statistical Association publicou uma declaração específica sobre o tema (Wasserstein & Lazar, 2016):\n\n| O *p*-valor é | O *p*-valor não é |\n|---|---|\n| Uma probabilidade condicional a $H_0$ | A probabilidade de $H_0$ ser verdadeira |\n| Uma medida de quão atípicos os dados são sob o acaso | A probabilidade de o resultado ser \"mero acaso\" |\n| Dependente do tamanho da amostra | Uma medida do tamanho ou da importância do efeito |\n\n::: {.callout-important}\nO *p*-valor responde a \"**se** não houvesse efeito, quão raro seria este resultado?\". Ele não responde a \"qual é a probabilidade de não haver efeito?\". As duas perguntas têm respostas diferentes.\n:::\n\n## 4.4 A regra de decisão\n\nPara transformar o *p*-valor em uma decisão, fixamos **antes da análise** um limiar chamado **nível de significância**, $\\alpha$. O valor convencional é $\\alpha = 0{,}05$.\n\n| Resultado | Decisão | Leitura |\n|---|---|---|\n| $p \\leq \\alpha$ | Rejeita-se $H_0$ | Os dados são atípicos demais para o acaso. O efeito é estatisticamente significante |\n| $p > \\alpha$ | Não se rejeita $H_0$ | A diferença é compatível com a flutuação aleatória. Isso não prova que $H_0$ seja verdadeira |\n\nNa lua cheia, $p \\approx 0{,}23 > 0{,}05$. Não rejeitamos $H_0$: o \"plantão de lua cheia\" é compatível com o acaso. Neste caso, sabemos que a decisão está correta, porque construímos os dados sem efeito.\n\n::: {.callout-note collapse=\"true\"}\n## Por que 0,05?\n\nO valor é uma convenção, popularizada por R. A. Fisher na década de 1920, e não uma propriedade matemática. Áreas diferentes adotam limiares diferentes. A física de partículas, por exemplo, exige evidências muito mais fortes antes de anunciar uma descoberta. O importante é fixar $\\alpha$ antes de olhar os dados. Escolher o limiar depois de ver o *p*-valor é uma versão da falácia do atirador do Texas.\n:::\n\n## 4.5 Permutação no `mtcars`\n\nRepetimos o procedimento para o câmbio. Sob $H_0$, o câmbio não afeta o consumo, e os 32 valores de `mpg` vêm de uma única distribuição. Qualquer divisão em 13 manuais e 19 automáticos seria tão plausível quanto a real.\n\n::: {#811d1653 .cell execution_count=14}\n``` {.python .cell-code}\n# Distribuição nula do câmbio\nmpg_values = mtcars[\"mpg\"].to_numpy()\nmpg_labels = (mtcars[\"am\"] == 1).to_numpy()\n\nmpg_null = permutation_null(mpg_values, mpg_labels)\n\nmpg_p = np.mean(np.abs(mpg_null) >= abs(delta_obs))\n\nmpg_p\n```\n\n::: {.cell-output .cell-output-display execution_count=48}\n```\nnp.float64(0.0001)\n```\n:::\n:::\n\n\n::: {#fe4703fc .cell execution_count=15}\n``` {.python .cell-code}\n# Distribuição nula do câmbio e posição do efeito observado\nfig, ax = plt.subplots(figsize=(9, 4))\n\nsns.histplot(mpg_null, bins=50, color=\"#A1C9F4\", ax=ax)\nfor value in [-delta_obs, delta_obs]:\n    ax.axvline(value, color=\"#DD8452\", linewidth=2)\n\nax.set(\n    title=\"Câmbio: onde cai o Δobs na distribuição do acaso?\",\n    xlabel=\"Δperm: diferença de médias (mpg) após embaralhar o câmbio\",\n    ylabel=\"Permutações\",\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-16-output-1.png){width=850 height=368}\n:::\n:::\n\n\nAgora, as linhas ficam nas extremidades, fora da região ocupada pelas permutações. Apenas uma em 10.000 chegou a uma diferença de 7,24 mpg. Como $p < 0{,}05$, rejeitamos $H_0$: uma diferença desse tamanho seria muito rara se o câmbio não importasse.\n\n::: {.callout-warning}\nRejeitar $H_0$ indica que a diferença dificilmente é acaso. **Não** indica que o câmbio seja a causa da diferença. Os carros manuais da base também são mais leves, uma questão que retomaremos na seção 6.3.\n:::\n\n# 5. O atalho paramétrico\n\nO teste de permutação constrói a distribuição nula por simulação. Um teste **paramétrico** chega ao mesmo destino por outro caminho:\n\n1. **Supor um modelo.** Os dados, ou as médias, seguem uma família conhecida, como a normal, com parâmetros $\\mu$ e $\\sigma$.\n2. **Derivar a distribuição nula.** Sob $H_0$, a estatística do teste segue uma distribuição teórica, como *t*, *F*, $\\chi^2$ ou *Z*.\n3. **Ler o *p*-valor.** A área na cauda vem de uma fórmula, sem simular nada.\n\nA vantagem é a rapidez e, quando as premissas valem, um poder maior. O risco é que, se as premissas falharem, o *p*-valor pode enganar.\n\n## 5.1 O erro-padrão\n\nPara substituir a simulação, a teoria precisa saber **quanto a diferença de médias oscila por acaso**. Essa oscilação corresponde à largura da distribuição nula, que podemos medir pelo desvio-padrão das permutações:\n\n::: {#801b844f .cell execution_count=16}\n``` {.python .cell-code}\n# Largura da distribuição nula do câmbio, medida pela simulação\nround(mpg_null.std(), 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=50}\n```\nnp.float64(2.16)\n```\n:::\n:::\n\n\nA teoria prevê essa largura sem simular nada. Sob $H_0$, os dois grupos vêm da mesma população, cujo desvio-padrão estimamos com os 32 carros juntos. A oscilação da diferença de médias é dada por:\n\n$$\nSE = s \\sqrt{\\frac{1}{n_A} + \\frac{1}{n_B}}\n$$\n\n::: {#94ff4c60 .cell execution_count=17}\n``` {.python .cell-code}\n# Largura da distribuição nula do câmbio, prevista pela fórmula\nn_manual, n_automatic = len(manual), len(automatic)\n\nse_null = mtcars.mpg.std() * np.sqrt(1 / n_manual + 1 / n_automatic)\n\nround(se_null, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=51}\n```\nnp.float64(2.17)\n```\n:::\n:::\n\n\nOs dois valores praticamente coincidem. A curva normal com essa largura descreve bem o histograma das permutações:\n\n::: {#fa741ee4 .cell execution_count=18}\n``` {.python .cell-code}\n# Histograma das permutações e curva normal prevista pela fórmula\nfig, ax = plt.subplots(figsize=(8, 4))\n\ngrid = np.linspace(-9, 9, 300)\n\nax.hist(mpg_null, bins=40, density=True, color=\"#A1C9F4\", label=\"10.000 permutações\")  # <1>\nax.plot(grid, stats.norm.pdf(grid, 0, se_null), color=\"#1F4E79\", linewidth=2, label=\"curva prevista pela fórmula\")\nfor value in [-se_null, se_null]:\n    ax.axvline(value, color=\"#DD8452\", linestyle=\"--\")\n\nax.set(\n    title=\"±1 erro-padrão\",\n    xlabel=\"Δperm: diferença de médias sob H₀ (mpg)\",\n    ylabel=\"Densidade\",\n)\nax.legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-19-output-1.png){width=753 height=369}\n:::\n:::\n\n\n1. `density=True` coloca o histograma na mesma escala da curva, com área total igual a 1.\n\nEssa largura recebe o nome de **erro-padrão** (SE, do inglês *standard error*). Ela funciona como a régua do acaso.\n\n## 5.2 Desvio-padrão e erro-padrão\n\nOs dois termos se parecem, mas medem coisas diferentes:\n\n| | Desvio-padrão ($s$) | Erro-padrão ($SE$) |\n|---|---|---|\n| O que mede | A dispersão dos **dados individuais** em torno da média | A variabilidade da **própria estimativa**, como $\\bar{x}$, entre amostras repetidas |\n| Com mais dados | Não diminui: é uma característica da população | Diminui: $SE(\\bar{x}) = s / \\sqrt{n}$ |\n\nO pronto-socorro simulado ilustra a diferença. Sorteamos 2.000 amostras de cada tamanho a partir dos 365 dias e, para cada tamanho, calculamos duas coisas: o desvio-padrão típico **dentro** de uma amostra e o desvio-padrão das médias **entre** as amostras.\n\n::: {#74c13d98 .cell execution_count=19}\n``` {.python .cell-code}\n# Desvio-padrão dos dados e das médias amostrais, por tamanho de amostra\nrng = np.random.default_rng(42)\n\ndef sample_summary(n, n_samples=2_000):\n    samples = rng.choice(moon_values, size=(n_samples, n))  # <1>\n    return {\n        \"dp_dos_dados\": samples.std(axis=1, ddof=1).mean(),  # <2>\n        \"dp_das_medias\": samples.mean(axis=1).std(ddof=1),  # <3>\n        \"previsto_s_raiz_n\": moon_values.std(ddof=1) / np.sqrt(n),\n    }\n\n(\n    pd.DataFrame({n: sample_summary(n) for n in [10, 40, 160, 640]})\n    .T\n    .rename_axis(\"n\")\n    .round(2)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=53}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dp_dos_dados</th>\n      <th>dp_das_medias</th>\n      <th>previsto_s_raiz_n</th>\n    </tr>\n    <tr>\n      <th>n</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>10</th>\n      <td>10.64</td>\n      <td>3.54</td>\n      <td>3.45</td>\n    </tr>\n    <tr>\n      <th>40</th>\n      <td>10.81</td>\n      <td>1.63</td>\n      <td>1.72</td>\n    </tr>\n    <tr>\n      <th>160</th>\n      <td>10.87</td>\n      <td>0.89</td>\n      <td>0.86</td>\n    </tr>\n    <tr>\n      <th>640</th>\n      <td>10.89</td>\n      <td>0.42</td>\n      <td>0.43</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. Cada linha da matriz é uma amostra de tamanho `n`, sorteada com reposição.\n2. Desvio-padrão dentro de cada amostra, depois a média entre as amostras.\n3. Desvio-padrão das 2.000 médias amostrais: o erro-padrão observado.\n\nO desvio-padrão dos dados fica estável em torno de 11 atendimentos, qualquer que seja $n$. O erro-padrão cai pela metade cada vez que $n$ quadruplica, exatamente como prevê $s/\\sqrt{n}$. O erro-padrão diz o quanto a estimativa mudaria se a coleta fosse repetida com outra amostra do mesmo tamanho.\n\n## 5.3 A estatística *t*\n\nCom a régua definida, a pergunta se torna: **quantos erros-padrão cabem entre 0 e $\\Delta_{obs}$?**\n\n::: {#b4111d31 .cell execution_count=20}\n``` {.python .cell-code}\n# Efeito observado do câmbio, medido em erros-padrão\nround(delta_obs / se_null, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=54}\n```\nnp.float64(3.34)\n```\n:::\n:::\n\n\nCabem cerca de 3,3 erros-padrão. Sob o acaso, a diferença de médias quase nunca ultrapassa 2 erros-padrão. Essa contagem é a **estatística *t***:\n\n$$\nt = \\frac{\\bar{x}_A - \\bar{x}_B}{SE}\n$$\n\nA fórmula da seção 5.1 usou um único desvio-padrão para os dois grupos. A versão de **Welch** estima a variância de cada grupo separadamente e não exige que sejam iguais:\n\n$$\nSE = \\sqrt{\\frac{s_A^2}{n_A} + \\frac{s_B^2}{n_B}}\n$$\n\nAqui, $s_A^2$ e $s_B^2$ são as variâncias amostrais e $n_A$ e $n_B$, os tamanhos dos grupos.\n\n::: {#bdd57e9b .cell execution_count=21}\n``` {.python .cell-code}\n# Estatística t de Welch calculada pela fórmula\nse_welch = np.sqrt(manual.var() / n_manual + automatic.var() / n_automatic)\n\nround(se_welch, 2), round(delta_obs / se_welch, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=55}\n```\n(np.float64(1.92), np.float64(3.77))\n```\n:::\n:::\n\n\nO teste *t* converte o número de erros-padrão em uma probabilidade, usando a distribuição *t* com um número de graus de liberdade calculado a partir dos dados. Na prática, `stats.ttest_ind` faz todo o cálculo:\n\n::: {#72e75431 .cell execution_count=22}\n``` {.python .cell-code}\n# Teste t de Welch no mtcars\nstats.ttest_ind(manual, automatic, equal_var=False)  # <1>\n```\n\n::: {.cell-output .cell-output-display execution_count=56}\n```\nTtestResult(statistic=np.float64(3.767123145144923), pvalue=np.float64(0.0013736383330710345), df=np.float64(18.332251638400464))\n```\n:::\n:::\n\n\n1. `equal_var=False` seleciona a versão de Welch. Com `True`, o SciPy usa a versão clássica, que supõe variâncias iguais.\n\nE no pronto-socorro:\n\n::: {#e0825e49 .cell execution_count=23}\n``` {.python .cell-code}\n# Teste t de Welch na lua cheia\nstats.ttest_ind(\n    er_visits.loc[er_visits.full_moon, \"visits\"],\n    er_visits.loc[~er_visits.full_moon, \"visits\"],\n    equal_var=False,\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=57}\n```\nTtestResult(statistic=np.float64(1.4048153658505091), pvalue=np.float64(0.1853402601391711), df=np.float64(12.043510826046889))\n```\n:::\n:::\n\n\nAs conclusões coincidem com as da permutação. No `mtcars`, $p < 0{,}05$ e rejeitamos $H_0$. Na lua cheia, $p > 0{,}05$ e não rejeitamos.\n\n::: {.callout-note collapse=\"true\"}\n## Por que \"Student\"?\n\nWilliam S. Gosset era químico da cervejaria Guinness e precisava tirar conclusões de amostras pequenas de cevada. A cervejaria não permitia que seus funcionários publicassem com o próprio nome, e Gosset publicou o teste em 1908 sob o pseudônimo \"Student\".\n:::\n\n## 5.4 Premissas e limitações do teste *t*\n\n| O que ele pressupõe | Onde ele tropeça |\n|---|---|\n| Observações independentes | Amostras pequenas e muito assimétricas |\n| Médias aproximadamente normais (teorema central do limite, com *n* moderado ou grande) | Valores atípicos: média e variância são sensíveis |\n| Variável em escala contínua | Dados pareados ou temporais exigem outra versão |\n| Na versão de Welch, as variâncias podem ser diferentes | Compara médias, não medianas nem formas |\n\n## 5.5 Um único valor atípico muda a história\n\nNa Aula 5, vimos que média e desvio-padrão são sensíveis a valores extremos. O teste *t* depende das duas medidas e herda essa fragilidade. Para ver o efeito, acrescentamos um carro automático cujo consumo foi digitado como 60 mpg, um erro de registro plausível.\n\n::: {#6f63cf93 .cell execution_count=24}\n``` {.python .cell-code}\n# Automáticos com um consumo digitado como 60 mpg\nautomatic_typo = pd.concat(\n    [automatic, pd.Series([60.])],\n    ignore_index=True,\n)\n```\n:::\n\n\n::: {#99ebcdeb .cell execution_count=25}\n``` {.python .cell-code}\n# Diferenças, dispersão e teste t, sem e com o valor digitado errado\ndef compare(group_a, group_b):\n    test = stats.ttest_ind(group_a, group_b, equal_var=False)\n    return {\n        \"dif_medias\": group_a.mean() - group_b.mean(),\n        \"dif_medianas\": group_a.median() - group_b.median(),\n        \"dp_automaticos\": group_b.std(),\n        \"t\": test.statistic,\n        \"p\": test.pvalue,\n    }\n\n(\n    pd.DataFrame(\n        {\n            \"mtcars original\": compare(manual, automatic),\n            \"+1 automático com 60 mpg\": compare(manual, automatic_typo),\n        }\n    )\n    .T\n    .round(4)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=59}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dif_medias</th>\n      <th>dif_medianas</th>\n      <th>dp_automaticos</th>\n      <th>t</th>\n      <th>p</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>mtcars original</th>\n      <td>7.2449</td>\n      <td>5.50</td>\n      <td>3.8340</td>\n      <td>3.7671</td>\n      <td>0.0014</td>\n    </tr>\n    <tr>\n      <th>+1 automático com 60 mpg</th>\n      <td>5.1023</td>\n      <td>5.25</td>\n      <td>10.2831</td>\n      <td>1.7805</td>\n      <td>0.0848</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nUm único erro de digitação reduz a diferença de médias e quase triplica o desvio-padrão dos automáticos. O erro-padrão aumenta, *t* cai pela metade, e o teste **deixa de detectar** a diferença ao nível de 5%. A diferença de medianas quase não se altera.\n\n::: {.callout-important}\nDiagnostique com boxplots **antes** de testar. Diante de valores atípicos, considere corrigir valores sentinela ou erros de registro, aplicar uma transformação como $\\log(x)$, vista na Aula 6, ou usar uma permutação sobre a diferença de medianas.\n:::\n\n## 5.6 Permutação e teste *t*\n\n| Dimensão | Permutação (não paramétrico) | Teste *t* (paramétrico) |\n|---|---|---|\n| Premissas | Livre de distribuição. Exige apenas intercambialidade sob $H_0$ | Médias aproximadamente normais. Escala contínua |\n| Custo computacional | Milhares de reamostragens | Irrisório: fórmula fechada |\n| Tamanho dos dados | Bom para amostras pequenas e dados assimétricos | Adequado para volumes moderados e grandes |\n| Interpretação | Frequência empírica do reordenamento aleatório | Posição de *t* em uma distribuição teórica |\n| Flexibilidade | Qualquer estatística: média, mediana, razão | Diferença de médias |\n\n::: {#1fa76579 .cell execution_count=26}\n``` {.python .cell-code}\n# p-valores dos dois métodos nos dois exemplos\n(\n    pd.DataFrame(\n        {\n            \"permutação\": [mpg_p, moon_p],\n            \"teste t (Welch)\": [\n                stats.ttest_ind(manual, automatic, equal_var=False).pvalue,\n                stats.ttest_ind(\n                    moon_values[moon_labels],\n                    moon_values[~moon_labels],\n                    equal_var=False,\n                ).pvalue,\n            ],\n        },\n        index=[\"mtcars\", \"Lua cheia\"],\n    )\n    .round(4)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=60}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>permutação</th>\n      <th>teste t (Welch)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>mtcars</th>\n      <td>0.0001</td>\n      <td>0.0014</td>\n    </tr>\n    <tr>\n      <th>Lua cheia</th>\n      <td>0.2300</td>\n      <td>0.1853</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nOs valores não são idênticos, porque os dois métodos constroem a distribuição nula de formas diferentes. As decisões, porém, coincidem nos dois exemplos.\n\n# 6. Armadilhas da decisão\n\n## 6.1 Dois tipos de erro\n\nQualquer decisão baseada em dados amostrais pode errar. Como nunca sabemos se $H_0$ é verdadeira, há quatro combinações possíveis:\n\n| | $H_0$ verdadeira | $H_0$ falsa |\n|---|---|---|\n| **Rejeitar $H_0$** | Erro do tipo I ($\\alpha$): falso positivo, \"descobrir\" um efeito que não existe | Decisão correta: poder estatístico ($1 - \\beta$) |\n| **Não rejeitar $H_0$** | Decisão correta: confiança ($1 - \\alpha$) | Erro do tipo II ($\\beta$): falso negativo, não detectar um efeito real |\n\nO nível de significância $\\alpha$ é exatamente a taxa de falsos positivos que aceitamos. Podemos verificar isso por simulação. Geramos 5.000 anos de pronto-socorro **sem** efeito da lua e contamos em quantos o teste rejeita $H_0$.\n\n::: {#5f16d975 .cell execution_count=27}\n``` {.python .cell-code}\n# Taxa de rejeição em 5.000 anos simulados sem efeito da lua\nrng = np.random.default_rng(1)\n\ndef rejection_rate(effect, n_moon=12, n_other=353, n_years=5_000, alpha=.05):\n    moon = rng.poisson(120 + effect, size=(n_years, n_moon))  # <1>\n    other = rng.poisson(120, size=(n_years, n_other))\n    p_values = stats.ttest_ind(moon, other, axis=1, equal_var=False).pvalue  # <2>\n    return np.mean(p_values <= alpha)\n\nrejection_rate(effect=0)\n```\n\n::: {.cell-output .cell-output-display execution_count=61}\n```\nnp.float64(0.0506)\n```\n:::\n:::\n\n\n1. Cada linha é um ano simulado. `effect` acrescenta atendimentos aos dias de lua cheia.\n2. Com `axis=1`, o SciPy aplica o teste a cada linha de uma vez e devolve 5.000 *p*-valores.\n\nCerca de 5% dos anos levam a uma rejeição, embora a lua não tenha efeito algum. Esse é o custo de usar $\\alpha = 0{,}05$.\n\nAgora, suponha que exista um efeito real e pequeno, de 5 atendimentos a mais por noite de lua cheia. Com quantos dias de lua cheia o teste consegue detectá-lo?\n\n::: {#11216eae .cell execution_count=28}\n``` {.python .cell-code}\n# Poder do teste para um efeito de +5 atendimentos, por número de dias de lua cheia\n(\n    pd.Series(\n        {\n            n_moon: rejection_rate(effect=5, n_moon=n_moon)\n            for n_moon in [12, 24, 60, 120]\n        },\n        name=\"poder\",\n    )\n    .rename_axis(\"dias de lua cheia\")\n    .to_frame()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>poder</th>\n    </tr>\n    <tr>\n      <th>dias de lua cheia</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>12</th>\n      <td>0.2910</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>0.5320</td>\n    </tr>\n    <tr>\n      <th>60</th>\n      <td>0.8856</td>\n    </tr>\n    <tr>\n      <th>120</th>\n      <td>0.9874</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nCom 12 noites de lua cheia, um ano de dados, o teste detecta o efeito em menos de um terço das vezes. Na maior parte dos anos, cometeria um erro do tipo II. Com mais dados, o poder aumenta.\n\nReduzir $\\alpha$ diminui os falsos positivos, mas aumenta $\\beta$. **Aumentar $n$ reduz os dois.**\n\n### 6.1.1 Muitos testes\n\nCom $\\alpha = 0{,}05$, espera-se cerca de um falso positivo a cada 20 testes sem efeito. Imagine 20 pronto-socorros em que a lua não tem efeito:\n\n::: {#0fb7f1cc .cell execution_count=29}\n``` {.python .cell-code}\n# p-valores da lua cheia em 20 pronto-socorros sem efeito\nrng = np.random.default_rng(7)\n\nhospital_p = stats.ttest_ind(\n    rng.poisson(120, size=(20, 12)),\n    rng.poisson(120, size=(20, 353)),\n    axis=1,\n    equal_var=False,\n).pvalue\n\nfig, ax = plt.subplots(figsize=(9, 3.5))\n\nax.bar(\n    np.arange(1, 21),\n    hospital_p,\n    color=np.where(hospital_p <= .05, \"#DD8452\", \"#A1C9F4\"),\n)\nax.axhline(.05, color=\"#1F4E79\", linestyle=\"--\")\nax.set(\n    title=\"20 pronto-socorros, nenhum efeito da lua\",\n    xlabel=\"Pronto-socorro\",\n    ylabel=\"p-valor\",\n    xticks=np.arange(1, 21),\n)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-30-output-1.png){width=849 height=320}\n:::\n:::\n\n\nA probabilidade de pelo menos um dos 20 testes rejeitar $H_0$ por acaso é $1 - 0{,}95^{20} \\approx 64\\%$. Quem testa muitas hipóteses e relata apenas as significantes repete a falácia do atirador do Texas.\n\n## 6.2 Significância estatística não é relevância prática\n\nO *p*-valor depende do tamanho da amostra. O erro-padrão encolhe com $\\sqrt{n}$, e um efeito minúsculo acaba se tornando \"significante\" quando $n$ é grande o bastante. A tabela mostra o *p*-valor de um mesmo efeito minúsculo, de 0,02 desvio-padrão, para tamanhos de amostra crescentes:\n\n::: {#f968433d .cell execution_count=30}\n``` {.python .cell-code}\n# p-valor de um efeito fixo de 0,02 desvio-padrão, por tamanho de grupo\ndef expected_p(d, n):\n    t = d * np.sqrt(n / 2)  # <1>\n    return 2 * stats.t.sf(t, df=2 * n - 2)  # <2>\n\n(\n    pd.Series(\n        {n: expected_p(.02, n) for n in [100, 1_000, 10_000, 100_000, 1_000_000]},\n        name=\"p\",\n    )\n    .rename_axis(\"n por grupo\")\n    .to_frame()\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=64}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>p</th>\n    </tr>\n    <tr>\n      <th>n por grupo</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>100</th>\n      <td>8.876809e-01</td>\n    </tr>\n    <tr>\n      <th>1000</th>\n      <td>6.547693e-01</td>\n    </tr>\n    <tr>\n      <th>10000</th>\n      <td>1.573148e-01</td>\n    </tr>\n    <tr>\n      <th>100000</th>\n      <td>7.748470e-06</td>\n    </tr>\n    <tr>\n      <th>1000000</th>\n      <td>2.099060e-45</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. Com dois grupos de tamanho $n$ e desvio-padrão comum, $t = d\\sqrt{n/2}$.\n2. `stats.t.sf` é a área da cauda direita da distribuição *t*. Multiplicamos por 2 porque o teste é bilateral.\n\nCom um milhão de observações por grupo, uma diferença irrelevante produz um *p*-valor astronomicamente pequeno. Em grandes bases de dados, quase tudo se torna \"significante\". Por isso, além do *p*-valor, reporte o **tamanho do efeito**. Uma medida comum é o *d* de Cohen, a diferença de médias expressa em desvios-padrão:\n\n$$\nd = \\frac{\\bar{x}_A - \\bar{x}_B}{s_{\\text{combinado}}}\n$$\n\n::: {#2ac55bd2 .cell execution_count=31}\n``` {.python .cell-code}\n# d de Cohen para o câmbio\npooled_sd = np.sqrt(\n    ((n_manual - 1) * manual.var() + (n_automatic - 1) * automatic.var())\n    / (n_manual + n_automatic - 2)  # <1>\n)\n\nround(delta_obs / pooled_sd, 2)\n```\n\n::: {.cell-output .cell-output-display execution_count=65}\n```\nnp.float64(1.48)\n```\n:::\n:::\n\n\n1. O desvio-padrão combinado é uma média das variâncias dos dois grupos, ponderada pelos graus de liberdade.\n\nComo referência, valores de *d* em torno de 0,2, 0,5 e 0,8 costumam ser descritos como efeitos pequenos, médios e grandes. No `mtcars`, $d \\approx 1{,}48$, um efeito grande. A pergunta final, porém, é se a diferença é **acionável**: grande o bastante e bem compreendida o bastante para orientar uma decisão.\n\n## 6.3 Confundidor: quem está por trás da diferença?\n\nO teste da seção 4.5 mostrou que os manuais gastam menos combustível e que essa diferença dificilmente é acaso. Isso significa que trocar o câmbio de um carro o tornaria mais econômico?\n\nO contexto dos dados sugere cautela. A *Motor Trend* mediu modelos de 1973 e 1974, logo após a crise do petróleo de 1973. Os manuais da amostra são, em sua maioria, compactos e esportivos importados, como Honda Civic, Fiat 128 e Toyota Corolla. Os automáticos são, em grande parte, sedãs grandes e pesados, como Cadillac, Lincoln e Chrysler.\n\n::: {#d72cd30d .cell execution_count=32}\n``` {.python .cell-code}\n# Peso médio por câmbio, em kg\n(\n    mtcars\n    .groupby(\"transmission\")\n    .weight_kg\n    .mean()\n    .round(0)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=66}\n```\ntransmission\nAutomático    1710.0\nManual        1094.0\nName: weight_kg, dtype: float64\n```\n:::\n:::\n\n\n::: {#2a5a3e18 .cell execution_count=33}\n``` {.python .cell-code}\n# Consumo versus peso, por câmbio\nfig, ax = plt.subplots(figsize=(7, 4.5))\n\nsns.scatterplot(\n    data=mtcars,\n    x=\"weight_kg\",\n    y=\"mpg\",\n    hue=\"transmission\",\n    palette={\"Manual\": \"#1F4E79\", \"Automático\": \"#A1C9F4\"},\n    edgecolor=\"#333333\",\n    s=70,\n    ax=ax,\n)\nax.set(\n    title=\"Carros leves consomem menos, e os manuais são mais leves\",\n    xlabel=\"Peso do carro (kg)\",\n    ylabel=\"Consumo (mpg)\",\n)\nax.legend(title=\"\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](07-inferencia-estatistica_files/figure-html/cell-34-output-1.png){width=656 height=416}\n:::\n:::\n\n\nO peso influencia as duas variáveis. Carros leves consomem menos, e os carros leves da amostra são, em sua maioria, manuais. Uma variável que afeta tanto o grupo quanto o desfecho, criando uma associação sem relação causal direta, é chamada de **confundidor**.\n\n\n\n\n\n\n```{mermaid}\nflowchart TB\n    W([Peso]) --> A([Câmbio])\n    W --> M([Consumo])\n    A -. \"?\" .-> M\n```\n\n\n\n\n\n\nPara separar os dois efeitos, precisamos comparar carros **de mesmo peso**. Uma regressão linear faz essa comparação. O modelo `mpg ~ am` reproduz a diferença de médias, e o modelo `mpg ~ am + wt` estima o efeito do câmbio mantendo o peso constante.\n\n::: {#575a611d .cell execution_count=34}\n``` {.python .cell-code}\n# Efeito do câmbio sem e com controle pelo peso\nmodels = {\n    \"mpg ~ am\": smf.ols(\"mpg ~ am\", data=mtcars).fit(),  # <1>\n    \"mpg ~ am + wt\": smf.ols(\"mpg ~ am + wt\", data=mtcars).fit(),\n}\n\n(\n    pd.DataFrame(\n        {\n            name: {\n                \"efeito_manual\": model.params[\"am\"],  # <2>\n                \"p\": model.pvalues[\"am\"],\n                \"R2\": model.rsquared,  # <3>\n            }\n            for name, model in models.items()\n        }\n    )\n    .T\n    .round(4)\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=68}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>efeito_manual</th>\n      <th>p</th>\n      <th>R2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>mpg ~ am</th>\n      <td>7.2449</td>\n      <td>0.0003</td>\n      <td>0.3598</td>\n    </tr>\n    <tr>\n      <th>mpg ~ am + wt</th>\n      <td>-0.0236</td>\n      <td>0.9879</td>\n      <td>0.7528</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. `smf.ols` ajusta uma regressão por mínimos quadrados a partir de uma fórmula. À esquerda do `~` fica a variável resposta, e à direita, as explicativas.\n2. O coeficiente de `am` estima a diferença de consumo entre manuais e automáticos.\n3. O $R^2$ indica a fração da variação do consumo explicada pelo modelo.\n\nSem controlar pelo peso, o coeficiente de `am` é exatamente $\\Delta_{obs} = 7{,}24$ mpg. Ao controlar pelo peso, o efeito do câmbio **desaparece**: fica próximo de zero, com $p \\approx 0{,}99$. O $R^2$ dobra, e o peso explica a maior parte da variação do consumo. Cada 1.000 libras (cerca de 454 kg) a mais custam aproximadamente 5,4 mpg.\n\n::: {.callout-note collapse=\"true\"}\n## Regressão linear\n\nA regressão linear será estudada em detalhe mais adiante no curso. Aqui, basta a intuição: o modelo `mpg ~ am + wt` pergunta quanto o consumo difere entre manuais e automáticos **entre carros de mesmo peso**. Se a diferença some quando o peso é fixado, era o peso, e não o câmbio, que separava os grupos.\n:::\n\n::: {.callout-important}\nUm *p*-valor pequeno mostra que a diferença dificilmente é acaso. Ele não mostra **o que** a causa.\n:::\n\n# 7. Guia rápido\n\nA sequência abaixo responde à pergunta norteadora da aula.\n\n| Passo | Ação | Ferramenta |\n|---|---|---|\n| 1. Medir | Calcular $\\Delta_{obs}$ e inspecionar os grupos | `groupby`, boxplot |\n| 2. Duvidar | Formular $H_0$: só há acaso | Hipóteses nula e alternativa |\n| 3. Simular | Construir a distribuição nula | Permutação ou distribuição *t* |\n| 4. Calcular | Obter o *p*-valor | `np.mean(np.abs(null) >= abs(obs))` ou `stats.ttest_ind` |\n| 5. Decidir | Comparar *p* com $\\alpha$, avaliar o tamanho do efeito e procurar confundidores | *d* de Cohen, contexto, regressão |\n\n## Síntese\n\n1. **Efeito observado.** $\\Delta_{obs}$ descreve a amostra. Sozinho, não prova um efeito populacional, porque a variabilidade amostral gera diferenças mesmo sem efeito real.\n2. **Hipótese nula.** $H_0$ formaliza o acaso. Sob ela, os rótulos dos grupos são intercambiáveis.\n3. **Distribuição nula.** A permutação, por simulação, e o teste *t*, por fórmula, constroem a distribuição da estatística sob $H_0$. O erro-padrão é a largura dessa distribuição.\n4. **Decisão.** $p \\leq \\alpha$ leva à rejeição de $H_0$. Tamanho do efeito, valores atípicos e confundidores decidem o que concluir.\n\nUm efeito é \"real\" quando seria improvável sob o acaso. E só importa se for grande e não for explicado por outra variável.\n\n## Glossário\n\n| Termo | Definição |\n|---|---|\n| $\\Delta_{obs}$ | Diferença entre as estatísticas, como as médias, dos grupos na amostra |\n| Erro-padrão (SE) | Variabilidade de uma estimativa entre amostras repetidas |\n| Hipótese nula ($H_0$) | Modelo cético: não há efeito, e a diferença é fruto do acaso |\n| Distribuição nula | Valores que a estatística assume quando $H_0$ é verdadeira |\n| *p*-valor | Probabilidade de um resultado tão ou mais extremo que o observado, supondo $H_0$ |\n| Significância ($\\alpha$) | Limiar fixado antes da análise. Risco aceito de falso positivo |\n| Poder ($1 - \\beta$) | Probabilidade de detectar um efeito que de fato existe |\n| Confundidor | Variável que afeta o grupo e o desfecho, criando associação sem causa |\n\n# Perguntas para consolidar\n\n## Pergunta 1: o que o *p*-valor da lua cheia diz, e o que não diz?\n\nNa lua cheia, $p \\approx 0{,}23$. Um colega conclui: \"há 23% de chance de a lua não ter efeito\". A frase está correta?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nNão. O *p*-valor é calculado **supondo** que $H_0$ seja verdadeira. Ele diz que, se a lua não tivesse efeito, cerca de 23% dos sorteios de 12 dias produziriam uma diferença pelo menos tão grande quanto a observada. Ele não atribui uma probabilidade à própria $H_0$.\n\nTambém não podemos concluir que a lua não tem efeito. Não rejeitar $H_0$ significa apenas que os dados são compatíveis com o acaso. A seção 6.1 mostrou que, com 12 noites por ano, mesmo um efeito real de 5 atendimentos passaria despercebido na maior parte das vezes.\n:::\n\n## Pergunta 2: significativo quer dizer correto?\n\nNo `mtcars`, a permutação deu $p < 0{,}001$. Isso significa que trocar o câmbio de um carro faria ele economizar combustível?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nNão. O teste mostra que a diferença entre os grupos dificilmente é acaso, mas não identifica sua causa. Os manuais da amostra são mais leves, e o peso, sozinho, explica a diferença de consumo. Outras características também separam os grupos, como potência, número de cilindros e a origem dos modelos.\n\nPara atribuir um efeito causal, seria necessário comparar carros semelhantes em tudo, exceto no câmbio. Um experimento controlado faria isso por construção. Com dados observacionais, só podemos ajustar pelos confundidores que medimos.\n:::\n\n## Pergunta 3: quando permutação e teste *t* discordam?\n\nNos dois exemplos, os métodos levaram à mesma decisão. Em que situação você esperaria que eles discordassem, e em qual confiaria mais?\n\n::: {.callout-note collapse=\"true\"}\n## Como pensar sobre isso\n\nO teste *t* supõe que a diferença de médias seja aproximadamente normal. Isso é razoável com amostras moderadas ou grandes, pelo teorema central do limite. Com amostras pequenas e distribuições muito assimétricas ou com valores atípicos, a aproximação pode falhar, e o *p*-valor do teste *t* fica impreciso.\n\nA permutação exige apenas que os rótulos sejam intercambiáveis sob $H_0$. Ela continua válida nesses casos e ainda permite trocar a estatística, por exemplo pela diferença de medianas. Em contrapartida, ambos os métodos supõem observações independentes. Nenhum dos dois é adequado, sem adaptação, para dados pareados ou séries temporais.\n:::\n\n# Para casa\n\n1. Adapte `permutation_null` para usar a diferença de **medianas**. Aplique-a ao cenário com o automático de 60 mpg e compare o *p*-valor com o do teste *t* da seção 5.5.\n2. Repita a simulação de poder da seção 6.1 com um efeito de 10 atendimentos. Quantas noites de lua cheia são necessárias para atingir um poder de 80%?\n3. Na base de imóveis da Aula 6, compare o aluguel de imóveis mobiliados e não mobiliados. Calcule $\\Delta_{obs}$, o *p*-valor por permutação e pelo teste *t*, e o *d* de Cohen. Repita a análise com o $\\log$ do aluguel e discuta as diferenças.\n4. Ainda na base de imóveis, a diferença de aluguel entre mobiliados e não mobiliados poderia ser explicada por outra variável? Proponha um confundidor e verifique sua hipótese com um gráfico.\n5. Antes de considerar o notebook pronto, use Restart Kernel and Run All.\n\n## Referências\n\n1. Adhikari, A.; DeNero, J.; Wagner, D. *Computational and Inferential Thinking: The Foundations of Data Science*. 2. ed. UC Berkeley. [inferentialthinking.com](https://inferentialthinking.com)\n2. Bruce, P.; Bruce, A.; Gedeck, P. *Practical Statistics for Data Scientists*. 2. ed. O'Reilly, 2020.\n3. Student. The probable error of a mean. *Biometrika*, 6(1), 1-25, 1908.\n4. Welch, B. L. The generalization of \"Student's\" problem when several different population variances are involved. *Biometrika*, 34(1-2), 28-35, 1947.\n5. Wasserstein, R. L.; Lazar, N. A. The ASA statement on p-values: context, process, and purpose. *The American Statistician*, 70(2), 129-133, 2016.\n6. Fisher, R. A. *The Design of Experiments*. Edinburgh: Oliver & Boyd, 1935.\n7. Rotton, J.; Kelly, I. W. Much ado about the full moon: a meta-analysis of lunar-lunacy research. *Psychological Bulletin*, 97(2), 286-306, 1985.\n8. Henderson, H. V.; Velleman, P. F. Building multiple regression models interactively. *Biometrics*, 37(2), 391-411, 1981.\n\n> Pode-se dizer que todo experimento existe apenas para dar aos fatos a chance de refutar a hipótese nula. (R. A. Fisher, *The Design of Experiments*, 1935, tradução livre)\n\n",
    "supporting": [
      "07-inferencia-estatistica_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}