<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Aula 7 - Inferência Estatística – Ciência de Dados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-31c5116dce638bf40351868cd08965ef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ba99d7a9af36e81ac0abe239f9976969.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../aulas/01-ferramentas-ambiente-versionamento.html">Roteiros de aula</a></li><li class="breadcrumb-item"><a href="../aulas/07-inferencia-estatistica.html">7. Inferência Estatística</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Ciência de Dados</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ciência de Dados</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Roteiros de aula</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/01-ferramentas-ambiente-versionamento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Ferramentas, Ambiente e Versionamento</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/02-introducao-dados-tabulares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Introdução aos Dados Tabulares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/03-analise-vendas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Análise de Vendas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/04-analise-vendas-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Análise de Vendas em R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/05-estatistica-descritiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Estatística Descritiva</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/06-imputacao-normalizacao-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Imputação e Normalização de Dados</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/07-inferencia-estatistica.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">7. Inferência Estatística</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#motivação" id="toc-motivação" class="nav-link active" data-scroll-target="#motivação">Motivação</a></li>
  <li><a href="#objetivos-de-aprendizagem" id="toc-objetivos-de-aprendizagem" class="nav-link" data-scroll-target="#objetivos-de-aprendizagem">Objetivos de aprendizagem</a></li>
  <li><a href="#preparando-os-dados" id="toc-preparando-os-dados" class="nav-link" data-scroll-target="#preparando-os-dados">1. Preparando os dados</a></li>
  <li><a href="#a-diferença-observada" id="toc-a-diferença-observada" class="nav-link" data-scroll-target="#a-diferença-observada">2. A diferença observada</a></li>
  <li><a href="#o-problema-da-aleatoriedade" id="toc-o-problema-da-aleatoriedade" class="nav-link" data-scroll-target="#o-problema-da-aleatoriedade">3. O problema da aleatoriedade</a>
  <ul class="collapse">
  <li><a href="#um-pronto-socorro-simulado" id="toc-um-pronto-socorro-simulado" class="nav-link" data-scroll-target="#um-pronto-socorro-simulado">3.1 Um pronto-socorro simulado</a></li>
  </ul></li>
  <li><a href="#formalizando-o-acaso" id="toc-formalizando-o-acaso" class="nav-link" data-scroll-target="#formalizando-o-acaso">4. Formalizando o acaso</a>
  <ul class="collapse">
  <li><a href="#hipóteses-nula-e-alternativa" id="toc-hipóteses-nula-e-alternativa" class="nav-link" data-scroll-target="#hipóteses-nula-e-alternativa">4.1 Hipóteses nula e alternativa</a></li>
  <li><a href="#o-teste-de-permutação" id="toc-o-teste-de-permutação" class="nav-link" data-scroll-target="#o-teste-de-permutação">4.2 O teste de permutação</a></li>
  <li><a href="#o-p-valor" id="toc-o-p-valor" class="nav-link" data-scroll-target="#o-p-valor">4.3 O <em>p</em>-valor</a></li>
  <li><a href="#a-regra-de-decisão" id="toc-a-regra-de-decisão" class="nav-link" data-scroll-target="#a-regra-de-decisão">4.4 A regra de decisão</a></li>
  <li><a href="#permutação-no-mtcars" id="toc-permutação-no-mtcars" class="nav-link" data-scroll-target="#permutação-no-mtcars">4.5 Permutação no <code>mtcars</code></a></li>
  </ul></li>
  <li><a href="#o-atalho-paramétrico" id="toc-o-atalho-paramétrico" class="nav-link" data-scroll-target="#o-atalho-paramétrico">5. O atalho paramétrico</a>
  <ul class="collapse">
  <li><a href="#o-erro-padrão" id="toc-o-erro-padrão" class="nav-link" data-scroll-target="#o-erro-padrão">5.1 O erro-padrão</a></li>
  <li><a href="#desvio-padrão-e-erro-padrão" id="toc-desvio-padrão-e-erro-padrão" class="nav-link" data-scroll-target="#desvio-padrão-e-erro-padrão">5.2 Desvio-padrão e erro-padrão</a></li>
  <li><a href="#a-estatística-t" id="toc-a-estatística-t" class="nav-link" data-scroll-target="#a-estatística-t">5.3 A estatística <em>t</em></a></li>
  <li><a href="#premissas-e-limitações-do-teste-t" id="toc-premissas-e-limitações-do-teste-t" class="nav-link" data-scroll-target="#premissas-e-limitações-do-teste-t">5.4 Premissas e limitações do teste <em>t</em></a></li>
  <li><a href="#um-único-valor-atípico-muda-a-história" id="toc-um-único-valor-atípico-muda-a-história" class="nav-link" data-scroll-target="#um-único-valor-atípico-muda-a-história">5.5 Um único valor atípico muda a história</a></li>
  <li><a href="#permutação-e-teste-t" id="toc-permutação-e-teste-t" class="nav-link" data-scroll-target="#permutação-e-teste-t">5.6 Permutação e teste <em>t</em></a></li>
  </ul></li>
  <li><a href="#armadilhas-da-decisão" id="toc-armadilhas-da-decisão" class="nav-link" data-scroll-target="#armadilhas-da-decisão">6. Armadilhas da decisão</a>
  <ul class="collapse">
  <li><a href="#dois-tipos-de-erro" id="toc-dois-tipos-de-erro" class="nav-link" data-scroll-target="#dois-tipos-de-erro">6.1 Dois tipos de erro</a></li>
  <li><a href="#muitos-testes" id="toc-muitos-testes" class="nav-link" data-scroll-target="#muitos-testes">6.2 Muitos testes</a></li>
  <li><a href="#significância-estatística-não-é-relevância-prática" id="toc-significância-estatística-não-é-relevância-prática" class="nav-link" data-scroll-target="#significância-estatística-não-é-relevância-prática">6.3 Significância estatística não é relevância prática</a></li>
  </ul></li>
  <li><a href="#guia-rápido" id="toc-guia-rápido" class="nav-link" data-scroll-target="#guia-rápido">7. Guia rápido</a>
  <ul class="collapse">
  <li><a href="#síntese" id="toc-síntese" class="nav-link" data-scroll-target="#síntese">Síntese</a></li>
  <li><a href="#glossário" id="toc-glossário" class="nav-link" data-scroll-target="#glossário">Glossário</a></li>
  </ul></li>
  <li><a href="#perguntas-para-consolidar" id="toc-perguntas-para-consolidar" class="nav-link" data-scroll-target="#perguntas-para-consolidar">Perguntas para consolidar</a>
  <ul class="collapse">
  <li><a href="#pergunta-1-o-que-o-p-valor-da-lua-cheia-diz-e-o-que-não-diz" id="toc-pergunta-1-o-que-o-p-valor-da-lua-cheia-diz-e-o-que-não-diz" class="nav-link" data-scroll-target="#pergunta-1-o-que-o-p-valor-da-lua-cheia-diz-e-o-que-não-diz">Pergunta 1: o que o <em>p</em>-valor da lua cheia diz, e o que não diz?</a></li>
  <li><a href="#pergunta-2-significativo-quer-dizer-correto" id="toc-pergunta-2-significativo-quer-dizer-correto" class="nav-link" data-scroll-target="#pergunta-2-significativo-quer-dizer-correto">Pergunta 2: significativo quer dizer correto?</a></li>
  <li><a href="#pergunta-3-quando-permutação-e-teste-t-discordam" id="toc-pergunta-3-quando-permutação-e-teste-t-discordam" class="nav-link" data-scroll-target="#pergunta-3-quando-permutação-e-teste-t-discordam">Pergunta 3: quando permutação e teste <em>t</em> discordam?</a></li>
  </ul></li>
  <li><a href="#para-casa" id="toc-para-casa" class="nav-link" data-scroll-target="#para-casa">Para casa</a>
  <ul class="collapse">
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/oandrefonseca/data-science/blob/main/aulas/07-inferencia-estatistica.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/oandrefonseca/data-science/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="07-inferencia-estatistica.ipynb" download="07-inferencia-estatistica.ipynb"><i class="bi bi-journal-code"></i>Jupyter</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../aulas/01-ferramentas-ambiente-versionamento.html">Roteiros de aula</a></li><li class="breadcrumb-item"><a href="../aulas/07-inferencia-estatistica.html">7. Inferência Estatística</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Aula 7 - Inferência Estatística</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">6 de outubro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="motivação" class="level2">
<h2 class="anchored" data-anchor-id="motivação">Motivação</h2>
<p>Na Aula 5, a estatística descritiva resumiu os dados observados sem generalizá-los. Na Aula 6, o diagnóstico orientou o tratamento da base. Em ambas, as conclusões ficaram restritas à amostra disponível. Nesta aula, damos o passo seguinte. Ao comparar dois grupos, encontramos uma diferença. A pergunta passa a ser se essa diferença diz algo sobre o processo que gerou os dados ou se é apenas um resultado da variabilidade aleatória da amostra.</p>
<p>Considere um exemplo clássico. A revista <em>Motor Trend</em> mediu, em 1974, o consumo de 32 modelos de carro. Os carros com câmbio manual percorrem, em média, cerca de 7 milhas a mais por galão do que os automáticos. A diferença parece grande, mas a amostra é pequena. Se a revista tivesse escolhido outros 32 carros, a diferença seria outra. Talvez menor, talvez nula, talvez invertida.</p>
<p>A estatística inferencial oferece um procedimento para responder a essa pergunta. Primeiro, supomos que <strong>não existe</strong> efeito algum. Em seguida, medimos quão raro seria observar uma diferença do tamanho da encontrada se essa suposição fosse verdadeira. Se a diferença for muito rara sob o acaso, temos evidência contra a suposição inicial. Estudaremos duas formas de construir essa referência: uma por simulação, o <strong>teste de permutação</strong>, e outra por fórmula, o <strong>teste <em>t</em> de Student</strong>.</p>
<blockquote class="blockquote">
<p><strong>Diferença real ou acaso?</strong></p>
</blockquote>
</section>
<section id="objetivos-de-aprendizagem" class="level2">
<h2 class="anchored" data-anchor-id="objetivos-de-aprendizagem">Objetivos de aprendizagem</h2>
<p>Ao final deste roteiro, você será capaz de:</p>
<ol type="1">
<li>Medir o efeito observado (<span class="math inline">\(\Delta_{obs}\)</span>) entre dois grupos e comparar sua dispersão com boxplots.</li>
<li>Formular a hipótese nula (<span class="math inline">\(H_0\)</span>) e a hipótese alternativa (<span class="math inline">\(H_1\)</span>) para uma comparação entre grupos.</li>
<li>Aplicar o teste de permutação e construir a distribuição empírica do acaso.</li>
<li>Aplicar o teste <em>t</em> de Student, reconhecendo suas premissas, seus limites e sua sensibilidade a valores atípicos.</li>
<li>Interpretar o <em>p</em>-valor, o nível de significância (<span class="math inline">\(\alpha\)</span>) e os erros dos tipos I e II, distinguindo significância estatística de relevância prática.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como usar este roteiro
</div>
</div>
<div class="callout-body-container callout-body">
<p>O roteiro usa a base <code>mtcars.csv</code>, salva em <code>mtcars/data/</code>, e um conjunto simulado de atendimentos em um pronto-socorro, gerado no próprio roteiro.</p>
<p>Não é necessário instalar novas bibliotecas. Os testes usam o módulo <code>stats</code> do SciPy, já empregado nas aulas anteriores.</p>
<p>Ao final, três perguntas ajudam a consolidar a interpretação dos testes.</p>
</div>
</div>
</section>
<section id="preparando-os-dados" class="level1">
<h1>1. Preparando os dados</h1>
<p>Começamos importando as bibliotecas usadas na simulação, nos testes e na visualização.</p>
<div id="fafcd4c6" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importa as bibliotecas e define o tema dos gráficos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>, palette<span class="op">=</span><span class="st">"colorblind"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A base <code>mtcars</code> reúne 32 modelos de carro vendidos nos Estados Unidos em 1973 e 1974. Usaremos duas de suas onze colunas:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coluna</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mpg</code></td>
<td>Consumo, em milhas por galão. Quanto maior, mais econômico</td>
</tr>
<tr class="even">
<td><code>am</code></td>
<td>Câmbio: 0 = automático, 1 = manual</td>
</tr>
</tbody>
</table>
<p>Ao carregar a base, criamos uma coluna auxiliar com um rótulo legível para o câmbio.</p>
<div id="ea94ec8c" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega a base e cria o rótulo do câmbio</span></span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="op">=</span> (</span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>    pd.read_csv(<span class="st">"mtcars/data/mtcars.csv"</span>)</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-2-5" class="code-annotation-target"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a>        transmission<span class="op">=</span><span class="kw">lambda</span> df: np.where(</span>
<span id="annotated-cell-2-6"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a>            df[<span class="st">"am"</span>] <span class="op">==</span> <span class="dv">1</span>,</span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Manual"</span>,</span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Automático"</span>,</span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a>mtcars.head()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="5" data-code-annotation="1"><code>np.where</code> escolhe o rótulo linha a linha, como na Aula 6.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="62">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">model</th>
<th data-quarto-table-cell-role="th">mpg</th>
<th data-quarto-table-cell-role="th">cyl</th>
<th data-quarto-table-cell-role="th">disp</th>
<th data-quarto-table-cell-role="th">hp</th>
<th data-quarto-table-cell-role="th">drat</th>
<th data-quarto-table-cell-role="th">wt</th>
<th data-quarto-table-cell-role="th">qsec</th>
<th data-quarto-table-cell-role="th">vs</th>
<th data-quarto-table-cell-role="th">am</th>
<th data-quarto-table-cell-role="th">gear</th>
<th data-quarto-table-cell-role="th">carb</th>
<th data-quarto-table-cell-role="th">transmission</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Mazda RX4</td>
<td>21.0</td>
<td>6</td>
<td>160.0</td>
<td>110</td>
<td>3.90</td>
<td>2.620</td>
<td>16.46</td>
<td>0</td>
<td>1</td>
<td>4</td>
<td>4</td>
<td>Manual</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Mazda RX4 Wag</td>
<td>21.0</td>
<td>6</td>
<td>160.0</td>
<td>110</td>
<td>3.90</td>
<td>2.875</td>
<td>17.02</td>
<td>0</td>
<td>1</td>
<td>4</td>
<td>4</td>
<td>Manual</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Datsun 710</td>
<td>22.8</td>
<td>4</td>
<td>108.0</td>
<td>93</td>
<td>3.85</td>
<td>2.320</td>
<td>18.61</td>
<td>1</td>
<td>1</td>
<td>4</td>
<td>1</td>
<td>Manual</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Hornet 4 Drive</td>
<td>21.4</td>
<td>6</td>
<td>258.0</td>
<td>110</td>
<td>3.08</td>
<td>3.215</td>
<td>19.44</td>
<td>1</td>
<td>0</td>
<td>3</td>
<td>1</td>
<td>Automático</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Hornet Sportabout</td>
<td>18.7</td>
<td>8</td>
<td>360.0</td>
<td>175</td>
<td>3.15</td>
<td>3.440</td>
<td>17.02</td>
<td>0</td>
<td>0</td>
<td>3</td>
<td>2</td>
<td>Automático</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="a-diferença-observada" class="level1">
<h1>2. A diferença observada</h1>
<p>O primeiro passo de qualquer comparação é descritivo. Calculamos uma estatística em cada grupo e medimos a distância entre elas. Chamamos essa distância de <strong>efeito observado</strong>:</p>
<p><span class="math display">\[
\Delta_{obs} = \bar{x}_A - \bar{x}_B
\]</span></p>
<p>Aqui, <span class="math inline">\(\bar{x}_A\)</span> e <span class="math inline">\(\bar{x}_B\)</span> são as médias amostrais dos grupos A e B. O sinal indica o sentido da diferença. Neste roteiro, o grupo A é sempre aquele em que suspeitamos de um efeito: os carros manuais e, mais adiante, os dias de lua cheia. Quando há assimetria ou valores atípicos, a diferença de medianas é uma alternativa mais robusta, pelos mesmos motivos discutidos na Aula 5.</p>
<p>Antes de calcular a diferença, resumimos cada grupo:</p>
<div id="7a28e1c0" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tamanho, média, mediana e desvio-padrão do consumo por câmbio</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    mtcars</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"transmission"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    .mpg</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    .agg([<span class="st">"size"</span>, <span class="st">"mean"</span>, <span class="st">"median"</span>, <span class="st">"std"</span>])</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="63">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">std</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">transmission</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Automático</td>
<td>19</td>
<td>17.15</td>
<td>17.3</td>
<td>3.83</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Manual</td>
<td>13</td>
<td>24.39</td>
<td>22.8</td>
<td>6.17</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>A tabela traz três informações importantes:</p>
<ul>
<li><strong>Os grupos têm tamanhos diferentes.</strong> São 19 automáticos e 13 manuais. Nenhum dos dois é grande, e cada carro tem peso considerável na média do seu grupo.</li>
<li><strong>Média e mediana contam histórias um pouco diferentes.</strong> Nos automáticos, as duas quase coincidem (17,15 e 17,3). Nos manuais, a média (24,39) fica acima da mediana (22,8), sinal de que alguns carros muito econômicos puxam a média para cima.</li>
<li><strong>Os manuais variam mais.</strong> O desvio-padrão dos manuais (6,17) é cerca de 60% maior que o dos automáticos (3,83).</li>
</ul>
<p>A diferença de médias resume a comparação em um único número:</p>
<div id="6fce56af" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Efeito observado: diferença das médias de consumo</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>manual <span class="op">=</span> mtcars.loc[mtcars.am <span class="op">==</span> <span class="dv">1</span>, <span class="st">"mpg"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>automatic <span class="op">=</span> mtcars.loc[mtcars.am <span class="op">==</span> <span class="dv">0</span>, <span class="st">"mpg"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>delta_obs <span class="op">=</span> manual.mean() <span class="op">-</span> automatic.mean()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(delta_obs, <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="64">
<pre><code>np.float64(7.24)</code></pre>
</div>
</div>
<p>Os carros manuais fazem, em média, 7,24 milhas por galão a mais. A diferença de medianas é menor, 5,5 mpg, coerente com a assimetria observada nos manuais. Nas duas medidas, porém, os manuais aparecem como mais econômicos.</p>
<p>O boxplot mostra a diferença e a dispersão de cada grupo. Cada ponto é um carro, e as linhas tracejadas marcam as médias. Como faremos o mesmo gráfico para o pronto-socorro, o boxplot com as observações sobrepostas fica em uma função:</p>
<div id="c324cd79" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="annotated-cell-5"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-5-1"><a href="#annotated-cell-5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot com as observações sobrepostas e as médias de cada grupo</span></span>
<span id="annotated-cell-5-2"><a href="#annotated-cell-5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_groups(data, x, y, order, ax, alpha<span class="op">=</span><span class="dv">1</span>, jitter<span class="op">=</span><span class="fl">.15</span>):</span>
<span id="annotated-cell-5-3"><a href="#annotated-cell-5-3" aria-hidden="true" tabindex="-1"></a>    sns.boxplot(</span>
<span id="annotated-cell-5-4"><a href="#annotated-cell-5-4" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>data, x<span class="op">=</span>x, y<span class="op">=</span>y, order<span class="op">=</span>order, ax<span class="op">=</span>ax,</span>
<span id="annotated-cell-5-5"><a href="#annotated-cell-5-5" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#A1C9F4"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-5-6" class="code-annotation-target"><a href="#annotated-cell-5-6" aria-hidden="true" tabindex="-1"></a>        showfliers<span class="op">=</span><span class="va">False</span>,</span>
<span id="annotated-cell-5-7"><a href="#annotated-cell-5-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-5-8"><a href="#annotated-cell-5-8" aria-hidden="true" tabindex="-1"></a>    sns.stripplot(</span>
<span id="annotated-cell-5-9"><a href="#annotated-cell-5-9" aria-hidden="true" tabindex="-1"></a>        data<span class="op">=</span>data, x<span class="op">=</span>x, y<span class="op">=</span>y, order<span class="op">=</span>order, ax<span class="op">=</span>ax,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-5-10" class="code-annotation-target"><a href="#annotated-cell-5-10" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#1F4E79"</span>, alpha<span class="op">=</span>alpha, jitter<span class="op">=</span>jitter,</span>
<span id="annotated-cell-5-11"><a href="#annotated-cell-5-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-5-12"><a href="#annotated-cell-5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-5-13"><a href="#annotated-cell-5-13" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="fl">4.5</span>))</span>
<span id="annotated-cell-5-14"><a href="#annotated-cell-5-14" aria-hidden="true" tabindex="-1"></a>plot_groups(mtcars, <span class="st">"transmission"</span>, <span class="st">"mpg"</span>, [<span class="st">"Automático"</span>, <span class="st">"Manual"</span>], ax)</span>
<span id="annotated-cell-5-15"><a href="#annotated-cell-5-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mean <span class="kw">in</span> [automatic.mean(), manual.mean()]:</span>
<span id="annotated-cell-5-16"><a href="#annotated-cell-5-16" aria-hidden="true" tabindex="-1"></a>    ax.axhline(mean, color<span class="op">=</span><span class="st">"#DD8452"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="annotated-cell-5-17"><a href="#annotated-cell-5-17" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="ss">f"Δobs = </span><span class="sc">{</span>delta_obs<span class="sc">:.2f}</span><span class="ss"> mpg"</span>, xlabel<span class="op">=</span><span class="st">""</span>,</span>
<span id="annotated-cell-5-18"><a href="#annotated-cell-5-18" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">"Consumo (milhas por galão)"</span>)</span>
<span id="annotated-cell-5-19"><a href="#annotated-cell-5-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-5-20"><a href="#annotated-cell-5-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-5" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="6" data-code-annotation="1">Os pontos já aparecem no <code>stripplot</code>. <code>showfliers=False</code> evita desenhá-los duas vezes.</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="10" data-code-annotation="2"><code>jitter</code> desloca os pontos lateralmente para que não se sobreponham. <code>alpha</code> controla a transparência.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-6-output-1.png" width="562" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As caixas quase não se sobrepõem. A caixa dos manuais começa perto de onde termina a dos automáticos, e a média dos manuais fica acima de praticamente todos os automáticos. Ainda assim, há sobreposição nos extremos: alguns automáticos consomem tão pouco quanto manuais típicos, e alguns manuais consomem tanto quanto automáticos típicos.</p>
<p>Os manuais parecem mais econômicos. Mas <span class="math inline">\(\Delta_{obs} \neq 0\)</span> é apenas uma descrição da amostra, não uma prova de diferença na população. Há três motivos para cautela:</p>
<ul>
<li><strong>Natureza estocástica.</strong> Cada amostra é uma entre muitas realizações possíveis. A média amostral flutua em torno do parâmetro verdadeiro e, por isso, dois grupos sem diferença real raramente apresentam médias idênticas.</li>
<li><strong>Sensibilidade a valores atípicos.</strong> Um único valor extremo pode deslocar <span class="math inline">\(\bar{x}\)</span> e fabricar um <span class="math inline">\(\Delta_{obs}\)</span> expressivo que não representa a maior parte dos dados.</li>
<li><strong>Recorte limitado.</strong> Os dados capturam uma janela no tempo e no espaço. Viés de amostragem e fatores ocultos limitam a extrapolação.</li>
</ul>
<p>O primeiro motivo é o tema central desta aula. Antes de formalizá-lo, vejamos como ele engana a intuição.</p>
</section>
<section id="o-problema-da-aleatoriedade" class="level1">
<h1>3. O problema da aleatoriedade</h1>
<p>A <strong>apofenia</strong> é a tendência humana de perceber padrões e relações significativas em dados puramente aleatórios. Vemos rostos em nuvens e sequências em números sorteados. Uma variante conhecida é a <em>falácia do atirador do Texas</em>: atirar contra a parede de um celeiro e, só depois, desenhar o alvo em volta do grupo de tiros mais próximos.</p>
<p>Um exemplo clássico entre profissionais de saúde é a crença de que “plantão de lua cheia é sempre cheio”. Uma meta-análise com dezenas de estudos (Rotton &amp; Kelly, 1985) não encontrou relação entre as fases da lua e o comportamento humano. A crença persiste por viés de confirmação: a noite agitada de lua cheia vira história, e a noite calma é esquecida.</p>
<section id="um-pronto-socorro-simulado" class="level2">
<h2 class="anchored" data-anchor-id="um-pronto-socorro-simulado">3.1 Um pronto-socorro simulado</h2>
<p>Para estudar a crença, simulamos um ano de atendimentos em um pronto-socorro fictício. A simulação tem uma vantagem didática importante: <strong>sabemos</strong> que a lua não tem efeito, porque os atendimentos de todos os dias são sorteados da mesma distribuição. Qualquer diferença que encontrarmos entre os grupos terá sido produzida apenas pelo acaso.</p>
<div id="81481f2c" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Um ano de atendimentos diários, sem nenhum efeito da lua</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-6-2" class="code-annotation-target"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">2726</span>)</span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-6-4" class="code-annotation-target"><a href="#annotated-cell-6-4" aria-hidden="true" tabindex="-1"></a>full_moon_days <span class="op">=</span> np.<span class="bu">round</span>(np.arange(<span class="dv">12</span>) <span class="op">*</span> <span class="fl">29.53</span> <span class="op">+</span> <span class="dv">14</span>)</span>
<span id="annotated-cell-6-5"><a href="#annotated-cell-6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-6"><a href="#annotated-cell-6-6" aria-hidden="true" tabindex="-1"></a>er_visits <span class="op">=</span> (</span>
<span id="annotated-cell-6-7"><a href="#annotated-cell-6-7" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame({<span class="st">"day"</span>: np.arange(<span class="dv">365</span>)})</span>
<span id="annotated-cell-6-8"><a href="#annotated-cell-6-8" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-6-9" class="code-annotation-target"><a href="#annotated-cell-6-9" aria-hidden="true" tabindex="-1"></a>        visits<span class="op">=</span>rng.poisson(<span class="dv">120</span>, size<span class="op">=</span><span class="dv">365</span>),</span>
<span id="annotated-cell-6-10"><a href="#annotated-cell-6-10" aria-hidden="true" tabindex="-1"></a>        full_moon<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"day"</span>].isin(full_moon_days),</span>
<span id="annotated-cell-6-11"><a href="#annotated-cell-6-11" aria-hidden="true" tabindex="-1"></a>        moon<span class="op">=</span><span class="kw">lambda</span> df: np.where(df[<span class="st">"full_moon"</span>], <span class="st">"Lua cheia"</span>, <span class="st">"Demais dias"</span>),</span>
<span id="annotated-cell-6-12"><a href="#annotated-cell-6-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-6-13"><a href="#annotated-cell-6-13" aria-hidden="true" tabindex="-1"></a>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-6" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="2" data-code-annotation="1">A semente fixa garante os mesmos atendimentos a cada execução.</span>
</dd>
<dt data-target-cell="annotated-cell-6" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="4" data-code-annotation="2">O ciclo lunar dura cerca de 29,53 dias, o que resulta em 12 dias de lua cheia no ano.</span>
</dd>
<dt data-target-cell="annotated-cell-6" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="9" data-code-annotation="3">A distribuição de Poisson é usada com frequência para contagens de eventos. Todos os dias têm a mesma média, 120 atendimentos.</span>
</dd>
</dl>
</div>
</div>
<p>Resumimos os dois grupos da mesma forma que no <code>mtcars</code>:</p>
<div id="b94a3d20" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Atendimentos por dia em cada grupo</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    er_visits</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"moon"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    .visits</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    .agg([<span class="st">"size"</span>, <span class="st">"mean"</span>, <span class="st">"median"</span>, <span class="st">"std"</span>])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="67">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">size</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">std</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">moon</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Demais dias</td>
<td>353</td>
<td>119.78</td>
<td>119.0</td>
<td>10.94</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lua cheia</td>
<td>12</td>
<td>123.67</td>
<td>121.5</td>
<td>9.36</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Os dias de lua cheia tiveram média de 123,67 atendimentos, contra 119,78 nos demais dias. A mediana também é maior na lua cheia (121,5 contra 119). Os dois grupos têm desvio-padrão parecido, entre 9 e 11 atendimentos.</p>
<p>Esse desvio-padrão ajuda a entender o que está acontecendo. Em uma distribuição de Poisson, a variância é igual à média. Com média de 120 atendimentos, o desvio-padrão diário é de cerca de <span class="math inline">\(\sqrt{120} \approx 11\)</span>. Um dia comum pode facilmente ter 110 ou 130 atendimentos. A média de apenas 12 dias ainda carrega boa parte dessa oscilação, enquanto a média de 353 dias é muito mais estável. Quando comparamos as duas médias, a oscilação do grupo pequeno aparece como uma “diferença”.</p>
<p>Assim como fizemos com <code>manual</code> e <code>automatic</code>, separamos os atendimentos de cada grupo e calculamos o efeito observado:</p>
<div id="b4f2bd11" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="annotated-cell-8"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-8-1"><a href="#annotated-cell-8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Atendimentos de cada grupo e efeito observado da lua cheia</span></span>
<span id="annotated-cell-8-2"><a href="#annotated-cell-8-2" aria-hidden="true" tabindex="-1"></a>moon_in <span class="op">=</span> er_visits.loc[er_visits.full_moon, <span class="st">"visits"</span>]</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-8-3" class="code-annotation-target"><a href="#annotated-cell-8-3" aria-hidden="true" tabindex="-1"></a>moon_out <span class="op">=</span> er_visits.loc[<span class="op">~</span>er_visits.full_moon, <span class="st">"visits"</span>]</span>
<span id="annotated-cell-8-4"><a href="#annotated-cell-8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-8-5"><a href="#annotated-cell-8-5" aria-hidden="true" tabindex="-1"></a>moon_obs <span class="op">=</span> moon_in.mean() <span class="op">-</span> moon_out.mean()</span>
<span id="annotated-cell-8-6"><a href="#annotated-cell-8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-8-7"><a href="#annotated-cell-8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(moon_obs, <span class="dv">2</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-8" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="3" data-code-annotation="1"><code>~</code> inverte uma série booleana. Aqui, seleciona os dias que <strong>não</strong> são de lua cheia.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="68">
<pre><code>np.float64(3.88)</code></pre>
</div>
</div>
<p>O boxplot usa a mesma função <code>plot_groups</code>. Com 365 pontos, aumentamos a transparência para que a sobreposição não esconda a distribuição.</p>
<div id="60f6e0a8" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Atendimentos por grupo</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="fl">4.5</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>plot_groups(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    er_visits, <span class="st">"moon"</span>, <span class="st">"visits"</span>, [<span class="st">"Demais dias"</span>, <span class="st">"Lua cheia"</span>], ax,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">.4</span>, jitter<span class="op">=</span><span class="fl">.2</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="ss">f"Δobs = </span><span class="sc">{</span>moon_obs<span class="sc">:+.2f}</span><span class="ss"> atendimentos/dia"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">""</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    ylabel<span class="op">=</span><span class="st">"Atendimentos por dia"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-10-output-1.png" width="561" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Os dias de lua cheia tiveram, em média, cerca de 3,9 atendimentos a mais. O resultado parece confirmar a crença, embora tenhamos construído os dados <strong>sem</strong> qualquer efeito da lua. Compare este boxplot com o do <code>mtcars</code>. Aqui, as caixas se sobrepõem quase inteiramente, e os 12 pontos da lua cheia se espalham pela mesma faixa ocupada pelos demais dias.</p>
<p>Temos agora duas diferenças: 7,24 mpg no <code>mtcars</code> e 3,9 atendimentos no pronto-socorro. Sabemos que a segunda é puro acaso. Precisamos de um procedimento que, sem conhecer a resposta de antemão, distinga um caso do outro. Esse procedimento precisa levar em conta não apenas o tamanho da diferença, mas também quanto a diferença oscilaria se não houvesse efeito algum.</p>
</section>
</section>
<section id="formalizando-o-acaso" class="level1">
<h1>4. Formalizando o acaso</h1>
<section id="hipóteses-nula-e-alternativa" class="level2">
<h2 class="anchored" data-anchor-id="hipóteses-nula-e-alternativa">4.1 Hipóteses nula e alternativa</h2>
<p>Um teste de hipóteses confronta duas proposições sobre a <strong>população</strong>, não sobre a amostra:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Hipótese</th>
<th>Notação</th>
<th>Leitura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nula (<span class="math inline">\(H_0\)</span>)</td>
<td><span class="math inline">\(\mu_A = \mu_B \iff \Delta = 0\)</span></td>
<td>Não há efeito. A diferença observada é fruto do acaso</td>
</tr>
<tr class="even">
<td>Alternativa (<span class="math inline">\(H_1\)</span>)</td>
<td><span class="math inline">\(\mu_A \neq \mu_B \iff \Delta \neq 0\)</span></td>
<td>Existe um efeito real no processo gerador dos dados</td>
</tr>
</tbody>
</table>
<p>Aqui, <span class="math inline">\(\mu\)</span> é a média populacional, <span class="math inline">\(\Delta\)</span> é o efeito verdadeiro, que desconhecemos, e <span class="math inline">\(\Delta_{obs}\)</span> é sua estimativa na amostra. A hipótese alternativa também aparece escrita como <span class="math inline">\(H_a\)</span>.</p>
<p>Por que partir da hipótese de <strong>ausência</strong> de efeito? Porque é a única das duas que descreve um cenário preciso. A hipótese “<span class="math inline">\(\Delta = 0\)</span>” diz exatamente como os dados deveriam se comportar, e isso nos permite simular ou calcular o que esperar sob ela. A hipótese “<span class="math inline">\(\Delta \neq 0\)</span>” admite infinitos valores para o efeito e não fornece, sozinha, uma referência para comparação.</p>
<p>Para os dois exemplos da aula:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Exemplo</th>
<th><span class="math inline">\(H_0\)</span></th>
<th><span class="math inline">\(H_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lua cheia</td>
<td><span class="math inline">\(\mu_{\text{lua cheia}} = \mu_{\text{demais dias}}\)</span>: a lua não afeta o movimento</td>
<td><span class="math inline">\(\mu_{\text{lua cheia}} \neq \mu_{\text{demais dias}}\)</span>: o movimento muda em noites de lua cheia</td>
</tr>
<tr class="even">
<td><code>mtcars</code></td>
<td><span class="math inline">\(\mu_{\text{manual}} = \mu_{\text{automático}}\)</span>: o câmbio não afeta o consumo</td>
<td><span class="math inline">\(\mu_{\text{manual}} \neq \mu_{\text{automático}}\)</span>: o consumo difere entre os câmbios</td>
</tr>
</tbody>
</table>
<p>As hipóteses alternativas acima são <strong>bilaterais</strong>: admitem diferenças nos dois sentidos. Uma alternativa <strong>unilateral</strong>, como “<span class="math inline">\(\mu_{\text{lua cheia}} &gt; \mu_{\text{demais dias}}\)</span>”, só consideraria o aumento de atendimentos. Usamos a versão bilateral porque, antes de olhar os dados, uma diferença no sentido oposto também seria informativa. Escolher o sentido depois de ver qual grupo teve a maior média seria uma forma de desenhar o alvo depois dos tiros.</p>
<p>A lógica do teste lembra a de um tribunal:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Julgamento</th>
<th>Teste de hipóteses</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Presunção de inocência</td>
<td><span class="math inline">\(H_0\)</span>: não há efeito</td>
</tr>
<tr class="even">
<td>Provas apresentadas</td>
<td>Dados observados (<span class="math inline">\(\Delta_{obs}\)</span>)</td>
</tr>
<tr class="odd">
<td>Culpado “além de dúvida razoável”</td>
<td><em>p</em>-valor <span class="math inline">\(\leq \alpha\)</span></td>
</tr>
<tr class="even">
<td>Condenar um inocente</td>
<td>Erro do tipo I (falso positivo)</td>
</tr>
<tr class="odd">
<td>Absolver um culpado</td>
<td>Erro do tipo II (falso negativo)</td>
</tr>
<tr class="even">
<td>“Não culpado” não significa inocente</td>
<td>Não rejeitar <span class="math inline">\(H_0\)</span> não prova <span class="math inline">\(H_0\)</span></td>
</tr>
</tbody>
</table>
<p>O réu é considerado inocente até que as provas tornem essa hipótese difícil de sustentar. Da mesma forma, partimos de <span class="math inline">\(H_0\)</span> e só a abandonamos se os dados forem improváveis sob ela. A última linha da tabela merece atenção. Um réu absolvido por falta de provas não foi declarado inocente. Da mesma forma, não rejeitar <span class="math inline">\(H_0\)</span> significa apenas que os dados não trouxeram evidência suficiente contra ela.</p>
</section>
<section id="o-teste-de-permutação" class="level2">
<h2 class="anchored" data-anchor-id="o-teste-de-permutação">4.2 O teste de permutação</h2>
<p>Se <span class="math inline">\(H_0\)</span> for verdadeira, o rótulo “lua cheia” não carrega informação alguma sobre o número de atendimentos. Os 365 valores vêm de uma única distribuição, e o rótulo poderia estar em quaisquer 12 dias do ano. Dizemos que, sob <span class="math inline">\(H_0\)</span>, os rótulos são <strong>intercambiáveis</strong>.</p>
<p>Essa ideia leva a um procedimento em quatro passos:</p>
<ol type="1">
<li><strong>Medir.</strong> Calcular a estatística nos dados reais: <span class="math inline">\(\Delta_{obs}\)</span>.</li>
<li><strong>Embaralhar.</strong> Sob <span class="math inline">\(H_0\)</span>, os rótulos não importam. Sortear novamente quais observações recebem cada rótulo.</li>
<li><strong>Recalcular.</strong> Calcular a mesma estatística nos dados embaralhados: <span class="math inline">\(\Delta_{perm}\)</span>.</li>
<li><strong>Repetir.</strong> Fazer isso muitas vezes, por exemplo 10.000, para obter a distribuição empírica de <span class="math inline">\(\Delta\)</span> sob o acaso, chamada <strong>distribuição nula</strong>.</li>
</ol>
<p>Um exemplo pequeno ajuda a fixar o procedimento. Suponha seis observações, três do grupo A e três do grupo B:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Valor</th>
<th>12</th>
<th>15</th>
<th>18</th>
<th>9</th>
<th>10</th>
<th>14</th>
<th>Média A</th>
<th>Média B</th>
<th><span class="math inline">\(\Delta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rótulos reais</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>B</td>
<td>B</td>
<td>B</td>
<td>15,00</td>
<td>11,00</td>
<td><span class="math inline">\(+4{,}00\)</span></td>
</tr>
<tr class="even">
<td>Um embaralhamento</td>
<td>A</td>
<td>B</td>
<td>B</td>
<td>A</td>
<td>B</td>
<td>A</td>
<td>11,67</td>
<td>14,33</td>
<td><span class="math inline">\(-2{,}67\)</span></td>
</tr>
</tbody>
</table>
<p>Os valores permanecem nas mesmas posições. Apenas os rótulos trocam de lugar, sempre com três A e três B. Com seis observações, há apenas 20 maneiras de escolher quais três recebem o rótulo A, e poderíamos listar todas. No pronto-socorro, há cerca de <span class="math inline">\(9{,}7 \times 10^{21}\)</span> maneiras de escolher 12 dias entre 365. Por isso, em vez de listar todas, sorteamos uma amostra grande delas.</p>
<p>Como aplicaremos o procedimento aos dois exemplos da aula, ele fica em uma função. A cada repetição, a função embaralha os rótulos e recalcula a diferença de médias. Em seguida, aplicamos a função aos dados do pronto-socorro:</p>
<div id="b4b32841" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="annotated-cell-10"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-10-1"><a href="#annotated-cell-10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribuição nula por permutação, aplicada à lua cheia</span></span>
<span id="annotated-cell-10-2"><a href="#annotated-cell-10-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> permutation_null(values, labels, n_perm<span class="op">=</span><span class="dv">10_000</span>, seed<span class="op">=</span><span class="dv">2026</span>):</span>
<span id="annotated-cell-10-3"><a href="#annotated-cell-10-3" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="annotated-cell-10-4"><a href="#annotated-cell-10-4" aria-hidden="true" tabindex="-1"></a>    null <span class="op">=</span> []</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-10-5" class="code-annotation-target"><a href="#annotated-cell-10-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_perm):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-10-6" class="code-annotation-target"><a href="#annotated-cell-10-6" aria-hidden="true" tabindex="-1"></a>        shuffled <span class="op">=</span> rng.permutation(labels)</span>
<span id="annotated-cell-10-7"><a href="#annotated-cell-10-7" aria-hidden="true" tabindex="-1"></a>        null.append(values[shuffled].mean() <span class="op">-</span> values[<span class="op">~</span>shuffled].mean())</span>
<span id="annotated-cell-10-8"><a href="#annotated-cell-10-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array(null)</span>
<span id="annotated-cell-10-9"><a href="#annotated-cell-10-9" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-10-10" class="code-annotation-target"><a href="#annotated-cell-10-10" aria-hidden="true" tabindex="-1"></a>moon_values <span class="op">=</span> er_visits[<span class="st">"visits"</span>].to_numpy()</span>
<span id="annotated-cell-10-11"><a href="#annotated-cell-10-11" aria-hidden="true" tabindex="-1"></a>moon_labels <span class="op">=</span> er_visits[<span class="st">"full_moon"</span>].to_numpy()</span>
<span id="annotated-cell-10-12"><a href="#annotated-cell-10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-10-13"><a href="#annotated-cell-10-13" aria-hidden="true" tabindex="-1"></a>moon_null <span class="op">=</span> permutation_null(moon_values, moon_labels)</span>
<span id="annotated-cell-10-14"><a href="#annotated-cell-10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-10-15"><a href="#annotated-cell-10-15" aria-hidden="true" tabindex="-1"></a>moon_null[:<span class="dv">5</span>].<span class="bu">round</span>(<span class="dv">2</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-10" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="5" data-code-annotation="1"><code>_</code> é o nome convencional para uma variável de laço que não será usada.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="6" data-code-annotation="2"><code>rng.permutation</code> devolve uma cópia embaralhada dos rótulos. Os valores ficam no lugar, e os rótulos mudam de dono.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="10" data-code-annotation="3">Arrays do NumPy aceitam indexação booleana sem alinhar índices, o que torna o laço mais rápido.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="70">
<pre><code>array([-5.33, -6.46, -2.23, -1.54,  4.49])</code></pre>
</div>
</div>
<p>Os cinco primeiros valores mostram o que o acaso produz. Alguns sorteios deram diferenças positivas, outros negativas, e algumas delas são maiores, em módulo, que os 3,9 atendimentos observados. Cada valor de <code>moon_null</code> é a diferença que teríamos observado se 12 dias quaisquer tivessem recebido o rótulo de lua cheia.</p>
<p>O histograma reúne as 10.000 diferenças. Como <span class="math inline">\(H_1\)</span> é bilateral, marcamos <span class="math inline">\(+\Delta_{obs}\)</span> e <span class="math inline">\(-\Delta_{obs}\)</span>. Como faremos o mesmo gráfico para o <code>mtcars</code>, ele também fica em uma função:</p>
<div id="d6cc6e0f" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribuição nula da lua cheia e posição do efeito observado</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_null(null, obs, title, xlabel):</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">4</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    sns.histplot(null, bins<span class="op">=</span><span class="dv">50</span>, color<span class="op">=</span><span class="st">"#A1C9F4"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> value <span class="kw">in</span> [<span class="op">-</span>obs, obs]:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        ax.axvline(value, color<span class="op">=</span><span class="st">"#DD8452"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    ax.<span class="bu">set</span>(title<span class="op">=</span>title, xlabel<span class="op">=</span>xlabel, ylabel<span class="op">=</span><span class="st">"Permutações"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>plot_null(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    moon_null,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    moon_obs,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Lua cheia: onde cai o Δobs na distribuição do acaso?"</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"Δperm: diferença de médias após sortear 12 dias como lua cheia"</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-12-output-1.png" width="850" height="369" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A distribuição nula tem duas características que valem para qualquer teste de permutação de diferença de médias:</p>
<ul>
<li><strong>Centro em zero.</strong> Sob <span class="math inline">\(H_0\)</span>, nenhum grupo é favorecido. Para cada sorteio que coloca os dias movimentados na lua cheia, há outro que os coloca nos demais dias.</li>
<li><strong>Largura que reflete a oscilação do acaso.</strong> A maior parte das diferenças fica entre <span class="math inline">\(-6\)</span> e <span class="math inline">\(+6\)</span> atendimentos. Essa faixa é o que o acaso, sozinho, consegue produzir com 12 dias contra 353.</li>
</ul>
<p>O efeito observado cai em uma região bem povoada da distribuição, longe das caudas. A proporção de permutações com resultado tão ou mais extremo que <span class="math inline">\(\Delta_{obs}\)</span> responde à pergunta “quão comum é esse resultado sob o acaso?”:</p>
<div id="b5f1d5ca" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="annotated-cell-12"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proporção de permutações tão ou mais extremas que o observado</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-12-2" class="code-annotation-target"><a href="#annotated-cell-12-2" aria-hidden="true" tabindex="-1"></a>moon_p <span class="op">=</span> np.mean(np.<span class="bu">abs</span>(moon_null) <span class="op">&gt;=</span> <span class="bu">abs</span>(moon_obs))</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-4"><a href="#annotated-cell-12-4" aria-hidden="true" tabindex="-1"></a>moon_p</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="2" data-code-annotation="1">A média de um vetor booleano é a proporção de <code>True</code>. O valor absoluto conta os dois sentidos: o teste é <strong>bilateral</strong>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="72">
<pre><code>np.float64(0.23)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Por que 10.000 permutações?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A proporção calculada é uma <strong>estimativa</strong> do <em>p</em>-valor exato, que exigiria percorrer todas as divisões possíveis. Como toda estimativa por sorteio, ela tem um erro. Com 10.000 permutações e um <em>p</em>-valor em torno de 0,2, esse erro é da ordem de 0,004, pequeno demais para mudar qualquer conclusão. Mais permutações tornam a estimativa mais precisa, ao custo de mais tempo de execução. A semente fixa em <code>permutation_null</code> garante que o resultado seja reproduzível.</p>
</div>
</div>
</div>
</section>
<section id="o-p-valor" class="level2">
<h2 class="anchored" data-anchor-id="o-p-valor">4.3 O <em>p</em>-valor</h2>
<p>Essa proporção tem nome. O <strong><em>p</em>-valor</strong> é a probabilidade, <strong>supondo <span class="math inline">\(H_0\)</span> verdadeira</strong>, de obter um efeito tão ou mais extremo que o observado:</p>
<p><span class="math display">\[
p = P\left(|\Delta_{perm}| \geq |\Delta_{obs}| \;\middle|\; H_0 \text{ verdadeira}\right)
\]</span></p>
<p>Cada parte da definição tem um papel:</p>
<ul>
<li><strong>“Supondo <span class="math inline">\(H_0\)</span> verdadeira”</strong>: a probabilidade é calculada no mundo em que não há efeito. Por isso usamos a distribuição nula, construída com rótulos embaralhados.</li>
<li><strong>“Tão ou mais extremo”</strong>: não perguntamos pela chance de obter exatamente 3,88, que é praticamente nula para qualquer valor específico. Perguntamos pela chance de obter algo pelo menos tão afastado de zero. Daí o sinal <span class="math inline">\(\geq\)</span>.</li>
<li><strong>Valor absoluto</strong>: como o teste é bilateral, diferenças de <span class="math inline">\(-3{,}88\)</span> ou menos também contam como tão extremas quanto <span class="math inline">\(+3{,}88\)</span>.</li>
</ul>
<p>No pronto-socorro, cerca de 23% das permutações produziram diferenças pelo menos tão grandes quanto a observada. Uma diferença de 3,9 atendimentos é, portanto, um resultado corriqueiro quando a lua não tem efeito algum. Aproximadamente um em cada quatro sorteios de 12 dias produziria algo assim.</p>
<p>O <em>p</em>-valor é frequentemente mal interpretado. A American Statistical Association publicou uma declaração específica sobre o tema (Wasserstein &amp; Lazar, 2016). A tabela a seguir resume os pontos principais com o exemplo da lua cheia:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>O <em>p</em>-valor é</th>
<th>Na lua cheia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Uma probabilidade condicional a <span class="math inline">\(H_0\)</span></td>
<td><strong>Se</strong> a lua não tiver efeito, 23% dos sorteios produzem uma diferença tão grande quanto a observada</td>
</tr>
<tr class="even">
<td>Uma medida de quão atípicos os dados são sob o acaso</td>
<td>Os dados são bastante típicos de um mundo sem efeito da lua</td>
</tr>
<tr class="odd">
<td>Dependente do tamanho da amostra</td>
<td>Com 10 anos de dados, a mesma diferença de 3,9 atendimentos teria um <em>p</em>-valor bem menor</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>O <em>p</em>-valor não é</th>
<th>Interpretação errada na lua cheia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A probabilidade de <span class="math inline">\(H_0\)</span> ser verdadeira</td>
<td>“Há 23% de chance de a lua não ter efeito”</td>
</tr>
<tr class="even">
<td>A probabilidade de o resultado ser “mero acaso”</td>
<td>“Há 23% de chance de a diferença ser acaso”</td>
</tr>
<tr class="odd">
<td>Uma medida do tamanho ou da importância do efeito</td>
<td>“Um <em>p</em>-valor menor significaria um efeito maior da lua”</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>O <em>p</em>-valor responde a “<strong>se</strong> não houvesse efeito, quão raro seria este resultado?”. Ele não responde a “qual é a probabilidade de não haver efeito?”. As duas perguntas têm respostas diferentes.</p>
</div>
</div>
</section>
<section id="a-regra-de-decisão" class="level2">
<h2 class="anchored" data-anchor-id="a-regra-de-decisão">4.4 A regra de decisão</h2>
<p>O <em>p</em>-valor é um número contínuo, mas muitas vezes precisamos de uma decisão: agir ou não agir, reforçar ou não a escala de plantão. Para isso, fixamos <strong>antes da análise</strong> um limiar chamado <strong>nível de significância</strong>, <span class="math inline">\(\alpha\)</span>. O valor convencional é <span class="math inline">\(\alpha = 0{,}05\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Resultado</th>
<th>Decisão</th>
<th>Leitura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(p \leq \alpha\)</span></td>
<td>Rejeita-se <span class="math inline">\(H_0\)</span></td>
<td>Os dados são atípicos demais para o acaso. O efeito é estatisticamente significante</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p &gt; \alpha\)</span></td>
<td>Não se rejeita <span class="math inline">\(H_0\)</span></td>
<td>A diferença é compatível com a flutuação aleatória. Isso não prova que <span class="math inline">\(H_0\)</span> seja verdadeira</td>
</tr>
</tbody>
</table>
<p>O valor de <span class="math inline">\(\alpha\)</span> tem uma interpretação direta. Se <span class="math inline">\(H_0\)</span> for verdadeira, o <em>p</em>-valor ficará abaixo de 0,05 em 5% das vezes, apenas por acaso. Ao usar <span class="math inline">\(\alpha = 0{,}05\)</span>, aceitamos errar dessa forma em 5% dos testes sem efeito real. A seção 6.2 ilustra essa propriedade com uma simulação.</p>
<p>Na lua cheia, <span class="math inline">\(p \approx 0{,}23 &gt; 0{,}05\)</span>. Não rejeitamos <span class="math inline">\(H_0\)</span>: o “plantão de lua cheia” é compatível com o acaso. Neste caso, sabemos que a decisão está correta, porque construímos os dados sem efeito.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Por que 0,05?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>O valor é uma convenção, popularizada por R. A. Fisher na década de 1920, e não uma propriedade matemática. Áreas diferentes adotam limiares diferentes. A física de partículas, por exemplo, exige evidências muito mais fortes antes de anunciar uma descoberta. O importante é fixar <span class="math inline">\(\alpha\)</span> antes de olhar os dados. Escolher o limiar depois de ver o <em>p</em>-valor é uma versão da falácia do atirador do Texas.</p>
</div>
</div>
</div>
</section>
<section id="permutação-no-mtcars" class="level2">
<h2 class="anchored" data-anchor-id="permutação-no-mtcars">4.5 Permutação no <code>mtcars</code></h2>
<p>Repetimos o procedimento para o câmbio. Sob <span class="math inline">\(H_0\)</span>, o câmbio não afeta o consumo, e os 32 valores de <code>mpg</code> vêm de uma única distribuição. Qualquer divisão em 13 manuais e 19 automáticos seria tão plausível quanto a real. Há cerca de 347 milhões dessas divisões, e novamente sorteamos 10.000 delas.</p>
<div id="9004aec7" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribuição nula do câmbio</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mpg_values <span class="op">=</span> mtcars[<span class="st">"mpg"</span>].to_numpy()</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mpg_labels <span class="op">=</span> (mtcars[<span class="st">"am"</span>] <span class="op">==</span> <span class="dv">1</span>).to_numpy()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>mpg_null <span class="op">=</span> permutation_null(mpg_values, mpg_labels)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>mpg_p <span class="op">=</span> np.mean(np.<span class="bu">abs</span>(mpg_null) <span class="op">&gt;=</span> <span class="bu">abs</span>(delta_obs))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>mpg_p</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="73">
<pre><code>np.float64(0.0001)</code></pre>
</div>
</div>
<div id="01584d9b" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribuição nula do câmbio e posição do efeito observado</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>plot_null(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    mpg_null,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    delta_obs,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Câmbio: onde cai o Δobs na distribuição do acaso?"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"Δperm: diferença de médias (mpg) após embaralhar o câmbio"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-15-output-1.png" width="850" height="368" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A distribuição nula tem a mesma forma de sino centrada em zero, agora na escala de milhas por galão. A maior parte das diferenças produzidas pelo acaso fica entre <span class="math inline">\(-4\)</span> e <span class="math inline">\(+4\)</span> mpg. As linhas do efeito observado ficam nas extremidades, fora da região ocupada pelas permutações. Apenas uma em 10.000 chegou a uma diferença de 7,24 mpg. Como <span class="math inline">\(p &lt; 0{,}05\)</span>, rejeitamos <span class="math inline">\(H_0\)</span>: uma diferença desse tamanho seria muito rara se o câmbio não importasse.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Resolução do <em>p</em>-valor por permutação
</div>
</div>
<div class="callout-body-container callout-body">
<p>Com 10.000 permutações, a menor proporção diferente de zero é <span class="math inline">\(1/10.000 = 0{,}0001\)</span>. Um resultado de 0,0001 indica apenas que o <em>p</em>-valor é muito pequeno, e a forma honesta de reportá-lo é “<span class="math inline">\(p &lt; 0{,}001\)</span>”. Para distinguir <em>p</em>-valores ainda menores, seriam necessárias mais permutações.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aviso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Rejeitar <span class="math inline">\(H_0\)</span> indica que a diferença dificilmente é acaso. <strong>Não</strong> indica que o câmbio seja a causa da diferença. Os carros manuais da base também diferem dos automáticos em outras características, uma questão que retomaremos na Pergunta 2.</p>
</div>
</div>
</section>
</section>
<section id="o-atalho-paramétrico" class="level1">
<h1>5. O atalho paramétrico</h1>
<p>O teste de permutação constrói a distribuição nula por simulação. Um teste <strong>paramétrico</strong> chega ao mesmo destino por outro caminho. O nome vem de <strong>parâmetro</strong>: uma quantidade fixa que descreve uma população inteira, como a média <span class="math inline">\(\mu\)</span> ou o desvio-padrão <span class="math inline">\(\sigma\)</span>. Em vez de simular, o teste paramétrico supõe que os dados seguem uma família de distribuições conhecida e usa a teoria para deduzir a distribuição nula. O procedimento tem três etapas:</p>
<ol type="1">
<li><strong>Supor um modelo.</strong> Os dados, ou as médias, seguem uma família conhecida, como a normal, com parâmetros <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>.</li>
<li><strong>Derivar a distribuição nula.</strong> Sob <span class="math inline">\(H_0\)</span>, a estatística do teste segue uma distribuição teórica, como <em>t</em>, <em>F</em>, <span class="math inline">\(\chi^2\)</span> ou <em>Z</em>.</li>
<li><strong>Ler o <em>p</em>-valor.</strong> A área na cauda vem de uma fórmula, sem simular nada.</li>
</ol>
<p>A vantagem é a rapidez e, quando as premissas valem, um poder maior. O risco é que, se as premissas falharem, o <em>p</em>-valor pode enganar.</p>
<section id="o-erro-padrão" class="level2">
<h2 class="anchored" data-anchor-id="o-erro-padrão">5.1 O erro-padrão</h2>
<p>Para substituir a simulação, a teoria precisa saber <strong>quanto a diferença de médias oscila por acaso</strong>. Essa oscilação corresponde à largura da distribuição nula, que podemos medir pelo desvio-padrão das permutações:</p>
<div id="c6913226" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Largura da distribuição nula do câmbio, medida pela simulação</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(mpg_null.std(), <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="75">
<pre><code>np.float64(2.16)</code></pre>
</div>
</div>
<p>A teoria prevê essa largura sem simular nada. O raciocínio tem duas etapas:</p>
<ol type="1">
<li><strong>A média de um grupo oscila menos que os dados individuais.</strong> Se os dados têm desvio-padrão <span class="math inline">\(s\)</span>, a média de <span class="math inline">\(n\)</span> observações independentes tem variância <span class="math inline">\(s^2/n\)</span>. Quanto maior o grupo, mais estável é sua média.</li>
<li><strong>A variância de uma diferença soma as variâncias.</strong> Quando subtraímos duas médias independentes, as oscilações das duas se acumulam. A variância de <span class="math inline">\(\bar{x}_A - \bar{x}_B\)</span> é <span class="math inline">\(s^2/n_A + s^2/n_B\)</span>.</li>
</ol>
<p>Sob <span class="math inline">\(H_0\)</span>, os dois grupos vêm da mesma população, cujo desvio-padrão estimamos com os 32 carros juntos. Tirando a raiz quadrada da variância, chegamos à largura da distribuição nula:</p>
<p><span class="math display">\[
SE = \sqrt{\frac{s^2}{n_A} + \frac{s^2}{n_B}} = s \sqrt{\frac{1}{n_A} + \frac{1}{n_B}}
\]</span></p>
<div id="cbb80bb2" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Largura da distribuição nula do câmbio, prevista pela fórmula</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n_manual, n_automatic <span class="op">=</span> <span class="bu">len</span>(manual), <span class="bu">len</span>(automatic)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>se_null <span class="op">=</span> mtcars.mpg.std() <span class="op">*</span> np.sqrt(<span class="dv">1</span> <span class="op">/</span> n_manual <span class="op">+</span> <span class="dv">1</span> <span class="op">/</span> n_automatic)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(se_null, <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="76">
<pre><code>np.float64(2.17)</code></pre>
</div>
</div>
<p>Os dois valores praticamente coincidem: 2,16 mpg pela simulação e 2,17 mpg pela fórmula. A curva normal com essa largura descreve bem o histograma das permutações:</p>
<div id="e3ea293d" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="annotated-cell-17"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-17-1"><a href="#annotated-cell-17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma das permutações e curva normal prevista pela fórmula</span></span>
<span id="annotated-cell-17-2"><a href="#annotated-cell-17-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="annotated-cell-17-3"><a href="#annotated-cell-17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-17-4"><a href="#annotated-cell-17-4" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">300</span>)</span>
<span id="annotated-cell-17-5"><a href="#annotated-cell-17-5" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-17-6" class="code-annotation-target"><a href="#annotated-cell-17-6" aria-hidden="true" tabindex="-1"></a>ax.hist(mpg_null, bins<span class="op">=</span><span class="dv">40</span>, density<span class="op">=</span><span class="va">True</span>,</span>
<span id="annotated-cell-17-7"><a href="#annotated-cell-17-7" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#A1C9F4"</span>, label<span class="op">=</span><span class="st">"10.000 permutações"</span>)</span>
<span id="annotated-cell-17-8"><a href="#annotated-cell-17-8" aria-hidden="true" tabindex="-1"></a>ax.plot(grid, stats.norm.pdf(grid, <span class="dv">0</span>, se_null),</span>
<span id="annotated-cell-17-9"><a href="#annotated-cell-17-9" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#1F4E79"</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"curva prevista pela fórmula"</span>)</span>
<span id="annotated-cell-17-10"><a href="#annotated-cell-17-10" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="annotated-cell-17-11"><a href="#annotated-cell-17-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> value <span class="kw">in</span> [<span class="op">-</span>se_null, se_null]:</span>
<span id="annotated-cell-17-12"><a href="#annotated-cell-17-12" aria-hidden="true" tabindex="-1"></a>    ax.axvline(value, color<span class="op">=</span><span class="st">"#DD8452"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="annotated-cell-17-13"><a href="#annotated-cell-17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-17-14"><a href="#annotated-cell-17-14" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">"±1 erro-padrão"</span>, xlabel<span class="op">=</span><span class="st">"Δperm: diferença de médias sob H₀ (mpg)"</span>,</span>
<span id="annotated-cell-17-15"><a href="#annotated-cell-17-15" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">"Densidade"</span>)</span>
<span id="annotated-cell-17-16"><a href="#annotated-cell-17-16" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="annotated-cell-17-17"><a href="#annotated-cell-17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-17-18"><a href="#annotated-cell-17-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-17-19"><a href="#annotated-cell-17-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-17" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-17" data-code-lines="6" data-code-annotation="1"><code>density=True</code> coloca o histograma na mesma escala da curva, com área total igual a 1.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-18-output-1.png" width="753" height="369" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Essa largura recebe o nome de <strong>erro-padrão</strong> (SE, do inglês <em>standard error</em>). Ela funciona como a régua do acaso: as linhas tracejadas marcam um erro-padrão para cada lado de zero, e cerca de dois terços das permutações caem entre elas.</p>
</section>
<section id="desvio-padrão-e-erro-padrão" class="level2">
<h2 class="anchored" data-anchor-id="desvio-padrão-e-erro-padrão">5.2 Desvio-padrão e erro-padrão</h2>
<p>Os dois termos se parecem, mas medem coisas diferentes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Desvio-padrão (<span class="math inline">\(s\)</span>)</th>
<th>Erro-padrão (<span class="math inline">\(SE\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>O que mede</td>
<td>A dispersão dos <strong>dados individuais</strong> em torno da média</td>
<td>A variabilidade da <strong>própria estimativa</strong>, como <span class="math inline">\(\bar{x}\)</span>, entre amostras repetidas</td>
</tr>
<tr class="even">
<td>Com mais dados</td>
<td>Não diminui: é uma característica da população</td>
<td>Diminui: <span class="math inline">\(SE(\bar{x}) = s / \sqrt{n}\)</span></td>
</tr>
</tbody>
</table>
<p>O pronto-socorro simulado ilustra a diferença. Sorteamos 2.000 amostras de cada tamanho a partir dos 365 dias e, para cada tamanho, calculamos duas coisas: o desvio-padrão típico <strong>dentro</strong> de uma amostra e o desvio-padrão das médias <strong>entre</strong> as amostras.</p>
<div id="4642d150" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="annotated-cell-18"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-18-1"><a href="#annotated-cell-18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio-padrão dos dados e das médias amostrais, por tamanho de amostra</span></span>
<span id="annotated-cell-18-2"><a href="#annotated-cell-18-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="annotated-cell-18-3"><a href="#annotated-cell-18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-18-4"><a href="#annotated-cell-18-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sample_summary(n, n_samples<span class="op">=</span><span class="dv">2_000</span>):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-18" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-18-5" class="code-annotation-target"><a href="#annotated-cell-18-5" aria-hidden="true" tabindex="-1"></a>    samples <span class="op">=</span> rng.choice(moon_values, size<span class="op">=</span>(n_samples, n))</span>
<span id="annotated-cell-18-6"><a href="#annotated-cell-18-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-18" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-18-7" class="code-annotation-target"><a href="#annotated-cell-18-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dp_dos_dados"</span>: samples.std(axis<span class="op">=</span><span class="dv">1</span>, ddof<span class="op">=</span><span class="dv">1</span>).mean(),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-18" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-18-8" class="code-annotation-target"><a href="#annotated-cell-18-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dp_das_medias"</span>: samples.mean(axis<span class="op">=</span><span class="dv">1</span>).std(ddof<span class="op">=</span><span class="dv">1</span>),</span>
<span id="annotated-cell-18-9"><a href="#annotated-cell-18-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"previsto_s_raiz_n"</span>: moon_values.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n),</span>
<span id="annotated-cell-18-10"><a href="#annotated-cell-18-10" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="annotated-cell-18-11"><a href="#annotated-cell-18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-18-12"><a href="#annotated-cell-18-12" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="annotated-cell-18-13"><a href="#annotated-cell-18-13" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame({n: sample_summary(n) <span class="cf">for</span> n <span class="kw">in</span> [<span class="dv">10</span>, <span class="dv">40</span>, <span class="dv">160</span>, <span class="dv">640</span>]})</span>
<span id="annotated-cell-18-14"><a href="#annotated-cell-18-14" aria-hidden="true" tabindex="-1"></a>    .T</span>
<span id="annotated-cell-18-15"><a href="#annotated-cell-18-15" aria-hidden="true" tabindex="-1"></a>    .rename_axis(<span class="st">"n"</span>)</span>
<span id="annotated-cell-18-16"><a href="#annotated-cell-18-16" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="annotated-cell-18-17"><a href="#annotated-cell-18-17" aria-hidden="true" tabindex="-1"></a>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-18" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-18" data-code-lines="5" data-code-annotation="1">Cada linha da matriz é uma amostra de tamanho <code>n</code>, sorteada com reposição.</span>
</dd>
<dt data-target-cell="annotated-cell-18" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-18" data-code-lines="7" data-code-annotation="2">Desvio-padrão dentro de cada amostra, depois a média entre as amostras.</span>
</dd>
<dt data-target-cell="annotated-cell-18" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-18" data-code-lines="8" data-code-annotation="3">Desvio-padrão das 2.000 médias amostrais: o erro-padrão observado.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="78">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dp_dos_dados</th>
<th data-quarto-table-cell-role="th">dp_das_medias</th>
<th data-quarto-table-cell-role="th">previsto_s_raiz_n</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>10.64</td>
<td>3.54</td>
<td>3.45</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">40</td>
<td>10.81</td>
<td>1.63</td>
<td>1.72</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">160</td>
<td>10.87</td>
<td>0.89</td>
<td>0.86</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">640</td>
<td>10.89</td>
<td>0.42</td>
<td>0.43</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Cada coluna da tabela responde a uma pergunta:</p>
<ul>
<li><strong><code>dp_dos_dados</code></strong>: quanto variam os dias dentro de uma amostra? Cerca de 11 atendimentos, qualquer que seja <span class="math inline">\(n\)</span>. Coletar mais dias não torna cada dia menos variável.</li>
<li><strong><code>dp_das_medias</code></strong>: quanto varia a média de uma amostra para outra? Com 10 dias, cerca de 3,5 atendimentos. Com 640 dias, cerca de 0,4. Cada vez que <span class="math inline">\(n\)</span> quadruplica, esse valor cai pela metade.</li>
<li><strong><code>previsto_s_raiz_n</code></strong>: o que a fórmula <span class="math inline">\(s/\sqrt{n}\)</span> prevê? Valores muito próximos da coluna anterior, o que confirma a fórmula.</li>
</ul>
<p>Em resumo, o desvio-padrão descreve os <strong>dados</strong>, e o erro-padrão descreve a <strong>precisão da estimativa</strong>. O erro-padrão diz o quanto a estimativa mudaria se a coleta fosse repetida com outra amostra do mesmo tamanho.</p>
</section>
<section id="a-estatística-t" class="level2">
<h2 class="anchored" data-anchor-id="a-estatística-t">5.3 A estatística <em>t</em></h2>
<p>Com a régua definida, a pergunta se torna: <strong>quantos erros-padrão cabem entre 0 e <span class="math inline">\(\Delta_{obs}\)</span>?</strong></p>
<div id="448e9fc2" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Efeito observado do câmbio, medido em erros-padrão</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(delta_obs <span class="op">/</span> se_null, <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="79">
<pre><code>np.float64(3.34)</code></pre>
</div>
</div>
<p>Cabem cerca de 3,3 erros-padrão. Sob o acaso, a diferença de médias quase nunca ultrapassa 2 erros-padrão: na curva normal, cerca de 95% da área fica entre <span class="math inline">\(-2\)</span> e <span class="math inline">\(+2\)</span>. Essa contagem é a <strong>estatística <em>t</em></strong>:</p>
<p><span class="math display">\[
t = \frac{\bar{x}_A - \bar{x}_B}{SE}
\]</span></p>
<p>A vantagem de medir a diferença em erros-padrão é que o resultado deixa de depender da unidade. Uma diferença de 7 mpg e uma de 4 atendimentos não são comparáveis diretamente. Medidas em erros-padrão, as duas passam a estar na mesma régua.</p>
<p>A fórmula da seção 5.1 usou um único desvio-padrão para os dois grupos. A versão de <strong>Welch</strong> estima a variância de cada grupo separadamente e não exige que sejam iguais:</p>
<p><span class="math display">\[
SE = \sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}}
\]</span></p>
<p>Aqui, <span class="math inline">\(s_A^2\)</span> e <span class="math inline">\(s_B^2\)</span> são as variâncias amostrais e <span class="math inline">\(n_A\)</span> e <span class="math inline">\(n_B\)</span>, os tamanhos dos grupos.</p>
<div id="75fd9726" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estatística t de Welch calculada pela fórmula</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>se_welch <span class="op">=</span> np.sqrt(manual.var() <span class="op">/</span> n_manual <span class="op">+</span> automatic.var() <span class="op">/</span> n_automatic)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">round</span>(se_welch, <span class="dv">2</span>), <span class="bu">round</span>(delta_obs <span class="op">/</span> se_welch, <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="80">
<pre><code>(np.float64(1.92), np.float64(3.77))</code></pre>
</div>
</div>
<p>O erro-padrão de Welch (1,92 mpg) é menor que o da seção 5.1 (2,17 mpg), e o <em>t</em> sobe de 3,34 para 3,77. A diferença tem uma explicação. O desvio-padrão dos 32 carros juntos inclui a distância entre os dois grupos: misturar manuais econômicos com automáticos menos econômicos aumenta a dispersão total. A versão de Welch mede a variação <strong>dentro</strong> de cada grupo e não é inflada por essa distância.</p>
<p>O teste <em>t</em> converte o número de erros-padrão em uma probabilidade. Para isso, usa a distribuição <em>t</em> em vez da normal. As duas têm forma de sino, mas a <em>t</em> tem caudas mais pesadas. A razão é que o erro-padrão também é estimado a partir dos dados e, em amostras pequenas, essa estimativa pode errar. A distribuição <em>t</em> incorpora essa incerteza extra por meio dos <strong>graus de liberdade</strong> (<em>df</em>, do inglês <em>degrees of freedom</em>), que crescem com o tamanho das amostras. Com poucos graus de liberdade, as caudas são pesadas. Com muitos, a distribuição <em>t</em> se aproxima da normal.</p>
<p>Na prática, <code>stats.ttest_ind</code> faz todo o cálculo. Guardamos o resultado em uma variável para reaproveitá-lo na seção 5.6:</p>
<div id="2e880835" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="annotated-cell-21"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-21-1"><a href="#annotated-cell-21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t de Welch no mtcars</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-21" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-21-2" class="code-annotation-target"><a href="#annotated-cell-21-2" aria-hidden="true" tabindex="-1"></a>mpg_ttest <span class="op">=</span> stats.ttest_ind(manual, automatic, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="annotated-cell-21-3"><a href="#annotated-cell-21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-21-4"><a href="#annotated-cell-21-4" aria-hidden="true" tabindex="-1"></a>mpg_ttest</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-21" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-21" data-code-lines="2" data-code-annotation="1"><code>equal_var=False</code> seleciona a versão de Welch. Com <code>True</code>, o SciPy usa a versão clássica, que supõe variâncias iguais.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="81">
<pre><code>TtestResult(statistic=np.float64(3.767123145144923), pvalue=np.float64(0.0013736383330710345), df=np.float64(18.332251638400464))</code></pre>
</div>
</div>
<p>O resultado tem três campos:</p>
<ul>
<li><strong><code>statistic</code></strong>: a estatística <em>t</em>, 3,77, a mesma calculada pela fórmula.</li>
<li><strong><code>pvalue</code></strong>: o <em>p</em>-valor bilateral, 0,0014.</li>
<li><strong><code>df</code></strong>: os graus de liberdade estimados pela fórmula de Welch, cerca de 18,3. O valor não é inteiro porque Welch ajusta os graus de liberdade conforme as variâncias e os tamanhos dos grupos.</li>
</ul>
<p>E no pronto-socorro:</p>
<div id="ec73c82d" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t de Welch na lua cheia</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>moon_ttest <span class="op">=</span> stats.ttest_ind(moon_in, moon_out, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>moon_ttest</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="82">
<pre><code>TtestResult(statistic=np.float64(1.4048153658505091), pvalue=np.float64(0.1853402601391711), df=np.float64(12.043510826046889))</code></pre>
</div>
</div>
<p>Aqui, <span class="math inline">\(t \approx 1{,}40\)</span>. A diferença observada cabe menos de uma vez e meia na régua do acaso, bem abaixo do limiar aproximado de 2 erros-padrão. O <em>p</em>-valor, cerca de 0,19, confirma que o resultado é comum sob <span class="math inline">\(H_0\)</span>.</p>
<p>As conclusões coincidem com as da permutação. No <code>mtcars</code>, <span class="math inline">\(p &lt; 0{,}05\)</span> e rejeitamos <span class="math inline">\(H_0\)</span>. Na lua cheia, <span class="math inline">\(p &gt; 0{,}05\)</span> e não rejeitamos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Por que “Student”?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>William S. Gosset era químico da cervejaria Guinness e precisava tirar conclusões de amostras pequenas de cevada. A cervejaria não permitia que seus funcionários publicassem com o próprio nome, e Gosset publicou o teste em 1908 sob o pseudônimo “Student”.</p>
</div>
</div>
</div>
</section>
<section id="premissas-e-limitações-do-teste-t" class="level2">
<h2 class="anchored" data-anchor-id="premissas-e-limitações-do-teste-t">5.4 Premissas e limitações do teste <em>t</em></h2>
<p>O atalho paramétrico só é confiável quando suas premissas são razoáveis. A tabela relaciona cada premissa ao modo de verificá-la e ao que acontece quando ela falha:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Premissa</th>
<th>Como verificar</th>
<th>Quando falha</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Observações independentes</td>
<td>Examinar como os dados foram coletados: medições repetidas no mesmo indivíduo ou dias consecutivos podem estar relacionados</td>
<td>Dados pareados ou temporais exigem outra versão do teste</td>
</tr>
<tr class="even">
<td>Médias aproximadamente normais</td>
<td>Histograma ou boxplot de cada grupo. Pelo teorema central do limite, a premissa é mais tranquila com <em>n</em> moderado ou grande</td>
<td>Amostras pequenas e muito assimétricas distorcem o <em>p</em>-valor</td>
</tr>
<tr class="odd">
<td>Variável em escala contínua</td>
<td>Verificar o tipo da variável</td>
<td>Variáveis ordinais ou categóricas pedem outros testes</td>
</tr>
<tr class="even">
<td>Na versão de Welch, as variâncias podem ser diferentes</td>
<td>Comparar os desvios-padrão dos grupos</td>
<td>A versão clássica, com <code>equal_var=True</code>, perde a validade quando as variâncias diferem muito</td>
</tr>
</tbody>
</table>
<p>Há ainda duas limitações que não dependem de premissas. O teste <em>t</em> compara <strong>médias</strong>, e não medianas ou formas de distribuição. E, por depender de média e variância, ele é sensível a valores atípicos.</p>
</section>
<section id="um-único-valor-atípico-muda-a-história" class="level2">
<h2 class="anchored" data-anchor-id="um-único-valor-atípico-muda-a-história">5.5 Um único valor atípico muda a história</h2>
<p>Na Aula 5, vimos que média e desvio-padrão são sensíveis a valores extremos. O teste <em>t</em> depende das duas medidas e herda essa fragilidade. Para ver o efeito, acrescentamos um carro automático cujo consumo foi digitado como 60 mpg, um erro de registro plausível.</p>
<div id="12bc7551" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Automáticos com um consumo digitado como 60 mpg</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>automatic_typo <span class="op">=</span> pd.concat(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    [automatic, pd.Series([<span class="fl">60.</span>])],</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    ignore_index<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A função abaixo reúne, para dois grupos, as medidas que o valor atípico pode afetar. Aplicamos a função à base original e à base com o valor digitado errado:</p>
<div id="c52b6328" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diferenças, dispersão e teste t, sem e com o valor digitado errado</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compare(group_a, group_b):</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    test <span class="op">=</span> stats.ttest_ind(group_a, group_b, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dif_medias"</span>: group_a.mean() <span class="op">-</span> group_b.mean(),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dif_medianas"</span>: group_a.median() <span class="op">-</span> group_b.median(),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"dp_automaticos"</span>: group_b.std(),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"t"</span>: test.statistic,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p"</span>: test.pvalue,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame(</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">"mtcars original"</span>: compare(manual, automatic),</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">"+1 automático com 60 mpg"</span>: compare(manual, automatic_typo),</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    .T</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="84">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dif_medias</th>
<th data-quarto-table-cell-role="th">dif_medianas</th>
<th data-quarto-table-cell-role="th">dp_automaticos</th>
<th data-quarto-table-cell-role="th">t</th>
<th data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">mtcars original</td>
<td>7.2449</td>
<td>5.50</td>
<td>3.8340</td>
<td>3.7671</td>
<td>0.0014</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">+1 automático com 60 mpg</td>
<td>5.1023</td>
<td>5.25</td>
<td>10.2831</td>
<td>1.7805</td>
<td>0.0848</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Um único valor errado age sobre as duas partes da estatística <em>t</em> ao mesmo tempo:</p>
<ol type="1">
<li><strong>O numerador diminui.</strong> O carro de 60 mpg eleva a média dos automáticos, e a diferença de médias cai de 7,24 para 5,10 mpg.</li>
<li><strong>O denominador aumenta.</strong> O desvio-padrão dos automáticos quase triplica, de 3,83 para 10,28 mpg. Com ele, cresce o erro-padrão.</li>
<li><strong>A razão despenca.</strong> Com o numerador menor e o denominador maior, <em>t</em> cai de 3,77 para 1,78, e o <em>p</em>-valor sobe de 0,0014 para 0,085.</li>
</ol>
<p>O teste <strong>deixa de detectar</strong> a diferença ao nível de 5%. A diferença de medianas, por outro lado, quase não se altera (de 5,50 para 5,25 mpg), porque a mediana depende apenas da ordenação dos valores.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Diagnostique com boxplots <strong>antes</strong> de testar. Diante de valores atípicos, considere corrigir valores sentinela ou erros de registro, aplicar uma transformação como <span class="math inline">\(\log(x)\)</span>, vista na Aula 6, ou usar uma permutação sobre a diferença de medianas.</p>
</div>
</div>
</section>
<section id="permutação-e-teste-t" class="level2">
<h2 class="anchored" data-anchor-id="permutação-e-teste-t">5.6 Permutação e teste <em>t</em></h2>
<p>Os dois métodos respondem à mesma pergunta por caminhos diferentes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimensão</th>
<th>Permutação (não paramétrico)</th>
<th>Teste <em>t</em> (paramétrico)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Premissas</td>
<td>Livre de distribuição. Exige apenas intercambialidade sob <span class="math inline">\(H_0\)</span></td>
<td>Médias aproximadamente normais. Escala contínua</td>
</tr>
<tr class="even">
<td>Custo computacional</td>
<td>Milhares de reamostragens</td>
<td>Irrisório: fórmula fechada</td>
</tr>
<tr class="odd">
<td>Tamanho dos dados</td>
<td>Bom para amostras pequenas e dados assimétricos</td>
<td>Adequado para volumes moderados e grandes</td>
</tr>
<tr class="even">
<td>Interpretação</td>
<td>Frequência empírica do reordenamento aleatório</td>
<td>Posição de <em>t</em> em uma distribuição teórica</td>
</tr>
<tr class="odd">
<td>Flexibilidade</td>
<td>Qualquer estatística: média, mediana, razão</td>
<td>Diferença de médias</td>
</tr>
</tbody>
</table>
<div id="8bc28f95" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p-valores dos dois métodos nos dois exemplos</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame(</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">"permutação"</span>: [mpg_p, moon_p],</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"teste t (Welch)"</span>: [mpg_ttest.pvalue, moon_ttest.pvalue],</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>        },</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>        index<span class="op">=</span>[<span class="st">"mtcars"</span>, <span class="st">"Lua cheia"</span>],</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="85">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">permutação</th>
<th data-quarto-table-cell-role="th">teste t (Welch)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">mtcars</td>
<td>0.0001</td>
<td>0.0014</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Lua cheia</td>
<td>0.2300</td>
<td>0.1853</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Os valores não são idênticos, porque os dois métodos constroem a distribuição nula de formas diferentes. No <code>mtcars</code>, o teste <em>t</em> dá 0,0014 e a permutação, 0,0001. Duas razões explicam a distância. Com cerca de 18 graus de liberdade, a distribuição <em>t</em> tem caudas mais pesadas que a distribuição das permutações e atribui mais probabilidade a valores extremos. Além disso, o <em>p</em>-valor da permutação está no limite da sua resolução. Na lua cheia, os valores ficam próximos (0,23 e 0,19). As decisões, porém, coincidem nos dois exemplos.</p>
</section>
</section>
<section id="armadilhas-da-decisão" class="level1">
<h1>6. Armadilhas da decisão</h1>
<p>Um teste de hipóteses termina em uma decisão, e toda decisão tomada com dados incompletos pode errar. Esta seção trata de três armadilhas: os dois tipos de erro, a multiplicação de testes e a confusão entre significância estatística e relevância prática.</p>
<section id="dois-tipos-de-erro" class="level2">
<h2 class="anchored" data-anchor-id="dois-tipos-de-erro">6.1 Dois tipos de erro</h2>
<p>Como nunca sabemos se <span class="math inline">\(H_0\)</span> é verdadeira, há quatro combinações possíveis entre a realidade e a decisão:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(H_0\)</span> verdadeira</th>
<th><span class="math inline">\(H_0\)</span> falsa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Rejeitar <span class="math inline">\(H_0\)</span></strong></td>
<td>Erro do tipo I (<span class="math inline">\(\alpha\)</span>): falso positivo, “descobrir” um efeito que não existe</td>
<td>Decisão correta: poder estatístico (<span class="math inline">\(1 - \beta\)</span>)</td>
</tr>
<tr class="even">
<td><strong>Não rejeitar <span class="math inline">\(H_0\)</span></strong></td>
<td>Decisão correta: confiança (<span class="math inline">\(1 - \alpha\)</span>)</td>
<td>Erro do tipo II (<span class="math inline">\(\beta\)</span>): falso negativo, não detectar um efeito real</td>
</tr>
</tbody>
</table>
<p>Os dois erros têm consequências concretas nos exemplos da aula. No <code>mtcars</code>, os erros seriam: a) do tipo I, concluir que o câmbio manual economiza combustível quando a diferença era acaso; b) do tipo II, deixar passar um efeito pequeno, mas real, do câmbio, já que a amostra tem só 32 carros. Na lua cheia, seriam: a) do tipo I, reforçar a escala de plantão em toda lua cheia sem necessidade; b) do tipo II, não perceber um efeito pequeno da lua, caso ele existisse, porque 12 noites por ano são poucas para detectá-lo.</p>
<p>O nível de significância <span class="math inline">\(\alpha\)</span> é exatamente a taxa de erro do tipo I que aceitamos. Ao usar <span class="math inline">\(\alpha = 0{,}05\)</span>, admitimos que, entre os testes feitos sem efeito real, cerca de 5% levarão a uma rejeição apenas por acaso. O limiar define, por construção, a taxa de alarmes falsos.</p>
<p>O erro do tipo II depende de fatores que <span class="math inline">\(\alpha\)</span> não controla. O <strong>poder</strong> de um teste, <span class="math inline">\(1 - \beta\)</span>, é a probabilidade de rejeitar <span class="math inline">\(H_0\)</span> quando existe um efeito real, ou seja, de detectar o que de fato existe. Ele cresce com o tamanho do efeito e com a quantidade de dados. Efeitos grandes se destacam facilmente da oscilação do acaso. Efeitos pequenos só aparecem quando há observações suficientes para estreitar a distribuição nula. É por isso que um ano de dados, com apenas 12 noites de lua cheia, dificilmente detectaria um efeito pequeno da lua, mesmo que ele existisse.</p>
<p>Os dois erros estão em tensão. Reduzir <span class="math inline">\(\alpha\)</span> torna o critério mais exigente e diminui os falsos positivos, mas também dificulta a detecção de efeitos reais e aumenta <span class="math inline">\(\beta\)</span>. Para um <span class="math inline">\(\alpha\)</span> fixo, a forma de reduzir <span class="math inline">\(\beta\)</span> é <strong>aumentar <span class="math inline">\(n\)</span></strong>: com mais dados, o erro-padrão diminui, e o efeito se separa melhor do acaso.</p>
</section>
<section id="muitos-testes" class="level2">
<h2 class="anchored" data-anchor-id="muitos-testes">6.2 Muitos testes</h2>
<p>O nível <span class="math inline">\(\alpha\)</span> controla o erro de <strong>um</strong> teste. Quando fazemos muitos testes, os falsos positivos se acumulam. Imagine 20 pronto-socorros em que a lua não tem efeito, cada um testado com <span class="math inline">\(\alpha = 0{,}05\)</span>:</p>
<div id="d9f0ad89" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p-valores da lua cheia em 20 pronto-socorros sem efeito</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">7</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>hospital_p <span class="op">=</span> stats.ttest_ind(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    rng.poisson(<span class="dv">120</span>, size<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">12</span>)),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    rng.poisson(<span class="dv">120</span>, size<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">353</span>)),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    axis<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    equal_var<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>).pvalue</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O gráfico mostra o <em>p</em>-valor de cada pronto-socorro e o limiar <span class="math inline">\(\alpha = 0{,}05\)</span>:</p>
<div id="b502a1b2" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p-valor de cada pronto-socorro, com destaque para as rejeições</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.5</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>ax.bar(</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    np.arange(<span class="dv">1</span>, <span class="dv">21</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    hospital_p,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span>np.where(hospital_p <span class="op">&lt;=</span> <span class="fl">.05</span>, <span class="st">"#DD8452"</span>, <span class="st">"#A1C9F4"</span>),</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">.05</span>, color<span class="op">=</span><span class="st">"#1F4E79"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"20 pronto-socorros, nenhum efeito da lua"</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"Pronto-socorro"</span>,</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    ylabel<span class="op">=</span><span class="st">"p-valor"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    xticks<span class="op">=</span>np.arange(<span class="dv">1</span>, <span class="dv">21</span>),</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="07-inferencia-estatistica_files/figure-html/cell-28-output-1.png" width="849" height="320" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A barra laranja marca o único pronto-socorro em que o teste rejeitou <span class="math inline">\(H_0\)</span>, apenas por acaso. Um em 20 é exatamente o que <span class="math inline">\(\alpha = 0{,}05\)</span> prevê. Note que, sob <span class="math inline">\(H_0\)</span>, os <em>p</em>-valores se espalham por todo o intervalo entre 0 e 1. Valores pequenos aparecem de vez em quando, mesmo sem efeito algum.</p>
<p>A probabilidade de <strong>pelo menos um</strong> falso positivo em <span class="math inline">\(k\)</span> testes independentes sem efeito é o complemento da probabilidade de nenhum deles errar:</p>
<p><span class="math display">\[
P(\text{pelo menos um falso positivo}) = 1 - (1 - \alpha)^k
\]</span></p>
<p>Com 20 testes, <span class="math inline">\(1 - 0{,}95^{20} \approx 64\%\)</span>. Uma solução simples é a <strong>correção de Bonferroni</strong>: usar <span class="math inline">\(\alpha/k\)</span> como limiar em cada teste. A tabela compara as duas abordagens:</p>
<div id="f15d6d14" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="annotated-cell-28"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-28-1"><a href="#annotated-cell-28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidade de pelo menos um falso positivo em k testes sem efeito</span></span>
<span id="annotated-cell-28-2"><a href="#annotated-cell-28-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">.05</span></span>
<span id="annotated-cell-28-3"><a href="#annotated-cell-28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-28-4"><a href="#annotated-cell-28-4" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="annotated-cell-28-5"><a href="#annotated-cell-28-5" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame({<span class="st">"k"</span>: [<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">20</span>, <span class="dv">100</span>]})</span>
<span id="annotated-cell-28-6"><a href="#annotated-cell-28-6" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<span id="annotated-cell-28-7"><a href="#annotated-cell-28-7" aria-hidden="true" tabindex="-1"></a>        sem_correcao<span class="op">=</span><span class="kw">lambda</span> df: <span class="dv">1</span> <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> alpha) <span class="op">**</span> df[<span class="st">"k"</span>],</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-28" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-28-8" class="code-annotation-target"><a href="#annotated-cell-28-8" aria-hidden="true" tabindex="-1"></a>        bonferroni<span class="op">=</span><span class="kw">lambda</span> df: <span class="dv">1</span> <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> df[<span class="st">"k"</span>]) <span class="op">**</span> df[<span class="st">"k"</span>],</span>
<span id="annotated-cell-28-9"><a href="#annotated-cell-28-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-28-10"><a href="#annotated-cell-28-10" aria-hidden="true" tabindex="-1"></a>    .set_index(<span class="st">"k"</span>)</span>
<span id="annotated-cell-28-11"><a href="#annotated-cell-28-11" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="annotated-cell-28-12"><a href="#annotated-cell-28-12" aria-hidden="true" tabindex="-1"></a>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-28" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-28" data-code-lines="8" data-code-annotation="1">Na correção de Bonferroni, cada teste usa o limiar <span class="math inline">\(\alpha/k\)</span>. Com 20 testes, o limiar passa a ser 0,0025.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="88">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">sem_correcao</th>
<th data-quarto-table-cell-role="th">bonferroni</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">k</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>0.050</td>
<td>0.050</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>0.226</td>
<td>0.049</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>0.642</td>
<td>0.049</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">100</td>
<td>0.994</td>
<td>0.049</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Sem correção, a chance de pelo menos um alarme falso cresce rapidamente e chega a quase 100% com 100 testes. Com Bonferroni, ela fica em torno de 5%, qualquer que seja <span class="math inline">\(k\)</span>. O custo é um critério mais exigente para cada teste e, portanto, menos poder.</p>
<p>O problema não se restringe a vários hospitais. Ele aparece sempre que um analista testa muitas variáveis, muitos subgrupos ou muitas versões da mesma análise e relata apenas os resultados significantes. Essa prática, conhecida como <em>p-hacking</em>, é a falácia do atirador do Texas aplicada a testes de hipóteses: os tiros são os testes, e o alvo é desenhado em volta dos que deram <span class="math inline">\(p &lt; 0{,}05\)</span>.</p>
</section>
<section id="significância-estatística-não-é-relevância-prática" class="level2">
<h2 class="anchored" data-anchor-id="significância-estatística-não-é-relevância-prática">6.3 Significância estatística não é relevância prática</h2>
<p>O <em>p</em>-valor depende do tamanho da amostra. Isso decorre da própria estatística <em>t</em>. Para dois grupos de tamanho <span class="math inline">\(n\)</span> e um efeito de <span class="math inline">\(d\)</span> desvios-padrão, a estatística vale aproximadamente:</p>
<p><span class="math display">\[
t = d \sqrt{\frac{n}{2}}
\]</span></p>
<p>O efeito <span class="math inline">\(d\)</span> fica fixo, mas <span class="math inline">\(\sqrt{n}\)</span> cresce sem limite. Mesmo um efeito minúsculo acaba gerando um <em>t</em> grande quando <span class="math inline">\(n\)</span> é grande o bastante. A tabela mostra o <em>p</em>-valor de um mesmo efeito minúsculo, de 0,02 desvio-padrão, para tamanhos de amostra crescentes:</p>
<div id="ec86b64a" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="annotated-cell-29"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-29-1"><a href="#annotated-cell-29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p-valor de um efeito fixo de 0,02 desvio-padrão, por tamanho de grupo</span></span>
<span id="annotated-cell-29-2"><a href="#annotated-cell-29-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="annotated-cell-29-3"><a href="#annotated-cell-29-3" aria-hidden="true" tabindex="-1"></a>    pd.Series(</span>
<span id="annotated-cell-29-4"><a href="#annotated-cell-29-4" aria-hidden="true" tabindex="-1"></a>        {</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-29-5" class="code-annotation-target"><a href="#annotated-cell-29-5" aria-hidden="true" tabindex="-1"></a>            n: <span class="dv">2</span> <span class="op">*</span> stats.t.sf(<span class="fl">.02</span> <span class="op">*</span> np.sqrt(n <span class="op">/</span> <span class="dv">2</span>), df<span class="op">=</span><span class="dv">2</span> <span class="op">*</span> n <span class="op">-</span> <span class="dv">2</span>)</span>
<span id="annotated-cell-29-6"><a href="#annotated-cell-29-6" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> n <span class="kw">in</span> [<span class="dv">100</span>, <span class="dv">1_000</span>, <span class="dv">10_000</span>, <span class="dv">100_000</span>, <span class="dv">1_000_000</span>]</span>
<span id="annotated-cell-29-7"><a href="#annotated-cell-29-7" aria-hidden="true" tabindex="-1"></a>        },</span>
<span id="annotated-cell-29-8"><a href="#annotated-cell-29-8" aria-hidden="true" tabindex="-1"></a>        name<span class="op">=</span><span class="st">"p"</span>,</span>
<span id="annotated-cell-29-9"><a href="#annotated-cell-29-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-29-10"><a href="#annotated-cell-29-10" aria-hidden="true" tabindex="-1"></a>    .rename_axis(<span class="st">"n por grupo"</span>)</span>
<span id="annotated-cell-29-11"><a href="#annotated-cell-29-11" aria-hidden="true" tabindex="-1"></a>    .to_frame()</span>
<span id="annotated-cell-29-12"><a href="#annotated-cell-29-12" aria-hidden="true" tabindex="-1"></a>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-29" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="5" data-code-annotation="1"><code>.02 * np.sqrt(n / 2)</code> é a estatística <span class="math inline">\(t = d\sqrt{n/2}\)</span>, com <span class="math inline">\(d = 0{,}02\)</span>. <code>stats.t.sf</code> devolve a área da cauda direita da distribuição <em>t</em>, e multiplicamos por 2 porque o teste é bilateral.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="89">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">p</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">n por grupo</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">100</td>
<td>8.876809e-01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1000</td>
<td>6.547693e-01</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10000</td>
<td>1.573148e-01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">100000</td>
<td>7.748470e-06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1000000</td>
<td>2.099060e-45</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Com 100 ou 1.000 observações por grupo, o efeito é indistinguível do acaso. Com 100.000, o <em>p</em>-valor já é da ordem de <span class="math inline">\(10^{-6}\)</span>. Com um milhão, ele chega a cerca de <span class="math inline">\(10^{-45}\)</span>. O efeito não mudou em nenhuma linha da tabela: o que mudou foi apenas a capacidade de detectá-lo. Em grandes bases de dados, quase tudo se torna “significante”.</p>
<p>Por isso, além do <em>p</em>-valor, reporte o <strong>tamanho do efeito</strong>. Uma medida comum é o <em>d</em> de Cohen, a diferença de médias expressa em desvios-padrão:</p>
<p><span class="math display">\[
d = \frac{\bar{x}_A - \bar{x}_B}{s_{\text{combinado}}}
\]</span></p>
<p>Aqui, <span class="math inline">\(s_{\text{combinado}}\)</span> é um desvio-padrão comum aos dois grupos, obtido a partir de uma média das variâncias de cada grupo, ponderada pelos seus tamanhos. Assim como a estatística <em>t</em>, o <em>d</em> mede a diferença em uma régua sem unidade. A diferença está na régua escolhida. O <em>t</em> divide pelo erro-padrão, que encolhe com <span class="math inline">\(\sqrt{n}\)</span>. O <em>d</em> divide pelo desvio-padrão dos dados, que não depende de <span class="math inline">\(n\)</span>. Por isso, o <em>d</em> não cresce com o tamanho da amostra: ele mede o quanto os grupos estão separados em relação à variação típica dos dados.</p>
<p>Como referência, valores de <em>d</em> em torno de 0,2, 0,5 e 0,8 costumam ser descritos como efeitos pequenos, médios e grandes. No <code>mtcars</code>, <span class="math inline">\(d \approx 1{,}48\)</span>: as médias estão separadas por cerca de um desvio-padrão e meio, um efeito grande. O tamanho do efeito descreve a magnitude da diferença na amostra. O <em>p</em>-valor, por sua vez, informa se essa diferença se distingue do acaso. As duas informações se complementam, e nenhuma substitui a outra.</p>
<p>A pergunta final é se a diferença é <strong>acionável</strong>: grande o bastante e bem compreendida o bastante para orientar uma decisão. Uma economia de 7 milhas por galão representa cerca de 40% a mais de distância com o mesmo combustível, o que seria relevante para um comprador em 1974, logo após a crise do petróleo. Mas, como discute a Pergunta 2, saber que a diferença existe ainda não diz o que a causa.</p>
</section>
</section>
<section id="guia-rápido" class="level1">
<h1>7. Guia rápido</h1>
<p>A sequência abaixo responde à pergunta norteadora da aula.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Passo</th>
<th>Ação</th>
<th>Ferramenta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Medir</td>
<td>Calcular <span class="math inline">\(\Delta_{obs}\)</span> e inspecionar os grupos</td>
<td><code>groupby</code>, boxplot</td>
</tr>
<tr class="even">
<td>2. Duvidar</td>
<td>Formular <span class="math inline">\(H_0\)</span>: só há acaso</td>
<td>Hipóteses nula e alternativa</td>
</tr>
<tr class="odd">
<td>3. Simular</td>
<td>Construir a distribuição nula</td>
<td>Permutação ou distribuição <em>t</em></td>
</tr>
<tr class="even">
<td>4. Calcular</td>
<td>Obter o <em>p</em>-valor</td>
<td><code>np.mean(np.abs(null) &gt;= abs(obs))</code> ou <code>stats.ttest_ind</code></td>
</tr>
<tr class="odd">
<td>5. Decidir</td>
<td>Comparar <em>p</em> com <span class="math inline">\(\alpha\)</span>, corrigir para múltiplos testes, avaliar o tamanho do efeito e o contexto dos dados</td>
<td>Bonferroni, <em>d</em> de Cohen, contexto</td>
</tr>
</tbody>
</table>
<section id="síntese" class="level2">
<h2 class="anchored" data-anchor-id="síntese">Síntese</h2>
<ol type="1">
<li><strong>Efeito observado.</strong> <span class="math inline">\(\Delta_{obs}\)</span> descreve a amostra. Sozinho, não prova um efeito populacional, porque a variabilidade amostral gera diferenças mesmo sem efeito real.</li>
<li><strong>Hipótese nula.</strong> <span class="math inline">\(H_0\)</span> formaliza o acaso. Sob ela, os rótulos dos grupos são intercambiáveis.</li>
<li><strong>Distribuição nula.</strong> A permutação, por simulação, e o teste <em>t</em>, por fórmula, constroem a distribuição da estatística sob <span class="math inline">\(H_0\)</span>. O erro-padrão é a largura dessa distribuição.</li>
<li><strong>Decisão.</strong> <span class="math inline">\(p \leq \alpha\)</span> leva à rejeição de <span class="math inline">\(H_0\)</span>. Com muitos testes, o limiar precisa ser corrigido. Tamanho do efeito, valores atípicos e o contexto dos dados decidem o que concluir.</li>
</ol>
<p>Um efeito é “real” quando seria improvável sob o acaso. E só importa se for grande e não for explicado por outra variável.</p>
</section>
<section id="glossário" class="level2">
<h2 class="anchored" data-anchor-id="glossário">Glossário</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Termo</th>
<th>Definição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta_{obs}\)</span></td>
<td>Diferença entre as estatísticas, como as médias, dos grupos na amostra</td>
</tr>
<tr class="even">
<td>Erro-padrão (SE)</td>
<td>Variabilidade de uma estimativa entre amostras repetidas</td>
</tr>
<tr class="odd">
<td>Hipótese nula (<span class="math inline">\(H_0\)</span>)</td>
<td>Modelo cético: não há efeito, e a diferença é fruto do acaso</td>
</tr>
<tr class="even">
<td>Distribuição nula</td>
<td>Valores que a estatística assume quando <span class="math inline">\(H_0\)</span> é verdadeira</td>
</tr>
<tr class="odd">
<td><em>p</em>-valor</td>
<td>Probabilidade de um resultado tão ou mais extremo que o observado, supondo <span class="math inline">\(H_0\)</span></td>
</tr>
<tr class="even">
<td>Significância (<span class="math inline">\(\alpha\)</span>)</td>
<td>Limiar fixado antes da análise. Risco aceito de falso positivo</td>
</tr>
<tr class="odd">
<td>Poder (<span class="math inline">\(1 - \beta\)</span>)</td>
<td>Probabilidade de detectar um efeito que de fato existe</td>
</tr>
<tr class="even">
<td>Correção de Bonferroni</td>
<td>Uso de <span class="math inline">\(\alpha/k\)</span> como limiar em cada um de <span class="math inline">\(k\)</span> testes, para controlar a chance de algum falso positivo</td>
</tr>
<tr class="odd">
<td><em>d</em> de Cohen</td>
<td>Diferença de médias expressa em desvios-padrão. Mede o tamanho do efeito</td>
</tr>
<tr class="even">
<td>Confundidor</td>
<td>Variável que afeta o grupo e o desfecho, criando associação sem causa</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="perguntas-para-consolidar" class="level1">
<h1>Perguntas para consolidar</h1>
<section id="pergunta-1-o-que-o-p-valor-da-lua-cheia-diz-e-o-que-não-diz" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-1-o-que-o-p-valor-da-lua-cheia-diz-e-o-que-não-diz">Pergunta 1: o que o <em>p</em>-valor da lua cheia diz, e o que não diz?</h2>
<p>Na lua cheia, <span class="math inline">\(p \approx 0{,}23\)</span>. Um colega conclui: “há 23% de chance de a lua não ter efeito”. A frase está correta?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Não. O <em>p</em>-valor é calculado <strong>supondo</strong> que <span class="math inline">\(H_0\)</span> seja verdadeira. Ele diz que, se a lua não tivesse efeito, cerca de 23% dos sorteios de 12 dias produziriam uma diferença pelo menos tão grande quanto a observada. Ele não atribui uma probabilidade à própria <span class="math inline">\(H_0\)</span>.</p>
<p>Também não podemos concluir que a lua não tem efeito. Não rejeitar <span class="math inline">\(H_0\)</span> significa apenas que os dados são compatíveis com o acaso. Como discutido na seção 6.1, com apenas 12 noites por ano o teste tem pouco poder, e mesmo um efeito real, mas pequeno, poderia passar despercebido.</p>
</div>
</div>
</div>
</section>
<section id="pergunta-2-significativo-quer-dizer-correto" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-2-significativo-quer-dizer-correto">Pergunta 2: significativo quer dizer correto?</h2>
<p>No <code>mtcars</code>, a permutação deu <span class="math inline">\(p &lt; 0{,}001\)</span>. Isso significa que trocar o câmbio de um carro faria ele economizar combustível?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Não. O teste mostra que a diferença entre os grupos dificilmente é acaso, mas não identifica sua causa. Os manuais da amostra são, em sua maioria, compactos importados, enquanto os automáticos são, em grande parte, sedãs grandes e pesados. Carros mais leves consomem menos, qualquer que seja o câmbio. O peso, a potência e o número de cilindros também separam os grupos. Uma variável que afeta tanto o grupo quanto o desfecho, criando uma associação sem relação causal direta, é chamada de <strong>confundidor</strong>.</p>
<p>Para atribuir um efeito causal, seria necessário comparar carros semelhantes em tudo, exceto no câmbio. Um experimento controlado faria isso por construção. Com dados observacionais, só podemos ajustar pelos confundidores que medimos.</p>
</div>
</div>
</div>
</section>
<section id="pergunta-3-quando-permutação-e-teste-t-discordam" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-3-quando-permutação-e-teste-t-discordam">Pergunta 3: quando permutação e teste <em>t</em> discordam?</h2>
<p>Nos dois exemplos, os métodos levaram à mesma decisão. Em que situação você esperaria que eles discordassem, e em qual confiaria mais?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>O teste <em>t</em> supõe que a diferença de médias seja aproximadamente normal. Isso é razoável com amostras moderadas ou grandes, pelo teorema central do limite. Com amostras pequenas e distribuições muito assimétricas ou com valores atípicos, a aproximação pode falhar, e o <em>p</em>-valor do teste <em>t</em> fica impreciso.</p>
<p>A permutação exige apenas que os rótulos sejam intercambiáveis sob <span class="math inline">\(H_0\)</span>. Ela continua válida nesses casos e ainda permite trocar a estatística, por exemplo pela diferença de medianas. Em contrapartida, ambos os métodos supõem observações independentes. Nenhum dos dois é adequado, sem adaptação, para dados pareados ou séries temporais.</p>
</div>
</div>
</div>
</section>
</section>
<section id="para-casa" class="level1">
<h1>Para casa</h1>
<ol type="1">
<li>Adapte <code>permutation_null</code> para usar a diferença de <strong>medianas</strong>. Aplique-a ao cenário com o automático de 60 mpg e compare o <em>p</em>-valor com o do teste <em>t</em> da seção 5.5.</li>
<li>Na base de imóveis da Aula 6, compare o aluguel de imóveis mobiliados e não mobiliados. Calcule <span class="math inline">\(\Delta_{obs}\)</span> e o <em>p</em>-valor por permutação e pelo teste <em>t</em>. Repita a análise com o <span class="math inline">\(\log\)</span> do aluguel e discuta as diferenças.</li>
<li>Ainda na base de imóveis, a diferença de aluguel entre mobiliados e não mobiliados poderia ser explicada por outra variável? Proponha um confundidor e verifique sua hipótese com um gráfico.</li>
<li>Antes de considerar o notebook pronto, use Restart Kernel and Run All.</li>
</ol>
<section id="referências" class="level2">
<h2 class="anchored" data-anchor-id="referências">Referências</h2>
<ol type="1">
<li>Adhikari, A.; DeNero, J.; Wagner, D. <em>Computational and Inferential Thinking: The Foundations of Data Science</em>. 2. ed.&nbsp;UC Berkeley. <a href="https://inferentialthinking.com">inferentialthinking.com</a></li>
<li>Bruce, P.; Bruce, A.; Gedeck, P. <em>Practical Statistics for Data Scientists</em>. 2. ed.&nbsp;O’Reilly, 2020.</li>
<li>Student. The probable error of a mean. <em>Biometrika</em>, 6(1), 1-25, 1908.</li>
<li>Welch, B. L. The generalization of “Student’s” problem when several different population variances are involved. <em>Biometrika</em>, 34(1-2), 28-35, 1947.</li>
<li>Wasserstein, R. L.; Lazar, N. A. The ASA statement on p-values: context, process, and purpose. <em>The American Statistician</em>, 70(2), 129-133, 2016.</li>
<li>Fisher, R. A. <em>The Design of Experiments</em>. Edinburgh: Oliver &amp; Boyd, 1935.</li>
<li>Rotton, J.; Kelly, I. W. Much ado about the full moon: a meta-analysis of lunar-lunacy research. <em>Psychological Bulletin</em>, 97(2), 286-306, 1985.</li>
<li>Henderson, H. V.; Velleman, P. F. Building multiple regression models interactively. <em>Biometrics</em>, 37(2), 391-411, 1981.</li>
</ol>
<blockquote class="blockquote">
<p>Pode-se dizer que todo experimento existe apenas para dar aos fatos a chance de refutar a hipótese nula. (R. A. Fisher, <em>The Design of Experiments</em>, 1935, tradução livre)</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/oandrefonseca\.github\.io\/data-science\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/oandrefonseca/data-science/blob/main/aulas/07-inferencia-estatistica.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/oandrefonseca/data-science/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></div></div></footer></body></html>