<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Aula 8 - Testes Paramétricos – Ciência de Dados</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-31c5116dce638bf40351868cd08965ef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ba99d7a9af36e81ac0abe239f9976969.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../aulas/01-ferramentas-ambiente-versionamento.html">Roteiros de aula</a></li><li class="breadcrumb-item"><a href="../aulas/08-testes-parametricos.html">8. Testes Paramétricos</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Ciência de Dados</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ciência de Dados</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Roteiros de aula</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/01-ferramentas-ambiente-versionamento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Ferramentas, Ambiente e Versionamento</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/02-introducao-dados-tabulares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Introdução aos Dados Tabulares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/03-analise-vendas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Análise de Vendas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/04-analise-vendas-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Análise de Vendas em R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/05-estatistica-descritiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Estatística Descritiva</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/06-imputacao-normalizacao-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Imputação e Normalização de Dados</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/07-inferencia-estatistica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Inferência Estatística</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../aulas/08-testes-parametricos.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">8. Testes Paramétricos</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#motivação" id="toc-motivação" class="nav-link active" data-scroll-target="#motivação">Motivação</a></li>
  <li><a href="#objetivos-de-aprendizagem" id="toc-objetivos-de-aprendizagem" class="nav-link" data-scroll-target="#objetivos-de-aprendizagem">Objetivos de aprendizagem</a></li>
  <li><a href="#preparando-os-dados" id="toc-preparando-os-dados" class="nav-link" data-scroll-target="#preparando-os-dados">1. Preparando os dados</a></li>
  <li><a href="#o-que-um-teste-paramétrico-exige" id="toc-o-que-um-teste-paramétrico-exige" class="nav-link" data-scroll-target="#o-que-um-teste-paramétrico-exige">2. O que um teste paramétrico exige</a>
  <ul class="collapse">
  <li><a href="#a-curva-teórica-e-sua-largura" id="toc-a-curva-teórica-e-sua-largura" class="nav-link" data-scroll-target="#a-curva-teórica-e-sua-largura">2.1 A curva teórica e sua largura</a></li>
  <li><a href="#as-três-premissas-clássicas" id="toc-as-três-premissas-clássicas" class="nav-link" data-scroll-target="#as-três-premissas-clássicas">2.2 As três premissas clássicas</a></li>
  <li><a href="#verificando-a-normalidade" id="toc-verificando-a-normalidade" class="nav-link" data-scroll-target="#verificando-a-normalidade">2.3 Verificando a normalidade</a></li>
  <li><a href="#o-tipo-de-variável" id="toc-o-tipo-de-variável" class="nav-link" data-scroll-target="#o-tipo-de-variável">2.4 O tipo de variável</a></li>
  <li><a href="#amostras-independentes-ou-pareadas" id="toc-amostras-independentes-ou-pareadas" class="nav-link" data-scroll-target="#amostras-independentes-ou-pareadas">2.5 Amostras independentes ou pareadas</a></li>
  <li><a href="#três-perguntas-escolhem-o-teste" id="toc-três-perguntas-escolhem-o-teste" class="nav-link" data-scroll-target="#três-perguntas-escolhem-o-teste">2.6 Três perguntas escolhem o teste</a></li>
  <li><a href="#intervalo-de-confiança" id="toc-intervalo-de-confiança" class="nav-link" data-scroll-target="#intervalo-de-confiança">2.7 Intervalo de confiança</a></li>
  </ul></li>
  <li><a href="#sete-casos-sete-testes" id="toc-sete-casos-sete-testes" class="nav-link" data-scroll-target="#sete-casos-sete-testes">3. Sete casos, sete testes</a>
  <ul class="collapse">
  <li><a href="#caso-1.-teste-t-de-uma-amostra" id="toc-caso-1.-teste-t-de-uma-amostra" class="nav-link" data-scroll-target="#caso-1.-teste-t-de-uma-amostra">Caso 1. Teste <em>t</em> de uma amostra</a></li>
  <li><a href="#caso-2.-teste-t-de-welch" id="toc-caso-2.-teste-t-de-welch" class="nav-link" data-scroll-target="#caso-2.-teste-t-de-welch">Caso 2. Teste <em>t</em> de Welch</a></li>
  <li><a href="#caso-3.-teste-t-pareado" id="toc-caso-3.-teste-t-pareado" class="nav-link" data-scroll-target="#caso-3.-teste-t-pareado">Caso 3. Teste <em>t</em> pareado</a></li>
  <li><a href="#caso-4.-anova-one-way" id="toc-caso-4.-anova-one-way" class="nav-link" data-scroll-target="#caso-4.-anova-one-way">Caso 4. ANOVA one-way</a></li>
  <li><a href="#caso-5.-correlação-de-pearson" id="toc-caso-5.-correlação-de-pearson" class="nav-link" data-scroll-target="#caso-5.-correlação-de-pearson">Caso 5. Correlação de Pearson</a></li>
  <li><a href="#caso-6.-teste-z-de-duas-proporções" id="toc-caso-6.-teste-z-de-duas-proporções" class="nav-link" data-scroll-target="#caso-6.-teste-z-de-duas-proporções">Caso 6. Teste <em>Z</em> de duas proporções</a></li>
  <li><a href="#caso-7.-qui-quadrado-de-independência" id="toc-caso-7.-qui-quadrado-de-independência" class="nav-link" data-scroll-target="#caso-7.-qui-quadrado-de-independência">Caso 7. Qui-quadrado de independência</a></li>
  </ul></li>
  <li><a href="#quando-as-premissas-falham" id="toc-quando-as-premissas-falham" class="nav-link" data-scroll-target="#quando-as-premissas-falham">4. Quando as premissas falham</a></li>
  <li><a href="#guia-rápido" id="toc-guia-rápido" class="nav-link" data-scroll-target="#guia-rápido">5. Guia rápido</a>
  <ul class="collapse">
  <li><a href="#síntese" id="toc-síntese" class="nav-link" data-scroll-target="#síntese">Síntese</a></li>
  </ul></li>
  <li><a href="#perguntas-para-consolidar" id="toc-perguntas-para-consolidar" class="nav-link" data-scroll-target="#perguntas-para-consolidar">Perguntas para consolidar</a>
  <ul class="collapse">
  <li><a href="#pergunta-1-por-que-o-pareamento-mudou-o-resultado-do-sleep" id="toc-pergunta-1-por-que-o-pareamento-mudou-o-resultado-do-sleep" class="nav-link" data-scroll-target="#pergunta-1-por-que-o-pareamento-mudou-o-resultado-do-sleep">Pergunta 1: por que o pareamento mudou o resultado do <code>sleep</code>?</a></li>
  <li><a href="#pergunta-2-não-rejeitar-h_0-no-caso-1-prova-que-a-frota-cumpre-a-meta" id="toc-pergunta-2-não-rejeitar-h_0-no-caso-1-prova-que-a-frota-cumpre-a-meta" class="nav-link" data-scroll-target="#pergunta-2-não-rejeitar-h_0-no-caso-1-prova-que-a-frota-cumpre-a-meta">Pergunta 2: não rejeitar <span class="math inline">\(H_0\)</span> no caso 1 prova que a frota cumpre a meta?</a></li>
  <li><a href="#pergunta-3-o-caso-6-precisava-de-um-teste-diferente-do-caso-7" id="toc-pergunta-3-o-caso-6-precisava-de-um-teste-diferente-do-caso-7" class="nav-link" data-scroll-target="#pergunta-3-o-caso-6-precisava-de-um-teste-diferente-do-caso-7">Pergunta 3: o caso 6 precisava de um teste diferente do caso 7?</a></li>
  </ul></li>
  <li><a href="#para-casa" id="toc-para-casa" class="nav-link" data-scroll-target="#para-casa">Para casa</a>
  <ul class="collapse">
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/oandrefonseca/data-science/blob/main/aulas/08-testes-parametricos.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/oandrefonseca/data-science/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="08-testes-parametricos.ipynb" download="08-testes-parametricos.ipynb"><i class="bi bi-journal-code"></i>Jupyter</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../aulas/01-ferramentas-ambiente-versionamento.html">Roteiros de aula</a></li><li class="breadcrumb-item"><a href="../aulas/08-testes-parametricos.html">8. Testes Paramétricos</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Aula 8 - Testes Paramétricos</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">6 de outubro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="motivação" class="level2">
<h2 class="anchored" data-anchor-id="motivação">Motivação</h2>
<p>Na Aula 7, construímos a distribuição nula de duas formas: embaralhando rótulos, no teste de permutação, e por fórmula, no teste <em>t</em> de Welch. Vimos também como ler o <em>p</em>-valor, como decidir com <span class="math inline">\(\alpha\)</span> e quais erros essa decisão pode cometer. Nesta aula, partimos desse ponto e respondemos a duas perguntas novas. <strong>Quando</strong> a distribuição nula pode vir de uma fórmula? E, diante de dados de natureza diferente, <strong>qual</strong> fórmula usar?</p>
<p>Um teste paramétrico troca a simulação por uma curva teórica: <em>t</em>, <em>F</em>, <em>Z</em> ou <span class="math inline">\(\chi^2\)</span>. Essa troca só é segura quando os dados cumprem certas premissas. A escolha da curva, por sua vez, depende do que medimos e de como as observações foram coletadas. A primeira parte do roteiro trata dessas condições. A segunda aplica sete testes a sete problemas reais, cada um com seu próprio conjunto de dados.</p>
<blockquote class="blockquote">
<p><strong>Qual teste responde à minha pergunta, e posso confiar nele?</strong></p>
</blockquote>
</section>
<section id="objetivos-de-aprendizagem" class="level2">
<h2 class="anchored" data-anchor-id="objetivos-de-aprendizagem">Objetivos de aprendizagem</h2>
<p>Ao final deste roteiro, você será capaz de:</p>
<ol type="1">
<li>Explicar o que torna um teste <em>paramétrico</em> e o que se ganha e se arrisca com ele.</li>
<li>Verificar normalidade, homocedasticidade e independência com Q-Q plot, Shapiro-Wilk e o desenho do estudo.</li>
<li>Escolher o teste pelo objetivo, pela escala da variável e pelo delineamento.</li>
<li>Aplicar em Python os testes <em>t</em> de uma amostra, de Welch e pareado, a ANOVA, a correlação de Pearson, o teste <em>Z</em> de duas proporções e o <span class="math inline">\(\chi^2\)</span> de independência.</li>
<li>Interpretar os resultados e reconhecer quando migrar para um teste não paramétrico.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como usar este roteiro
</div>
</div>
<div class="callout-body-container callout-body">
<p>O roteiro usa cinco conjuntos de dados, cada um salvo em <code>&lt;nome&gt;/data/</code>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Base</th>
<th>Origem</th>
<th>Casos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mtcars</code></td>
<td>Revista <em>Motor Trend</em>, 1974 (já usada na Aula 7)</td>
<td>1 e 5</td>
</tr>
<tr class="even">
<td><code>penguins</code></td>
<td>Pinguins do arquipélago Palmer, Antártida</td>
<td>2</td>
</tr>
<tr class="odd">
<td><code>sleep</code></td>
<td>Ensaio clínico com dois soníferos (Student, 1908)</td>
<td>3</td>
</tr>
<tr class="even">
<td><code>iris</code></td>
<td>Flores de três espécies de íris (Fisher, 1936)</td>
<td>4</td>
</tr>
<tr class="odd">
<td><code>titanic</code></td>
<td>Passageiros do naufrágio do Titanic, 1912</td>
<td>2.3, 6 e 7</td>
</tr>
</tbody>
</table>
<p>Além das bibliotecas da Aula 7, usamos o <code>statsmodels</code> no caso 6.</p>
</div>
</div>
</section>
<section id="preparando-os-dados" class="level1">
<h1>1. Preparando os dados</h1>
<p>Começamos com as bibliotecas e as cinco bases. Cada caso usa apenas algumas colunas, apresentadas quando o caso começar.</p>
<div id="9b11c7ae" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importa as bibliotecas e define o tema dos gráficos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> proportions_ztest, proportion_confint</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>, palette<span class="op">=</span><span class="st">"colorblind"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="9174acac" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega as cinco bases</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="op">=</span> pd.read_csv(<span class="st">"mtcars/data/mtcars.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>penguins <span class="op">=</span> pd.read_csv(<span class="st">"penguins/data/penguins.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>sleep <span class="op">=</span> pd.read_csv(<span class="st">"sleep/data/sleep.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>iris <span class="op">=</span> pd.read_csv(<span class="st">"iris/data/iris.csv"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>titanic <span class="op">=</span> pd.read_csv(<span class="st">"titanic/data/titanic.csv"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As cinco bases têm tamanhos bem diferentes, do ensaio clínico com 20 registros ao Titanic com quase 900 passageiros:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Base</th>
<th>Linhas</th>
<th>Colunas</th>
<th>Cada linha representa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mtcars</code></td>
<td>32</td>
<td>12</td>
<td>Um modelo de carro</td>
</tr>
<tr class="even">
<td><code>penguins</code></td>
<td>344</td>
<td>8</td>
<td>Um pinguim</td>
</tr>
<tr class="odd">
<td><code>sleep</code></td>
<td>20</td>
<td>3</td>
<td>Um paciente com uma das duas drogas</td>
</tr>
<tr class="even">
<td><code>iris</code></td>
<td>150</td>
<td>5</td>
<td>Uma flor</td>
</tr>
<tr class="odd">
<td><code>titanic</code></td>
<td>891</td>
<td>15</td>
<td>Um passageiro</td>
</tr>
</tbody>
</table>
<p>O tamanho da amostra influencia diretamente as decisões desta aula. Com 20 registros, a normalidade precisa ser verificada com cuidado. Com centenas, o teorema central do limite torna o teste <em>t</em> robusto, mas o Shapiro-Wilk passa a rejeitar desvios pequenos.</p>
</section>
<section id="o-que-um-teste-paramétrico-exige" class="level1">
<h1>2. O que um teste paramétrico exige</h1>
<section id="a-curva-teórica-e-sua-largura" class="level2">
<h2 class="anchored" data-anchor-id="a-curva-teórica-e-sua-largura">2.1 A curva teórica e sua largura</h2>
<p>Um teste paramétrico não simula a distribuição nula: ele supõe que os dados seguem uma família conhecida, como a normal, e lê o <em>p</em>-valor como uma área sob uma curva teórica. No caso de uma média, a estatística e a largura da curva são:</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{SE}
\qquad\qquad
SE = \frac{s}{\sqrt{n}}
\]</span></p>
<p>Aqui, <span class="math inline">\(\mu_0\)</span> é o valor de referência sob <span class="math inline">\(H_0\)</span>. Sob <span class="math inline">\(H_0\)</span>, <em>t</em> segue a distribuição <em>t</em> de Student com <span class="math inline">\(n - 1\)</span> graus de liberdade.</p>
<p>O erro-padrão decide se uma diferença é grande ou pequena. Considere a mesma diferença de 1,5 unidade em duas amostras de 20 observações, uma com dados pouco dispersos (<span class="math inline">\(SE = 0{,}52\)</span>) e outra com dados muito dispersos (<span class="math inline">\(SE = 1{,}29\)</span>). Na <a href="#fig-same-diff" class="quarto-xref">Figura&nbsp;1</a>, a diferença está na mesma posição nos dois painéis. O que muda é a largura da curva ao redor dela.</p>
<div id="cell-fig-same-diff" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-same-diff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-same-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-testes-parametricos_files/figure-html/fig-same-diff-output-1.png" width="1041" height="350" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-same-diff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: A mesma diferença observada (1,5 unidade, linha laranja) diante de duas distribuições nulas com larguras diferentes. As áreas sombreadas são as diferenças tão ou mais extremas que a observada, nos dois sentidos. Com erro-padrão pequeno (esquerda), elas somam cerca de 1%. Com erro-padrão grande (direita), cerca de 26%.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Dividindo a diferença pelo erro-padrão, os dois cenários vão para a mesma régua (<a href="#fig-t-scale" class="quarto-xref">Figura&nbsp;2</a>). O primeiro dá <span class="math inline">\(t = 2{,}88\)</span> e cai na região de rejeição (<span class="math inline">\(p \approx 0{,}01\)</span>). O segundo dá <span class="math inline">\(t = 1{,}16\)</span> e cai no miolo da curva (<span class="math inline">\(p \approx 0{,}26\)</span>).</p>
<div id="cell-fig-t-scale" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-t-scale" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-scale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-testes-parametricos_files/figure-html/fig-t-scale-output-1.png" width="753" height="349" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-scale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Os dois cenários na escala da estatística <em>t</em>, sobre a distribuição <em>t</em> com 19 graus de liberdade. As áreas sombreadas formam a região de rejeição para α = 0,05. O valor t = 2,88 (erro-padrão pequeno) cai na cauda e leva à rejeição de H₀. O valor t = 1,16 (erro-padrão grande) cai no miolo.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A diferença é a mesma, mas as conclusões são opostas. E nenhuma das duas merece confiança se as premissas do teste não valerem.</p>
</section>
<section id="as-três-premissas-clássicas" class="level2">
<h2 class="anchored" data-anchor-id="as-três-premissas-clássicas">2.2 As três premissas clássicas</h2>
<p>Premissas violadas distorcem o erro-padrão e a forma da distribuição nula. Na prática, o <span class="math inline">\(\alpha\)</span> de 5% deixa de ser 5%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Premissa</th>
<th>O que afirma</th>
<th>Se falhar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Normalidade</strong></td>
<td>A resposta, ou os resíduos do modelo, segue uma distribuição normal na população</td>
<td>A distribuição da estatística muda, e o <em>p</em>-valor se descalibra em amostras pequenas</td>
</tr>
<tr class="even">
<td><strong>Homocedasticidade</strong></td>
<td>A variância é a mesma em todos os grupos: <span class="math inline">\(\sigma_1^2 = \sigma_2^2 = \dots\)</span></td>
<td>O erro-padrão combinado fica errado. A solução é a versão de Welch</td>
</tr>
<tr class="odd">
<td><strong>Independência</strong></td>
<td>A medida de uma unidade não influencia as demais</td>
<td>Nenhum ajuste de fórmula resolve. É preciso mudar o desenho do teste, por exemplo para o pareado</td>
</tr>
</tbody>
</table>
<p>A independência é a premissa mais crítica e também a única que não se verifica olhando os dados: ela depende de <strong>como</strong> foram coletados. A homocedasticidade se verifica comparando os desvios-padrão dos grupos ou com o teste de Levene, que aparecerá nos casos 2 e 4. A normalidade tem ferramentas próprias, apresentadas a seguir.</p>
</section>
<section id="verificando-a-normalidade" class="level2">
<h2 class="anchored" data-anchor-id="verificando-a-normalidade">2.3 Verificando a normalidade</h2>
<p>Há dois instrumentos complementares:</p>
<ul>
<li><strong>Diagnóstico gráfico.</strong> O histograma com a curva normal revela assimetria, bimodalidade e valores atípicos. O <strong>Q-Q plot</strong> compara os quantis da amostra com os quantis esperados de uma normal. Se os dados forem normais, os pontos seguem uma reta.</li>
<li><strong>Teste formal.</strong> O <strong>Shapiro-Wilk</strong> testa <span class="math inline">\(H_0\)</span>: os dados vêm de uma normal. A estatística <span class="math inline">\(W\)</span> varia de 0 a 1, e valores próximos de 1 indicam forma próxima da normal. Se <span class="math inline">\(p &lt; \alpha\)</span>, rejeitamos a normalidade.</li>
</ul>
<p>O gráfico mostra <strong>como</strong> os dados fogem da normal. O teste diz <strong>se</strong> o desvio é maior que o esperado pelo acaso. Cada forma de distribuição deixa uma assinatura típica no Q-Q plot:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Forma da distribuição</th>
<th>Assinatura no Q-Q plot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normal</td>
<td>Pontos sobre a reta</td>
</tr>
<tr class="even">
<td>Assimetria à direita</td>
<td>Curva em U: as duas pontas acima da reta</td>
</tr>
<tr class="odd">
<td>Assimetria à esquerda</td>
<td>Arco (∩): as duas pontas abaixo da reta</td>
</tr>
<tr class="even">
<td>Caudas pesadas</td>
<td>Forma de S: as pontas fogem da reta em sentidos opostos</td>
</tr>
<tr class="odd">
<td>Caudas leves</td>
<td>S invertido: as pontas achatadas</td>
</tr>
<tr class="even">
<td>Bimodal</td>
<td>Degrau no meio: faltam observações no centro</td>
</tr>
</tbody>
</table>
<p>Vejamos dois casos reais: o consumo dos carros do <code>mtcars</code> e o preço das passagens do Titanic.</p>
<div id="9b569e09" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="annotated-cell-3"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-3-1"><a href="#annotated-cell-3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q-Q plot e Shapiro-Wilk em duas variáveis reais</span></span>
<span id="annotated-cell-3-2"><a href="#annotated-cell-3-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="annotated-cell-3-3"><a href="#annotated-cell-3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-3-4"><a href="#annotated-cell-3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, values, title <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="annotated-cell-3-5"><a href="#annotated-cell-3-5" aria-hidden="true" tabindex="-1"></a>    axes,</span>
<span id="annotated-cell-3-6"><a href="#annotated-cell-3-6" aria-hidden="true" tabindex="-1"></a>    [mtcars[<span class="st">"mpg"</span>], titanic[<span class="st">"fare"</span>]],</span>
<span id="annotated-cell-3-7"><a href="#annotated-cell-3-7" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"mtcars · mpg (n = 32)"</span>, <span class="st">"titanic · fare (n = 891)"</span>],</span>
<span id="annotated-cell-3-8"><a href="#annotated-cell-3-8" aria-hidden="true" tabindex="-1"></a>):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-3-9" class="code-annotation-target"><a href="#annotated-cell-3-9" aria-hidden="true" tabindex="-1"></a>    stats.probplot(values, dist<span class="op">=</span><span class="st">"norm"</span>, plot<span class="op">=</span>ax)</span>
<span id="annotated-cell-3-10"><a href="#annotated-cell-3-10" aria-hidden="true" tabindex="-1"></a>    ax.<span class="bu">set</span>(title<span class="op">=</span>title, xlabel<span class="op">=</span><span class="st">"Quantil teórico da normal"</span>,</span>
<span id="annotated-cell-3-11"><a href="#annotated-cell-3-11" aria-hidden="true" tabindex="-1"></a>           ylabel<span class="op">=</span><span class="st">"Quantil da amostra"</span>)</span>
<span id="annotated-cell-3-12"><a href="#annotated-cell-3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-3-13"><a href="#annotated-cell-3-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-3-14"><a href="#annotated-cell-3-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="annotated-cell-3-15"><a href="#annotated-cell-3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-3-16"><a href="#annotated-cell-3-16" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(</span>
<span id="annotated-cell-3-17"><a href="#annotated-cell-3-17" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="annotated-cell-3-18"><a href="#annotated-cell-3-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mpg"</span>: stats.shapiro(mtcars[<span class="st">"mpg"</span>]),</span>
<span id="annotated-cell-3-19"><a href="#annotated-cell-3-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"fare"</span>: stats.shapiro(titanic[<span class="st">"fare"</span>]),</span>
<span id="annotated-cell-3-20"><a href="#annotated-cell-3-20" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="annotated-cell-3-21"><a href="#annotated-cell-3-21" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span>[<span class="st">"W"</span>, <span class="st">"p"</span>],</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-3-22" class="code-annotation-target"><a href="#annotated-cell-3-22" aria-hidden="true" tabindex="-1"></a>).T</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="9" data-code-annotation="1"><code>stats.probplot</code> ordena os valores e os compara com os quantis de uma normal. Com <code>plot=ax</code>, desenha os pontos e a reta de referência.</span>
</dd>
<dt data-target-cell="annotated-cell-3" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="22" data-code-annotation="2"><code>stats.shapiro</code> devolve a estatística <span class="math inline">\(W\)</span> e o <em>p</em>-valor.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-6-output-1.png" width="945" height="368" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">W</th>
<th data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">mpg</td>
<td>0.947565</td>
<td>1.228814e-01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">fare</td>
<td>0.521891</td>
<td>1.084044e-43</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Os dois diagnósticos concordam. No <code>mtcars</code>, os pontos seguem a reta, com um leve afastamento só na cauda direita. O Shapiro-Wilk dá <span class="math inline">\(W \approx 0{,}95\)</span> e <span class="math inline">\(p \approx 0{,}12\)</span>: não rejeitamos a normalidade. No Titanic, o Q-Q plot forma uma curva acentuada, a assinatura de forte assimetria à direita. Algumas tarifas ficam quase 10 desvios-padrão acima da média. O teste dá <span class="math inline">\(W \approx 0{,}52\)</span> e um <em>p</em>-valor praticamente zero.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cuidado com o tamanho da amostra
</div>
</div>
<div class="callout-body-container callout-body">
<p>Com <em>n</em> pequeno, o Shapiro-Wilk tem pouco poder e deixa passar desvios importantes. Com <em>n</em> grande, rejeita desvios irrelevantes. Por isso, a decisão nunca deve se apoiar só no <em>p</em>-valor do teste: olhe sempre o Q-Q plot. Lembre também que, pelo teorema central do limite, com amostras moderadas ou grandes o que precisa ser aproximadamente normal é a <strong>média</strong>, não cada observação.</p>
</div>
</div>
</section>
<section id="o-tipo-de-variável" class="level2">
<h2 class="anchored" data-anchor-id="o-tipo-de-variável">2.4 O tipo de variável</h2>
<p>Saber a forma da distribuição não basta. O teste também depende de <strong>o que</strong> medimos. A escala da variável resposta define quais operações fazem sentido e, portanto, quais testes podem ser aplicados:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Exemplo</th>
<th>Operações permitidas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Numérica contínua</td>
<td>Consumo em mpg (<code>mtcars</code>)</td>
<td>Média, desvio-padrão, todas as operações</td>
</tr>
<tr class="even">
<td>Numérica discreta</td>
<td>Número de carburadores (<code>mtcars</code>): 1, 2, 3, 4, 6 ou 8</td>
<td>Contagem, ordem, mediana, moda. Média com cautela</td>
</tr>
<tr class="odd">
<td>Categórica binária</td>
<td>Sobreviveu ou não (<code>titanic</code>)</td>
<td>Frequência e proporção</td>
</tr>
<tr class="even">
<td>Categórica ordinal</td>
<td>Escala Likert de 1 a 5, escolaridade</td>
<td>Ordenação, mediana, percentis</td>
</tr>
<tr class="odd">
<td>Categórica nominal</td>
<td>Espécie (<code>iris</code>, <code>penguins</code>), classe da cabine (<code>titanic</code>)</td>
<td>Contagem, moda, tabela de contingência</td>
</tr>
</tbody>
</table>
<p>Em uma variável ordinal, há ordem entre os níveis, mas a distância entre eles não é medida diretamente. Tratar uma escala Likert como contínua, sem justificativa, invalida o cálculo do erro-padrão.</p>
</section>
<section id="amostras-independentes-ou-pareadas" class="level2">
<h2 class="anchored" data-anchor-id="amostras-independentes-ou-pareadas">2.5 Amostras independentes ou pareadas</h2>
<p>O teste depende ainda de <strong>como</strong> as observações foram coletadas:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Independentes</th>
<th>Pareadas (dependentes)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exemplo</td>
<td>Massa de pinguins machos e fêmeas (<code>penguins</code>)</td>
<td>Sono dos mesmos pacientes com duas drogas (<code>sleep</code>)</td>
</tr>
<tr class="even">
<td>Foco</td>
<td>Diferença entre médias: <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span></td>
<td>Média das diferenças individuais: <span class="math inline">\(D = X_2 - X_1\)</span></td>
</tr>
<tr class="odd">
<td>Erro-padrão</td>
<td>Carrega a variação entre indivíduos</td>
<td>O pareamento cancela a variação de base de cada indivíduo</td>
</tr>
<tr class="even">
<td>Poder</td>
<td>Menor, para o mesmo <em>n</em></td>
<td>Maior: isola o efeito do tratamento</td>
</tr>
</tbody>
</table>
<p>A pergunta-chave é: <strong>saber o valor de uma observação diz algo sobre uma observação do outro grupo?</strong> Se sim, as amostras são pareadas. O caso 3 mostra o que acontece quando essa estrutura é ignorada.</p>
</section>
<section id="três-perguntas-escolhem-o-teste" class="level2">
<h2 class="anchored" data-anchor-id="três-perguntas-escolhem-o-teste">2.6 Três perguntas escolhem o teste</h2>
<p>A escolha do teste resulta de três perguntas, feitas nesta ordem:</p>
<ol type="1">
<li><strong>Qual o objetivo?</strong> Comparar médias, comparar proporções ou medir associação.</li>
<li><strong>Qual a escala?</strong> Da resposta e da variável explicativa: contínua, binária ou nominal.</li>
<li><strong>Qual o desenho?</strong> Uma amostra, dois grupos ou três ou mais; independentes ou pareados.</li>
</ol>
<p>Respondidas as três, o teste fica determinado, e resta verificar suas premissas. A matriz abaixo resume os sete casos desta aula:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo</th>
<th>Resposta</th>
<th>Explicativa e desenho</th>
<th>Teste</th>
<th>Caso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Média contra uma meta</td>
<td>Contínua</td>
<td>Nenhuma (valor <span class="math inline">\(\mu_0\)</span>)</td>
<td><em>t</em> de uma amostra</td>
<td>1 · <code>mtcars</code></td>
</tr>
<tr class="even">
<td>Médias de 2 grupos</td>
<td>Contínua</td>
<td>Binária, independentes</td>
<td><em>t</em> de Welch</td>
<td>2 · <code>penguins</code></td>
</tr>
<tr class="odd">
<td>Antes e depois</td>
<td>Contínua</td>
<td>2 momentos, pareados</td>
<td><em>t</em> pareado</td>
<td>3 · <code>sleep</code></td>
</tr>
<tr class="even">
<td>Médias de 3 ou mais grupos</td>
<td>Contínua</td>
<td>Nominal, independentes</td>
<td>ANOVA + Tukey</td>
<td>4 · <code>iris</code></td>
</tr>
<tr class="odd">
<td>Associação linear</td>
<td>Contínua</td>
<td>Contínua</td>
<td>Pearson</td>
<td>5 · <code>mtcars</code></td>
</tr>
<tr class="even">
<td>Proporções de 2 grupos</td>
<td>Binária</td>
<td>Binária, independentes</td>
<td><em>Z</em> de duas proporções</td>
<td>6 · <code>titanic</code></td>
</tr>
<tr class="odd">
<td>Associação entre categorias</td>
<td>Nominal</td>
<td>Nominal, independentes</td>
<td>Qui-quadrado</td>
<td>7 · <code>titanic</code></td>
</tr>
</tbody>
</table>
<p>Errar a escolha, por exemplo usando um teste para amostras independentes em dados pareados, ou vários testes <em>t</em> no lugar da ANOVA, altera as taxas de erro dos tipos I e II.</p>
</section>
<section id="intervalo-de-confiança" class="level2">
<h2 class="anchored" data-anchor-id="intervalo-de-confiança">2.7 Intervalo de confiança</h2>
<p>Outro conceito importante é o <strong>intervalo de confiança</strong>. Assim como o <em>p</em>-valor responde se um valor específico, o de <span class="math inline">\(H_0\)</span>, é compatível com os dados. O <strong>intervalo de confiança</strong> delimita: que valores do parâmetro são compatíveis com os dados. Em uma média, ele é construído a partir da estimativa e do erro-padrão:</p>
<p><span class="math display">\[
\bar{x} \pm t_{crit} \cdot SE
\]</span></p>
<p>Aqui, <span class="math inline">\(t_{crit}\)</span> é o valor crítico da distribuição <em>t</em> com <span class="math inline">\(n - 1\)</span> graus de liberdade, cerca de 2 para amostras moderadas. No caso 1, por exemplo, a média de 20,09 mpg, com erro-padrão de 1,07 mpg e <span class="math inline">\(t_{crit} = 2{,}04\)</span>, gera o intervalo de 95% de 17,9 a 22,3 mpg.</p>
<p>Três pontos orientam a leitura:</p>
<ul>
<li><strong>Interpretação.</strong> O “95%” descreve o método, não um intervalo específico. Se repetíssemos a coleta muitas vezes, 95% dos intervalos construídos dessa forma conteriam o valor verdadeiro do parâmetro. Não é correto dizer que há 95% de probabilidade de a média estar dentro de um intervalo já calculado.</li>
<li><strong>Largura.</strong> O intervalo é mais estreito quando o erro-padrão é menor: com mais dados ou dados menos dispersos, a estimativa fica mais precisa.</li>
<li><strong>Ligação com o teste.</strong> Um intervalo de 95% que <strong>não contém</strong> o valor de <span class="math inline">\(H_0\)</span> equivale a rejeitar <span class="math inline">\(H_0\)</span> com <span class="math inline">\(\alpha = 0{,}05\)</span> em um teste bilateral. Se o contém, não rejeitamos. A vantagem do intervalo é mostrar também o tamanho do efeito e a incerteza sobre ele.</li>
</ul>
<p>Nos casos a seguir, o intervalo é obtido com o método <code>.confidence_interval()</code>, disponível nos resultados dos testes <em>t</em> e da correlação de Pearson.</p>
</section>
</section>
<section id="sete-casos-sete-testes" class="level1">
<h1>3. Sete casos, sete testes</h1>
<p>Cada caso segue o mesmo roteiro: o cenário com as hipóteses, em destaque, as premissas do teste, o cálculo passo a passo, a verificação das premissas nos dados, o gráfico e a interpretação.</p>
<p>Antes de mais nada, as funções de teste do SciPy e do <code>statsmodels</code> devolvem objetos com vários campos, como <code>TtestResult(statistic=..., pvalue=..., df=...)</code>. Para ler os resultados com mais facilidade, usamos ao longo da aula uma função que resume cada teste em uma única linha:</p>
<div id="054d7d5e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="annotated-cell-4"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-4-1"><a href="#annotated-cell-4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resume o resultado de um teste em uma linha legível</span></span>
<span id="annotated-cell-4-2"><a href="#annotated-cell-4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report(name, result, stat<span class="op">=</span><span class="st">"estatística"</span>, df<span class="op">=</span><span class="va">None</span>):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-4-3" class="code-annotation-target"><a href="#annotated-cell-4-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(result, <span class="bu">tuple</span>):</span>
<span id="annotated-cell-4-4"><a href="#annotated-cell-4-4" aria-hidden="true" tabindex="-1"></a>        value, p <span class="op">=</span> result</span>
<span id="annotated-cell-4-5"><a href="#annotated-cell-4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="annotated-cell-4-6"><a href="#annotated-cell-4-6" aria-hidden="true" tabindex="-1"></a>        value, p <span class="op">=</span> result.statistic, result.pvalue</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-4-7" class="code-annotation-target"><a href="#annotated-cell-4-7" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df <span class="cf">if</span> df <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="bu">getattr</span>(result, <span class="st">"df"</span>, <span class="va">None</span>)</span>
<span id="annotated-cell-4-8"><a href="#annotated-cell-4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-4-9"><a href="#annotated-cell-4-9" aria-hidden="true" tabindex="-1"></a>    parts <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>stat<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>value<span class="sc">:.3f}</span><span class="ss">"</span>]</span>
<span id="annotated-cell-4-10"><a href="#annotated-cell-4-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> df <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="annotated-cell-4-11"><a href="#annotated-cell-4-11" aria-hidden="true" tabindex="-1"></a>        parts.append(<span class="ss">f"gl = </span><span class="sc">{</span>df<span class="sc">:.4g}</span><span class="ss">"</span> <span class="cf">if</span> np.isscalar(df) <span class="cf">else</span> <span class="ss">f"gl = </span><span class="sc">{</span>df<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-4-12"><a href="#annotated-cell-4-12" aria-hidden="true" tabindex="-1"></a>    parts.append(<span class="st">"p &lt; 0.001"</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.001</span> <span class="cf">else</span> <span class="ss">f"p = </span><span class="sc">{</span>p<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-4-13" class="code-annotation-target"><a href="#annotated-cell-4-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">hasattr</span>(result, <span class="st">"confidence_interval"</span>):</span>
<span id="annotated-cell-4-14"><a href="#annotated-cell-4-14" aria-hidden="true" tabindex="-1"></a>        ci <span class="op">=</span> result.confidence_interval()</span>
<span id="annotated-cell-4-15"><a href="#annotated-cell-4-15" aria-hidden="true" tabindex="-1"></a>        parts.append(<span class="ss">f"IC 95% [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.2f}</span><span class="ss"> ; </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="annotated-cell-4-16"><a href="#annotated-cell-4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-4-17"><a href="#annotated-cell-4-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">" · "</span>.join(parts))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-4" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="3" data-code-annotation="1">Algumas funções, como <code>proportions_ztest</code>, devolvem apenas uma tupla com a estatística e o <em>p</em>-valor.</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="7" data-code-annotation="2"><code>getattr</code> busca os graus de liberdade no resultado e devolve <code>None</code> quando o teste não os informa.</span>
</dd>
<dt data-target-cell="annotated-cell-4" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="13" data-code-annotation="3">Os testes <em>t</em> e a correlação de Pearson oferecem o método <code>.confidence_interval()</code>, que devolve o intervalo de confiança de 95%.</span>
</dd>
</dl>
</div>
</div>
<section id="caso-1.-teste-t-de-uma-amostra" class="level2">
<h2 class="anchored" data-anchor-id="caso-1.-teste-t-de-uma-amostra">Caso 1. Teste <em>t</em> de uma amostra</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>A gestão de uma frota pergunta se o consumo médio (<code>mpg</code>) dos veículos atende à meta de projeto de 20 mpg. Você tem os dados de 32 carros: a média deles basta para responder?</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: o consumo médio é igual à meta (<span class="math inline">\(\mu = 20\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: o consumo médio é diferente da meta (<span class="math inline">\(\mu \neq 20\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Observações independentes entre si.</li>
<li>Variável resposta numérica contínua.</li>
<li>Distribuição normal na população ou amostra grande o bastante para que a média seja aproximadamente normal, pelo teorema central do limite.</li>
</ul>
<p>Calculamos a estatística passo a passo, seguindo as fórmulas da seção 2.1:</p>
<div id="dec2005d" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="annotated-cell-5"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-5-1"><a href="#annotated-cell-5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t de uma amostra, passo a passo</span></span>
<span id="annotated-cell-5-2"><a href="#annotated-cell-5-2" aria-hidden="true" tabindex="-1"></a>mpg <span class="op">=</span> mtcars[<span class="st">"mpg"</span>]</span>
<span id="annotated-cell-5-3"><a href="#annotated-cell-5-3" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="dv">20</span></span>
<span id="annotated-cell-5-4"><a href="#annotated-cell-5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-5-5"><a href="#annotated-cell-5-5" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(mpg)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-5-6" class="code-annotation-target"><a href="#annotated-cell-5-6" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> mpg.std() <span class="op">/</span> np.sqrt(n)</span>
<span id="annotated-cell-5-7"><a href="#annotated-cell-5-7" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> (mpg.mean() <span class="op">-</span> target) <span class="op">/</span> se</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-5" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-5-8" class="code-annotation-target"><a href="#annotated-cell-5-8" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> stats.t.sf(<span class="bu">abs</span>(t), df<span class="op">=</span>n <span class="op">-</span> <span class="dv">1</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-5" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="6" data-code-annotation="1"><code>.std()</code> do pandas usa <span class="math inline">\(n - 1\)</span> no denominador, como a fórmula do desvio-padrão amostral.</span>
</dd>
<dt data-target-cell="annotated-cell-5" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-5" data-code-lines="8" data-code-annotation="2"><code>stats.t.sf</code> é a área da cauda direita da curva <em>t</em>. Multiplicamos por 2 porque o teste é bilateral.</span>
</dd>
</dl>
</div>
</div>
<div id="1dfb6458" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"média       = </span><span class="sc">{</span>mpg<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"dp          = </span><span class="sc">{</span>mpg<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"erro-padrão = </span><span class="sc">{</span>se<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t           = </span><span class="sc">{</span>t<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"gl          = </span><span class="sc">{</span>n <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p           = </span><span class="sc">{</span>p<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>média       = 20.091
dp          = 6.027
erro-padrão = 1.065
t           = 0.085
gl          = 31
p           = 0.933</code></pre>
</div>
</div>
<p>A média da frota, 20,09 mpg, fica só 0,09 mpg acima da meta. Como o erro-padrão é de 1,07 mpg, a diferença equivale a menos de um décimo de erro-padrão. A função do SciPy confirma o resultado e fornece o intervalo de confiança de 95% para a média:</p>
<div id="9728b3b9" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t de uma amostra com o SciPy</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>case1 <span class="op">=</span> stats.ttest_1samp(mpg, popmean<span class="op">=</span>target)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"t de uma amostra"</span>, case1, stat<span class="op">=</span><span class="st">"t"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t de uma amostra: t = 0.085 · gl = 31 · p = 0.933 · IC 95% [17.92 ; 22.26]</code></pre>
</div>
</div>
<p>O intervalo de confiança contém os valores de média compatíveis com os dados.</p>
<p>Quanto às premissas, os carros são modelos distintos, e a seção 2.3 já mostrou que o consumo passa no Shapiro-Wilk (<span class="math inline">\(p \approx 0{,}12\)</span>).</p>
<p>O gráfico mostra os carros, a média e o intervalo em relação à meta. A mesma visualização será usada no caso 3, por isso fica em uma função:</p>
<div id="ee4cf612" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="annotated-cell-8"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-8-1"><a href="#annotated-cell-8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pontos, média e intervalo de confiança em relação a um valor de referência</span></span>
<span id="annotated-cell-8-2"><a href="#annotated-cell-8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_mean_ci(values, ci, ref, xlabel, ax):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-8-3" class="code-annotation-target"><a href="#annotated-cell-8-3" aria-hidden="true" tabindex="-1"></a>    jitter <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>).uniform(<span class="fl">0.6</span>, <span class="fl">1.4</span>, <span class="bu">len</span>(values))</span>
<span id="annotated-cell-8-4"><a href="#annotated-cell-8-4" aria-hidden="true" tabindex="-1"></a>    ax.scatter(values, jitter, color<span class="op">=</span><span class="st">"#1F4E79"</span>, alpha<span class="op">=</span><span class="fl">.7</span>)</span>
<span id="annotated-cell-8-5"><a href="#annotated-cell-8-5" aria-hidden="true" tabindex="-1"></a>    error <span class="op">=</span> [[values.mean() <span class="op">-</span> ci.low], [ci.high <span class="op">-</span> values.mean()]]</span>
<span id="annotated-cell-8-6"><a href="#annotated-cell-8-6" aria-hidden="true" tabindex="-1"></a>    ax.errorbar(values.mean(), <span class="fl">0.2</span>, xerr<span class="op">=</span>error, fmt<span class="op">=</span><span class="st">"o"</span>, color<span class="op">=</span><span class="st">"#DD8452"</span>,</span>
<span id="annotated-cell-8-7"><a href="#annotated-cell-8-7" aria-hidden="true" tabindex="-1"></a>                ecolor<span class="op">=</span><span class="st">"#1F4E79"</span>, capsize<span class="op">=</span><span class="dv">6</span>, markersize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="annotated-cell-8-8"><a href="#annotated-cell-8-8" aria-hidden="true" tabindex="-1"></a>    ax.axvline(ref, color<span class="op">=</span><span class="st">"#333333"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="annotated-cell-8-9"><a href="#annotated-cell-8-9" aria-hidden="true" tabindex="-1"></a>    ax.<span class="bu">set</span>(xlabel<span class="op">=</span>xlabel, yticks<span class="op">=</span>[], ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">0.2</span>, <span class="fl">1.6</span>),</span>
<span id="annotated-cell-8-10"><a href="#annotated-cell-8-10" aria-hidden="true" tabindex="-1"></a>           title<span class="op">=</span><span class="ss">f"média </span><span class="sc">{</span>values<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss"> · IC 95% [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.2f}</span><span class="ss"> ; </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="annotated-cell-8-11"><a href="#annotated-cell-8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-8-12"><a href="#annotated-cell-8-12" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.5</span>))</span>
<span id="annotated-cell-8-13"><a href="#annotated-cell-8-13" aria-hidden="true" tabindex="-1"></a>plot_mean_ci(mpg, case1.confidence_interval(), target, <span class="st">"Consumo (mpg)"</span>, ax)</span>
<span id="annotated-cell-8-14"><a href="#annotated-cell-8-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-8-15"><a href="#annotated-cell-8-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-8" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="3" data-code-annotation="1">Os pontos recebem uma altura aleatória apenas para não se sobreporem. O eixo vertical não tem significado.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-11-output-1.png" width="752" height="320" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> Os carros se espalham dos dois lados da meta, de 10 a 34 mpg. A média (ponto laranja) cai praticamente sobre a linha tracejada, e o intervalo de confiança, de 17,9 a 22,3 mpg, contém a meta com folga. Se a média real da frota fosse 20 mpg, diferenças iguais ou maiores que a observada surgiriam em 93% das amostras (<span class="math inline">\(p \approx 0{,}93\)</span>). Não rejeitamos <span class="math inline">\(H_0\)</span>: não há evidência de que a frota esteja fora da meta. Isso, porém, não prova que <span class="math inline">\(\mu = 20\)</span>. Os dados são apenas compatíveis com a meta, como também seriam com qualquer valor dentro do intervalo.</p>
</section>
<section id="caso-2.-teste-t-de-welch" class="level2">
<h2 class="anchored" data-anchor-id="caso-2.-teste-t-de-welch">Caso 2. Teste <em>t</em> de Welch</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma equipe de biólogos de campo quer saber se machos e fêmeas de pinguins têm massas corporais (<code>body_mass</code>, em gramas) médias diferentes, um sinal de dimorfismo sexual. Cada grupo é formado por animais distintos.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: machos e fêmeas têm, em média, a mesma massa (<span class="math inline">\(\mu_1 = \mu_2\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: as massas médias são diferentes (<span class="math inline">\(\mu_1 \neq \mu_2\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Observações independentes, dentro de cada grupo e entre os grupos.</li>
<li>Variável resposta numérica contínua.</li>
<li>Distribuição normal em cada grupo ou amostras grandes o bastante para o teorema central do limite.</li>
<li>As variâncias dos grupos <strong>não</strong> precisam ser iguais. É isso que distingue a versão de Welch do teste <em>t</em> clássico.</li>
</ul>
<p>A base tem 344 pinguins, mas 11 não têm o sexo registrado. Ficamos com os 333 restantes:</p>
<div id="b308d7c9" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pinguins com sexo e massa registrados</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>penguins_sex <span class="op">=</span> penguins.dropna(subset<span class="op">=</span>[<span class="st">"sex"</span>, <span class="st">"body_mass"</span>])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>males <span class="op">=</span> penguins_sex.loc[penguins_sex[<span class="st">"sex"</span>] <span class="op">==</span> <span class="st">"male"</span>, <span class="st">"body_mass"</span>]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> penguins_sex.loc[penguins_sex[<span class="st">"sex"</span>] <span class="op">==</span> <span class="st">"female"</span>, <span class="st">"body_mass"</span>]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O teste de Welch usa a variância de cada grupo separadamente. A tabela traz a parcela <span class="math inline">\(s^2/n\)</span> de cada um, que mede a incerteza da média do grupo:</p>
<div id="9fd38188" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumo por grupo e parcelas do erro-padrão de Welch</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>welch_table <span class="op">=</span> (</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    penguins_sex</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"sex"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    .body_mass</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    .agg(n<span class="op">=</span><span class="st">"size"</span>, média<span class="op">=</span><span class="st">"mean"</span>, dp<span class="op">=</span><span class="st">"std"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    .assign(s2_n<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"dp"</span>] <span class="op">**</span> <span class="dv">2</span> <span class="op">/</span> df[<span class="st">"n"</span>])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>welch_table.<span class="bu">round</span>(<span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">média</th>
<th data-quarto-table-cell-role="th">dp</th>
<th data-quarto-table-cell-role="th">s2_n</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">sex</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">female</td>
<td>165</td>
<td>3862.3</td>
<td>666.2</td>
<td>2689.6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">male</td>
<td>168</td>
<td>4545.7</td>
<td>787.6</td>
<td>3692.6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="a8ec9b53" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-11-1"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Erro-padrão da diferença, estatística t e teste de Welch</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-2" class="code-annotation-target"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a>se_diff <span class="op">=</span> np.sqrt(welch_table[<span class="st">"s2_n"</span>].<span class="bu">sum</span>())</span>
<span id="annotated-cell-11-3"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a>t_manual <span class="op">=</span> (males.mean() <span class="op">-</span> females.mean()) <span class="op">/</span> se_diff</span>
<span id="annotated-cell-11-4"><a href="#annotated-cell-11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-5"><a href="#annotated-cell-11-5" aria-hidden="true" tabindex="-1"></a>case2 <span class="op">=</span> stats.ttest_ind(males, females, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="annotated-cell-11-6"><a href="#annotated-cell-11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-7"><a href="#annotated-cell-11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"erro-padrão da diferença = </span><span class="sc">{</span>se_diff<span class="sc">:.1f}</span><span class="ss"> g"</span>)</span>
<span id="annotated-cell-11-8"><a href="#annotated-cell-11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t calculado à mão = </span><span class="sc">{</span>t_manual<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-11-9"><a href="#annotated-cell-11-9" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"t de Welch"</span>, case2, stat<span class="op">=</span><span class="st">"t"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="2" data-code-annotation="1">O erro-padrão da diferença é a raiz da soma das duas parcelas <span class="math inline">\(s^2/n\)</span>. Cada grupo entra com a sua própria variância.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>erro-padrão da diferença = 79.9 g
t calculado à mão = 8.55
t de Welch: t = 8.555 · gl = 323.9 · p &lt; 0.001 · IC 95% [526.25 ; 840.58]</code></pre>
</div>
</div>
<p>Os machos pesam, em média, 4.546 g, e as fêmeas, 3.862 g: uma diferença de 683 g. O erro-padrão da diferença é de cerca de 80 g, e a diferença cabe 8,55 vezes nele. Os graus de liberdade, cerca de 324, vêm da correção de Welch-Satterthwaite, que ajusta a curva <em>t</em> quando as variâncias diferem.</p>
<p>Com mais de 160 animais por grupo, o teorema central do limite garante a normalidade das médias. E as variâncias, diferem? O teste de Levene verifica a homocedasticidade:</p>
<div id="fbb04903" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="annotated-cell-12"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-12-1"><a href="#annotated-cell-12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Homocedasticidade, intervalo da diferença e sobreposição dos grupos</span></span>
<span id="annotated-cell-12-2"><a href="#annotated-cell-12-2" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> case2.confidence_interval()</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-12-4" class="code-annotation-target"><a href="#annotated-cell-12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Levene: p = </span><span class="sc">{</span>stats<span class="sc">.</span>levene(males, females)<span class="sc">.</span>pvalue<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-12-5"><a href="#annotated-cell-12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"IC 95% da diferença: [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.0f}</span><span class="ss"> ; </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.0f}</span><span class="ss">] g"</span>)</span>
<span id="annotated-cell-12-6"><a href="#annotated-cell-12-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fêmeas acima do macho médio: </span><span class="sc">{</span>(females <span class="op">&gt;</span> males.mean())<span class="sc">.</span>mean()<span class="sc">:.0%}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="4" data-code-annotation="1">O teste de Levene tem <span class="math inline">\(H_0\)</span>: as variâncias dos grupos são iguais.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene: p = 0.014
IC 95% da diferença: [526 ; 841] g
fêmeas acima do macho médio: 25%</code></pre>
</div>
</div>
<p>O desvio-padrão dos machos (788 g) é maior que o das fêmeas (666 g), e o Levene rejeita a igualdade de variâncias (<span class="math inline">\(p \approx 0{,}014\)</span>). Esse é o motivo para usar a versão de Welch. O intervalo de confiança de 95% da diferença vai de 526 a 841 g, longe de zero.</p>
<p>O gráfico mostra cada pinguim e a média de cada grupo. Ele será reutilizado no caso 4, por isso fica em uma função:</p>
<div id="09a77db1" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observações e média de cada grupo</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_group_means(data, x, y, order, ylabel, ax):</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    sns.stripplot(data<span class="op">=</span>data, x<span class="op">=</span>x, y<span class="op">=</span>y, order<span class="op">=</span>order, ax<span class="op">=</span>ax,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                  color<span class="op">=</span><span class="st">"#1F4E79"</span>, alpha<span class="op">=</span><span class="fl">.5</span>, jitter<span class="op">=</span><span class="fl">.25</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    means <span class="op">=</span> data.groupby(x)[y].mean().reindex(order)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    ax.hlines(means, np.arange(<span class="bu">len</span>(order)) <span class="op">-</span> <span class="fl">.35</span>, np.arange(<span class="bu">len</span>(order)) <span class="op">+</span> <span class="fl">.35</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span><span class="st">"#DD8452"</span>, linewidth<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">""</span>, ylabel<span class="op">=</span>ylabel)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="c7f5f538" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="fl">4.5</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plot_group_means(penguins_sex, <span class="st">"sex"</span>, <span class="st">"body_mass"</span>, [<span class="st">"female"</span>, <span class="st">"male"</span>],</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Massa corporal (g)"</span>, ax)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="st">"Fêmeas"</span>, <span class="st">"Machos"</span>])</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-17-output-1.png" width="561" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> Os dois grupos se sobrepõem bastante: cerca de 25% das fêmeas pesam mais que o macho médio. Ainda assim, a média dos machos fica bem acima da média das fêmeas. Se machos e fêmeas tivessem a mesma massa média, uma diferença de 683 g seria praticamente impossível por acaso (<span class="math inline">\(p &lt; 0{,}001\)</span>). Rejeitamos <span class="math inline">\(H_0\)</span>: há evidência de dimorfismo sexual, com machos mais pesados. Note que o teste fala de <strong>médias</strong>. Ele não afirma que todo macho é mais pesado que toda fêmea.</p>
</section>
<section id="caso-3.-teste-t-pareado" class="level2">
<h2 class="anchored" data-anchor-id="caso-3.-teste-t-pareado">Caso 3. Teste <em>t</em> pareado</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>Em um ensaio clínico, os mesmos 10 pacientes testaram dois soníferos, um em cada período, e foram medidas as horas extras de sono (<code>extra</code>). O médico quer saber se a droga 2 rende mais horas de sono que a droga 1.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: em média, a droga 2 não muda as horas de sono em relação à droga 1 (<span class="math inline">\(\mu_D = 0\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: em média, as horas de sono mudam entre as drogas (<span class="math inline">\(\mu_D \neq 0\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Cada par de medidas vem da mesma unidade, no caso o mesmo paciente.</li>
<li>Os pares são independentes entre si.</li>
<li>Variável resposta numérica contínua.</li>
<li>As diferenças dentro de cada par, <span class="math inline">\(D_i = X_{2i} - X_{1i}\)</span>, seguem aproximadamente uma distribuição normal.</li>
</ul>
<p>A base <code>sleep</code> está no formato longo: uma linha por paciente e droga. Reorganizamos para uma linha por paciente e calculamos a diferença:</p>
<div id="45a7f0a1" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="annotated-cell-15"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-15-1"><a href="#annotated-cell-15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Uma linha por paciente, com a diferença entre as drogas</span></span>
<span id="annotated-cell-15-2"><a href="#annotated-cell-15-2" aria-hidden="true" tabindex="-1"></a>sleep_wide <span class="op">=</span> (</span>
<span id="annotated-cell-15-3"><a href="#annotated-cell-15-3" aria-hidden="true" tabindex="-1"></a>    sleep</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-15-4" class="code-annotation-target"><a href="#annotated-cell-15-4" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span><span class="st">"ID"</span>, columns<span class="op">=</span><span class="st">"group"</span>, values<span class="op">=</span><span class="st">"extra"</span>)</span>
<span id="annotated-cell-15-5"><a href="#annotated-cell-15-5" aria-hidden="true" tabindex="-1"></a>    .rename(columns<span class="op">=</span>{<span class="dv">1</span>: <span class="st">"droga_1"</span>, <span class="dv">2</span>: <span class="st">"droga_2"</span>})</span>
<span id="annotated-cell-15-6"><a href="#annotated-cell-15-6" aria-hidden="true" tabindex="-1"></a>    .assign(D<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"droga_2"</span>] <span class="op">-</span> df[<span class="st">"droga_1"</span>])</span>
<span id="annotated-cell-15-7"><a href="#annotated-cell-15-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-15-8"><a href="#annotated-cell-15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-9"><a href="#annotated-cell-15-9" aria-hidden="true" tabindex="-1"></a>sleep_wide</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-15" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-15" data-code-lines="4" data-code-annotation="1"><code>.pivot</code> transforma os valores da coluna <code>group</code> em colunas, uma para cada droga.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">group</th>
<th data-quarto-table-cell-role="th">droga_1</th>
<th data-quarto-table-cell-role="th">droga_2</th>
<th data-quarto-table-cell-role="th">D</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>0.7</td>
<td>1.9</td>
<td>1.2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>-1.6</td>
<td>0.8</td>
<td>2.4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>-0.2</td>
<td>1.1</td>
<td>1.3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>-1.2</td>
<td>0.1</td>
<td>1.3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>-0.1</td>
<td>-0.1</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>3.4</td>
<td>4.4</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>3.7</td>
<td>5.5</td>
<td>1.8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>0.8</td>
<td>1.6</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>0.0</td>
<td>4.6</td>
<td>4.6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>2.0</td>
<td>3.4</td>
<td>1.4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>A partir daqui, as colunas originais saem de cena. O teste pareado é um teste <em>t</em> de uma amostra sobre a coluna <code>D</code>, com <span class="math inline">\(\mu_0 = 0\)</span>:</p>
<p><span class="math display">\[
t = \frac{\bar{D} - 0}{s_D / \sqrt{n}}
\]</span></p>
<div id="23edc263" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste t pareado e o mesmo teste ignorando o pareamento</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>case3 <span class="op">=</span> stats.ttest_rel(sleep_wide[<span class="st">"droga_2"</span>], sleep_wide[<span class="st">"droga_1"</span>])</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>unpaired <span class="op">=</span> stats.ttest_ind(sleep_wide[<span class="st">"droga_2"</span>], sleep_wide[<span class="st">"droga_1"</span>])</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"t"</span>: [case3.statistic, unpaired.statistic], <span class="st">"p"</span>: [case3.pvalue, unpaired.pvalue]},</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span>[<span class="st">"pareado"</span>, <span class="st">"ignorando o pareamento"</span>],</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>).<span class="bu">round</span>(<span class="dv">4</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">t</th>
<th data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">pareado</td>
<td>4.0621</td>
<td>0.0028</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ignorando o pareamento</td>
<td>1.8608</td>
<td>0.0792</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>A média das diferenças é de 1,58 h, com desvio-padrão de 1,23 h. O teste pareado dá <span class="math inline">\(t = 4{,}06\)</span> com 9 graus de liberdade e <span class="math inline">\(p \approx 0{,}003\)</span>. Com os <strong>mesmos dados</strong>, tratados como dois grupos independentes, o <em>p</em>-valor sobe para 0,079, e a diferença deixa de ser significante.</p>
<p>O motivo aparece no gráfico. À esquerda, cada linha liga as duas medidas de um paciente. À direita, cada ponto é a diferença de um paciente, com a média e o intervalo de confiança:</p>
<div id="db2c5610" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linhas por paciente e diferenças com intervalo de confiança</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>), width_ratios<span class="op">=</span>[<span class="dv">1</span>, <span class="fl">1.6</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot([<span class="dv">0</span>, <span class="dv">1</span>], sleep_wide[[<span class="st">"droga_1"</span>, <span class="st">"droga_2"</span>]].T, color<span class="op">=</span><span class="st">"#1F4E79"</span>, marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(xticks<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1</span>], xticklabels<span class="op">=</span>[<span class="st">"Droga 1"</span>, <span class="st">"Droga 2"</span>], xlim<span class="op">=</span>(<span class="op">-</span><span class="fl">.3</span>, <span class="fl">1.3</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            ylabel<span class="op">=</span><span class="st">"Horas extras de sono"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plot_mean_ci(sleep_wide[<span class="st">"D"</span>], case3.confidence_interval(), <span class="dv">0</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Diferença de sono: droga 2 − droga 1 (horas)"</span>, axes[<span class="dv">1</span>])</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-20-output-1.png" width="1137" height="368" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Os pacientes são muito diferentes entre si: alguns dormem bem com qualquer droga, outros dormem pouco. A correlação entre as duas medidas de cada paciente é de cerca de 0,80. Vistos como dois grupos soltos, os pontos se misturam, e a variação <strong>entre pacientes</strong> esconde o efeito. Olhando paciente a paciente, o padrão aparece: as linhas sobem em 9 dos 10 casos, e nenhum paciente piora. O pareamento cancela a variação de base de cada pessoa e isola o efeito da droga.</p>
<p>Há, porém, uma ressalva. Com apenas 10 diferenças, a normalidade pesa mais:</p>
<div id="02457d82" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalidade das diferenças e alternativa não paramétrica</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"Shapiro-Wilk das diferenças"</span>, stats.shapiro(sleep_wide[<span class="st">"D"</span>]), stat<span class="op">=</span><span class="st">"W"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"Wilcoxon"</span>, stats.wilcoxon(sleep_wide[<span class="st">"D"</span>]), stat<span class="op">=</span><span class="st">"T"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapiro-Wilk das diferenças: W = 0.830 · p = 0.033
Wilcoxon: T = 0.000 · p = 0.004</code></pre>
</div>
</div>
<p>O Shapiro-Wilk rejeita a normalidade das diferenças (<span class="math inline">\(p \approx 0{,}03\)</span>), em boa parte por causa do paciente com ganho de 4,6 h. O teste de Wilcoxon dos postos sinalizados, a alternativa não paramétrica ao <em>t</em> pareado, chega à mesma conclusão (<span class="math inline">\(p \approx 0{,}004\)</span>).</p>
<p><strong>Interpretação.</strong> Quase todos os pacientes estão à direita da linha de zero, e o intervalo da média, de 0,70 a 2,46 h, não toca nela. Se as duas drogas fossem equivalentes, um ganho médio de 1,58 h surgiria em apenas 0,3% dos ensaios. Rejeitamos <span class="math inline">\(H_0\)</span>: nos mesmos pacientes, a droga 2 rende em média cerca de 1,6 h a mais de sono que a droga 1.</p>
</section>
<section id="caso-4.-anova-one-way" class="level2">
<h2 class="anchored" data-anchor-id="caso-4.-anova-one-way">Caso 4. ANOVA one-way</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um botânico mede flores de três espécies de íris e quer saber se o comprimento médio da sépala (<code>sepal_length</code>) é o mesmo nas três, antes de usá-lo para diferenciá-las.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: as três espécies têm o mesmo comprimento médio (<span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: pelo menos uma espécie tem média diferente.</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Observações independentes, dentro de cada grupo e entre os grupos.</li>
<li>Variável resposta numérica contínua.</li>
<li>Resíduos aproximadamente normais em cada grupo.</li>
<li>Variâncias iguais entre os grupos (homocedasticidade).</li>
</ul>
<p>Por que não comparar as espécies duas a duas com três testes <em>t</em>? Porque cada teste tem 5% de chance de falso positivo, e a chance de errar pelo menos uma vez cresce com o número de comparações, como vimos na seção 6.2 da Aula 7. Com <span class="math inline">\(k\)</span> grupos, há <span class="math inline">\(k(k-1)/2\)</span> pares: 3 pares para 3 grupos, 10 para 5. A ANOVA responde à pergunta com <strong>um único teste</strong> e mantém o <span class="math inline">\(\alpha\)</span> em 5%.</p>
<p>A ideia da ANOVA é comparar duas fontes de variação. Se as médias das espécies se afastam muito da média geral, em relação à variação natural dentro de cada espécie, a estatística <em>F</em> fica grande:</p>
<p><span class="math display">\[
F = \frac{MQG}{MQR} = \frac{SQG / (k - 1)}{SQR / (N - k)}
\]</span></p>
<p>Aqui, <span class="math inline">\(SQG\)</span> é a soma de quadrados <strong>entre</strong> grupos, <span class="math inline">\(SQR\)</span> a soma de quadrados <strong>dentro</strong> dos grupos (resíduos), <span class="math inline">\(k\)</span> o número de grupos e <span class="math inline">\(N\)</span> o total de observações. Calculamos a tabela da ANOVA passo a passo:</p>
<div id="de8395f4" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="annotated-cell-19"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-19-1"><a href="#annotated-cell-19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabela da ANOVA calculada passo a passo</span></span>
<span id="annotated-cell-19-2"><a href="#annotated-cell-19-2" aria-hidden="true" tabindex="-1"></a>grand_mean <span class="op">=</span> iris[<span class="st">"sepal_length"</span>].mean()</span>
<span id="annotated-cell-19-3"><a href="#annotated-cell-19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-19-4"><a href="#annotated-cell-19-4" aria-hidden="true" tabindex="-1"></a>by_species <span class="op">=</span> (</span>
<span id="annotated-cell-19-5"><a href="#annotated-cell-19-5" aria-hidden="true" tabindex="-1"></a>    iris</span>
<span id="annotated-cell-19-6"><a href="#annotated-cell-19-6" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"species"</span>)</span>
<span id="annotated-cell-19-7"><a href="#annotated-cell-19-7" aria-hidden="true" tabindex="-1"></a>    .sepal_length</span>
<span id="annotated-cell-19-8"><a href="#annotated-cell-19-8" aria-hidden="true" tabindex="-1"></a>    .agg(n<span class="op">=</span><span class="st">"size"</span>, média<span class="op">=</span><span class="st">"mean"</span>, dp<span class="op">=</span><span class="st">"std"</span>)</span>
<span id="annotated-cell-19-9"><a href="#annotated-cell-19-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-19-10"><a href="#annotated-cell-19-10" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-19-11" class="code-annotation-target"><a href="#annotated-cell-19-11" aria-hidden="true" tabindex="-1"></a>ss_between <span class="op">=</span> (by_species[<span class="st">"n"</span>] <span class="op">*</span> (by_species[<span class="st">"média"</span>] <span class="op">-</span> grand_mean) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="annotated-cell-19-12"><a href="#annotated-cell-19-12" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-19" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-19-13" class="code-annotation-target"><a href="#annotated-cell-19-13" aria-hidden="true" tabindex="-1"></a>ss_within <span class="op">=</span> ((by_species[<span class="st">"n"</span>] <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> by_species[<span class="st">"dp"</span>] <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="annotated-cell-19-14"><a href="#annotated-cell-19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-19-15"><a href="#annotated-cell-19-15" aria-hidden="true" tabindex="-1"></a>k, N <span class="op">=</span> <span class="bu">len</span>(by_species), <span class="bu">len</span>(iris)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-19" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-19" data-code-lines="11" data-code-annotation="1">Quanto cada média de espécie se afasta da média geral, ao quadrado, ponderado pelo tamanho do grupo.</span>
</dd>
<dt data-target-cell="annotated-cell-19" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-19" data-code-lines="13" data-code-annotation="2">A soma dos desvios ao quadrado dentro de um grupo é <span class="math inline">\((n - 1)s^2\)</span>. Somamos os três grupos.</span>
</dd>
</dl>
</div>
</div>
<div id="a696e205" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"SQ"</span>: [ss_between, ss_within], <span class="st">"gl"</span>: [k <span class="op">-</span> <span class="dv">1</span>, N <span class="op">-</span> k]},</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span>[<span class="st">"entre espécies"</span>, <span class="st">"dentro (resíduos)"</span>],</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>).assign(MQ<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"SQ"</span>] <span class="op">/</span> df[<span class="st">"gl"</span>]).<span class="bu">round</span>(<span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">SQ</th>
<th data-quarto-table-cell-role="th">gl</th>
<th data-quarto-table-cell-role="th">MQ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">entre espécies</td>
<td>63.212</td>
<td>2</td>
<td>31.606</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">dentro (resíduos)</td>
<td>38.956</td>
<td>147</td>
<td>0.265</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>O quadrado médio entre espécies (31,61) é cerca de 119 vezes o quadrado médio dentro das espécies (0,265). Conferimos com o SciPy e, como a ANOVA só diz que <strong>alguma</strong> média difere, usamos o teste de Tukey para descobrir <strong>quais</strong>:</p>
<div id="16f1826d" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="annotated-cell-21"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-21-1"><a href="#annotated-cell-21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA, comparações de Tukey e homocedasticidade</span></span>
<span id="annotated-cell-21-2"><a href="#annotated-cell-21-2" aria-hidden="true" tabindex="-1"></a>setosa, versicolor, virginica <span class="op">=</span> [</span>
<span id="annotated-cell-21-3"><a href="#annotated-cell-21-3" aria-hidden="true" tabindex="-1"></a>    group[<span class="st">"sepal_length"</span>] <span class="cf">for</span> _, group <span class="kw">in</span> iris.groupby(<span class="st">"species"</span>)</span>
<span id="annotated-cell-21-4"><a href="#annotated-cell-21-4" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="annotated-cell-21-5"><a href="#annotated-cell-21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-21-6"><a href="#annotated-cell-21-6" aria-hidden="true" tabindex="-1"></a>anova <span class="op">=</span> stats.f_oneway(setosa, versicolor, virginica)</span>
<span id="annotated-cell-21-7"><a href="#annotated-cell-21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-21-8"><a href="#annotated-cell-21-8" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"ANOVA"</span>, anova, stat<span class="op">=</span><span class="st">"F"</span>, df<span class="op">=</span>(k <span class="op">-</span> <span class="dv">1</span>, N <span class="op">-</span> k))</span>
<span id="annotated-cell-21-9"><a href="#annotated-cell-21-9" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"Levene"</span>, stats.levene(setosa, versicolor, virginica))</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-21" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-21-10" class="code-annotation-target"><a href="#annotated-cell-21-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.tukey_hsd(setosa, versicolor, virginica))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-21" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-21" data-code-lines="10" data-code-annotation="1">Na saída do Tukey, os grupos são numerados na ordem dos argumentos: 0 = setosa, 1 = versicolor, 2 = virginica.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA: F = 119.265 · gl = (2, 147) · p &lt; 0.001
Levene: estatística = 6.353 · p = 0.002
Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.930     0.000    -1.174    -0.686
 (0 - 2)     -1.582     0.000    -1.826    -1.338
 (1 - 0)      0.930     0.000     0.686     1.174
 (1 - 2)     -0.652     0.000    -0.896    -0.408
 (2 - 0)      1.582     0.000     1.338     1.826
 (2 - 1)      0.652     0.000     0.408     0.896
</code></pre>
</div>
</div>
<p>A ANOVA dá <span class="math inline">\(F \approx 119{,}3\)</span> com <span class="math inline">\((2, 147)\)</span> graus de liberdade e <span class="math inline">\(p &lt; 0{,}001\)</span>. O Tukey indica que os três pares diferem, com diferenças de 0,65 a 1,58 cm e todos os <em>p</em>-valores abaixo de 0,001. A fração da variação total explicada pela espécie, <span class="math inline">\(\eta^2 = SQG / (SQG + SQR)\)</span>, é de cerca de 0,62.</p>
<div id="fe84a8e3" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprimento da sépala por espécie</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">4.5</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plot_group_means(iris, <span class="st">"species"</span>, <span class="st">"sepal_length"</span>, [<span class="st">"setosa"</span>, <span class="st">"versicolor"</span>, <span class="st">"virginica"</span>],</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Comprimento da sépala (cm)"</span>, ax)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-25-output-1.png" width="657" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> As médias sobem de setosa (5,01 cm) para versicolor (5,94 cm) e virginica (6,59 cm), e a distância entre elas é grande em relação à dispersão dentro de cada espécie. Se as espécies tivessem a mesma sépala média, diferenças desse tamanho seriam praticamente impossíveis por acaso. Rejeitamos <span class="math inline">\(H_0\)</span>: o comprimento da sépala distingue as três espécies, e todos os pares diferem entre si.</p>
<p>Fica uma ressalva. O teste de Levene rejeita a igualdade de variâncias (<span class="math inline">\(p \approx 0{,}002\)</span>): a dispersão cresce de setosa para virginica. Nesse caso, uma alternativa mais segura é a ANOVA de Welch, seguida do teste de Games-Howell. Com diferenças tão grandes, a conclusão não muda.</p>
</section>
<section id="caso-5.-correlação-de-pearson" class="level2">
<h2 class="anchored" data-anchor-id="caso-5.-correlação-de-pearson">Caso 5. Correlação de Pearson</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um engenheiro quer entender se carros mais pesados (<code>wt</code>, em milhares de libras) tendem a gastar mais combustível (<code>mpg</code>), e quão forte é essa relação, antes de propor um projeto mais leve.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: não há relação linear entre peso e consumo (<span class="math inline">\(\rho = 0\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: existe relação linear entre peso e consumo (<span class="math inline">\(\rho \neq 0\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Pares de observações independentes entre si.</li>
<li>As duas variáveis são numéricas contínuas.</li>
<li>A relação entre elas é linear.</li>
<li>Normalidade bivariada e ausência de valores atípicos influentes.</li>
</ul>
<p>O coeficiente de Pearson mede o quanto duas variáveis numéricas andam juntas <strong>em linha reta</strong>. O numerador soma os produtos dos desvios: é positivo quando valores altos de uma variável acompanham valores altos da outra. O denominador padroniza o resultado e o prende entre <span class="math inline">\(-1\)</span> e <span class="math inline">\(+1\)</span>:</p>
<p><span class="math display">\[
r = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum (x_i - \bar{x})^2 \cdot \sum (y_i - \bar{y})^2}}
\]</span></p>
<div id="ee95d820" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Pearson pela fórmula e pelo SciPy</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dx <span class="op">=</span> mtcars[<span class="st">"wt"</span>] <span class="op">-</span> mtcars[<span class="st">"wt"</span>].mean()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>dy <span class="op">=</span> mtcars[<span class="st">"mpg"</span>] <span class="op">-</span> mtcars[<span class="st">"mpg"</span>].mean()</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>r_manual <span class="op">=</span> (dx <span class="op">*</span> dy).<span class="bu">sum</span>() <span class="op">/</span> np.sqrt((dx <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>() <span class="op">*</span> (dy <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>case5 <span class="op">=</span> stats.pearsonr(mtcars[<span class="st">"wt"</span>], mtcars[<span class="st">"mpg"</span>])</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"r calculado à mão = </span><span class="sc">{</span>r_manual<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"Pearson"</span>, case5, stat<span class="op">=</span><span class="st">"r"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>r calculado à mão = -0.868
Pearson: r = -0.868 · p &lt; 0.001 · IC 95% [-0.93 ; -0.74]</code></pre>
</div>
</div>
<p>O coeficiente vale <span class="math inline">\(r \approx -0{,}87\)</span>, com <span class="math inline">\(p &lt; 0{,}001\)</span>. O sinal negativo indica a direção: mais peso, menos milhas por galão. O tamanho indica a força. Como referência, valores de <span class="math inline">\(|r|\)</span> abaixo de 0,3 costumam ser descritos como fracos, entre 0,3 e 0,5 como moderados e acima de 0,5 como fortes.</p>
<p>O coeficiente tem duas propriedades úteis. Ele é <strong>simétrico</strong>: <span class="math inline">\(r(\text{peso}, \text{consumo}) = r(\text{consumo}, \text{peso})\)</span>. E é <strong>invariante</strong> a mudanças de unidade. Convertendo o peso para quilogramas, o resultado não muda:</p>
<div id="7c2e770e" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># O coeficiente não depende da unidade de medida</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>r_kg <span class="op">=</span> stats.pearsonr(mtcars[<span class="st">"wt"</span>] <span class="op">*</span> <span class="fl">453.6</span>, mtcars[<span class="st">"mpg"</span>]).statistic</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"r com o peso em kg = </span><span class="sc">{</span>r_kg<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>r com o peso em kg = -0.868</code></pre>
</div>
</div>
<div id="5e1ff95f" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="annotated-cell-25"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-25-1"><a href="#annotated-cell-25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consumo versus peso, com a reta de mínimos quadrados</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-25" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-25-2" class="code-annotation-target"><a href="#annotated-cell-25-2" aria-hidden="true" tabindex="-1"></a>slope, intercept <span class="op">=</span> np.polyfit(mtcars[<span class="st">"wt"</span>], mtcars[<span class="st">"mpg"</span>], deg<span class="op">=</span><span class="dv">1</span>)</span>
<span id="annotated-cell-25-3"><a href="#annotated-cell-25-3" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(mtcars[<span class="st">"wt"</span>].<span class="bu">min</span>(), mtcars[<span class="st">"wt"</span>].<span class="bu">max</span>(), <span class="dv">100</span>)</span>
<span id="annotated-cell-25-4"><a href="#annotated-cell-25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-25-5"><a href="#annotated-cell-25-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">4.5</span>))</span>
<span id="annotated-cell-25-6"><a href="#annotated-cell-25-6" aria-hidden="true" tabindex="-1"></a>ax.scatter(mtcars[<span class="st">"wt"</span>], mtcars[<span class="st">"mpg"</span>], color<span class="op">=</span><span class="st">"#1F4E79"</span>, alpha<span class="op">=</span><span class="fl">.8</span>)</span>
<span id="annotated-cell-25-7"><a href="#annotated-cell-25-7" aria-hidden="true" tabindex="-1"></a>ax.plot(grid, intercept <span class="op">+</span> slope <span class="op">*</span> grid, color<span class="op">=</span><span class="st">"#DD8452"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="annotated-cell-25-8"><a href="#annotated-cell-25-8" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="ss">f"r = </span><span class="sc">{</span>case5<span class="sc">.</span>statistic<span class="sc">:.2f}</span><span class="ss">"</span>, xlabel<span class="op">=</span><span class="st">"Peso (wt, 1.000 lb)"</span>,</span>
<span id="annotated-cell-25-9"><a href="#annotated-cell-25-9" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">"Consumo (mpg)"</span>)</span>
<span id="annotated-cell-25-10"><a href="#annotated-cell-25-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-25-11"><a href="#annotated-cell-25-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-25" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-25" data-code-lines="2" data-code-annotation="1"><code>np.polyfit</code> com <code>deg=1</code> ajusta a reta que melhor descreve os pontos, apenas para guiar o olhar.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-28-output-1.png" width="657" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> Os pontos descem da esquerda para a direita e ficam próximos da reta. Se peso e consumo não tivessem relação linear, um <em>r</em> tão forte seria praticamente impossível por acaso. Rejeitamos <span class="math inline">\(H_0\)</span>: carros mais pesados tendem a fazer menos milhas por galão.</p>
<p>Dois limites merecem atenção. Pearson só enxerga relações <strong>lineares</strong>: uma relação em forma de U pode ter <span class="math inline">\(r \approx 0\)</span> e, para relações monotônicas mas curvas, o coeficiente de Spearman é mais adequado. E correlação <strong>não é causalidade</strong>: o coeficiente mede associação, e a causa exige um mecanismo ou um experimento.</p>
</section>
<section id="caso-6.-teste-z-de-duas-proporções" class="level2">
<h2 class="anchored" data-anchor-id="caso-6.-teste-z-de-duas-proporções">Caso 6. Teste <em>Z</em> de duas proporções</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um historiador analisa o naufrágio do Titanic: a regra “mulheres e crianças primeiro” deixou marca nos números? A sobrevivência (<code>survived</code>) foi diferente entre mulheres e homens (<code>sex</code>)?</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: mulheres e homens tiveram a mesma taxa de sobrevivência (<span class="math inline">\(p_1 = p_2\)</span>).</li>
<li><span class="math inline">\(H_1\)</span>: as taxas de sobrevivência foram diferentes (<span class="math inline">\(p_1 \neq p_2\)</span>).</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>Variável resposta binária: sucesso ou fracasso.</li>
<li>Observações independentes, dentro de cada grupo e entre os grupos.</li>
<li>Amostras grandes o bastante para a aproximação normal: <span class="math inline">\(n \cdot \hat{p} \geq 5\)</span> e <span class="math inline">\(n \cdot (1 - \hat{p}) \geq 5\)</span> em cada grupo.</li>
</ul>
<p>A resposta agora é <strong>binária</strong>: sobreviveu (1) ou não (0). A média de uma variável 0/1 é a proporção de uns, e a comparação passa a ser entre proporções. Sob <span class="math inline">\(H_0\)</span>, as duas taxas são iguais, e a melhor estimativa dessa taxa comum é a <strong>proporção combinada</strong> <span class="math inline">\(\hat{p}\)</span>, que junta os dois grupos:</p>
<p><span class="math display">\[
Z = \frac{\hat{p}_1 - \hat{p}_2}{\sqrt{\hat{p}(1 - \hat{p})\left(\dfrac{1}{n_1} + \dfrac{1}{n_2}\right)}}
\qquad
\hat{p} = \frac{x_1 + x_2}{n_1 + n_2}
\]</span></p>
<div id="f920eda6" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="annotated-cell-26"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-26-1"><a href="#annotated-cell-26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sobreviventes, total e proporção por sexo</span></span>
<span id="annotated-cell-26-2"><a href="#annotated-cell-26-2" aria-hidden="true" tabindex="-1"></a>by_sex <span class="op">=</span> (</span>
<span id="annotated-cell-26-3"><a href="#annotated-cell-26-3" aria-hidden="true" tabindex="-1"></a>    titanic</span>
<span id="annotated-cell-26-4"><a href="#annotated-cell-26-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">"sex"</span>)</span>
<span id="annotated-cell-26-5"><a href="#annotated-cell-26-5" aria-hidden="true" tabindex="-1"></a>    .survived</span>
<span id="annotated-cell-26-6"><a href="#annotated-cell-26-6" aria-hidden="true" tabindex="-1"></a>    .agg(sobreviventes<span class="op">=</span><span class="st">"sum"</span>, n<span class="op">=</span><span class="st">"size"</span>)</span>
<span id="annotated-cell-26-7"><a href="#annotated-cell-26-7" aria-hidden="true" tabindex="-1"></a>    .assign(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-26" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-26-8" class="code-annotation-target"><a href="#annotated-cell-26-8" aria-hidden="true" tabindex="-1"></a>        nao_sobreviventes<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"n"</span>] <span class="op">-</span> df[<span class="st">"sobreviventes"</span>],</span>
<span id="annotated-cell-26-9"><a href="#annotated-cell-26-9" aria-hidden="true" tabindex="-1"></a>        proporcao<span class="op">=</span><span class="kw">lambda</span> df: df[<span class="st">"sobreviventes"</span>] <span class="op">/</span> df[<span class="st">"n"</span>],</span>
<span id="annotated-cell-26-10"><a href="#annotated-cell-26-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-26-11"><a href="#annotated-cell-26-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-26-12"><a href="#annotated-cell-26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-26-13"><a href="#annotated-cell-26-13" aria-hidden="true" tabindex="-1"></a>by_sex.<span class="bu">round</span>(<span class="dv">3</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-26" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-26" data-code-lines="8" data-code-annotation="1">Sobreviventes e não sobreviventes correspondem a <span class="math inline">\(n \cdot \hat{p}\)</span> e <span class="math inline">\(n \cdot (1 - \hat{p})\)</span>. A condição de aplicação exige que os dois sejam pelo menos 5 em cada grupo.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">sobreviventes</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">nao_sobreviventes</th>
<th data-quarto-table-cell-role="th">proporcao</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">sex</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">female</td>
<td>233</td>
<td>314</td>
<td>81</td>
<td>0.742</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">male</td>
<td>109</td>
<td>577</td>
<td>468</td>
<td>0.189</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Sobreviveram 74,2% das mulheres (233 de 314) e 18,9% dos homens (109 de 577). A menor contagem da condição é 81, muito acima de 5. Calculamos <em>Z</em> pela fórmula e com o <code>statsmodels</code>:</p>
<div id="9374b64c" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="annotated-cell-27"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-27-1"><a href="#annotated-cell-27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estatística Z pela fórmula e pelo statsmodels</span></span>
<span id="annotated-cell-27-2"><a href="#annotated-cell-27-2" aria-hidden="true" tabindex="-1"></a>p_pooled <span class="op">=</span> by_sex[<span class="st">"sobreviventes"</span>].<span class="bu">sum</span>() <span class="op">/</span> by_sex[<span class="st">"n"</span>].<span class="bu">sum</span>()</span>
<span id="annotated-cell-27-3"><a href="#annotated-cell-27-3" aria-hidden="true" tabindex="-1"></a>se_pooled <span class="op">=</span> np.sqrt(p_pooled <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_pooled) <span class="op">*</span> (<span class="dv">1</span> <span class="op">/</span> by_sex[<span class="st">"n"</span>]).<span class="bu">sum</span>())</span>
<span id="annotated-cell-27-4"><a href="#annotated-cell-27-4" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> by_sex.loc[<span class="st">"female"</span>, <span class="st">"proporcao"</span>] <span class="op">-</span> by_sex.loc[<span class="st">"male"</span>, <span class="st">"proporcao"</span>]</span>
<span id="annotated-cell-27-5"><a href="#annotated-cell-27-5" aria-hidden="true" tabindex="-1"></a>z_manual <span class="op">=</span> diff <span class="op">/</span> se_pooled</span>
<span id="annotated-cell-27-6"><a href="#annotated-cell-27-6" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-27" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-27-7" class="code-annotation-target"><a href="#annotated-cell-27-7" aria-hidden="true" tabindex="-1"></a>case6 <span class="op">=</span> proportions_ztest(by_sex[<span class="st">"sobreviventes"</span>], by_sex[<span class="st">"n"</span>])</span>
<span id="annotated-cell-27-8"><a href="#annotated-cell-27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-27-9"><a href="#annotated-cell-27-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"proporção combinada = </span><span class="sc">{</span>p_pooled<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-27-10"><a href="#annotated-cell-27-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Z calculado à mão = </span><span class="sc">{</span>z_manual<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-27-11"><a href="#annotated-cell-27-11" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"Z de duas proporções"</span>, case6, stat<span class="op">=</span><span class="st">"Z"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-27" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-27" data-code-lines="7" data-code-annotation="1"><code>proportions_ztest</code> recebe o número de sucessos e o total de cada grupo e devolve a estatística <em>Z</em> e o <em>p</em>-valor.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>proporção combinada = 0.384
Z calculado à mão = 16.22
Z de duas proporções: Z = 16.219 · p &lt; 0.001</code></pre>
</div>
</div>
<p>A proporção combinada é de 38,4%, a taxa geral de sobrevivência. A estatística vale <span class="math inline">\(Z \approx 16{,}2\)</span>: a diferença entre as taxas equivale a mais de 16 erros-padrão. O gráfico mostra cada taxa com seu intervalo de confiança de 95%:</p>
<div id="98253cae" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="annotated-cell-28"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-28-1"><a href="#annotated-cell-28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proporção de sobreviventes por sexo, com intervalo de confiança</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-28" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-28-2" class="code-annotation-target"><a href="#annotated-cell-28-2" aria-hidden="true" tabindex="-1"></a>low, high <span class="op">=</span> proportion_confint(by_sex[<span class="st">"sobreviventes"</span>], by_sex[<span class="st">"n"</span>])</span>
<span id="annotated-cell-28-3"><a href="#annotated-cell-28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-28-4"><a href="#annotated-cell-28-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">3.5</span>))</span>
<span id="annotated-cell-28-5"><a href="#annotated-cell-28-5" aria-hidden="true" tabindex="-1"></a>ax.barh([<span class="st">"Homens"</span>, <span class="st">"Mulheres"</span>], by_sex.loc[[<span class="st">"male"</span>, <span class="st">"female"</span>], <span class="st">"proporcao"</span>],</span>
<span id="annotated-cell-28-6"><a href="#annotated-cell-28-6" aria-hidden="true" tabindex="-1"></a>        xerr<span class="op">=</span>[(by_sex[<span class="st">"proporcao"</span>] <span class="op">-</span> low)[[<span class="st">"male"</span>, <span class="st">"female"</span>]],</span>
<span id="annotated-cell-28-7"><a href="#annotated-cell-28-7" aria-hidden="true" tabindex="-1"></a>              (high <span class="op">-</span> by_sex[<span class="st">"proporcao"</span>])[[<span class="st">"male"</span>, <span class="st">"female"</span>]]],</span>
<span id="annotated-cell-28-8"><a href="#annotated-cell-28-8" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>[<span class="st">"#A1C9F4"</span>, <span class="st">"#1F4E79"</span>], capsize<span class="op">=</span><span class="dv">6</span>)</span>
<span id="annotated-cell-28-9"><a href="#annotated-cell-28-9" aria-hidden="true" tabindex="-1"></a>ax.axvline(p_pooled, color<span class="op">=</span><span class="st">"#DD8452"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="annotated-cell-28-10"><a href="#annotated-cell-28-10" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>), xlabel<span class="op">=</span><span class="st">"Proporção de sobreviventes (com IC 95%)"</span>)</span>
<span id="annotated-cell-28-11"><a href="#annotated-cell-28-11" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-28-12"><a href="#annotated-cell-28-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-28" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-28" data-code-lines="2" data-code-annotation="1"><code>proportion_confint</code> devolve os limites inferior e superior do intervalo de confiança de cada proporção.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-31-output-1.png" width="657" height="321" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> A barra das mulheres é quase quatro vezes a dos homens, e os intervalos ficam muito longe um do outro e da taxa geral de 38% (linha tracejada). Se mulheres e homens tivessem a mesma chance de sobreviver, 55 pontos percentuais de diferença seriam impossíveis por acaso (<span class="math inline">\(p &lt; 0{,}001\)</span>). Rejeitamos <span class="math inline">\(H_0\)</span>: a regra “mulheres e crianças primeiro” aparece nos dados.</p>
</section>
<section id="caso-7.-qui-quadrado-de-independência" class="level2">
<h2 class="anchored" data-anchor-id="caso-7.-qui-quadrado-de-independência">Caso 7. Qui-quadrado de independência</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cenário
</div>
</div>
<div class="callout-body-container callout-body">
<p>O mesmo historiador pergunta se a classe da passagem (<code>pclass</code>: 1ª, 2ª ou 3ª) teve relação com quem sobreviveu (<code>survived</code>), ou se a sobrevivência foi independente da classe.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: a sobrevivência não depende da classe. As variáveis são independentes.</li>
<li><span class="math inline">\(H_1\)</span>: a sobrevivência está associada à classe.</li>
</ul>
</div>
</div>
<p><strong>Premissas do teste</strong></p>
<ul>
<li>As duas variáveis são categóricas.</li>
<li>Observações independentes, cada uma contada em uma única célula da tabela.</li>
<li>Frequência esperada de pelo menos 5 em pelo menos 80% das células e nenhuma abaixo de 1. Quando essa condição falha, usa-se o teste exato de Fisher.</li>
</ul>
<p>Com duas variáveis categóricas, os dados se resumem a uma <strong>tabela de contingência</strong>, que conta os passageiros em cada combinação de classe e desfecho:</p>
<div id="51fbf4c2" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="annotated-cell-29"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-29-1"><a href="#annotated-cell-29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabela de contingência: classe por desfecho</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-29" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-29-2" class="code-annotation-target"><a href="#annotated-cell-29-2" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> pd.crosstab(titanic[<span class="st">"pclass"</span>], titanic[<span class="st">"survived"</span>])</span>
<span id="annotated-cell-29-3"><a href="#annotated-cell-29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-29-4"><a href="#annotated-cell-29-4" aria-hidden="true" tabindex="-1"></a>observed</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-29" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-29" data-code-lines="2" data-code-annotation="1"><code>pd.crosstab</code> conta as ocorrências de cada combinação de valores das duas colunas.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">survived</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">pclass</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>80</td>
<td>136</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>97</td>
<td>87</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>372</td>
<td>119</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>O teste compara essas contagens observadas (<span class="math inline">\(O\)</span>) com as que <strong>esperaríamos se a classe não tivesse nada a ver com a sobrevivência</strong> (<span class="math inline">\(E\)</span>). Sob independência, a contagem esperada de cada célula é o total da linha vezes o total da coluna, dividido pelo total geral. A estatística soma as discrepâncias padronizadas de todas as células:</p>
<p><span class="math display">\[
\chi^2 = \sum \frac{(O - E)^2}{E}
\qquad
\text{gl} = (\text{linhas} - 1)(\text{colunas} - 1)
\]</span></p>
<div id="a1798516" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="annotated-cell-30"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-30-1"><a href="#annotated-cell-30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Qui-quadrado, frequências esperadas e parcela de cada célula</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-30" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-30-2" class="code-annotation-target"><a href="#annotated-cell-30-2" aria-hidden="true" tabindex="-1"></a>case7 <span class="op">=</span> stats.chi2_contingency(observed)</span>
<span id="annotated-cell-30-3"><a href="#annotated-cell-30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-30-4"><a href="#annotated-cell-30-4" aria-hidden="true" tabindex="-1"></a>expected <span class="op">=</span> pd.DataFrame(</span>
<span id="annotated-cell-30-5"><a href="#annotated-cell-30-5" aria-hidden="true" tabindex="-1"></a>    case7.expected_freq, index<span class="op">=</span>observed.index, columns<span class="op">=</span>observed.columns</span>
<span id="annotated-cell-30-6"><a href="#annotated-cell-30-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-30-7"><a href="#annotated-cell-30-7" aria-hidden="true" tabindex="-1"></a>contributions <span class="op">=</span> (observed <span class="op">-</span> expected) <span class="op">**</span> <span class="dv">2</span> <span class="op">/</span> expected</span>
<span id="annotated-cell-30-8"><a href="#annotated-cell-30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-30-9"><a href="#annotated-cell-30-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"χ² = </span><span class="sc">{</span>case7<span class="sc">.</span>statistic<span class="sc">:.2f}</span><span class="ss">, gl = </span><span class="sc">{</span>case7<span class="sc">.</span>dof<span class="sc">}</span><span class="ss">, p = </span><span class="sc">{</span>case7<span class="sc">.</span>pvalue<span class="sc">:.1e}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-30-10"><a href="#annotated-cell-30-10" aria-hidden="true" tabindex="-1"></a>pd.concat({<span class="st">"esperado"</span>: expected, <span class="st">"(O−E)²/E"</span>: contributions}, axis<span class="op">=</span><span class="dv">1</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-30" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-30" data-code-lines="2" data-code-annotation="1"><code>stats.chi2_contingency</code> calcula as frequências esperadas, a estatística, os graus de liberdade e o <em>p</em>-valor a partir da tabela observada.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>χ² = 102.89, gl = 2, p = 4.5e-23</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="32">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">esperado</th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">(O−E)²/E</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">survived</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">pclass</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>133.1</td>
<td>82.9</td>
<td>21.2</td>
<td>34.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>113.4</td>
<td>70.6</td>
<td>2.4</td>
<td>3.8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>302.5</td>
<td>188.5</td>
<td>15.9</td>
<td>25.6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>A estatística vale <span class="math inline">\(\chi^2 \approx 102{,}9\)</span>, com 2 graus de liberdade e <span class="math inline">\(p &lt; 0{,}001\)</span>. A menor frequência esperada é 70,6, e a condição de aplicação é atendida com folga. As parcelas mostram <strong>onde</strong> está o desvio: as maiores contribuições vêm da 1ª classe, que sobreviveu muito mais que o esperado, e da 3ª, que sobreviveu muito menos.</p>
<div id="892dd345" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="annotated-cell-31"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-31-1"><a href="#annotated-cell-31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contagens observadas e esperadas sob independência</span></span>
<span id="annotated-cell-31-2"><a href="#annotated-cell-31-2" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> (</span>
<span id="annotated-cell-31-3"><a href="#annotated-cell-31-3" aria-hidden="true" tabindex="-1"></a>    pd.concat(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-31" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-31-4" class="code-annotation-target"><a href="#annotated-cell-31-4" aria-hidden="true" tabindex="-1"></a>        {<span class="st">"observado"</span>: observed.stack(), <span class="st">"esperado"</span>: expected.stack()},</span>
<span id="annotated-cell-31-5"><a href="#annotated-cell-31-5" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">1</span>,</span>
<span id="annotated-cell-31-6"><a href="#annotated-cell-31-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="annotated-cell-31-7"><a href="#annotated-cell-31-7" aria-hidden="true" tabindex="-1"></a>    .rename(index<span class="op">=</span>{<span class="dv">0</span>: <span class="st">"morreu"</span>, <span class="dv">1</span>: <span class="st">"sobreviveu"</span>}, level<span class="op">=</span><span class="st">"survived"</span>)</span>
<span id="annotated-cell-31-8"><a href="#annotated-cell-31-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-31-9"><a href="#annotated-cell-31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-31-10"><a href="#annotated-cell-31-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">4</span>))</span>
<span id="annotated-cell-31-11"><a href="#annotated-cell-31-11" aria-hidden="true" tabindex="-1"></a>comparison.plot.bar(ax<span class="op">=</span>ax, color<span class="op">=</span>[<span class="st">"#1F4E79"</span>, <span class="st">"#A1C9F4"</span>], rot<span class="op">=</span><span class="dv">0</span>)</span>
<span id="annotated-cell-31-12"><a href="#annotated-cell-31-12" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">ª · </span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> c, d <span class="kw">in</span> comparison.index])</span>
<span id="annotated-cell-31-13"><a href="#annotated-cell-31-13" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">""</span>, ylabel<span class="op">=</span><span class="st">"Passageiros"</span>)</span>
<span id="annotated-cell-31-14"><a href="#annotated-cell-31-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-31-15"><a href="#annotated-cell-31-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-31" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-31" data-code-lines="4" data-code-annotation="1"><code>.stack()</code> transforma a tabela em uma série com uma linha por célula, indexada por classe e desfecho.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="08-testes-parametricos_files/figure-html/cell-34-output-1.png" width="849" height="368" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação.</strong> Se classe e sobrevivência fossem independentes, as barras escuras e claras teriam a mesma altura em cada par. Em vez disso, a 1ª classe tem mais sobreviventes que o esperado (136 contra 83), e a 3ª classe tem muito menos (119 contra 188). A taxa de sobrevivência cai de 63% na 1ª classe para 47% na 2ª e 24% na 3ª. Um desequilíbrio desse tamanho seria praticamente impossível por acaso. Rejeitamos <span class="math inline">\(H_0\)</span>: a chance de sobreviver dependeu da classe de embarque. O V de Cramér, uma medida da força da associação entre 0 e 1, vale cerca de 0,34, uma associação moderada.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Z e qui-quadrado: o mesmo teste em tabelas 2 × 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>O teste <em>Z</em> do caso 6 também pode ser escrito como um qui-quadrado sobre a tabela sexo × sobrevivência, que tem 2 linhas e 2 colunas. Nesse caso particular, <span class="math inline">\(Z^2 = \chi^2\)</span>: <span class="math inline">\(16{,}2^2 \approx 263\)</span>. As duas abordagens dão o mesmo <em>p</em>-valor. O qui-quadrado tem a vantagem de se estender a tabelas maiores, como a da classe, com três linhas.</p>
</div>
</div>
</div>
</section>
</section>
<section id="quando-as-premissas-falham" class="level1">
<h1>4. Quando as premissas falham</h1>
<p>Se as premissas não se sustentam, troca-se o teste. As alternativas não paramétricas trabalham, em geral, com <strong>postos</strong>: a posição de cada valor na ordenação, em vez do valor em si. Isso as torna robustas a assimetria e a valores atípicos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Paramétrico</th>
<th>Alternativa não paramétrica</th>
<th>Como funciona</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>t</em> de duas amostras</td>
<td>Mann-Whitney</td>
<td>Compara a soma dos postos dos dois grupos</td>
</tr>
<tr class="even">
<td><em>t</em> pareado</td>
<td>Wilcoxon dos postos sinalizados</td>
<td>Postos das diferenças, com sinal</td>
</tr>
<tr class="odd">
<td>ANOVA one-way</td>
<td>Kruskal-Wallis</td>
<td>Postos em três ou mais grupos</td>
</tr>
<tr class="even">
<td>Pearson</td>
<td>Spearman</td>
<td>Correlação dos postos: capta relações monotônicas</td>
</tr>
<tr class="odd">
<td>Qualquer um</td>
<td>Permutação</td>
<td>Distribuição nula por embaralhamento (Aula 7)</td>
</tr>
</tbody>
</table>
<p>Amostras com menos de 10 observações, assimetria forte, valores atípicos extremos ou escala ordinal são sinais para trocar o teste. O preço é perder um pouco de poder nas situações em que as premissas valeriam.</p>
</section>
<section id="guia-rápido" class="level1">
<h1>5. Guia rápido</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Pergunta</th>
<th>Teste</th>
<th>Função</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A média difere de uma meta?</td>
<td><em>t</em> de uma amostra</td>
<td><code>stats.ttest_1samp</code></td>
</tr>
<tr class="even">
<td>Dois grupos independentes têm a mesma média?</td>
<td><em>t</em> de Welch</td>
<td><code>stats.ttest_ind(..., equal_var=False)</code></td>
</tr>
<tr class="odd">
<td>A mesma unidade muda entre dois momentos?</td>
<td><em>t</em> pareado</td>
<td><code>stats.ttest_rel</code></td>
</tr>
<tr class="even">
<td>Três ou mais grupos têm a mesma média?</td>
<td>ANOVA + Tukey</td>
<td><code>stats.f_oneway</code>, <code>stats.tukey_hsd</code></td>
</tr>
<tr class="odd">
<td>Duas variáveis contínuas têm relação linear?</td>
<td>Pearson</td>
<td><code>stats.pearsonr</code></td>
</tr>
<tr class="even">
<td>Dois grupos têm a mesma proporção?</td>
<td><em>Z</em> de duas proporções</td>
<td><code>proportions_ztest</code></td>
</tr>
<tr class="odd">
<td>Duas variáveis categóricas são independentes?</td>
<td>Qui-quadrado</td>
<td><code>stats.chi2_contingency</code></td>
</tr>
<tr class="even">
<td>Os dados são normais?</td>
<td>Q-Q plot + Shapiro-Wilk</td>
<td><code>stats.probplot</code>, <code>stats.shapiro</code></td>
</tr>
<tr class="odd">
<td>As variâncias são iguais?</td>
<td>Levene</td>
<td><code>stats.levene</code></td>
</tr>
</tbody>
</table>
<section id="síntese" class="level2">
<h2 class="anchored" data-anchor-id="síntese">Síntese</h2>
<ol type="1">
<li><strong>Paramétrico.</strong> A distribuição nula vem da teoria (<em>t</em>, <em>F</em>, <em>Z</em> ou <span class="math inline">\(\chi^2\)</span>), em troca de premissas.</li>
<li><strong>Premissas.</strong> Antes do teste, verifique normalidade, homocedasticidade e independência. O Q-Q plot e o Shapiro-Wilk se complementam.</li>
<li><strong>Escolha.</strong> O objetivo, a escala da variável e o delineamento determinam o teste.</li>
<li><strong>Pareamento.</strong> Ignorar o pareamento infla o erro-padrão: no <code>sleep</code>, o <em>p</em>-valor foi de 0,003 para 0,079.</li>
<li><strong>Muitos grupos.</strong> Com três ou mais grupos, use a ANOVA seguida de um teste post-hoc, nunca uma série de testes <em>t</em>.</li>
</ol>
</section>
</section>
<section id="perguntas-para-consolidar" class="level1">
<h1>Perguntas para consolidar</h1>
<section id="pergunta-1-por-que-o-pareamento-mudou-o-resultado-do-sleep" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-1-por-que-o-pareamento-mudou-o-resultado-do-sleep">Pergunta 1: por que o pareamento mudou o resultado do <code>sleep</code>?</h2>
<p>Os mesmos 20 números deram <span class="math inline">\(p \approx 0{,}003\)</span> no teste pareado e <span class="math inline">\(p \approx 0{,}079\)</span> no teste para amostras independentes. Como isso é possível?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A diferença média é a mesma nas duas análises: 1,58 h. O que muda é o erro-padrão. No teste independente, ele inclui a variação entre pacientes, que é grande: alguns dormem bem com qualquer droga, outros não. No teste pareado, cada paciente serve de controle para si mesmo. A diferença <span class="math inline">\(D\)</span> elimina o nível de base de cada pessoa, e sobra apenas a variação do efeito da droga, que é pequena. Com um erro-padrão menor, a mesma diferença se distingue do acaso. Ignorar o pareamento não é apenas menos eficiente: é usar um teste cuja premissa de independência foi violada.</p>
</div>
</div>
</div>
</section>
<section id="pergunta-2-não-rejeitar-h_0-no-caso-1-prova-que-a-frota-cumpre-a-meta" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-2-não-rejeitar-h_0-no-caso-1-prova-que-a-frota-cumpre-a-meta">Pergunta 2: não rejeitar <span class="math inline">\(H_0\)</span> no caso 1 prova que a frota cumpre a meta?</h2>
<p>No caso 1, <span class="math inline">\(p \approx 0{,}93\)</span>. O gestor pode afirmar que o consumo médio da frota é de 20 mpg?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Não. O teste mostra apenas que os dados são compatíveis com a meta. O intervalo de confiança, de 17,9 a 22,3 mpg, mostra que eles também são compatíveis com uma frota 2 mpg abaixo ou acima da meta. Com 32 carros e um desvio-padrão de 6 mpg, a precisão da média é limitada. Para afirmar que a frota está <strong>dentro</strong> de uma faixa aceitável, seria necessário outro desenho de teste, chamado teste de equivalência, ou uma amostra maior.</p>
</div>
</div>
</div>
</section>
<section id="pergunta-3-o-caso-6-precisava-de-um-teste-diferente-do-caso-7" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-3-o-caso-6-precisava-de-um-teste-diferente-do-caso-7">Pergunta 3: o caso 6 precisava de um teste diferente do caso 7?</h2>
<p>Os casos 6 e 7 usam a mesma base e a mesma resposta, a sobrevivência. Por que um usa <em>Z</em> e o outro <span class="math inline">\(\chi^2\)</span>?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como pensar sobre isso
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A diferença está na variável explicativa. No caso 6, ela é binária (sexo), e a pergunta é se duas proporções são iguais. No caso 7, ela tem três categorias (classe), e o teste <em>Z</em> de duas proporções não se aplica diretamente. Para tabelas 2 × 2, os dois testes são equivalentes: <span class="math inline">\(Z^2 = \chi^2\)</span>. O qui-quadrado generaliza a comparação de proporções para qualquer número de categorias.</p>
</div>
</div>
</div>
</section>
</section>
<section id="para-casa" class="level1">
<h1>Para casa</h1>
<ol type="1">
<li>Repita o caso 2 comparando a massa corporal das espécies Adelie e Gentoo. Verifique as premissas antes de escolher entre o <em>t</em> clássico e o de Welch.</li>
<li>Aplique a ANOVA do caso 4 ao comprimento da <strong>pétala</strong> (<code>petal_length</code>). O que o teste de Levene indica? Compare o resultado com o teste de Kruskal-Wallis (<code>stats.kruskal</code>).</li>
<li>No <code>mtcars</code>, calcule a correlação de Pearson e a de Spearman (<code>stats.spearmanr</code>) entre a potência (<code>hp</code>) e o consumo (<code>mpg</code>). Faça o gráfico de dispersão e discuta qual coeficiente descreve melhor a relação.</li>
<li>No Titanic, teste se a taxa de sobrevivência difere entre os portos de embarque (<code>embarked</code>). Qual teste você escolheu, e por quê?</li>
<li>Antes de considerar o notebook pronto, use Restart Kernel and Run All.</li>
</ol>
<section id="referências" class="level2">
<h2 class="anchored" data-anchor-id="referências">Referências</h2>
<ol type="1">
<li>Bruce, P.; Bruce, A.; Gedeck, P. <em>Practical Statistics for Data Scientists</em>. 2. ed.&nbsp;O’Reilly, 2020.</li>
<li>Student. The probable error of a mean. <em>Biometrika</em>, 6(1), 1-25, 1908.</li>
<li>Welch, B. L. The generalization of “Student’s” problem when several different population variances are involved. <em>Biometrika</em>, 34(1-2), 28-35, 1947.</li>
<li>Shapiro, S. S.; Wilk, M. B. An analysis of variance test for normality (complete samples). <em>Biometrika</em>, 52(3-4), 591-611, 1965.</li>
<li>Fisher, R. A. The use of multiple measurements in taxonomic problems. <em>Annals of Eugenics</em>, 7(2), 179-188, 1936.</li>
<li>Horst, A. M.; Hill, A. P.; Gorman, K. B. <em>palmerpenguins: Palmer Archipelago (Antarctica) penguin data</em>. R package, 2020.</li>
<li>Henderson, H. V.; Velleman, P. F. Building multiple regression models interactively. <em>Biometrics</em>, 37(2), 391-411, 1981.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/oandrefonseca\.github\.io\/data-science\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/oandrefonseca/data-science/blob/main/aulas/08-testes-parametricos.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/oandrefonseca/data-science/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></div></div></footer></body></html>